const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src', 'data', 'paraFamilia.ts');
let txt = fs.readFileSync(filePath, 'utf8');

const marcador = '  return null;\n}';

const novos = `
  // ─── Dia 31 — Gn 22:1–19 ────────────────────────────────────────────────
  if (d.dia === 31) return \`PARA A FAMÍLIA · Gênesis 22:1–19

TEMA: A Obediência que Não Entende Mas Confia

---

TÍTULO DO SERMÃO FAMILIAR
"O Monte Moriá: Quando Deus Pede o Que É Mais Precioso"

BIG IDEA PARA A FAMÍLIA
Deus testou Abraão pedindo o que era mais precioso — o filho da promessa — e Abraão obedeceu sem entender, porque confiava que Deus mesmo proveria. Esta perícope é o ápice da fé abraâmica: obediência radical que não negocia com Deus, e confiança que não depende de compreensão.

PERGUNTA PARA A FAMÍLIA
Há algo que Deus está pedindo de você — ou de nossa família — que parece contrário às suas promessas, e como a fé de Abraão no monte Moriá nos ensina a obedecer antes de entender?

PALAVRA-CHAVE DE TRANSIÇÃO
Vejamos três momentos do monte Moriá em Gênesis 22:1–19: o TESTE que Deus impõe (22:1-2), a JORNADA da obediência radical (22:3-10) e a PROVISÃO que só Deus dá (22:11-19).

---

MOVIMENTOS DO SERMÃO

I. O TESTE: "TOMA AGORA TEU FILHO, TEU ÚNICO" (A)
§ Indicação Textual: Gn 22:1–2 ("depois destas coisas aconteceu que Deus tentou Abraão, e disse-lhe: Abraão! E ele respondeu: Eis-me aqui. E disse: Toma agora teu filho, teu único, Isaque, a quem amas, e vai à terra de Moriá, e oferece-o ali em holocausto sobre uma das montanhas que eu te disser") — o imperativo divino que inverte tudo
§ Exegese: O versículo 1 abre com "depois destas coisas" — conectando ao nascimento de Isaque (21:1-8) e ao pacto com Abimeleque (21:22-34). No auge da bênção vem o teste. O narrador revela imediatamente ao leitor: "Deus tentou (nissah) Abraão" — não para destruí-lo, mas para provar e revelar a qualidade de sua fé. Abraão não sabe que é teste. O imperativo de Deus em 22:2 é elaborado em quatro apositivos crescentes: "teu filho" → "teu único" → "Isaque" → "a quem amas." Cada apositivo estreita o objeto até que não haja escapatória: é exatamente aquele filho insubstituível, o filho da promessa. E o comando: "oferece-o em holocausto." Deus pede que Abraão destrua com as próprias mãos a própria promessa. A aparente contradição é total.
§ Teologia Reformada: A CFW III.1 e a CFB 3.1 afirmam que Deus decretou desde a eternidade tudo o que acontece — inclusive os testes que vêm sobre Seus filhos. Herman Bavinck (Reformed Dogmatics, v.3): "O teste de Abraão não foi crueldade divina — foi pedagogia soberana. Deus nunca testa para destruir; testa para revelar e fortalecer o que já implantou pela graça. O que o teste de Moriá revelou é que Abraão havia aprendido, ao longo de décadas, que Deus é mais confiável do que qualquer promessa que Ele mesmo havia dado." J.C. Ryle (Santidade): "O teste mais severo da fé é quando Deus parece contradizer Suas próprias promessas. É nesses momentos que a fé madura se distingue da fé condicional: a fé madura obedece antes de entender; a fé condicional só obedece quando entende."
§ Aplicação Familiar: Pais: Há algo que Deus parece estar pedindo de vocês que parece contradizer o que Ele havia prometido — uma perda, uma renúncia, uma mudança de planos? O teste de Abraão ensina que a obediência precede a compreensão. / Filhos: Você já teve que obedecer a seus pais sem entender por quê? A obediência que não depende de compreensão é treino para a fé adulta. Abraão obedeceu sem entender — e Deus providenciou. / Noivos: O casamento pedirá renúncias — de sonhos, de planos, de preferências — que parecerão contrários ao que você havia esperado. Aprendam agora que a fé que obedece antes de entender é a base do lar cristão. / Casal: Há uma área da vida familiar onde Deus está pedindo obediência antes que vocês entendam o propósito? O teste de Abraão não veio no início da jornada, mas depois de décadas de fé. A maturidade espiritual não elimina os testes — aprofunda a confiança no Testador. / Avós: Os anos de fé trazem testes cada vez mais profundos — perdas, renúncias, "Moriás" inesperados. Como a confiança em Deus se aprofundou ao longo dos testes que vocês atravessaram?

II. A JORNADA: "IRÁ COMIGO E VOLTARÁ" — CENTRO ◉ (Gn 22:3–10)
§ Indicação Textual: Gn 22:3 ("levantou-se Abraão de madrugada, e albardou o seu jumento, e tomou consigo dois dos seus moços e Isaque, seu filho; e rachou lenha para o holocausto, e se levantou e foi ao lugar que Deus lhe havia dito") e 22:5 ("disse Abraão aos seus moços: Ficai aqui com o jumento; eu e o rapaz iremos até lá, e adoraremos, e voltaremos a vós") e 22:8 ("Deus proverá para si o cordeiro para o holocausto, meu filho") — a obediência imediata, a fé implícita e a revelação do nome
§ Exegese: Três detalhes revelam a profundidade da fé de Abraão: (1) 22:3 — "levantou-se de madrugada": não houve hesitação noturna, negociação ou demora. A obediência foi imediata e completa. (2) 22:5 — "eu e o rapaz iremos... e voltaremos a vós": o plural "voltaremos" (nashub) é teologicamente denso. Abraão diz a dois servos que ambos — ele e Isaque — voltarão. Hebreus 11:19 explica: "considerou que Deus era poderoso para ressuscitar até os mortos." Abraão planejava obedecer completamente — e confiava que Deus ou impediria ou ressuscitaria. (3) 22:8 — "Deus proverá para si o cordeiro": a palavra hebraica yireh (proverá/verá) é a raiz do nome que Abraão dará ao lugar em 22:14: Yahweh Yireh — o Senhor provê. A revelação do nome de Deus emerge no momento de obediência radical — não antes.
§ Teologia Reformada: A CFW XIV.1-2 e a CFB 14.1-2 ensinam que a fé salvadora inclui obediência ao que Deus ordena. O autor de Hebreus (11:17-19) identifica a fé de Abraão em Moriá como ato da fé justificante: "Pela fé, Abraão, quando foi provado, ofereceu Isaque." Joel Beeke (Reformed Preaching): "A frase 'Deus proverá' (Gn 22:8) é uma das afirmações de fé mais profundas do Antigo Testamento. Abraão não sabia como Deus proveria — mas sabia que Ele o faria. Esta é a anatomia da confiança bíblica: não a certeza dos meios, mas a certeza do Provedor." Calvino (Comentário 22:5): "O 'voltaremos' de Abraão não era falsidade — era fé. Ele afirmava o que acreditava que Deus faria, mesmo sem saber como. A linguagem da fé antecipa o que a providência cumprirá."
§ Aplicação Familiar: Pais: Quando vocês enfrentam situações onde não veem como Deus pode resolver — financeiras, de saúde, de relacionamento — conseguem dizer "Deus proverá" com a convicção de Abraão, ou apenas como expressão piadosa? A diferença é se sua obediência muda com ou sem a resposta. / Filhos: Abraão rachou a lenha, carregou o fogo e andou três dias antes de Deus agir. A obediência de Abraão não esperou a providência para começar — começou antes de vê-la. Como você obedece a Deus quando a resposta ainda não chegou? / Noivos: "Deus proverá" é a frase que sustentará o lar de vocês em momentos de incerteza. Mas é frase viva na fé ou chavão repetido sem convicção? A fé de Abraão foi testada — a de vocês também será. / Casal: Como casal, quando enfrentam o equivalente ao "terceiro dia de caminhada" — quando a solução ainda não apareceu — qual é o movimento de vocês: fé que continua caminhando, ou paralisação? / Avós: Os anos ensinaram a vocês que Deus provê. Que "Yahweh Yireh" vocês podem testemunhar para a família mais jovem — momentos em que viram a provisão de Deus chegar no momento mais improvável?

III. A PROVISÃO: YAHWEH YIREH E A RENOVAÇÃO DO PACTO (A')
§ Indicação Textual: Gn 22:11–13 ("o anjo do Senhor o chamou do céu... Abraão! Abraão!... Não estendas a tua mão sobre o rapaz... Então levantou Abraão os seus olhos e olhou, e eis que estava atrás um carneiro preso pelos chifres num espinheiro; e foi Abraão e tomou o carneiro e ofereceu-o em holocausto em lugar de seu filho") e 22:14 ("chamou Abraão o nome daquele lugar: O Senhor Provê; donde se diz até ao dia de hoje: No monte do Senhor se provê") e 22:17–18 ("te abençoarei muito... e na tua descendência serão benditas todas as nações da terra, porquanto obedeceste à minha voz") — o resgate, o nome revelado e a renovação da aliança
§ Exegese: O resgate de Isaque em 22:11-13 acontece no último momento — não antes que o braço de Abraão estivesse estendido (22:10: "Abraão estendeu a mão e tomou o cutelo"). Deus não interveio antes do limite — mas antes da consumação irreversível. O carneiro estava ali "atrás" — nos arbustos, presente durante toda a jornada, aguardando o momento certo. A providência de Deus não começou no monte: estava preparada antes da chegada. O nome Yahweh Yireh (22:14) torna-se teônimo permanente: "No monte do Senhor se provê." E a renovação da aliança em 22:16-18 é a confirmação mais solene do pacto abraâmico: Deus jura por Si mesmo — não pode jurar por algo maior (Hb 6:13) — porque Abraão obedeceu. A obediência de Abraão é o contexto da renovação — não a causa (a graça veio antes), mas a ocasião onde Deus pronuncia a bênção com novo peso.
§ Teologia Reformada: A CFW VII.3 e a CFB 7.3 descrevem o pacto de graça como iniciativa unilateral de Deus, sustentado por Sua fidelidade. A renovação do pacto em 22:16-18 confirma que a aliança não estava em risco — mas a fé de Abraão precisava ser revelada, tanto para ele quanto para a história da redenção. R.C. Sproul (Knowing Scripture): "O nome Yahweh Yireh não é apenas memória histórica — é programa teológico. Deus se revela como Provedor justamente onde a necessidade é mais aguda e os recursos humanos são zero. O monte Moriá é o endereço permanente onde Deus encontra a necessidade radical com provisão radical." Thomas Watson (A Body of Divinity): "O carneiro preso nos espinheiros por trás de Abraão estava ali durante toda a caminhada de três dias — Abraão não o viu porque ainda não era hora. Assim opera a providência: a provisão está preparada antes que a necessidade seja reconhecida. A fé não cria a provisão — revela o que Deus já havia preparado."
§ Aplicação Familiar: Pais: "No monte do Senhor se provê" — há um "monte" na vida de vocês agora onde a provisão ainda não apareceu, mas onde a fé diz que Deus já a preparou? O carneiro estava nos arbustos durante toda a caminhada — a fé caminha mesmo sem vê-lo. / Filhos: O carneiro estava preso nos espinheiros durante toda a caminhada de três dias — mas Abraão só o viu quando levantou os olhos. Às vezes a provisão de Deus já está presente; precisamos levantar os olhos para vê-la. / Noivos: Que "carneiro nos espinheiros" — provisões que Deus já preparou mas que vocês ainda não perceberam — pode estar esperando ser visto no lar que vão construir? / Casal: Celebrem os "Yahweh Yireh" do lar de vocês — os momentos em que Deus proveu no último momento, quando os recursos humanos haviam terminado. Esses momentos merecem ser nomeados e lembrados, como Abraão nomeou o monte. / Avós: "No monte do Senhor se provê" — que nomes de lugares, situações ou momentos da vida de vocês poderiam receber o nome "Yahweh Yireh"? Compartilhem esses momentos com filhos e netos como herança de fé.

---

EIXO REDENTOR (HISTÓRICO-REDENTIVO)
Gênesis 22 é o texto do Antigo Testamento que mais claramente prefigura a crucificação. O pai que oferece o filho único amado; o filho que carrega a lenha (o instrumento de sua morte); o monte Moriá — identificado em 2 Crônicas 3:1 como o mesmo monte onde Salomão construiu o Templo, e a tradição aponta para o mesmo complexo do Calvário; o carneiro substituto que morre no lugar de Isaque. Mas a tipologia tem diferença decisiva: Deus não poupou o Seu próprio Filho (Rm 8:32) — o carneiro para Abraão chegou; para o Pai eterno, não havia carneiro. Cristo foi o cordeiro de Deus que tira o pecado do mundo (Jo 1:29), o substituto definitivo que morreu para que os filhos da promessa vivessem. "No monte do Senhor se provê" encontrou seu cumprimento absoluto no Calvário.

DOUTRINA CENTRAL
A Obediência da Fé Radical: Abraão obedeceu sem entender — porque sua fé estava ancorada não na promessa mas no Promissor. O teste de Moriá revelou que décadas de caminhada com Deus haviam produzido uma fé que confia no caráter de Deus quando as circunstâncias contradizem as promessas. Yahweh Yireh é o nome de Deus que emerge da obediência radical: Deus se revela como Provedor justamente onde os recursos humanos chegam ao fim. Cf. CFW XIV; XVII; CFB 14; 17; Hb 11:17-19.

APLICAÇÕES PARA A FAMÍLIA
▸ Para os Pais: "Levantou-se de madrugada" — a obediência de Abraão foi imediata e sem negociação. Que área da vida de vocês ainda está em negociação com Deus, quando a resposta certa seria "levantou-se de madrugada"?
▸ Para os Filhos: O carneiro estava nos arbustos durante toda a caminhada — Abraão só o viu quando levantou os olhos. Esta semana, peça a Deus que abra seus olhos para a provisão que Ele já preparou mas que você ainda não está vendo.
▸ Para os Noivos: "Deus proverá" — comprometam-se desde agora a que, nos momentos de incerteza do lar, a primeira resposta seja essa afirmação de fé, não o pânico ou a acusação mútua.
▸ Para o Casal: Nomeiem os "Yahweh Yireh" do lar de vocês — os momentos em que Deus proveu quando os recursos humanos haviam terminado. Registrem, celebrem, contem aos filhos.
▸ Para os Avós: O teste de Abraão veio depois de décadas de fé. Os testes mais profundos geralmente vêm na maturidade. Que "Moriá" de vocês pode ser compartilhado com a família como testemunho de que Deus provê?

DINÂMICA FAMILIAR
1. Leiam 22:1-2 em voz alta. Perguntem: "Quatro apositivos descrevem Isaque: 'teu filho, teu único, Isaque, a quem amas.' Por que o texto elabora tanto? O que isso nos diz sobre o custo do que Deus pediu?"
2. Leiam 22:3. Perguntem: "Abraão 'levantou-se de madrugada.' Por que isso é importante? O que teria acontecido se ele esperasse, hesitasse, ou tentasse negociar primeiro?"
3. Leiam 22:5 e 22:8. Discutam: "Abraão disse 'voltaremos' (plural) e 'Deus proverá.' Ele sabia como? O que é fé que afirma sem saber o como?"
4. Leiam 22:13-14. Perguntem: "O carneiro estava lá durante toda a caminhada. O que isso nos ensina sobre como a providência de Deus opera — antes de ser vista?"
5. Atividade: Cada membro da família nomeia um "monte Moriá" pessoal — um momento de obediência difícil ou de provisão inesperada — e compartilha com a família.
6. Orem juntos usando as palavras de 22:14: "Yahweh Yireh — Senhor que provê. Confiamos que no monte onde estamos hoje, Tu já preparaste a provisão que ainda não vemos."

AUTORES REFORMADOS
▸ João Calvino (Comentário ao Gênesis 22:8): "'Deus proverá' não foi evasão — foi confissão de fé. Abraão não sabia o mecanismo da provisão; sabia quem era o Provedor. Esta é a distinção entre fé bíblica e esperança vaga: a fé bíblica não aposta nos meios — aposta no caráter do Deus que prometeu."
▸ Herman Bavinck (Reformed Dogmatics, v.3): "O teste de Abraão não foi crueldade divina — foi pedagogia soberana. Deus nunca testa para destruir; testa para revelar e fortalecer o que já implantou pela graça. Moriá revelou não o que Abraão faria por Deus, mas o que décadas de graça haviam produzido na alma de Abraão."
▸ Thomas Watson (A Body of Divinity): "O carneiro preso nos espinheiros estava ali durante toda a caminhada de três dias. A provisão de Deus não começa quando nossa necessidade é reconhecida — começa quando Deus decreta. A fé não cria a provisão; levanta os olhos para vê-la onde já estava."\`;

  // ─── Dia 32 — Gn 22:20–24 ────────────────────────────────────────────────
  if (d.dia === 32) return \`PARA A FAMÍLIA · Gênesis 22:20–24

TEMA: A Genealogia que Prepara: A Providência nos Detalhes Familiares

---

TÍTULO DO SERMÃO FAMILIAR
"A Família de Naor: Como Deus Prepara o Futuro nos Detalhes que Parecem Ordinários"

BIG IDEA PARA A FAMÍLIA
Após o ápice dramático de Moriá, Gênesis registra uma genealogia que parece ordinária — mas que prepara a providência de Deus para o casamento de Isaque. Esta perícope ensina que Deus opera no que parece comum e sem drama para preparar o que virá, e que a família cristã aprende a ver a providência nos detalhes cotidianos.

PERGUNTA PARA A FAMÍLIA
Como sua família aprende a reconhecer a mão de Deus nas situações aparentemente ordinárias e sem drama — nas notícias comuns, nas genealogias da vida — que estão preparando o que Ele planeja para o futuro?

PALAVRA-CHAVE DE TRANSIÇÃO
Vejamos esta perícope em três camadas: a NOTÍCIA que chega a Abraão (22:20a), a GENEALOGIA que revela a providência (22:20b-23) e a CONEXÃO que será decisiva (22:23-24) — tudo em Gênesis 22:20–24.

---

MOVIMENTOS DO SERMÃO

I. A NOTÍCIA: "FOI ANUNCIADO A ABRAÃO" (A)
§ Indicação Textual: Gn 22:20 ("aconteceu depois destas coisas que foi anunciado a Abraão, dizendo: Eis que também Milca deu filhos a Naor, teu irmão") — a chegada de notícia familiar após o teste de Moriá
§ Exegese: O versículo 20 abre com "depois destas coisas" — exatamente como 22:1 havia aberto o teste de Abraão. O narrador usa a mesma fórmula para indicar sequência narrativa. Após o ápice espiritual de Moriá, a narrativa desce para o cotidiano: chega notícia da família de Naor, irmão de Abraão que havia ficado em Harã (cf. 11:31). A notícia é simples: "Milca deu filhos a Naor." Não é revelação dramática nem teofania — é informação familiar ordinária. Mas a notícia não é irrelevante: é o sinal de que a providência de Deus para a segunda geração está sendo preparada. O texto não explica isso imediatamente — apenas registra. A genealogia que segue parecerá árida, mas contém o nome que mudará o curso da história: Rebeca.
§ Teologia Reformada: A CFW V.1 e a CFB 5.1 afirmam que Deus governa todas as coisas — inclusive as genealogias, os casamentos e as notícias familiares ordinárias. Herman Bavinck (The Christian Family): "A providência de Deus não opera apenas nos momentos dramáticos — Moriá, o dilúvio, o chamado de Abraão. Opera igualmente nos nascimentos registrados em genealogias, nos casamentos arranjados por emissários, nas notícias que chegam por mensageiros. A família que aprende a ver a providência nos detalhes ordinários tem visão teológica mais profunda do que a que só reconhece Deus nas teofanias." R.C. Sproul (The Providence of God): "Deus não governa apenas as grandes viradas da história — governa cada detalhe que prepara as grandes viradas. A genealogia de Naor em Gênesis 22 é detalhe que prepara Gênesis 24. Quem não lê com atenção perde a providência."
§ Aplicação Familiar: Pais: Há notícias aparentemente ordinárias na vida da família — mudanças de emprego, encontros inesperados, conexões familiares distantes — que vocês têm descartado como acaso, mas que podem ser a mão de Deus preparando o próximo capítulo? / Filhos: Às vezes Deus trabalha no que parece entediante — uma aula, um encontro sem graça, uma conversa sem importância — para preparar algo que só vai aparecer mais tarde. Como você aprende a prestar atenção ao que parece ordinário? / Noivos: O casamento de vocês foi preparado por uma série de "genealogias" — escolhas, encontros, movimentos que parecem acidentais. Conversem sobre como Deus orquestrou os detalhes que os trouxeram até este momento. / Casal: Olhem para trás na história de vocês como casal. Que "notícias ordinárias" — empregos, mudanças, encontros — parecem agora ter sido movimentos da providência de Deus preparando o que veio depois? / Avós: Com a perspectiva dos anos, as genealogias da vida — os detalhes que na época pareciam insignificantes — revelam a mão de Deus com mais clareza. Compartilhem com filhos e netos como Deus estava operando no que parecia comum.

II. A GENEALOGIA: OS FILHOS DE NAOR — CENTRO ◉ (Gn 22:20b–23)
§ Indicação Textual: Gn 22:20b–22 ("Uz, seu primogênito, e Buz, seu irmão, e Quemuel, pai de Arã, e Quesede, e Hazo, e Pildás, e Jidlafe, e Betuel") e 22:23 ("e Betuel gerou a Rebeca; estes oito filhos deu Milca a Naor, irmão de Abraão") — a lista genealógica que culmina no nome decisivo
§ Exegese: A lista de 22:20b-22 — oito nomes em sucessão — parece árida. Mas o narrador a constrói como crescendo até um clímax: o versículo 23 termina com "Betuel gerou a Rebeca." O nome Rebeca aparece pela primeira vez na Bíblia aqui — não em contexto dramático, mas no fim de uma lista genealógica. A apresentação é deliberadamente contida: antes que o leitor saiba quem Rebeca é, ela é inserida como dado genealógico. A estrutura retórica é de revelação progressiva: a genealogia constrói tensão até que o nome decisivo cai no fim. "Betuel gerou a Rebeca" — com esse versículo, a providência de Deus para Isaque está documentada: a futura esposa do filho da promessa existe, é da família certa, da tribo certa. O que parecia lista árida é mapa da providência.
§ Teologia Reformada: A CFW III.1 e a CFB 3.1 afirmam que Deus decretou desde a eternidade todas as coisas que vêm a existir — inclusive cada nascimento em cada genealogia. Calvino (Comentário 22:23): "A menção de Rebeca no fim desta lista genealógica é providência narrativa: o Espírito Santo inspira o registro deste nome porque Ele sabia que seria decisivo. A genealogia não é ornamento literário — é arquivo da providência de Deus ao longo das gerações." Joel Beeke (Parenting by God's Promises): "Os filhos que nascem nas famílias cristãs não são acidentes biológicos — são providências. Cada nome na genealogia de Naor representa uma vida que Deus planejou, um propósito que Ele conhecia antes da fundação do mundo. O nome Rebeca no fim desta lista é lembrete de que Deus conhece o nome de cada filho antes de qualquer pai conhecer."
§ Aplicação Familiar: Pais: "Betuel gerou a Rebeca" — cada filho que Deus dá tem propósito inscrito na providência de Deus, mesmo quando ainda não é claro. Como você olha para seus filhos à luz de que Deus os planejou para um propósito que ainda se desdobrará? / Filhos: Seu nome está na "genealogia" de Deus — Ele o conhecia antes de você nascer. Isso não é frase religiosa: é a afirmação teológica de Gênesis 22:23 para cada vida que Deus traz ao mundo. / Noivos: O nome da futura esposa de Isaque aparece numa lista genealógica que ele nunca leu. O providência de Deus para o casamento de vocês também foi preparada em detalhes que nenhum de vocês escolheu. Como isso muda a maneira de ver o lar que vão construir? / Casal: Que "Rebecas" — propósitos para os filhos de vocês — vocês vislumbram na providência de Deus, mesmo que ainda não estejam claros? Como oram especificamente pelos propósitos divinos na vida de cada filho? / Avós: Olhando para a genealogia da família de vocês — os nomes, as histórias, as providências — que padrão de fidelidade de Deus ao longo das gerações você pode identificar e compartilhar?

III. A CONEXÃO DECISIVA: MILCA E REUMÁ — E O QUE VIRÁ (A')
§ Indicação Textual: Gn 22:24 ("e a sua concubina, que se chamava Reumá, também ela deu à luz Teba, e Gaã, e Taaás, e Maaca") — a menção da concubina e seus filhos como completude do registro familiar
§ Exegese: O versículo 24 registra os filhos de Reumá, concubina de Naor — quatro filhos que complementam o registro. O texto distingue claramente entre "Milca" (esposa legítima, 22:20) e "Reumá" (concubina, 22:24), e entre os oito filhos de Milca e os quatro de Reumá. Esta distinção não é moralista — é genealógica: a linhagem que importará para a promessa vem de Milca, não de Reumá. Betuel, filho de Milca, é o pai de Rebeca. A perícope encerra com este registro completo porque o narrador está documentando o mundo no qual a providência de Deus para Isaque se situará. O capítulo 24 mostrará Eliezer indo buscar Rebeca — e a genealogia de 22:20-24 é a fundação invisível que torna isso possível. Sem o registro aqui, o leitor não compreende a legitimidade do casamento de Isaque.
§ Teologia Reformada: A CFW V.2 e a CFB 5.2 afirmam que a providência de Deus se estende a todos os eventos — inclusive os registros familiares e genealógicos que parecem secundários. Herman Bavinck (Reformed Dogmatics, v.2): "A distinção entre Milca e Reumá no texto de Gênesis não é julgamento moral das duas mulheres — é documentação providencial. Deus usará a linhagem de Milca para a promessa. Este é o padrão da eleição: não mérito, mas providência soberana que opera através de estruturas humanas para cumprir propósitos eternos." Thomas Watson (All Things for Good): "Mesmo as listas genealógicas que parecem irrelevantes estão a serviço da providência. Quem duvida disso deveria perguntar: por que o Espírito Santo inspirou que Rebeca fosse mencionada aqui, nesta lista, antes de qualquer narração de sua história? Porque a providência documenta antes de revelar."
§ Aplicação Familiar: Pais: A família de Deus tem uma "genealogia" — a história da fé transmitida de geração em geração. Vocês estão documentando ativamente essa história para seus filhos? Fotos, cartas, histórias orais, diários — a documentação da providência é parte da transmissão da fé. / Filhos: Você conhece a história da fé de sua família — avós, bisavós, como o evangelho chegou até sua casa? Pergunte a seus pais e avós: há uma "Rebeca" na genealogia de vocês — alguém que Deus usou decisivamente para que a fé chegasse até você? / Noivos: O lar que vocês vão construir começará a sua própria genealogia de fé. Que registro você pretende deixar para os filhos e netos de vocês — não apenas de conquistas, mas da fidelidade de Deus ao longo das gerações? / Casal: Estão documentando a história de fé do lar de vocês? Journais, cadernos de oração, álbuns com memórias de providência — esses registros são a "genealogia" que os filhos e netos lerão como Gênesis 22. / Avós: Vocês são os "Betuel" da família — os que transmitem a linhagem de fé para a próxima geração. Que forma de documentação — cartas, vídeos, diários — poderiam deixar para que os netos, no futuro, "leiam o nome" de vocês como marca da providência de Deus?

---

EIXO REDENTOR (HISTÓRICO-REDENTIVO)
A genealogia de Naor culmina em Rebeca — que se tornará a mãe de Jacó, que se tornará Israel, cujos filhos formarão as doze tribos, da qual virá o rei Davi, e de cuja linhagem nascerá Cristo (Mt 1:1-16). A "lista árida" de Gênesis 22:20-24 está na linha direta da genealogia de Jesus. A providência de Deus que opera nos detalhes genealógicos de Gênesis é a mesma que Mateus documenta em seu capítulo 1: Deus orquestra a história familiar das gerações para que, "na plenitude do tempo" (Gl 4:4), o Filho prometido nascesse de mulher. Cada nome na genealogia bíblica é fio de uma tapeçaria que só se revela completamente no Natal.

DOUTRINA CENTRAL
A Providência de Deus nos Detalhes Familiares: Deus opera não apenas nos momentos de teofania e teste dramático, mas igualmente nas genealogias, nos nascimentos, nas notícias ordinárias que preparam os capítulos seguintes. A menção de Rebeca no fim de uma lista genealógica é prova de que a providência de Deus antecede o drama — ela o prepara nos bastidores do cotidiano. A família cristã que aprende a ver Deus nos detalhes ordinários cultiva uma espiritualidade mais profunda e mais realista do que a que só reconhece Deus nas cenas dramáticas. Cf. CFW V; III; CFB 5; 3.

APLICAÇÕES PARA A FAMÍLIA
▸ Para os Pais: Documentem a história de fé do lar — registros de oração respondida, momentos de providência, histórias de como Deus agiu. Esses registros são a "genealogia" que seus filhos e netos lerão.
▸ Para os Filhos: Esta semana, pergunte a seus pais ou avós: "Como o evangelho chegou até nossa família?" A resposta é a genealogia de fé de vocês — tão real quanto a de Naor.
▸ Para os Noivos: O lar de vocês começará uma nova genealogia de fé. Desde o primeiro dia, registrem como Deus está agindo — em diário, caderno de oração ou álbum de memórias.
▸ Para o Casal: Olhem juntos para a "genealogia" do lar de vocês até agora — os detalhes que pareciam ordinários e que, em retrospecto, revelam a mão de Deus. Deem graças juntos.
▸ Para os Avós: Vocês são os portadores da genealogia de fé da família. Esta semana, escrevam — em carta, e-mail ou vídeo — a história de como Deus os chamou e sustentou, para que os netos a tenham.

DINÂMICA FAMILIAR
1. Leiam 22:20-23 em voz alta. Perguntem: "Esta parece uma lista comum de nomes. Mas o último versículo menciona Rebeca — que será a esposa de Isaque. O que isso nos ensina sobre como Deus opera no ordinário?"
2. Perguntem: "Se alguém lesse uma 'genealogia' da nossa família, que nome apareceria como decisivo para a fé que temos hoje? Quem foi o 'Betuel' da nossa família?"
3. Atividade: Cada membro escreve três "detalhes ordinários" da semana que podem ser providência de Deus preparando algo futuro. Compartilhem.
4. Discutam: "A genealogia de Naor parece irrelevante depois do drama de Moriá. Mas era essencial para o que viria. Que 'genealogias' na sua vida parecem irrelevantes agora, mas podem ser essenciais para o que Deus está preparando?"
5. Atividade de família: Construam juntos uma "árvore de providência" — não genealógica, mas de fé: como o evangelho chegou até cada um de vocês, quem foram as pessoas-chave, que eventos decisivos prepararam a fé de vocês.
6. Orem agradecendo a Deus pela providência nos detalhes ordinários: "Senhor, que aprendamos a ver Tua mão não apenas nos Moriás dramáticos, mas nas genealogias cotidianas que Tu estás escrevendo para nós."

AUTORES REFORMADOS
▸ João Calvino (Comentário ao Gênesis 22:23): "A menção de Rebeca no fim desta lista genealógica é providência narrativa: o Espírito Santo inspira o registro deste nome porque Ele sabia que seria decisivo. A genealogia não é ornamento literário — é arquivo da providência de Deus ao longo das gerações."
▸ Herman Bavinck (The Christian Family): "A providência de Deus não opera apenas nos momentos dramáticos. Opera igualmente nos nascimentos registrados em genealogias, nos casamentos arranjados por emissários, nas notícias que chegam por mensageiros. A família que aprende a ver a providência nos detalhes ordinários tem visão teológica mais profunda do que a que só reconhece Deus nas teofanias."
▸ Joel Beeke (Parenting by God's Promises): "Os filhos que nascem nas famílias cristãs não são acidentes biológicos — são providências. Cada nome na genealogia de Naor representa uma vida que Deus planejou. O nome Rebeca no fim desta lista é lembrete de que Deus conhece o nome de cada filho antes de qualquer pai conhecer."\`;

  // ─── Dia 33 — Gn 23:1–20 ────────────────────────────────────────────────
  if (d.dia === 33) return \`PARA A FAMÍLIA · Gênesis 23:1–20

TEMA: A Morte com Dignidade: Como a Família Cristã Lida com a Perda

---

TÍTULO DO SERMÃO FAMILIAR
"Sara em Hebrom: Como Abraão Chorou, Negociou e Enterrou com Esperança"

BIG IDEA PARA A FAMÍLIA
Abraão chorou a morte de Sara e trabalhou para enterrá-la com dignidade em terra que ele mesmo comprou — porque a sepultura na terra prometida era ato de fé: quem enterra na terra da promessa crê que a promessa ainda é real. Esta perícope ensina como a família cristã lida com a morte: com lágrimas reais, dignidade prática e esperança enraizada na promessa de Deus.

PERGUNTA PARA A FAMÍLIA
Como nossa família lida com a morte — a morte de entes queridos, a perspectiva da nossa própria morte — à luz da esperança cristã, e o que Abraão nos ensina sobre chorar com fé e agir com esperança diante da perda?

PALAVRA-CHAVE DE TRANSIÇÃO
Vejamos três gestos de Abraão em Gênesis 23:1–20: as LÁGRIMAS que não escondem (23:1-2), a NEGOCIAÇÃO que honra (23:3-16) e a SEPULTURA que confessa fé (23:17-20).

---

MOVIMENTOS DO SERMÃO

I. AS LÁGRIMAS DE ABRAÃO: O LUTO QUE A FÉ NÃO SUPRIME (A)
§ Indicação Textual: Gn 23:1–2 ("a vida de Sara foi de cento e vinte e sete anos; estes foram os anos da vida de Sara. E Sara morreu em Quiriate-Arba, que é Hebrom, na terra de Canaã; e Abraão veio para prantear Sara e para chora por ela") — a morte de Sara registrada com solenidade e o luto de Abraão sem disfarce
§ Exegese: Gênesis 23:1 é o único versículo da Bíblia que registra explicitamente a idade de uma mulher ao morrer. Sara recebe honra rara: sua vida é contada em anos, seu lugar de morte nomeado, sua morte lamentada pelo marido. O versículo 2 registra dois verbos para o luto de Abraão: "prantear" (saphad — lamento público, ritual fúnebre) e "chorar" (bakah — choro de dor pessoal e íntima). Os dois verbos juntos indicam que Abraão não escolheu entre dignidade pública e dor privada — ele expressou ambos. O texto hebraico de 23:2 tem uma curiosidade sintática que comentaristas notam: "veio para prantear... e para chorar" — o "e" (waw) pode sugerir sequência: primeiro o ritual público (prantear), depois o choro privado, ou ambos simultâneos. De qualquer forma, Abraão não suprimiu o luto pela fé: chorou.
§ Teologia Reformada: A CFW XXXII.3 e a CFB 31.3 afirmam que os crentes que morrem "vão para com Deus" — mas não ensinam que os que ficam não devem chorar. J.C. Ryle (Expository Thoughts): "A fé cristã não suprime o luto — ela o transforma. Abraão chorou por Sara porque a amava e porque a perda é real. A diferença entre o luto do crente e do incrédulo não é a ausência de lágrimas — é a presença da esperança nas lágrimas. O crente chora 'não como os que não têm esperança' (1Ts 4:13) — mas chora." Joel Beeke (Parenting by God's Promises): "Pais que nunca demonstram dor diante dos filhos estão ensinando que a fé é anestesia emocional. Pais que choram com esperança estão ensinando que a fé é companhia real na dor — não negação dela. Abraão chorou. Isso é teologia pastoral."
§ Aplicação Familiar: Pais: Como vocês lidam com o luto na frente dos filhos? Abraão chorou publicamente pela esposa — não suprimiu as lágrimas pela fé. A família cristã madura ensina os filhos que chorar é humano e santo, desde que as lágrimas estejam enraizadas na esperança. / Filhos: Você tem permissão de chorar quando perde alguém que ama. A fé cristã não diz "não chore." Diz "chore com esperança." Há diferença enorme entre os dois. / Noivos: O casamento incluirá perdas — de pessoas amadas, de sonhos, de saúde. Conversem agora sobre como pretendem atravessar juntos os momentos de luto — com lágrimas reais e esperança real, não com estoicismo piedoso. / Casal: Como vocês dois lidam diferentemente com o luto? Que espaço o lar de vocês tem para as lágrimas — dos filhos, um do outro, de vocês mesmos? Abraão não esperou que as lágrimas passassem para agir: chorou e depois se levantou (23:3). / Avós: Os anos trazem mais despedidas. Como vocês têm demonstrado à família que é possível chorar e ainda crer — que luto e esperança coexistem sem contradição?

II. A NEGOCIAÇÃO: COMPRANDO TERRA COM DIGNIDADE — CENTRO ◉ (Gn 23:3–16)
§ Indicação Textual: Gn 23:3–4 ("levantou-se Abraão de diante do seu morto e falou aos filhos de Hete, dizendo: Sou estrangeiro e peregrino entre vós; dai-me a posse de uma sepultura entre vós para que eu enterre o meu morto para longe de mim") e 23:9 ("que me dê a caverna de Macpela, que é sua, que está na extremidade do seu campo; pelo seu justo preço ma dê no meio de vós, por posse de sepultura") e 23:16 ("Abraão aceitou a oferta de Efrom e Abraão pesou a Efrom a prata que havia falado... quatrocentos siclos de prata, moeda corrente entre os mercadores") — a negociação detalhada e o preço pago
§ Exegese: O texto registra a negociação com detalhe incomum para a narrativa bíblica: os discursos de Abraão (23:4, 23:8-9), as respostas dos hititas (23:5-6, 23:10-11), a oferta de Efrom (23:11), a resposta de Abraão (23:13), o preço nomeado (23:15) e o pagamento (23:16). A riqueza de detalhes não é acidental — é evidência de que a aquisição da sepultura era ato de importância jurídica e teológica. Abraão abre a negociação identificando-se: "sou estrangeiro e peregrino" (23:4). Esta autoidentificação é confissão teológica: Abraão reconhece que não tem direito legal sobre a terra — ainda. A oferta inicial dos hititas em 23:6 é generosa: "sepulte seu morto no melhor de nossos sepulcros." Efrom oferece o campo de graça (23:11). Mas Abraão insiste em pagar: "pelo seu justo preço ma dê" (23:9). Por quê? Porque Abraão não quer posse condicional ou presente revogável: quer título legal. A escritura paga de 400 siclos torna a caverna de Macpela propriedade permanente e indiscutível da família de Abraão na terra prometida.
§ Teologia Reformada: A CFW XIX.4 e a CFB 19.4 afirmam que a lei de Deus regula as relações civis, inclusive transações de propriedade. Abraão negociou honestamente, pagou o preço justo e documentou legalmente a transação. Herman Bavinck (The Christian Family): "Que Abraão insistisse em pagar o preço justo mesmo quando lhe foi oferecido o campo gratuitamente revela integridade comercial integrada à fé. A família cristã não aceita vantagens indevidas mesmo quando oferecidas por gentileza — porque sua reputação de honestidade é parte de seu testemunho." Calvino (Comentário 23:9): "Abraão não aceitou o campo de graça porque gratuidade criaria dependência e ambiguidade de posse. Pagou para ter título claro. A integridade nas transações comerciais é virtude cristã tão real quanto a oração — e às vezes mais visível ao mundo."
§ Aplicação Familiar: Pais: "Levantou-se Abraão de diante do seu morto" (23:3) — Abraão chorou e depois se levantou para agir. A maturidade cristã diante da perda inclui tanto as lágrimas quanto a capacidade de se levantar e agir com responsabilidade. Como vocês ensinam os filhos a se levantar depois do luto? / Filhos: Abraão insistiu em pagar o preço justo mesmo quando lhe foi oferecido de graça. O que isso nos ensina sobre honestidade nas transações — não aceitar vantagens indevidas mesmo quando oferecidas? / Noivos: Que acordos financeiros e práticos vocês precisam fazer agora — antes do casamento — com clareza e honestidade, como Abraão fez com Efrom? A clareza nos acordos práticos é parte da integridade do lar. / Casal: Como vocês lidam com transações financeiras — pagamentos, acordos, compras? A integridade de Abraão em pagar o preço justo mesmo sem obrigação é modelo para a honestidade financeira do lar cristão. / Avós: A preparação para a morte inclui planejamento prático — testamentos, disposições, acordos claros com filhos. Abraão se levantou do luto e foi providenciar. Vocês têm tomado as providências práticas necessárias, com a clareza e honestidade de Abraão?

III. A SEPULTURA: O ATO DE FÉ NA TERRA DA PROMESSA (A')
§ Indicação Textual: Gn 23:17–19 ("assim ficou o campo de Efrom, que estava em Macpela, defronte de Manre... confirmado como propriedade de Abraão... e depois disto Abraão sepultou a Sara, sua mulher, na caverna do campo de Macpela, defronte de Manre, que é Hebrom, na terra de Canaã") e 23:20 ("assim ficou o campo e a caverna que nele havia confirmados a Abraão como posse de sepultura, da parte dos filhos de Hete") — a titulação legal e o ato de sepultura na terra prometida
§ Exegese: Os versículos 17-20 fecham a transação com linguagem legal detalhada: o campo, a caverna, as árvores nos limites do campo — tudo confirmado como propriedade de Abraão "diante de todos os que entravam pela porta da cidade" (23:18), ou seja, com testemunhas públicas. A documentação é minuciosa porque a posse importa. E então, 23:19: "Abraão sepultou a Sara... na terra de Canaã." Este detalhe — "na terra de Canaã" — não é geográfico: é teológico. Abraão poderia ter enterrado Sara em Harã (onde estava a família de Naor) ou em qualquer outro lugar. Ele insiste em enterrá-la na terra prometida — na terra para a qual Deus o havia chamado em Gênesis 12, a terra que ainda não era sua legalmente exceto por esta pequena parcela de 400 siclos. Enterrar na terra prometida é confissão de fé: "eu creio que esta terra será nossa, e por isso enterro aqui minha amada esperando a ressurreição."
§ Teologia Reformada: A CFW XXXII.1 e a CFB 31.1 ensinam que os corpos dos crentes "repousam em seus sepulcros até a ressurreição." A sepultura de Sara na terra prometida é ato escatológico: Abraão aguarda a ressurreição dos mortos na terra que Deus prometeu. Hebreus 11:13-16 interpreta a fé dos patriarcas que morreram sem receber as promessas: "confessando que eram estrangeiros e peregrinos sobre a terra... desejam uma pátria melhor, isto é, celestial." A sepultura de Sara em Canaã é o primeiro passo físico dessa confissão. R.C. Sproul (Last Days According to Jesus): "O cuidado cristão com os mortos — o sepultamento com dignidade — não é superstição: é confissão escatológica. O corpo que é sepultado aguarda a ressurreição. A família que cuida dos mortos com dignidade está confessando que eles não são lixo descartável, mas pessoas feitas à imagem de Deus que aguardam a redenção completa do corpo."
§ Aplicação Familiar: Pais: Como vocês falam sobre a morte e a ressurreição na presença dos filhos? A sepultura de Sara na terra prometida é ato de ensino: Abraão estava declarando com suas ações o que acreditava sobre Deus, a terra e a ressurreição. Nossos gestos diante da morte ensinam os filhos o que realmente cremos. / Filhos: Abraão sepultou Sara "na terra de Canaã" — na terra da promessa — porque acreditava que a promessa ainda era real mesmo depois da morte. O que você acredita sobre o que acontece depois da morte, e como essa crença muda a forma de você viver agora? / Noivos: Conversem sobre a morte — não como morbidez, mas como realidade que molda como se vive. Que crenças cristãs sobre morte, ressurreição e vida eterna vocês querem que estruturem o lar de vocês? / Casal: A sepultura de Sara foi ato de esperança escatológica de Abraão. Como a esperança da ressurreição molda o lar de vocês na prática — no luto, no planejamento, na conversa com os filhos sobre morte? / Avós: A perspectiva da própria morte — e a esperança da ressurreição — muda como você vive hoje? Compartilhe com filhos e netos o que a esperança cristã diante da morte significa para vocês — concretamente, não apenas como doutrina.

---

EIXO REDENTOR (HISTÓRICO-REDENTIVO)
Sara morreu como "estrangeira e peregrina" na terra prometida — e foi enterrada por Abraão que comprou com seu próprio dinheiro o único pedaço de terra da promessa que possuiu em vida. Hebreus 11:13-16 interpreta esse padrão: os patriarcas "confessando que eram estrangeiros e peregrinos sobre a terra... desejam uma pátria melhor, isto é, celestial." A caverna de Macpela apontava para além de Canaã — para a Nova Canaã, a nova criação onde os filhos da promessa habitarão para sempre (Ap 21:1-5). Cristo, o descendente prometido de Abraão, também foi sepultado (Mt 27:59-60) — mas seu túmulo ficou vazio (Mt 28:6). A ressurreição de Cristo é a garantia de que o que a sepultura de Sara aguardava se cumpriu: "eu sou a ressurreição e a vida" (Jo 11:25). A esperança escatológica de Abraão no monte Macpela encontrou seu fundamento definitivo no sepulcro vazio do Calvário.

DOUTRINA CENTRAL
A Esperança Escatológica no Luto Cristão: Abraão chorou a morte de Sara — porque a perda é real e o amor genuíno gera dor genuína. Mas se levantou, negociou com dignidade e sepultou Sara na terra da promessa — porque a fé que enterra com esperança confessa que a morte não é a última palavra. O luto cristão não é ausência de lágrimas; é presença de esperança nas lágrimas. A sepultura do crente na terra é confissão escatológica: aguardamos a ressurreição do corpo e a vida do mundo que há de vir. Cf. CFW XXXII; CFB 31; Hb 11:13-16.

APLICAÇÕES PARA A FAMÍLIA
▸ Para os Pais: "Levantou-se Abraão de diante do seu morto" — chorando e depois agindo. Ensinem os filhos que luto e responsabilidade coexistem: não se suprime o choro pela fé, nem se paralisa pela dor quando há o que fazer.
▸ Para os Filhos: Você tem permissão de chorar quando perde alguém. A fé cristã não elimina as lágrimas — as transforma. "Não como os que não têm esperança" — mas com esperança real, não com dor anestesiada.
▸ Para os Noivos: Conversem sobre a morte — a perspectiva da própria morte e da morte de quem amam. Que esperança cristã vocês querem que estruture o lar de vocês diante da inevitabilidade da perda?
▸ Para o Casal: Como casal, já planejaram práticas disposições diante da morte — testamentos, desejos, conversas com os filhos? Abraão se levantou do luto e providenciou. Integridade prática diante da morte é parte da fé.
▸ Para os Avós: A esperança da ressurreição — concreta, bíblica, pessoal — é a herança mais valiosa que vocês podem transmitir. Compartilhem com filhos e netos o que essa esperança significa para vocês na vida cotidiana.

DINÂMICA FAMILIAR
1. Leiam 23:1-2. Perguntem: "O texto diz que Abraão 'veio para prantear e para chorar.' Ele não suprimiu as lágrimas. O que isso nos ensina sobre como a fé lida com o luto?"
2. Leiam 23:3-4. Perguntem: "'Levantou-se Abraão de diante do seu morto.' Depois de chorar, ele agiu. Como você equilibra luto e responsabilidade — quando é tempo de chorar e quando é tempo de se levantar e agir?"
3. Leiam 23:9. Discutam: "Abraão insistiu em pagar o preço justo mesmo quando lhe foi oferecido de graça. O que isso nos ensina sobre integridade nas transações práticas?"
4. Leiam 23:19-20. Perguntem: "Abraão sepultou Sara 'na terra de Canaã' — na terra da promessa. Por que isso era importante? O que o local de sepultura confessava sobre o que Abraão acreditava?"
5. Discutam como família: "Como nós, como família cristã, lidamos com a morte? Que crenças sobre ressurreição e vida eterna estruturam nossa maneira de viver — e de morrer?"
6. Orem juntos com base na esperança escatológica: "Senhor, como Abraão enterrou Sara na terra da promessa, nós também ancoramos nossa esperança na ressurreição de Cristo. Que a perspectiva da vida eterna mude como vivemos juntos hoje."

AUTORES REFORMADOS
▸ J.C. Ryle (Expository Thoughts): "A fé cristã não suprime o luto — ela o transforma. Abraão chorou por Sara porque a amava e porque a perda é real. A diferença entre o luto do crente e do incrédulo não é a ausência de lágrimas — é a presença da esperança nas lágrimas."
▸ Herman Bavinck (The Christian Family): "Que Abraão insistisse em pagar o preço justo mesmo quando lhe foi oferecido o campo gratuitamente revela integridade comercial integrada à fé. A família cristã não aceita vantagens indevidas mesmo quando oferecidas por gentileza — porque sua reputação de honestidade é parte de seu testemunho."
▸ R.C. Sproul (Last Days According to Jesus): "O cuidado cristão com os mortos não é superstição: é confissão escatológica. O corpo que é sepultado aguarda a ressurreição. A família que cuida dos mortos com dignidade está confessando que eles não são descartáveis, mas pessoas feitas à imagem de Deus que aguardam a redenção completa do corpo."\`;

`;

if (!txt.includes(marcador)) {
  console.error('ERRO: marcador não encontrado');
  process.exit(1);
}

txt = txt.replace(marcador, novos + marcador);
fs.writeFileSync(filePath, txt, 'utf8');
console.log('OK — perícopes 31 a 33 inseridas em paraFamilia.ts');
