const fs = require('fs');
const path = require('path');
const outPath = path.join(__dirname, 'src/data/devocionalFamiliar.ts');

const dev = (dia, semana, estacao, leitura, subtema, tema, pg, rt, pger, rh, rm, cp, oa, rf) => {
  const o = { dia, semana, estacao, leitura, subtema, tema, tipo: 'devocional',
    perguntaGancho: pg, reflexaoTexto: rt, perguntaGeradora: pger,
    reflexaoHomem: rh, reflexaoMulher: rm, compromissoPratico: cp, oracaoAlianca: oa };
  if (rf) o.reflexaoFilhos = rf;
  return o;
};
const mesa = (dia, semana, estacao, tema, lc) => {
  const o = { dia, semana, estacao, leitura: 'Revisao da semana', subtema: tema, tema, tipo: 'mesa-alianca' };
  if (lc) o.leituraComplementar = lc;
  return o;
};
const aplic = (dia, semana, estacao, subtema, tema, rt, oa) =>
  ({ dia, semana, estacao, leitura: subtema, subtema, tema, tipo: 'aplicacao', reflexaoTexto: rt, oracaoAlianca: oa });

const days = [
  // SEMANA 5
  dev(29,5,'I — O Noivo se revela','Marcos 1','Urgencia e prontidao para servir juntos desde o inicio','Prontidao para servir',
    'Marcos abre com Jesus chamando discipulos que imediatamente deixam tudo — qual e a area onde a prontidao do casal para responder ao chamado de Deus ainda esta travada?',
    'O ritmo de Marcos e marcado pela urgencia — tudo acontece com prontidao. O chamado ao servico nao espera condicoes ideais. O casal que serve junto desde o inicio constroi um vinculo que a passividade nunca oferece.',
    'O que esta impedindo voces de servirem juntos com mais prontidao — falta de tempo, energia, visao ou disposicao?',
    'Voce tem sido o primeiro a responder ao chamado de servir dentro de casa — ou espera que o conjuge tome a iniciativa primeiro?',
    'A prontidao para servir comeca com disposicao interior — em qual area voce sente que sua disposicao precisa ser renovada?',
    'Identifiquem juntos uma oportunidade de servir alguem esta semana e executem-na juntos.',
    'Senhor, que sejamos prontos para servir como os primeiros discipulos. Amen.'
  ),
  dev(30,5,'I — O Noivo se revela','Marcos 2','Graca que restaura relacionamentos quebrados','Graca restauradora',
    'Os amigos do paralitico abriram o teto para leva-lo a Jesus — quem no lar de voces precisa ser carregado ao Senhor pelos outros agora?',
    'Jesus perdoa antes de curar — a ordem e reveladora. A graca que restaura relacionamentos comeca com o perdao que nao foi merecido e nao pode ser ganho.',
    'Ha algum aspecto do relacionamento que voces tem tentado consertar com esforco proprio ao inves de trazer ao Senhor para restauracao?',
    'Voce tem sido para o conjuge alguem que carrega as fraquezas ao Senhor em oracao — ou alguem que julga e pressiona pela mudanca?',
    'A graca que voce recebeu de Deus esta transbordando para o conjuge — ou voce tem uma conta de graca para Deus e outra, mais escassa, para o casamento?',
    'Orem juntos pedindo especificamente que Deus restaure um aspecto do relacionamento que parece paralisado.',
    'Senhor, tua graca restaura o que o pecado quebrou. Que essa mesma graca opere no nosso lar. Amen.'
  ),
  dev(31,5,'I — O Noivo se revela','Marcos 3','Prioridade da familia espiritual sem desprezar a natural','Familia espiritual e natural',
    'Quando a familia de Jesus veio busca-lo por acharem que ele estava fora de si, ele reposicionou as lealdades — como o casal equilibra familia extensa e chamado espiritual?',
    'O lar cristao pertence a uma familia maior: a comunidade da fe. Essa pertenca nao cancela os lacos naturais mas os contextualiza dentro de uma lealdade mais profunda ao Reino.',
    'Ha pressao da familia extensa sobre as decisoes do lar de voces que precisa ser gentil mas firmemente reposicionada?',
    'Voce tem protegido a familia nuclear das pressoes excessivas da familia extensa sem criar ruptura desnecessaria?',
    'Como voce tem nutrido os lacos com a comunidade de fe enquanto mantem os vinculos familiares naturais saudaveis?',
    'Conversem sobre um limite saudavel que precisam estabelecer ou reafirmar com a familia extensa.',
    'Pai, que pertencemos a ti antes de pertencermos a qualquer familia humana. Da-nos sabedoria para honrar todos os lacos. Amen.'
  ),
  dev(32,5,'I — O Noivo se revela','Marcos 4','Paciencia com o crescimento lento dentro do casamento','Crescimento lento e certo',
    'A parabola do crescimento secreto diz que a semente cresce sem que o agricultor saiba como — em qual area do conjuge voce precisa confiar no crescimento que nao ve ainda?',
    'O crescimento espiritual e relacional segue o ritmo da semente, nao do microondas. O casal que insiste em ver resultados imediatos perde a capacidade de celebrar o desenvolvimento gradual.',
    'Em qual aspecto do relacionamento voce tem pressionado por mudanca rapida ao inves de confiar no crescimento lento e genuino?',
    'Voce tem dado espaco ao crescimento gradual do conjuge sem pressionar por transformacoes que so Deus pode produzir?',
    'A impaciencia com o proprio crescimento ou com o do conjuge frequentemente vira critica — como voce pode substituir a critica pela confianca paciente?',
    'Identifiquem uma area de crescimento no conjuge que merece ser celebrada — mesmo que ainda incompleta.',
    'Senhor, da-nos paciencia com o teu processo. Que confiemos no crescimento que nao vemos ainda. Amen.'
  ),
  dev(33,5,'I — O Noivo se revela','Marcos 5; Marcos 6','Fe em meio ao desespero e a urgencia familiar / Perseverar apesar da rejeicao e do cansaco','Fe no desespero',
    'Jairo humilhou sua posicao social para prostrar-se diante de Jesus em desespero pela filha — ha uma necessidade urgente no lar de voces que exige esse mesmo humilhamento?',
    'Marcos 5 e 6 mostram fe em cenarios extremos: uma mulher doente ha doze anos, uma filha morta, Jesus rejeitado em sua propria cidade. Perseverar na fe diante da rejeicao e do cansaco e o teste mais dificil — e o mais formador.',
    'O cansaco ou a sensacao de rejeicao tem impedido voces de buscarem a Deus com a mesma urgencia que buscavam no inicio do relacionamento?',
    'Voce tem demonstrado para o conjuge que busca a Deus com urgencia quando o lar esta em necessidade?',
    'Como voce tem mantido a fe viva nos periodos em que o conjuge ou o lar parece estar passando por estagnacao ou rejeicao?',
    'Orem juntos por uma situacao do lar que parece desesperadora — com a fe de Jairo que se prostrou diante de Jesus.',
    'Senhor, que nos prostremos diante de ti nas nossas urgencias. Que a rejeicao e o cansaco nao nos afastem de ti. Amen.'
  ),
  dev(34,5,'I — O Noivo se revela','Marcos 7','Pureza interior acima da aparencia religiosa em casa','Pureza interior no lar',
    'Jesus ensina que o que contamina nao vem de fora, mas do coracao — o que no coracao de voces ainda precisa de limpeza antes que o lar seja purificado?',
    'Tradicoes religiosas externas podem esconder coracoes nao transformados. O lar cristao que cuida mais da aparencia espiritual do que da transformacao interior esta construindo uma ilusao.',
    'Que habito externo de espiritualidade no lar cobre uma realidade interior que precisa ser abordada com honestidade?',
    'Ha algo que vem do seu coracao — ciume, amargura, critica, impaciencia — que contamina o ambiente do lar mais do que qualquer influencia externa?',
    'Como voce tem cuidado da pureza interior — nao apenas como padrao moral, mas como resultado da comunhao com Deus?',
    'Cada um identifica uma impureza interior — nao do conjuge, mas de si mesmo — e pede perdao a Deus e ao conjuge.',
    'Senhor, cria em nos um coracao puro. Que o nosso lar seja transparente e genuino. Amen.'
  ),
  mesa(35,5,'I — O Noivo se revela','Mesa da Alianca — Semana 5'),

  // SEMANA 6
  dev(36,6,'I — O Noivo se revela','Marcos 8','Negar-se a si mesmo como caminho de amor conjugal','Negacao que liberta o amor',
    'Jesus diz que quem quiser salvar a sua vida a perdera — como isso se aplica a um casal onde cada um quer preservar sua autonomia e seu conforto?',
    'A negacao de si mesmo nao e autoestima baixa; e a libertacao do ego que exige sempre ser o centro. O amor conjugal mais profundo nasce quando cada conjuge escolhe o bem do outro acima do proprio conforto de forma consistente.',
    'Em qual area especifica do relacionamento voce mais resiste a negacao de si mesmo?',
    'Negar-se como lider significa servir antes de ser servido — em qual area do lar voce ainda exige privilegio ao inves de oferecer servico?',
    'A negacao de si nao e perda de identidade, mas de ego defensivo — o que mudaria no relacionamento se voce soltasse a necessidade de estar certa?',
    'Escolham hoje uma area onde cada um vai negar a preferencia propria em favor da preferencia do conjuge.',
    'Senhor, que percamos a vida por ti e por amor um ao outro — e encontremos vida mais abundante. Amen.'
  ),
  dev(37,6,'I — O Noivo se revela','Marcos 9','Humildade em vez de rivalidade dentro do lar','Humildade contra rivalidade',
    'Os discipulos discutiam no caminho quem seria o maior — voces tem discussoes semelhantes no lar, mesmo que em forma disfarcada?',
    'A rivalidade entre conjuges e sutil: pode aparecer como comparacao de quem trabalha mais, quem sacrifica mais, quem esta mais cansado. Jesus coloca uma crianca no centro como modelo de grandeza no Reino.',
    'Em quais momentos a rivalidade velada — quem faz mais, quem sabe mais, quem cedeu mais — aparece no lar de voces?',
    'Voce tem usado o argumento de quem prove mais ou quem trabalha mais para justificar menos servico em casa?',
    'Como voce pode cultivar humildade genuina no relacionamento sem cair na posicao de sempre ceder sem voz?',
    'Conversem honestamente sobre uma area onde a rivalidade ou a comparacao tem criado tensao.',
    'Senhor, que o menor seja o maior no nosso lar. Liberta-nos da rivalidade que divide. Amen.'
  ),
  dev(38,6,'I — O Noivo se revela','Marcos 10','O desenho de Deus para o um so corpo do casamento','Um so corpo',
    'Jesus cita Genesis ao falar sobre casamento: eles serao uma so carne. O que esta impedindo a unidade plena entre voces?',
    'Marcos 10 traz o ensino mais direto de Jesus sobre o casamento nos Evangelhos sinoticos. A unidade nao e apenas emocional ou espiritual — e fisica, pratica, cotidiana. O design de Deus para o casamento e totalidade compartilhada.',
    'Em quais dimensoes — emocional, espiritual, fisica, financeira — voces vivem mais em paralelo do que em unidade real?',
    'Voce tem construido a unidade do casal ativamente — conversas profundas, intimidade, projetos compartilhados — ou deixado o relacionamento funcionar no piloto automatico?',
    'A unidade requer abertura e vulnerabilidade — em qual area voce ainda mantem paredes que impedem a plena unidade?',
    'Identifiquem uma area onde precisam construir mais unidade e combinem uma acao pratica para esta semana.',
    'Senhor que fez os dois um so, que a nossa unidade seja real e profunda em todas as dimensoes. Amen.'
  ),
  dev(39,6,'I — O Noivo se revela','Marcos 11','Fe que produz fruto visivel na vida a dois','Fe com fruto visivel',
    'Jesus limpou o templo com indignacao santa — ha algo no lar de voces que precisa ser purificado com a mesma clareza e coragem?',
    'A entrada triunfal e a purificacao do templo mostram Jesus agindo com autoridade sobre o que e seu. A fe que move montanhas nao e magia — e confianca radical enraizada em relacionamento. Essa mesma fe opera dentro do lar.',
    'O que voces tem pedido em fe para o lar que ainda nao trouxeram honestamente diante de Deus?',
    'Ha algo no lar — um padrao, um habito, uma dinamica — que voce sabe que precisa mudar mas tem faltado coragem para confrontar?',
    'Como a sua fe ativa — nao apenas crencas, mas acoes — tem moldado o ambiente espiritual do lar?',
    'Orem juntos com fe especifica por algo concreto no lar — algo que parece impossivel humanamente.',
    'Senhor, que a nossa fe produza frutos visiveis. Que nao apenas creiamos mas oremos e ajamos com confianca em ti. Amen.'
  ),
  dev(40,6,'I — O Noivo se revela','Marcos 12','Amor sacrificial acima da aparencia de generosidade','Amor sacrificial real',
    'A viuva deu tudo o que tinha — dois obolos. Voce tem dado ao relacionamento o que sobra da sua energia e atencao, ou o que e mais precioso?',
    'A generosidade medida pelo que sobra e muito diferente da generosidade que da do que e essencial. Amor sacrificial real no casamento aparece nas pequenas renucias diarias — do tempo livre, do conforto, da razao de ser comprovada.',
    'O que voce oferece ao conjuge — do que sobra ou do que e precioso?',
    'Voce tem dado ao conjuge e ao lar sua atencao de qualidade — ou apenas as sobras de uma agenda preenchida por outras prioridades?',
    'Em quais maneiras voce tem sido generosa com o conjuge de forma que custa algo real — nao apenas o que e facil dar?',
    'Cada um decide dar ao conjuge algo precioso esta semana: tempo sem agenda, atencao plena, um gesto que custa.',
    'Senhor, que a nossa generosidade no lar nasca do amor, nao da aparencia. Que demos nao do sobro mas do essencial. Amen.'
  ),
  dev(41,6,'I — O Noivo se revela','Marcos 13; Marcos 14','Vigilancia fiel diante da incerteza do futuro / Entrega total apesar do medo e da traicao','Fidelidade sob pressao',
    'No Getsemani, Jesus quis que os discipulos velassem com ele — mas eles dormiram. Quem no casal tende a dormir quando o outro mais precisa de companhia?',
    'A vigilancia de Marcos 13 e a entrega do Getsemani em Marcos 14 formam o retrato da fidelidade sob pressao maxima. O casal que permanece desperto um para o outro nas noites dificeis do relacionamento expressa um amor que espelha o de Cristo.',
    'Ha algum medo ou traicao que ainda nao foi totalmente processado entre voces — que precisa ser trazido a superficie com honestidade e cuidado?',
    'Voce tem estado presente — de verdade presente — quando o conjuge enfrenta seus Getsemanis pessoais?',
    'Como voce tem comunicado ao conjuge que esta com ele mesmo nas noites mais dificeis — nas crises que ele nao escolheu?',
    'Conversem sobre um medo real sobre o futuro do lar e orem juntos sobre ele com entrega como a de Jesus.',
    'Senhor, que nao durmamos quando o outro precisa de nos. Que a fidelidade seja nossa resposta ao medo. Amen.'
  ),
  mesa(42,6,'I — O Noivo se revela','Mesa da Alianca — Semana 6'),

  // SEMANA 7
  dev(43,7,'I — O Noivo se revela','Marcos 15','Amor que vai ate o fim, mesmo sob sofrimento','Amor ate o fim',
    'Na cruz, Jesus amou ate o fim — o que significaria para o casamento de voces um amor que nao desiste mesmo quando o custo e alto?',
    'O amor que vai ate o fim nao e sempre intenso emocionalmente — as vezes e silencioso, fiel e presente quando seria mais facil desistir.',
    'Em qual momento do relacionamento voce sentiu mais fortemente a tentacao de desistir — e o que fez voce ficar?',
    'Amar ate o fim exige que o homem nao use a saida como ameaca ou como escape — como voce tem demonstrado permanencia ao conjuge?',
    'O amor ate o fim tambem se manifesta em nao guardar rancor silencioso — ha algo que voce ainda carrega que precisaria ser nomeado e liberado?',
    'Escrevam juntos ou verbalizem: \"Escolho ficar\" — uma renovacao simples do compromisso de permanencia.',
    'Jesus, que amaste ate o fim, ensina-nos esse mesmo amor. Amen.'
  ),
  dev(44,7,'I — O Noivo se revela','Marcos 16','Esperanca da ressurreicao que muda tudo no lar','Esperanca que transforma',
    'As mulheres foram ao tumulo esperando findar algo — e encontraram um comeco. Ha algo no lar de voces que parece morto mas precisa de fe na possibilidade de ressurreicao?',
    'A ressurreicao nao e apenas a vitoria sobre a morte fisica — e a declaracao de que Deus transforma fins em comecos. Relacionamentos que pareciam acabados podem ressurgir.',
    'Em qual dimensao do relacionamento voce mais precisa de esperanca renovada agora?',
    'Como a certeza da ressurreicao de Cristo fundamenta sua esperanca em Deus para o lar — especialmente nas areas que parecem sem vida?',
    'A esperanca ressurreiccional nao e negacao da realidade, mas confianca em Deus acima dela — como isso se traduz na forma como voce enfrenta as dificuldades do lar?',
    'Identifiquem juntos uma area do relacionamento que precisa de ressurreicao e orem especificamente pedindo renovacao.',
    'Senhor ressuscitado, que a tua vitoria sobre a morte seja esperanca viva em tudo que parece morto no nosso lar. Amen.'
  ),
  dev(45,7,'I — O Noivo se revela','Lucas 1','Deus age em casais que se sentem estereis ou pequenos demais','Deus escolhe o improvavel',
    'Zacarias e Isabel esperaram por decadas e pareciam fora do tempo quando Deus agiu — voces ja se sentiram pequenos demais ou tarde demais para que Deus usasse o lar de voces?',
    'Lucas 1 e um capitulo de casais: Zacarias e Isabel, Maria e Jose. Deus escolhe o improvavel, o velho, o jovem demais, o pequeno. A grandeza do lar cristao nao e medida pela aparencia externa mas pela disponibilidade ao proposito de Deus.',
    'Em qual area voces tem se sentido insuficientes para o chamado que Deus colocou no lar — e que mentira precisa ser substituida pela verdade do evangelho?',
    'Zacarias duvidou e ficou em silencio — como voce processa a duvida sobre o chamado de Deus para o seu lar?',
    'Maria disse \"eis aqui a serva do Senhor\" — em qual area do lar voce precisa renovar essa postura de disponibilidade?',
    'Declarem juntos uma area especifica do lar que entregam a soberania de Deus — mesmo sem entender o plano.',
    'Senhor que escolhes o improvavel, usa-nos mesmo na nossa insuficiencia. Que o nosso lar seja lugar de tua gloria. Amen.'
  ),
  dev(46,7,'I — O Noivo se revela','Lucas 2','Familia obediente a Palavra e a promessa recebida','Familia obediente a Palavra',
    'Jose e Maria cumpriram todos os rituais da Lei mesmo sendo a familia escolhida para o Messias — como a obediencia a Palavra molda a rotina espiritual do lar de voces?',
    'A obediencia de Jose e Maria nao era performatica — era o ritmo de quem vive pela Palavra. O lar que obedece cria um ambiente onde a promessa cresce.',
    'Quais praticas de obediencia a Palavra — culto familiar, oracao, leitura biblica — o lar de voces tem cultivado com consistencia?',
    'Como voce tem liderado o lar em obediencia a Palavra — nao como regra religiosa mas como amor de resposta?',
    'Maria guardava e meditava as coisas no coracao — voce tem cultivado uma vida interior de meditacao que alimente o lar?',
    'Estabelecam ou reafirmem uma pratica espiritual regular para o lar — algo simples mas constante.',
    'Senhor, que a obediencia seja o ritmo do nosso lar. Que a tua Palavra forme o ambiente onde a vida a dois cresce. Amen.',
    'Lucas 2 mostra a familia de Jesus cumprindo os ritos religiosos com fidelidade — como voce pode transmitir aos seus filhos o valor da obediencia como amor, nao como fardo?'
  ),
  dev(47,7,'I — O Noivo se revela','Lucas 3','Preparacao de coracao antes de qualquer missao em conjunto','Preparacao antes da missao',
    'Joao Batista chamou as pessoas a preparacao antes de qualquer avanco espiritual — o que no lar de voces precisa ser preparado ou limpo antes de avancar?',
    'Preparar o caminho do Senhor e uma imagem de remocao de obstaculos interiores. Arrependimento, reordenamento de prioridades, humildade — tudo isso prepara o terreno para que Deus aja.',
    'Que obstaculo interior — no coracao de cada um — esta impedindo o avanco espiritual do lar?',
    'O arrependimento genuino muda o comportamento — em qual area da sua vida ha necessidade de arrependimento real que afeta o lar?',
    'A preparacao espiritual comeca com disponibilidade de coracao — como voce tem criado espaco para Deus trabalhar em voce antes de trabalhar atraves de voce?',
    'Cada um ora em voz alta por arrependimento de algo especifico — sem encobrir, mas com honestidade diante de Deus e do conjuge.',
    'Senhor, prepara os nossos coracoes. Remove os obstaculos que impedem tua obra no lar. Amen.'
  ),
  dev(48,7,'I — O Noivo se revela','Lucas 4','Fidelidade a Palavra mesmo sob pressao e rejeicao','Fidelidade sob rejeicao',
    'Jesus foi rejeitado em sua propria cidade, por seus proprios conhecidos — como voces tem respondido quando a fidelidade a Deus gera incompreensao em quem esta proximo?',
    'Lucas 4 mostra Jesus resistindo a tentacao com a Escritura e permanecendo fiel mesmo quando a rejeicao vem de dentro — da propria comunidade. O casal cristao as vezes enfrenta a maior pressao nao do mundo, mas de dentro da propria familia extensa.',
    'Ha alguma conviccao espiritual do lar que esta sob pressao de rejeicao ou incompreensao por pessoas proximas?',
    'Voce tem sido fiel a conviccao biblica mesmo quando ela nao e popular — inclusive dentro do lar?',
    'Como voce tem protegido os valores do lar quando ha pressao externa para ceder?',
    'Conversem sobre uma conviccao do lar que voces querem proteger juntos — e como farao isso concretamente.',
    'Senhor, que sejamos fieis a tua Palavra mesmo quando a rejeicao vem de perto. Amen.'
  ),
  mesa(49,7,'I — O Noivo se revela','Mesa da Alianca — Semana 7'),

  // SEMANA 8
  dev(50,8,'I — O Noivo se revela','Lucas 5','Deixar tudo para seguir o chamado juntos','Largar as redes juntos',
    'Pedro, Tiago e Joao deixaram tudo e o seguiram — o que ainda esta nas maos de voces que precisaria ser largado para seguir o chamado juntos mais plenamente?',
    'Largar as redes nao significa irresponsabilidade, mas reordenamento de prioridades. O casal que faz de Deus a primeira lealdade descobre que as outras dimensoes da vida ganham sentido e ordem.',
    'Ha algo — projeto, ambicao, habito, relacionamento — que voces sabem que precisariam largar para servir a Deus com mais inteireza?',
    'Voce tem chamado o conjuge a um projeto maior que voces mesmos — ou o lar esta fechado em si mesmo?',
    'Ha redes de seguranca que voce ainda segura por medo, ao inves de confiar em Deus para o que vem depois?',
    'Orem juntos pedindo que Deus identifique o que precisa ser largado para um proximo passo.',
    'Senhor, que larguemos o que segura para seguir-te mais livremente juntos. Amen.'
  ),
  dev(51,8,'I — O Noivo se revela','Lucas 6; Lucas 7','Carater radical de amor dentro do proprio lar / Compaixao e perdao que restauram relacoes partidas','Amor radical dentro de casa',
    'Jesus manda amar os inimigos — quanto mais devemos amar o conjuge, que e aliado, nao inimigo. Ha momentos em que voce trata o conjuge como adversario?',
    'As bem-aventurancas de Lucas incluem bencaos e ais — o amor radical que Jesus prega nao e neutro. Ele transforma a forma como enxergamos os conflitos: o conjuge nunca e o inimigo real.',
    'Em quais momentos de conflito voce tende a posicionar o conjuge como adversario ao inves de aliado contra o problema?',
    'Como voce pode demonstrar amor ativo e concreto ao conjuge nas proximas 24 horas — nao apenas ausencia de conflito?',
    'A compaixao que Jesus demonstra pela viuva de Naim nao espera pedido — como voce pode se antecipar a necessidade do conjuge esta semana?',
    'Facam algo surpreendente e generoso um pelo outro hoje — sem que seja esperado.',
    'Senhor, que o amor radical que pregaste seja o amor que praticamos em casa. Amen.'
  ),
  dev(52,8,'I — O Noivo se revela','Lucas 8','Fe firme em meio a tempestade familiar','Firmes na tempestade',
    'Jesus dormia na tempestade — e os discipulos entraram em panico. Quem no casal tende a entrar em panico mais rapido quando a tempestade chega ao lar?',
    'A tempestade acalmada por Jesus e uma imagem de sua soberania sobre tudo o que ameaca. A mulher com fluxo de sangue e a filha de Jairo mostram que a fe alcanca Jesus mesmo em multidoes e urgencias.',
    'Qual tempestade atual no lar de voces voces precisam trazer a Jesus com mais urgencia e confianca?',
    'Voce tem sido presenca tranquilizadora e ancora espiritual para o conjuge nas tempestades — ou aumenta a ansiedade do lar?',
    'A mulher tocou o manto de Jesus discretamente, mas com fe real — como voce busca a Deus nas suas crises pessoais que afetam o lar?',
    'Orem juntos sobre a principal tempestade atual do lar — com a fe de quem cre que Jesus esta no barco.',
    'Senhor que acalmas as tempestades, que a tua paz governe nosso lar mesmo nas crises. Amen.'
  ),
  dev(53,8,'I — O Noivo se revela','Lucas 9','Prioridades claras para um casal que serve','Prioridades definidas',
    'Quem quiser salvar a sua vida, a perdera — como essa inversao do reino se manifesta nas prioridades praticas do lar de voces?',
    'Lucas 9 e cheio de chamados: enviar, alimentar, confessar, carregar a cruz. O casal que nao definiu prioridades claras e arrastado por qualquer demanda urgente. Clareza de chamado produz paz mesmo em vida ocupada.',
    'Se voces tivessem que listar as tres prioridades principais do lar, o que estaria nessa lista — e o cotidiano reflete essas prioridades?',
    'Voce tem exercido a lideranca de definir e guardar as prioridades do lar — ou deixa que o urgente sempre substitua o importante?',
    'Ha distracoes ou compromissos que voce sabe que estao deslocando as prioridades mais importantes do lar?',
    'Escrevam juntos as tres prioridades do lar para esta temporada de vida.',
    'Senhor, clarifica nossas prioridades. Que nao percamos o essencial pelo urgente. Amen.'
  ),
  dev(54,8,'I — O Noivo se revela','Lucas 10','Equilibrio entre servico e presenca dentro de casa','Servico e presenca equilibrados',
    'Jesus nao reprovou Marta por servir, mas por deixar o servico roubar a presenca — em qual area do lar o ativismo tem substituido a presenca real?',
    'Maria escolheu a boa parte — presenca antes de produtividade. O lar que so funciona mas nao se encontra esta perdendo algo essencial. Servico e presenca precisam coexistir, mas a presenca tem prioridade sobre o desempenho.',
    'Qual conjuge tende mais a postura de Marta — e como isso cria tensao no relacionamento?',
    'Voce esta presente emocionalmente no lar — ou fisicamente presente mas mentalmente ausente na agenda, no trabalho ou no celular?',
    'Como voce cultiva momentos de presenca genuina com o conjuge — nao apenas de gerenciamento eficiente do lar?',
    'Estabelecam um momento diario de presenca genuina — sem agenda, sem servico — so para estarem juntos.',
    'Senhor, que escolhamos a boa parte tambem dentro de casa. Que a presenca preceda o servico. Amen.'
  ),
  dev(55,8,'I — O Noivo se revela','Lucas 11','Oracao como habito diario e nao ocasional do casal','Oracao como habito diario',
    'Os discipulos pediram a Jesus que os ensinasse a orar — e isso sugere que orar bem e algo que se aprende. Como esta o aprendizado de oracao do casal de voces?',
    'A oracao que Jesus ensina comeca com o Pai — nao com as necessidades. O casal que ora junto regularmente constroi um vinculo espiritual que vai alem do emocional e do fisico.',
    'O que tem impedido o casal de orar junto com mais consistencia — e o que seria necessario mudar para tornar isso um habito real?',
    'Voce tem assumido a iniciativa de convidar o conjuge para momentos de oracao juntos — ou espera que isso aconteca espontaneamente?',
    'Como voce pode tornar a oracao conjunta mais natural e menos formal no cotidiano do lar?',
    'Comprometam-se a orar juntos por 5 minutos todas as noites por 7 dias — simples, curto, consistente.',
    'Pai, ensina-nos a orar. Que a nossa oracao conjunta seja o fio de ouro que une nosso lar a ti. Amen.'
  ),
  mesa(56,8,'I — O Noivo se revela','Mesa da Alianca — Semana 8'),

  // SEMANA 9
  dev(57,9,'I — O Noivo se revela','Lucas 12','Confiar a Deus o sustento e o futuro da familia','Confiar o futuro a Deus',
    'Jesus fala ao casal sobrecarregado de preocupacoes — qual preocupacao sobre o futuro do lar tem tirado o sono de voces?',
    'A soberania de Deus sobre as aves e os lirios nao e ilustracao abstrata — e o fundamento de uma confianca real. O casal que entrega o futuro a Deus vive com uma leveza que o planejamento ansioso nunca oferece.',
    'Ha uma area financeira ou de futuro no lar que voces tem tentado controlar ao inves de confiar?',
    'Voce tem sido fonte de confianca e paz para o conjuge em relacao ao futuro — ou e sua ansiedade que mais aparece nessas conversas?',
    'Como voce expressaria a confianca em Deus para o futuro do lar de forma concreta — nao apenas em palavras?',
    'Identifiquem uma preocupacao especifica sobre o futuro e orem sobre ela com a confianca de quem sabe que Deus prove.',
    'Pai, o futuro do nosso lar esta nas tuas maos. Ensina-nos a confiar e a viver com leveza. Amen.'
  ),
  dev(58,9,'I — O Noivo se revela','Lucas 13','Paciencia com o crescimento espiritual do outro','Paciencia com o crescimento do outro',
    'A figueira recebeu mais um ano — Deus e paciente com o crescimento lento. Como voce tem sido paciente com o ritmo espiritual do conjuge?',
    'A paciencia de Deus com a figueira esteril e um retrato de sua longanimidade com cada um de nos. O casal que aprende a dar espaco para o crescimento do outro sem pressionar cria um ambiente onde a transformacao pode acontecer.',
    'Em qual area voce tem sido impaciente com o crescimento do conjuge — e como isso tem afetado o relacionamento?',
    'Voce tem orado pela transformacao do conjuge ou apenas esperado e criticado quando a mudanca nao vem?',
    'Como voce pode expressar encorajamento ao crescimento do conjuge ao inves de frustracao com o ritmo?',
    'Digam um ao outro uma area de crescimento que percebem no outro — com gratidao, nao como cobranca.',
    'Senhor, que sejamos pacientes um com o outro como tu es conosco. Amen.'
  ),
  dev(59,9,'I — O Noivo se revela','Lucas 14; Lucas 15','Contar o custo antes de construir a vida a dois / A alegria da reconciliacao restaurada em familia','Contar o custo e celebrar a volta',
    'Jesus diz que e preciso sentar e contar o custo antes de construir — voces contaram o custo real do casamento antes de comecar?',
    'Lucas 14 e 15 formam um contraste belissimo: a seriedade de quem planeja e a festa de quem recebe o perdido de volta. O filho prodigo nao apenas volta — ele e recebido com festa. O casamento que aprende a celebrar o retorno e as reconciliacoes e mais saudavel do que o que apenas tolera.',
    'Ha algo no relacionamento de voces que nunca foi totalmente celebrado — um retorno, uma reconciliacao, uma superacao — e que merece ser comemorado?',
    'Voce ja sentou honestamente para contar o custo do casamento — nao apenas os beneficios, mas o que ele exige?',
    'Ha uma historia de reconciliacao no relacionamento de voces que precisaria ser celebrada com mais gratidao e alegria?',
    'Planejem juntos uma pequena celebracao de algo que Deus fez no relacionamento — uma virada, uma superacao.',
    'Pai, que celebremos o que tu restauras. Que contemos o custo com coragem e dancemos quando o perdido volta. Amen.'
  ),
  dev(60,9,'I — O Noivo se revela','Lucas 16','Fidelidade com o que Deus ja confiou ao lar','Fidelidade com o que foi dado',
    'Jesus diz que quem e fiel no pouco e fiel no muito — em qual area pequena do lar voces tem sido descuidados?',
    'A parabola do administrador injusto ensina sobre fidelidade com o que foi confiado. O lar, as financas, o tempo, o relacionamento — tudo e administracao do que pertence a Deus.',
    'Em qual dimensao do lar — financeira, espiritual, relacional — voces tem sido menos fieis do que deveriam?',
    'Voce tem administrado com integridade os recursos e responsabilidades do lar — ou ha areas de negligencia que voce sabe que precisariam ser corrigidas?',
    'Como voce pode demonstrar fidelidade em uma area pequena do lar esta semana — algo que tem adiado ou negligenciado?',
    'Identifiquem uma area de administracao do lar que precisa de mais fidelidade e combinem uma acao concreta.',
    'Senhor, da-nos fidelidade no pouco para que possas confiar-nos o muito. Amen.'
  ),
  dev(61,9,'I — O Noivo se revela','Lucas 17','Gratidao e perdao constantes dentro do casamento','Gratidao e perdao constantes',
    'Dos dez leprosos curados, so um voltou para agradecer — como esta a proporcao de gratidao no lar de voces?',
    'A gratidao e o perdao sao dois habitos que, praticados juntos, criam uma cultura de graca dentro do lar. O leproso que voltou para agradecer nao estava obrigado — ele estava transformado.',
    'Voce tem expressado gratidao pelo conjuge com regularidade — ou o reconhecimento e raro e o lar vive de critica implicita?',
    'Em quais areas do relacionamento voce precisa de renovacao da gratidao — lugares onde o habitual se tornou invisivel?',
    'Como voce pode cultivar um espirito de gratidao pratica pelo conjuge nos proximos dias?',
    'Cada um diz tres coisas especificas pelo qual e grato no conjuge — coisas concretas, nao genericas.',
    'Senhor, que a gratidao seja habito do nosso lar. Que nao sejamos os nove que nao voltaram. Amen.'
  ),
  dev(62,9,'I — O Noivo se revela','Lucas 18','Humildade e persistencia na oracao do casal','Persistir em oracao',
    'A viuva persistia diante do juiz — e Jesus usa essa imagem para ensinar sobre oracao. O casal tem orado com essa tenacidade pelas necessidades do lar?',
    'Lucas 18 apresenta dois personagens que sao modelo de oracao e um que e antitipo: o fariseu orgulhoso e o publicano humilhado. A oracao que agrada a Deus e aquela que parte da consciencia da propria necessidade.',
    'O casal tem orado juntos com humildade real — reconhecendo a propria dependencia de Deus — ou a oracao e mais performance espiritual?',
    'Voce tem orado com persistencia por algo especifico para o lar — ou desiste depois de um tempo sem resposta visivel?',
    'Como voce pode cultivar maior humildade na sua oracao pessoal e na oracao conjunta com o conjuge?',
    'Orem juntos hoje com a humildade do publicano — reconhecendo a necessidade e confiando na graca de Deus.',
    'Senhor, que venhamos a ti como o publicano, nao como o fariseu. Que nossa oracao seja real e persistente. Amen.'
  ),
  mesa(63,9,'I — O Noivo se revela','Mesa da Alianca — Semana 9'),

  // SEMANA 10
  dev(64,10,'I — O Noivo se revela','Lucas 19','Transformacao real que gera frutos visiveis em casa','Transformacao com frutos reais',
    'Zaqueu nao apenas acreditou — ele mudou de vida imediatamente, de forma pratica e verificavel. Qual mudanca pratica deveria caracterizar o lar de voces?',
    'A conversao de Zaqueu e verificada pelo que muda em seu comportamento com o dinheiro. A transformacao que Cristo opera nao e apenas interior — ela produz frutos visiveis. O lar cristao e aquele onde a graca produz mudanca real e observavel.',
    'Qual mudanca pratica o casal sabe que precisa acontecer no lar — mas que tem sido adiada por desconforto ou comodidade?',
    'Ha uma area financeira ou de relacionamento no lar onde a transformacao deveria ter produzido mais fruto do que tem produzido?',
    'Como voce pode demonstrar esta semana que a fe que professa esta produzindo mudanca real no cotidiano do lar?',
    'Identifiquem juntos uma mudanca pratica que querem implementar no lar como fruto de transformacao espiritual.',
    'Senhor, que a tua graca produza em nos mudancas reais e visiveis. Que o lar testemunhe da tua obra. Amen.'
  ),
  dev(65,10,'I — O Noivo se revela','Lucas 20','Prioridades corretas diante de Deus e do mundo','Prioridades certas',
    'Dai a Cesar o que e de Cesar e a Deus o que e de Deus — como o casal tem equilibrado lealdades e prioridades nessa tensao?',
    'Jesus nao ignora as responsabilidades civis — mas as subordina claramente a uma lealdade maior. O lar cristao precisa de clareza sobre o que pertence a Deus e o que pertence ao mundo.',
    'Ha alguma area da vida do lar onde a pressao cultural ou social esta competindo com o que voces sabem que pertence a Deus?',
    'Voce tem tomado decisoes de lideranca no lar a partir das prioridades do Reino — ou a partir da pressao cultural ao redor?',
    'Como voce tem ajudado o conjuge a manter as prioridades corretas diante das multiplas demandas do cotidiano?',
    'Conversem sobre uma area de tensao entre as exigencias do mundo e o chamado de Deus — e como querem responder a ela.',
    'Senhor, que te demos o que e teu — a primazia sobre tudo. Que as prioridades do Reino ordenem o nosso lar. Amen.'
  ),
  dev(66,10,'I — O Noivo se revela','Lucas 21','Generosidade sacrificial e vigilancia fiel','Dar com generosidade sacrificial',
    'A viuva deu de sua pobreza — nao de sua abundancia. Em que dimensao o lar de voces tem dado do que e precioso, nao apenas do que sobra?',
    'A generosidade que Jesus honra nao e calculada pela quantidade mas pela proporcao do sacrificio. O lar que aprende a dar de forma sacrificial desenvolve uma liberdade em relacao ao material que e profundamente formadora.',
    'Ha uma area onde voces sentem o chamado de dar de forma mais sacrificial — financeiramente, de tempo, de energia — mas tem resistido?',
    'Voce tem liderado o lar em generosidade genuina — nao apenas com o que sobra, mas com o que custa?',
    'Como voce pode estimular uma cultura de generosidade no lar que seja transmitida como valor para os filhos?',
    'Comprometam-se a um gesto de generosidade sacrificial esta semana — algo que custa mais do que o habitual.',
    'Senhor, que seamos generosos como a viuva — do poco que temos, nao do sobro que nos resta. Amen.',
    'A generosidade da viuva e um modelo para os filhos de que dar e um ato de fe, nao de abundancia — como voce tem ensinado isso em casa?'
  ),
  dev(67,10,'I — O Noivo se revela','Lucas 22; Lucas 23','A instituicao da alianca e a fraqueza humana reconhecida / Sofrimento inocente e perdao levado ate o fim','Alianca e fraqueza reconhecida',
    'Jesus institui a Ceia da alianca na noite em que seria traido — o que isso diz sobre o amor que nao depende do comportamento do amado para ser fiel?',
    'Lucas 22 e 23 mostram o mais alto e o mais baixo da experiencia humana juntos: a instituicao da alianca e a traicao, a entrega e o abandono, o amor maximo e a fraqueza dos que amam. Pedro negou e voltou. O lar que sobrevive a traicoes menores aprende com esses textos que o retorno e possivel.',
    'Ha algum momento em que voce falhou o conjuge de forma significativa — e como voce processou isso entre si?',
    'Como o exemplo de Jesus na cruz — perdonado os que o crucificaram — ilumina o que voce e chamado a fazer com as falhas do conjuge?',
    'O sofrimento injusto e parte da experiencia crista — como voce tem respondido quando sofre algo injusto dentro do proprio relacionamento?',
    'Orem juntos pela graca de amar mesmo quando o amado falha — e pela coragem de voltar quando voces falham.',
    'Senhor, que a alianca que instituiste seja mais forte do que as nossas fraquezas. Que o perdao que tu tens por nos flua entre nos. Amen.'
  ),
  dev(68,10,'I — O Noivo se revela','Lucas 24','Esperanca que reacende o coracao desanimado do casal','Esperanca que reaviva',
    'Os dois discipulos de Emaus estavam indo embora — desanimados, vencidos. Jesus se aproxima e caminha com eles. O lar ja passou por uma temporada assim?',
    'A historia de Emaus e a historia do coracao que perdeu a esperanca — e foi encontrado pelo Ressuscitado no caminho. Jesus nao repreende o desanimo; ele entra nele e o transforma com a Palavra e a presenca.',
    'Ha alguma esperanca que voces tinham para o lar que parece ter se apagado — e que precisaria ser reaquecida pela Palavra de Deus?',
    'Voce tem sido presenca que acende esperanca no conjuge quando ele esta no caminho de Emaus — ou voce mesmo esta nesse caminho e precisa de encorajamento?',
    'Como a Palavra de Deus tem reaquecido o coracao de voces nas temporadas de desanimo do lar?',
    'Compartilhem um momento em que a Palavra de Deus reaqueceu a esperanca de voces — e orem por quem esta em Emaus agora.',
    'Senhor ressuscitado, caminha conosco quando estamos desanimados. Aquece nosso coracao com a tua Palavra. Amen.'
  ),
  dev(69,10,'I — O Noivo se revela','Joao 1','Deus habita entre nos, inclusive dentro do lar','O Verbo habita no lar',
    'O Verbo se fez carne e habitou entre nos — o que significa que Deus escolheu habitar em um espaco fisico, em um lar real?',
    'A incarnacao de Cristo e a declaracao maxima de que Deus nao e distante — ele habitou entre nos. O lar que recebe a presenca de Cristo nao e um espaco sagrado apenas nos domingos; e um lugar onde Deus habita no cotidiano.',
    'Como o lar de voces pode ser mais conscientemente um lugar de habitacao da presenca de Deus — nao apenas um espaco de convivencia?',
    'Voce tem levado a serio que Deus habita no lar — que suas palavras, seus gestos e suas atitudes dentro de casa acontecem diante da sua presenca?',
    'Como voce pode criar um ambiente no lar onde a presenca de Cristo seja bem-vinda e bem recebida — nao apenas tolerada?',
    'Orem juntos convidando a presenca de Cristo para cada comodo do lar — de forma concreta e pessoal.',
    'Senhor Verbo encarnado, que habites no nosso lar com a mesma realidade com que habitaste entre os homens. Amen.'
  ),
  mesa(70,10,'I — O Noivo se revela','Mesa da Alianca — Semana 10'),

  // SEMANA 11
  dev(71,11,'I — O Noivo se revela','Joao 2','Jesus honra o casamento com sua primeira gloria revelada','Jesus nas bodas',
    'Jesus realizou seu primeiro milagre em um casamento — o que isso diz sobre o valor que ele da ao casamento?',
    'A presenca de Jesus nas bodas de Cana nao e acidental; e a declaracao de que o casamento e digno da sua primeira manifestacao de gloria. Quando o vinho acaba — quando os recursos, a energia ou a paixao inicial diminuem — Jesus transforma o que ha em algo melhor.',
    'Em qual area do relacionamento o vinho acabou — onde os recursos ou a energia estao baixos — e voces precisam da intervencao de Jesus?',
    'Voce esta trazendo as necessidades do casamento a Jesus com a confianca de Maria — \"fazei tudo o que ele vos disser\"?',
    'Como a presenza de Cristo no casamento de voces tem transformado o que parecia insuficiente em algo melhor?',
    'Orem juntos sobre a area onde o vinho acabou — e confiem que Jesus pode transformar.',
    'Senhor que honraste o casamento com tua primeira gloria, continua a agir no nosso. Transforma o que temos em algo melhor do que imaginamos. Amen.'
  ),
  dev(72,11,'I — O Noivo se revela','Joao 3','Renovacao interior necessaria para amar de verdade','Nascer de novo para amar',
    'Jesus diz a Nicodemos que e preciso nascer de novo — que ninguem pode ver o Reino sem essa renovacao. Como essa verdade se aplica ao amor conjugal?',
    'O amor conjugal que nao nasce do Espirito de Deus tende a ser condicional, calculado e sazonal. O novo nascimento nao e apenas para a vida eterna — e o que torna possivel amar com o amor de Deus que e incondicional.',
    'Em qual area do seu amor pelo conjuge voce percebe que ainda esta operando a partir da natureza velha — ego, controle, expectativa — ao inves da natureza nova?',
    'Como o novo nascimento tem mudado a forma como voce ama — de forma concreta e verificavel no relacionamento?',
    'O Espirito sopra onde quer — como voce tem se mantido aberto a obra do Espirito no seu coracao para que o amor se renove?',
    'Orem juntos pedindo que o Espirito renuove o amor de voces — de forma especifica e honesta.',
    'Senhor, que o novo nascimento que nos deste produza um amor novo que excede o que somos por nos mesmos. Amen.'
  ),
  dev(73,11,'I — O Noivo se revela','Joao 4','Jesus ve e restaura historias conjugais quebradas','Jesus restaura historias quebradas',
    'Jesus encontrou a mulher samaritana — com toda a sua historia de relacionamentos quebrados — e nao a condenou. Como isso fala ao casal sobre historias dificeis do passado?',
    'A conversa de Jesus com a samaritana e uma das mais notaveis do Evangelho: ele ve o que ela esconde, nao julga o que ela falhou e oferece o que ela mais precisa. O lar que traz suas historias quebradas a Jesus descobre agua viva que sacia.',
    'Ha alguma historia do passado — propria ou do conjuge — que ainda nao foi trazida completamente a Jesus para restauracao?',
    'Como voce tem lidado com o passado do conjuge que voce conhece — com a graca de Jesus ou com julgamento que nao cabe a voce?',
    'A agua viva que Jesus oferece e o que sacia — o que voce tem buscado para saciar o que so Cristo pode satisfazer?',
    'Se ha uma historia quebrada do passado que ainda pesa no relacionamento, orem juntos sobre ela hoje.',
    'Senhor que viste a samaritana sem condenar, ve-nos e restaura o que foi quebrado em nos antes de nos encontrarmos. Amen.'
  ),
  dev(74,11,'I — O Noivo se revela','Joao 5','Disposicao de ser curado, nao apenas de reclamar do sofrimento','Querer ser curado',
    'Jesus pergunta ao paralítico: \"Queres ser curado?\" — essa pergunta tambem e para o casal. Ha dores relacionais que voces preferem cultivar a curar?',
    'A pergunta de Jesus ao paralitico e perturbadora porque sugere que nao e obvio que todos querem ser curados. Algumas pessoas preferem a dor conhecida a incerteza da cura. Isso vale tambem para padroes relacionais.',
    'Ha algum padrao disfuncional no relacionamento de voces que voces ja se acostumaram — e que precisaria ser curado?',
    'Voce prefere reclamar do que o conjuge nao faz a dar o passo de pedir ajuda — de Deus, do conjuge ou de um conselheiro?',
    'O que mudaria no relacionamento se voces dissessem a Deus: \"Queremos ser curados\" — em relacao a um padrao especifico?',
    'Identifiquem um padrao relacional que precisa de cura e orem especificamente pedindo a Deus essa intervencao.',
    'Senhor, que queiramos ser curados mais do que ter razao. Que te entroguemos os padroes que precisam de transformacao. Amen.'
  ),
  dev(75,11,'I — O Noivo se revela','Joao 6; Joao 7','Cristo como sustento diario e constante da familia / Sede que so e satisfeita em Cristo','Cristo como sustento real',
    'Jesus diz \"Eu sou o pao da vida\" — em que medida ele tem sido o sustento real do lar de voces, nao apenas um elemento da rotina religiosa?',
    'O discurso do pao da vida em Joao 6 e radical: muitos discipulos foram embora porque a exigencia era exclusiva. O lar que tem Cristo como centro real descobre que ele sacia o que nenhuma outra coisa pode saciar.',
    'Qual necessidade do lar voces tem tentado saciar com substitutos — trabalho, entretenimento, aprovacao — que so Cristo pode genuinamente suprir?',
    'Voce tem se alimentado da Palavra de Deus como o pao diario que sustenta sua vida e seu amor pelo conjuge?',
    'Como a sede espiritual nao saciada de um dos conjuges tem afetado o lar — e o que precisa mudar?',
    'Comprometam-se juntos a se alimentar da Palavra de Deus diariamente nesta semana — nao como regra, mas como necessidade real.',
    'Senhor pao da vida, sacia-nos. Que te busquemos a ti antes de buscar qualquer outro sustento. Amen.'
  ),
  dev(76,11,'I — O Noivo se revela','Joao 8','Graca que nao condena, mas tambem nao deixa como esta','Graca sem condenacao',
    'Jesus diz a mulher adultera: \"Nem eu te condeno; vai e nao peques mais\" — como esse modelo une graca e chamado a santidade dentro do casamento?',
    'A graca sem condenacao e tambem a graca que nao deixa como esta. Jesus nao minimiza o pecado; ele o perdoa e direciona a um caminho diferente. O amor conjugal que modela isso nao e permissividade — e cuidado que exige o melhor do amado.',
    'Ha alguma area onde voce tem sido mais condenatorio do que graciosos com o conjuge — ou onde voce tem confundido graca com permissividade?',
    'Voce tem dito ao conjuge que nao o condena quando ele falha — de forma credivel, nao apenas formal?',
    'Como voce pode expressar simultaneamente graca real e expectativa saudavel de crescimento ao conjuge?',
    'Orem juntos pedindo a sabedoria de Jesus — que nem condena nem deixa como esta.',
    'Senhor, que a nossa graca seja real como a tua. Que nao condenemos, mas tambem nao sejamos indiferentes ao crescimento do outro. Amen.'
  ),
  mesa(77,11,'I — O Noivo se revela','Mesa da Alianca — Semana 11'),

  // SEMANA 12
  dev(78,12,'I — O Noivo se revela','Joao 9','Fe que amadurece a medida que e testada em casa','Fe que amadurece no teste',
    'O cego de nascenca foi curado e foi ganhando coragem de falar sobre Jesus a medida que era questionado — como a fe de voces amadureceu atraves dos testes do relacionamento?',
    'A fe testada e a fe que amadurece. O cego sabia pouco sobre Jesus — mas sabia o que tinha experimentado. O casal que pode dizer \"um dia eramos cegos, agora vemos\" na area do relacionamento tem um testemunho poderoso.',
    'Qual teste — uma crise, uma discordancia, uma perda — contribuiu mais para o amadurecimento da fe de voces como casal?',
    'Voce tem sido honesto sobre o que sabe de Deus a partir da experiencia, mesmo quando nao tem todas as respostas teologicas?',
    'Como a fe de voces tem crescido atraves dos desafios do relacionamento nos ultimos anos?',
    'Compartilhem um com o outro como um momento dificil do relacionamento fortaleceu a fe de voces.',
    'Senhor, que os nossos testes se tornem testimonhos. Que a nossa fe amadureca atraves das provas. Amen.'
  ),
  dev(79,12,'I — O Noivo se revela','Joao 10','Cuidado sacrificial como modelo de lideranca no lar','O bom pastor no lar',
    'O bom pastor conhece suas ovelhas pelo nome e da a vida por elas — como esse modelo de lideranca define o que significa guiar o lar?',
    'O bom pastor nao dirige o rebanho de longe — ele caminha na frente, conhece cada ovelha e se sacrifica. A lideranca no lar que Jesus modela e pessoal, sacrificial e comprometida com o bem de cada membro.',
    'Voce conhece profundamente o conjuge — suas lutas, medos, sonhos, necessidades nao ditas — com a profundidade do pastor que conhece as ovelhas pelo nome?',
    'Como voce tem exercido a lideranca do lar de forma sacrificial — nao apenas gerenciando, mas dando de si mesmo?',
    'Ha uma area onde o conjuge precisa de guia e cuidado que voce nao tem provido com a mesma atencao que o pastor da ao rebanho?',
    'Conversem sobre o que cada um mais precisa em termos de cuidado e guia — e comprometam-se a providencia-lo.',
    'Senhor bom pastor, que a tua lideranca seja o modelo da nossa. Que conhamos profundamente a quem amamos. Amen.'
  ),
  dev(80,12,'I — O Noivo se revela','Joao 11','Esperanca diante da perda e do luto familiar','Esperanca no luto',
    'Jesus chorou diante do tumulo de Lazaro — mesmo sabendo que ia ressuscita-lo. O que esse choro diz sobre como Deus se relaciona com o luto humano?',
    'O luto e legitimo mesmo para quem tem esperanca na ressurreicao. Jesus nao apressou o processo — ele chorou primeiro. O lar cristao que experimenta perda pode ser honesto sobre a dor sem perder a esperanca.',
    'Ha alguma perda — de um sonho, de uma pessoa, de uma fase — que ainda nao foi suficientemente lamentada no lar de voces?',
    'Voce tem dado espaco ao luto do conjuge sem pressa para o outro seguir em frente — ou tende a apressar o processo de cura?',
    'Como a esperanca da ressurreicao fala de forma especifica a uma perda que o lar de voces ja experimentou?',
    'Orem juntos sobre uma perda que o lar ainda carrega — com honestidade e com esperanca.',
    'Senhor que choraste com Maria, chora conosco nas nossas perdas. Que a esperanca da ressurreicao fale mais alto. Amen.'
  ),
  dev(81,12,'I — O Noivo se revela','Joao 12','Entrega generosa e sacrificial dentro do relacionamento','Entrega total',
    'Maria ungiu os pes de Jesus com um perfume preciosíssimo e foi criticada por desperdicio — ha gestos de amor ao conjuge que voce tem inibido por medo de parecer excessivo?',
    'A generosidade de Maria foi descrita por Jesus como algo que seria lembrado em todo o mundo. O amor sacrificial e o amor que nao calcula o custo. O casal que unge o outro com o que tem de mais precioso — tempo, atencao, presenca — e o casal que constroi algo memoravel.',
    'O que e o seu nardo — o mais precioso que voce tem — e como voce pode derrema-lo sobre o conjuge?',
    'Ha recursos de atencao, tempo ou presenca que voce tem guardado para si e que o conjuge mais precisa?',
    'Como voce pode expressar um amor que nao calcula o custo de forma concreta e surpreendente?',
    'Facam um gesto de entrega generosa um pelo outro — algo que custa mais do que e habitual.',
    'Senhor, que amemos como Maria amou — sem calcular, sem guardar. Que o nosso amor seja memoravel pela generosidade. Amen.'
  ),
  dev(82,12,'I — O Noivo se revela','Joao 13','Servico mutuo como marca visivel do lar cristao','Lava-pes no casamento',
    'Jesus lavou os pes dos discipulos — inclusive de Judas, que o trairia. O que esse ato diz sobre o servico que nao depende do merecimento do servido?',
    'O lava-pes e um ato de servico humilhante para os padroes culturais da epoca — e Jesus o faz como declaracao de como o amor funciona no Reino. O lar onde os dois lavam os pes um do outro — servindo sem calcular merecimento — e um lar que espelha o amor de Cristo.',
    'Ha momentos em que voce se recusa a servir o conjuge porque sente que ele nao merece — ou porque ainda esta esperando que ele sirva primeiro?',
    'Voce tem servido o conjuge com a mesma dignidade com que Jesus lavou os pes — vendo o servico como honra, nao como rebaixamento?',
    'Em qual area pratica do lar voce pode hoje lavar os pes do conjuge — servir de forma concreta e humilde?',
    'Cada um faz um gesto de servico pratico e humilde pelo outro hoje — algo que normalmente seria esperado do outro.',
    'Senhor que lavaste os pes dos teus, ensina-nos a servir um ao outro com a mesma graca e sem calcular o merecimento. Amen.'
  ),
  dev(83,12,'I — O Noivo se revela','Joao 14; Joao 15','Paz em meio a ausencia, a espera e a incerteza / Permanecer em Cristo como fonte de fruto','Paz e permanencia em Cristo',
    'Jesus diz \"a minha paz vos deixo; a minha paz vos dou\" — como a paz que Jesus oferece difere da paz que o mundo pode dar ao lar de voces?',
    'Joao 14 e 15 sao pronunciados na vespera da morte de Jesus — em um momento de maxima incerteza. A paz que ele oferece nao depende das circunstancias, mas da sua presenca. Permanecer na videira e a condicao do fruto — sem esse vinculo, nada que o lar produz dura.',
    'O lar de voces esta fundamentado na paz de Cristo — ou na ausencia de conflito, que e uma coisa bem diferente?',
    'Voce tem permanecido conectado a Cristo de forma que o fruto do relacionamento seja genuino — ou tem vivido da energia religiosa propria?',
    'Em qual area da vida do lar voces precisam escolher a paz de Cristo ao inves da ansiedade ou do conflito?',
    'Orem juntos pedindo a paz que excede todo entendimento — e comprometam-se a permanecer na videira esta semana.',
    'Senhor, que a tua paz seja a paz do nosso lar. Que permaneçamos em ti e produzamos fruto que dure. Amen.'
  ),
  mesa(84,12,'I — O Noivo se revela','Mesa da Alianca — Semana 12'),

  // SEMANA 13
  dev(85,13,'I — O Noivo se revela','Joao 16','Esperanca que atravessa a dor temporaria do casal','Dor temporaria, esperanca eterna',
    'Jesus diz: \"Vos tereis tribulacao no mundo; mas tende bom animo, eu venci o mundo\" — qual tribulacao atual no lar precisa ser colocada sob essa perspectiva?',
    'A dor de dar a luz que Jesus menciona e intensa mas temporaria — e seguida de alegria que o sofrimento nao cancela. O casal em uma temporada de dificuldade pode ter essa mesma perspectiva: o sofrimento e real mas nao e a ultima palavra.',
    'Qual dificuldade atual do lar voces precisam colocar sob a luz da vitoria de Cristo — sem negar a dor, mas sem perder a esperanca?',
    'Voce tem sido para o conjuge uma presenca de esperanca nas tribulacoes — ou se afoga junto com ele na dificuldade?',
    'Como a certeza da vitoria de Cristo sobre o mundo muda concretamente a forma como voces enfrentam as dificuldades do lar?',
    'Orem juntos sobre a tribulacao atual do lar — declarando juntos que Cristo ja venceu.',
    'Senhor vencedor, que a tua vitoria seja a nossa esperanca em cada dificuldade. Que o bom animo nao nos falte. Amen.'
  ),
  dev(86,13,'I — O Noivo se revela','Joao 17','Unidade como testemunho diante de quem observa o lar','Unidade que testemunha',
    'Jesus ora para que seus discipulos sejam um — e diz que essa unidade e o testemunho que convence o mundo. Como a unidade do casal de voces testemunha ao redor?',
    'A oracao sacerdotal de Jesus nao e apenas pela unidade interior — e pela unidade que o mundo veja. O casal cristao unido e uma das provas mais poderosas de que o evangelho e real e transforma relacionamentos.',
    'Como a unidade — ou a falta dela — no relacionamento de voces tem afetado o testemunho diante de filhos, amigos e conhecidos?',
    'Voce tem trabalhado ativamente para a unidade do lar — ou deixa que as divisoes se acumulem sem confronta-las?',
    'Qual divisao no casal, se resolvida, produziria o testemunho mais poderoso ao redor?',
    'Identifiquem uma area de divisao que precisam abordar — e orem juntos pedindo a unidade pela qual Jesus orou.',
    'Senhor que oraste pela nossa unidade, que ela seja real o suficiente para que o mundo veja. Amen.'
  ),
  dev(87,13,'I — O Noivo se revela','Joao 18','Fraqueza humana reconhecida em meio a provacao','Reconhecer a propria fraqueza',
    'Pedro negou a Jesus tres vezes — o mesmo Pedro que horas antes havia prometido morrer por ele. Como a fraqueza de Pedro fala sobre a sua propria confianca em si mesmo no relacionamento?',
    'A diferenca entre Pedro e Judas nao foi a queda — foi o que veio depois da queda. Pedro chorou amargamente e voltou; Judas foi embora definitivamente. O lar que reconhece a fraqueza e volta tem um futuro diferente do lar que se fecha em vergonha ou endurecimento.',
    'Ha alguma promessa que voce fez ao conjuge e que nao cumpriu — e que ainda precisa ser reconhecida e encaminhada?',
    'Voce tem reconhecido suas fraquezas e limites ao conjuge com honestidade — ou mantem uma imagem de forca que impede a intimidade real?',
    'Como a graca de Deus com Pedro — que voltou e liderou a Igreja — fala a voce sobre um fracasso seu que ainda pesa?',
    'Compartilhem um com o outro uma fraqueza pessoal real — sem exigencia de solucao imediata, apenas com vulnerabilidade.',
    'Senhor, que reconhequemos nossas fraquezas com a honestidade de Pedro — e que voltemos com a coragem dele. Amen.'
  ),
  dev(88,13,'I — O Noivo se revela','Joao 19','Cuidado familiar concreto ate o ultimo instante','Cuidado ate o fim',
    'Na cruz, com a propria vida escorrendo, Jesus cuida da mae — confia-la ao discipulo amado. O cuidado com as pessoas que amamos nao para diante de qualquer pressao.',
    'O gesto de Jesus da cruz em favor da mae e um ato de cuidado concreto e praticamente impossivel nas circunstancias — e ainda assim ele o faz. Amar ate o fim e continuarmos a cuidar do outro mesmo quando estamos nos exaurindo.',
    'Ha alguem no lar — conjuge, filho, pai — que precisa de um cuidado concreto que voce tem adiado por estar ocupado com suas proprias demandas?',
    'Como voce pode demonstrar hoje que o cuidado pelo conjuge nao cede diante de pressoes e demandas?',
    'Em qual area do lar o cuidado concreto — nao teorico — esta faltando?',
    'Identifiquem uma necessidade pratica do conjuge e atendam-na hoje de forma concreta e inesperada.',
    'Senhor, que o nosso cuidado pelo outro nao ceda diante das pressoes. Que amemos ate o fim, em gestos concretos. Amen.'
  ),
  dev(89,13,'I — O Noivo se revela','Joao 20','Fe que pode nascer mesmo da duvida','Fe nascida da duvida',
    'Tomas disse que nao creria sem ver — e Jesus apareceu especialmente para ele. Como Jesus trata a duvida honesta do casal?',
    'Jesus nao repreende Tomas — ele aparece para ele. A duvida honesta e um ponto de partida para a fe madura, nao um sinal de rejeicao. O lar que permite duvidas honestas sem julgamento e um lar onde a fe pode crescer de forma genuina.',
    'Ha alguma duvida espiritual que voce ou o conjuge tem carregado sem espaco para processa-la — por medo de julgamento ou de parecer fraco?',
    'Voce cria um ambiente no lar onde duvidas podem ser expressas com seguranca — ou a expectativa e de certeza constante?',
    'Como voce pode ser para o conjuge a presenca que nao repreende a duvida mas convida para a experiencia de Cristo?',
    'Compartilhem uma duvida espiritual honesta — e orem juntos pedindo que Jesus se revele como fez com Tomas.',
    'Senhor, que aparecas nas nossas duvidas como apareceste para Tomas. Que a fe nasca da experiencia real de ti. Amen.'
  ),
  dev(90,13,'I — O Noivo se revela','Joao 21','Recomeço depois da falha, ainda amado e enviado','Recomeço depois da falha',
    'Jesus restaurou Pedro perguntando tres vezes se ele o amava — correspondendo as tres negacoes. Ha algo no relacionamento de voces que precisa de uma restauracao assim, deliberada e correspondente?',
    'O cafe da manha que Jesus prepara para os discipulos na beira do lago e um ato de graca ordinaria que antecede a restauracao extraordinaria de Pedro. A graca que restaura nao humilha; ela reconstrui. O lar que sabe restaurar sem humilhar e um lar seguro.',
    'Ha algum aspecto da confianca entre voces que foi quebrado e que ainda nao foi restaurado de forma deliberada e intencional?',
    'Voce tem dado ao conjuge que falhou a mesma graca que Jesus deu a Pedro — ou ainda guarda a falha como arma?',
    'Qual recomeço o relacionamento precisa — em qual area o lar poderia comecar de novo com mais graca e menos peso do passado?',
    'Se ha algo que precisa de restauracao entre voces, usem este devocional como momento de dar esse passo deliberadamente.',
    'Senhor que restauraste Pedro com graca e o enviaste com missao, faze o mesmo conosco. Que os nossos recomecos sejam reais. Amen.'
  ),
  mesa(91,13,'I — O Noivo se revela','Mesa da Alianca — Semana 13'),
];

let content = '';
for (const d of days) {
  content += '  ' + JSON.stringify(d) + ',\n';
}

fs.appendFileSync(outPath, content);
console.log('Part 2 done, days 29-91, file size:', fs.statSync(outPath).size);
