// Days 92-182 (Estacao II, Semanas 14-26)
const fs = require('fs');
const path = require('path');
const outPath = path.join(__dirname, 'src/data/devocionalFamiliar.ts');

const dev = (dia, semana, estacao, leitura, subtema, tema, pg, rt, pger, rh, rm, cp, oa, rf) => {
  const o = { dia, semana, estacao, leitura, subtema, tema, tipo: 'devocional',
    perguntaGancho: pg, reflexaoTexto: rt, perguntaGeradora: pger,
    reflexaoHomem: rh, reflexaoMulher: rm, compromissoPratico: cp, oracaoAlianca: oa };
  if (rf) o.reflexaoFilhos = rf;
  return o;
};
const mesa = (dia, semana, estacao, tema, lc) => {
  const o = { dia, semana, estacao, leitura: 'Revisao da semana', subtema: tema, tema, tipo: 'mesa-alianca' };
  if (lc) o.leituraComplementar = lc;
  return o;
};
const aplic = (dia, semana, estacao, subtema, tema, rt, oa) =>
  ({ dia, semana, estacao, leitura: subtema, subtema, tema, tipo: 'aplicacao', reflexaoTexto: rt, oracaoAlianca: oa });

const days = [
  // SEMANA 14 — Atos
  dev(92,14,'II — A Noiva e formada','Atos 1; Atos 2','Esperar em oracao antes de decidir juntos / Unidade e comunhao como marca da nova familia de fe','Oracao antes de decidir',
    'Os discipulos esperaram em Jerusalem antes de agir — voces tem praticado o habito de esperar em oracao antes de tomar decisoes importantes no lar?',
    'Atos comeca com uma espera ativa: orar juntos antes de agir. A Pentecostes trouxe unidade e comunhao — e isso comecou com a oracao comunitaria. O casal que decide junto com Deus antes de agir descobre uma direcao que a pressa nunca oferece.',
    'Ha uma decisao importante no lar de voces que tem sido tomada sem suficiente espera e oracao?',
    'Voce tem liderado o lar em discernimento conjunto — orando, esperando e decidindo juntos — ou toma decisoes unilateralmente?',
    'Como voce pode criar um ritmo de oracao antes de decisoes — mesmo as pequenas — que moldaria a cultura espiritual do lar?',
    'Identifiquem uma decisao pendente no lar e comprometam-se a orar juntos por ela por uma semana antes de decidir.',
    'Senhor, que esperemos em ti antes de agir. Que as nossas decisoes nasçam da oracao, nao da pressa. Amen.'
  ),
  dev(93,14,'II — A Noiva e formada','Atos 3','Fe simples que produz testemunho visivel ao redor','Testemunho visivel',
    'Pedro e Joao nao tinham prata nem ouro — mas tinham Cristo. O que o lar de voces tem para oferecer que o dinheiro nao pode comprar?',
    'O milagre da cura do coxo comecou com o que Pedro e Joao nao tinham — e terminou com o que eles tinham: o nome de Jesus. O lar cristao e um testemunho quando o que tem em Cristo e mais visivel do que o que nao tem materialmente.',
    'Qual aspecto do lar de voces — a forma como amam, como perdoam, como servem — tem sido testemunho para quem esta de fora?',
    'Voce tem sido corajoso em oferecer o que realmente tem — o nome e o poder de Cristo — nas necessidades das pessoas ao redor?',
    'Como o lar de voces pode ser uma fonte de cura e esperanca para alguem proximo esta semana?',
    'Identifiquem alguem ao redor com uma necessidade real e sirvam a essa necessidade esta semana.',
    'Senhor, que o que temos em ti seja mais visivel do que o que nos falta. Que o nosso lar testemunhe de ti. Amen.'
  ),
  dev(94,14,'II — A Noiva e formada','Atos 4','Coragem e generosidade compartilhadas no lar','Coragem e generosidade',
    'Os primeiros cristaos oraram por coragem — nao por seguranca — diante da oposicao. O que o lar de voces costuma pedir a Deus quando ha pressao?',
    'A comunidade primitiva vendia suas posses e repartia com todos. A generosidade que emerge de uma fe corajosa nao e imposta — e fruto de um coracao transformado. O lar que pratica generosidade radical reflete essa cultura do Reino.',
    'Ha alguma area onde o lar de voces poderia exercitar generosidade mais corajosa — de dinheiro, de tempo, de espaco?',
    'Voce pede a Deus coragem para testemunhar e servir — ou pede principalmente conforto e seguranca?',
    'Como a generosidade da comunidade primitiva desafia a cultura financeira do lar de voces?',
    'Orem juntos pedindo coragem — nao seguranca — para o que Deus tem chamado o lar a fazer.',
    'Senhor, da-nos coragem como aos primeiros cristaos. Que a generosidade seja fruto da nossa fe, nao da nossa sobra. Amen.'
  ),
  dev(95,14,'II — A Noiva e formada','Atos 5','Honestidade radical dentro da propria comunidade','Honestidade radical',
    'Ananias e Safira morreram por uma mentira — a gravidade do texto choca. Mas o que isso diz sobre a seriedade da honestidade diante de Deus e da comunidade?',
    'A mentira de Ananias e Safira nao foi sobre dinheiro apenas — foi sobre aparencia. Eles queriam o credito sem a entrega real. O lar que mantem aparencias diante da comunidade de fe sem honestidade interior esta no mesmo territorio.',
    'Ha alguma area onde o lar de voces mantem uma aparencia de algo que nao corresponde a realidade interior?',
    'Voce tem sido honesto com o conjuge sobre sua vida interior — lutas, tentacoes, estados de fe — ou mantem uma performance de espiritualidade?',
    'Como a honestidade radical — inclusive sobre dinheiro, tempo e prioridades — poderia fortalecer o lar e o testemunho de voces?',
    'Compartilhem com honestidade uma area onde ha discrepancia entre a aparencia e a realidade no lar.',
    'Senhor, guarda-nos da mentira disfarçada de espiritualidade. Que sejamos transparentes diante de ti e um do outro. Amen.'
  ),
  dev(96,14,'II — A Noiva e formada','Atos 6','Distribuicao sabia de responsabilidades dentro de casa','Responsabilidades bem divididas',
    'Os apostolos identificaram um problema pratico — a distribuicao de alimentos — e delegaram de forma sabia. Como voces tem dividido as responsabilidades do lar?',
    'A solucao dos apostolos foi pratica e espiritual ao mesmo tempo: identificar pessoas capazes, delegar com confianca e liberar para que cada um focasse no seu chamado. O lar que divide bem as responsabilidades funciona com mais paz e menos ressentimento.',
    'Ha responsabilidades no lar de voces que estao desigualmente distribuidas — gerando desgaste em um dos lados?',
    'Voce tem assumido responsabilidades do lar com a mesma seriedade e integridade com que assume compromissos externos?',
    'Como voce pode dividir as responsabilidades do lar de forma mais equitativa e que reflita os dons e capacidades de cada um?',
    'Conversem sobre a distribuicao atual das responsabilidades do lar e ajustem o que estiver desequilibrado.',
    'Senhor, da-nos sabedoria para dividir bem o que carregamos. Que a casa funcione com justicia e graca. Amen.'
  ),
  dev(97,14,'II — A Noiva e formada','Atos 7','Perdao levado ate o fim, mesmo sob injustica','Perdoar ate o fim',
    'Estevao foi apedrejado e orou pelo perdao dos seus algozes — como esse modelo extremo ilumina o perdao que voces sao chamados a praticar no lar?',
    'O discurso de Estevao mostra fe que nao cede diante da injustica — e a oracao no momento da morte mostra um perdao que vai ate o fim. O lar cristao nao e chamado a esse nivel de heroismo todo dia, mas a cultura de perdao que Estevao exemplifica deve permear o cotidiano.',
    'Ha alguma injustica sofrida dentro ou fora do lar que voces ainda nao perdoaram de forma real?',
    'Como o exemplo de Estevao desafia a forma como voce responde quando e tratado injustamente pelo conjuge?',
    'O que o perdao ate o fim — sem guardar, sem usar como historico de acusacao — custaria a voce em relacao ao conjuge?',
    'Se ha algo por perdoar profundamente, orem juntos sobre isso com a disposicao de Estevao.',
    'Senhor, que o perdao que damos chegue ate o fim — como o de Estevao. Que nao guardemos o que tu ja perdoaste. Amen.'
  ),
  mesa(98,14,'II — A Noiva e formada','Mesa da Alianca — Semana 14'),

  // SEMANA 15
  dev(99,15,'II — A Noiva e formada','Atos 8','O evangelho alcanca quem parece de fora da familia','Ninguem esta fora do alcance',
    'Filipe foi enviado a uma estrada deserta para encontrar um eunuco etíope — Deus direciona ao improvavel. Voces ja estiveram prontos para ser enviados a onde nao esperavam?',
    'O evangelho cruza fronteiras geograficas, raciais e culturais em Atos 8. Nenhuma pessoa esta tao longe que o amor de Cristo nao alcance. O lar cristao que vive essa perspectiva nao fecha os olhos para quem esta ao redor.',
    'Ha alguma pessoa no circulo de voces que parece improvavel para o evangelho — e que voces poderiam alcançar?',
    'Voce tem estado disponivel para ser enviado aonde o Espirito indica — mesmo quando o destino parece inconveniente?',
    'Como o lar de voces pode ser um ponto de alcance para quem esta ao redor — nas redes, no bairro, na familia?',
    'Orem juntos pelo nome de uma pessoa especifica que voces querem alcançar com o evangelho.',
    'Senhor, que o nosso lar seja ponto de envio para quem ainda nao te conhece. Amen.'
  ),
  dev(100,15,'II — A Noiva e formada','Atos 9','Transformacao radical possivel no coracao mais resistente','Transformacao radical',
    'Paulo perseguia a Igreja antes de ser transformado — voces ja viram transformacao radical na vida de alguem que parecia impossivel?',
    'A conversao de Paulo e a prova maxima de que nenhum coracao e impenetravel a graca de Deus. O lar que cre nessa possibilidade nao desiste de orar por parentes, amigos ou pelo proprio conjuge que parece endurecido.',
    'Ha alguem por quem voces tem orado por transformacao que parece improvavel — e que precisam continuar crendo em Deus?',
    'Voce tem sido um Ananias para alguem — a pessoa que vai ao encontro do transformado e o recebe na comunidade?',
    'Como a historia de Paulo desafia o limite da sua fe na transformacao de pessoas especificas?',
    'Orem juntos por uma pessoa especifica cuja transformacao parece improvavel — com a fe de quem cre em Deus que fez Paulo.',
    'Senhor que transformaste Paulo, nenhum coracao e impossivel para ti. Que creiamos nisso no nosso lar. Amen.'
  ),
  dev(101,15,'II — A Noiva e formada','Atos 10','Quebrar preconceitos para incluir verdadeiramente o outro','Incluir sem preconceito',
    'Pedro precisou de uma visao repetida tres vezes para aceitar que Deus nao faz distincao de pessoas — que preconceitos o lar de voces ainda precisa quebrar?',
    'A visao de Pedro e a abertura a casa de Cornelio mostram que a graca de Deus vai alem de nossas categorias de quem merece ou nao. O lar que e genuinamente inclusivo — sem distinção de merito — testemunha o carater de Deus.',
    'Ha preconceitos — culturais, sociais, familiares — que voces precisam ativamente quebrar para amar como Deus ama?',
    'Voce tem sido como Pedro — precisando de visoes repetidas antes de abrir a porta para quem parece diferente?',
    'Como o lar de voces pode praticar hospitalidade genuina que vai alem do circulo confortavel?',
    'Identifiquem uma pessoa ou grupo que voces tenderiam a excluir e conversem sobre como o lar pode se abrir.',
    'Senhor, quebra os nossos preconceitos como quebraste os de Pedro. Que o nosso lar seja aberto como o teu coracao. Amen.'
  ),
  dev(102,15,'II — A Noiva e formada','Atos 11','Prestar contas e crescer em comunidade, nao isolado','Crescer em comunidade',
    'Pedro teve que prestar contas da sua visita a Cornelio para a comunidade de Jerusalem — como o lar de voces esta inserido numa comunidade que pode fazer perguntas e ajudar no crescimento?',
    'O crescimento espiritual solitario e fragil. A comunidade que faz perguntas, que questiona e que caminha junto e parte do design de Deus para a formacao crista. O lar isolado e vulneravel de formas que o lar conectado nao e.',
    'O lar de voces esta conectado de forma genuina a uma comunidade que conhece voces de verdade — nao apenas superficialmente?',
    'Voce tem prestado contas das decisoes do lar a pessoas de confianca — nao apenas buscando aprovacao, mas abertura para correccao?',
    'Como voces podem se aprofundar na conexao com a comunidade de fe — alem da presenca dominical?',
    'Identifiquem um casal ou pessoa de confianca com quem voces podem se aprofundar em comunidade real.',
    'Senhor, que nao cresçamos sozinhos. Que o lar seja parte viva de uma comunidade que nos conhece e nos forma. Amen.'
  ),
  dev(103,15,'II — A Noiva e formada','Atos 12','Oracao perseverante da familia por quem sofre','Orar pelo que sofre',
    'A comunidade orava pela libertacao de Pedro — e ele bateu na porta de Maria sem que eles soubessem que a oracao tinha sido respondida. O lar de voces tem orado com essa perseveranca por quem sofre?',
    'A oracao da comunidade de Jerusalem era tao persistente que quando Pedro bateu na porta, eles nao acreditaram de imediato. A oracao perseverante e o servico mais poderoso que um lar pode prestar por quem esta em dificuldade.',
    'Ha alguem em sofrimento real — na familia, na comunidade — por quem o lar de voces tem orado persistentemente?',
    'Voce tem intercedido pelo conjuge nos momentos em que ele sofre — com oracao real, nao apenas presenca fisica?',
    'Como o lar pode se tornar um lugar de intercedo regular por pessoas especificas que sofrem?',
    'Orem juntos agora por alguem que voces sabem que esta passando por uma dificuldade real.',
    'Senhor, ensina-nos a orar com a perseverancia da comunidade de Jerusalem. Que nao desistamos de interceder. Amen.'
  ),
  dev(104,15,'II — A Noiva e formada','Atos 13','Comissionamento e missao compartilhada pelo casal','Missao compartilhada',
    'Paulo e Barnabe foram separados e enviados — como o lar de voces entende o seu proprio comissionamento para alguma missao especifica?',
    'O comissionamento de Paulo e Barnabe comecou com oracao e jejum comunitario. A missao nao emergiu de iniciativa propria — emergiu da escuta ao Espirito. O casal que e comissionado juntos por Deus descobre um proposito que une mais do que qualquer projeto individual.',
    'Voces ja oraram juntos para identificar o chamado especifico de Deus para o lar — nao apenas ocupacoes, mas missao?',
    'Voce tem sido Barnabe para o conjuge — encorajando e apoiando o que Deus esta chamando o outro a fazer?',
    'Como o lar de voces pode ser comissionado para servir em alguma area especifica esta temporada?',
    'Orem juntos pedindo ao Espirito que revele qual e a missao especifica do lar nesta temporada de vida.',
    'Senhor, separa-nos e nos envia juntos para onde queres. Que nossa missao seja tua missao. Amen.'
  ),
  mesa(105,15,'II — A Noiva e formada','Mesa da Alianca — Semana 15'),

  // SEMANA 16
  dev(106,16,'II — A Noiva e formada','Atos 14','Perseverar apesar da rejeicao externa','Perseverar sob rejeicao',
    'Paulo foi apedrejado em Listra e continuou — que nivel de rejeicao ou dificuldade o lar de voces ja enfrentou e como respondeu?',
    'A perseveranca de Paulo e Barnabe diante da perseguicao e resistencia e notavel. Eles nao buscaram aprovacao universal; seguiram fieis ao chamado. O lar que persevera apesar da rejeicao — de parentes, cultura, ou circunstancias — esta construindo carater genuino.',
    'Qual rejeicao ou resistencia externa o lar de voces esta enfrentando agora — e como isso tem afetado a fe e a unidade?',
    'Voce tem sido fonte de encorajamento ao conjuge quando ha resistencia externa — ou a dificuldade os divide?',
    'Como a perspectiva de Paulo — que contava o sofrimento como parte do chamado — muda a forma de voces responder as dificuldades?',
    'Orem juntos sobre uma area de resistencia externa que o lar enfrenta — pedindo perseveranca, nao necessariamente alivio.',
    'Senhor, que a rejeicao nao nos dobres. Que perseveremos no chamado mesmo quando o caminho e dificil. Amen.'
  ),
  dev(107,16,'II — A Noiva e formada','Atos 15','Resolver conflitos com graca e clareza, sem explodir','Conflitos resolvidos com graca',
    'O Concilio de Jerusalem resolveu um conflito teologico real com debate, escuta e decisao coletiva — como voces tem resolvido os conflitos no lar?',
    'Atos 15 mostra que conflitos genuinos podem ser resolvidos sem ruptura quando ha disposicao de ouvir, falar com honestidade e buscar o que e certo juntos. A separacao entre Paulo e Barnabe no mesmo capitulo mostra que nem todo conflito resolve — mas que a forma como se separa importa.',
    'Qual padrao de resolucao de conflitos o lar de voces tem praticado — e o que precisaria mudar para que os conflitos fortalecessem em vez de enfraquecerem?',
    'Voce tende a explodir, a recuar em silencio, ou a buscar resolucao genuina quando ha conflito com o conjuge?',
    'Como o modelo do Concilio — debate honesto, escuta genuina, decisao conjunta — poderia ser aplicado nos conflitos do lar?',
    'Identifiquem um conflito nao resolvido e comprometam-se a aborda-lo desta semana com o modelo de Atos 15.',
    'Senhor, da-nos sabedoria para resolver conflitos com graca e clareza. Que os desentendimentos nos aprofundem, nao nos dividam. Amen.'
  ),
  dev(108,16,'II — A Noiva e formada','Atos 16','Hospitalidade e conversao que alcancam familias inteiras','Hospitalidade que alcanca familias',
    'Lidia abriu sua casa para Paulo e sua equipe depois de ser batizada — como a hospitalidade do lar de voces pode ser instrumento do evangelho?',
    'A conversao de Lidia e do carcereiro de Filipos envolveram familias inteiras — o evangelho na era apostolica chegava aos lares. A hospitalidade crista nao e apenas educacao social; e uma pratica evangelistica e formadora.',
    'O lar de voces tem sido hospitaleiro de forma que abre espaco para o evangelho chegar a outros?',
    'Voce tem usado o lar como instrumento de bencao e alcance — nao apenas como espaco privado para a familia?',
    'Quem poderia ser convidado ao lar de voces para uma refeicao ou conversa que poderia abrir portas para o evangelho?',
    'Planejem juntos uma ocasiao de hospitalidade deliberada — com alguem especifico em mente.',
    'Senhor, que o nosso lar seja aberto como o de Lidia. Que a hospitalidade seja caminho do evangelho. Amen.'
  ),
  dev(109,16,'II — A Noiva e formada','Atos 17','Testemunho respeitoso mesmo em contexto hostil','Testemunho respeitoso',
    'Paulo no Areopago começa pelo que os atenienses ja sabiam — o altar ao deus desconhecido. Como voces tem construido pontes ao inves de muros no testemunho da fe?',
    'O discurso de Paulo em Atenas e um modelo de engajamento cultural respeitoso: ele conhecia a cultura, citava seus poetas e construia pontes para o evangelho. O lar que testemunha com respeito e conhecimento e mais eficaz do que o que apenas condemna.',
    'Como voces tem se preparado para dar razao da fe que tem de forma respeitosa e contextualizada — com quem esta ao redor?',
    'Voce tende a confrontar ou a construir pontes quando fala da fe com quem nao cre — e o que o modelo de Paulo sugere?',
    'Ha alguem no circulo de voces a quem voce poderia testemunhar de forma mais respeitosa e contextualizada?',
    'Conversem sobre como o lar pode ser mais engajado culturalmente sem perder a firmeza da mensagem do evangelho.',
    'Senhor, da-nos sabedoria de Paulo no Areopago — para falar de ti de forma que os outros possam ouvir. Amen.'
  ),
  dev(110,16,'II — A Noiva e formada','Atos 18','Priscila e Aquila: um casal que serve unido no ministerio','Casal unido no servico',
    'Priscila e Aquila aparecem sempre juntos, sempre servindo — como voces tem servido ao Reino de forma unida como casal?',
    'Priscila e Aquila sao o unico casal que o NT descreve com consistencia como unidade ministerial. Eles hospedaram Paulo, trabalharam com as maos, ensinaram Apolo e abriram o lar para a Igreja. O servico conjugal unido e um testemunho poderoso.',
    'Ha alguma area de servico que voces poderiam exercer juntos como casal — que seria mais poderosa do que cada um fazendo separadamente?',
    'Voce valoriza e apoia o ministerio do conjuge — ou tende a ve-lo como competidor de tempo e atencao?',
    'Como o modelo de Priscila e Aquila desafia a forma como voces tem pensado sobre servir ao Reino como casal?',
    'Identifiquem uma area de servico que poderiam exercer juntos nesta temporada e comprometam-se a comecar.',
    'Senhor, que o nosso casal sirva ao teu Reino como Priscila e Aquila — juntos, generosos, disponiveis. Amen.'
  ),
  dev(111,16,'II — A Noiva e formada','Atos 19','Poder genuino versus imitacao vazia dentro de casa','Poder genuino',
    'Os filhos de Esceva tentaram usar o nome de Jesus sem conhece-lo — e foram derrotados. Ha praticas espirituais no lar de voces que sao mais imitacao do que experiencia real?',
    'O episodio dos filhos de Esceva e comico mas sombrio: o poder espiritual nao e tecnica — e relacionamento. O lar que pratica espiritualidade sem intimidade com Cristo pode ter a forma da piedade sem o poder.',
    'Ha areas da espiritualidade do lar onde voces tem imitado o que outros fazem sem experiencia real do que esta por tras?',
    'Voce tem intimidade real com Cristo — ou pratica religiosa que funciona como substituto da intimidade?',
    'Como voce pode aprofundar a experiencia real de Cristo no lar — alem das formas externas de religiosidade?',
    'Orem juntos por avivamento interior — nao por mais praticas, mas por mais presenca real de Cristo.',
    'Senhor, que o nosso poder no lar venha de ti, nao de formulas. Que a nossa espiritualidade seja real e nao imitacao. Amen.'
  ),
  mesa(112,16,'II — A Noiva e formada','Mesa da Alianca — Semana 16'),

  // SEMANA 17
  dev(113,17,'II — A Noiva e formada','Atos 20','Lideranca que serve com lagrimas e integridade','Liderar com lagrimas',
    'Paulo disse que serviu ao Senhor com toda a humildade, lagrimas e tentacoes — que tipo de lideranca esse modelo desafia voces a exercer no lar?',
    'A lideranca de Paulo em Efeso foi marcada por intensidade emocional real: ele chorou, advertiu, serviu. O lar que tem um lider que nao tem vergonha das proprias lagrimas e um lar onde a emocao tem espaco.',
    'Voce exerce lideranca no lar com integridade suficiente para que as pessoas ao seu redor possam testemunhar o que e real em voce?',
    'Ha lagrimas que voce tem escondido do conjuge — emocoes reais que ficam guardadas por medo de vulnerabilidade?',
    'Como voce pode exercer lideranca no lar com mais integridade emocional — sendo real em vez de performativo?',
    'Compartilhem algo que os toca profundamente — com honestidade emocional sem filtro.',
    'Senhor, que lideremos o lar com a integridade de Paulo — lagrimas, humildade e cuidado real. Amen.'
  ),
  dev(114,17,'II — A Noiva e formada','Atos 21','Disposicao de sofrer pelo chamado comum','Sofrer pelo chamado',
    'Paulo sabia que prisoes e sofrimentos o esperavam em Jerusalem — e foi assim mesmo. Qual chamado no lar de voces exige esse nivel de disposicao ao custo?',
    'A determinacao de Paulo de ir a Jerusalem mesmo advertido pelo Espirito e pelos amigos e um dos momentos mais comoventes de Atos. O sofrimento voluntario por um chamado maior e a marca de uma fe madura. O casal que e capaz de sofrer juntos por algo que vale a pena e o casal que tem proposito.',
    'Ha algo no chamado de voces como casal que tem exigido sacrificio real — e como voces tem respondido a esse custo?',
    'Voce tem sido a presenca que encoraja o conjuge no chamado dificil — ou tende a recomendar o caminho mais seguro?',
    'Como a disposicao de Paulo ao sofrimento por um chamado maior desafia as escolhas do lar de voces?',
    'Orem juntos sobre o custo real do chamado de voces e expressem disposicao de paga-lo.',
    'Senhor, que sejamos como Paulo — dispostos ao custo do chamado. Que o proposito seja maior do que o conforto. Amen.'
  ),
  dev(115,17,'II — A Noiva e formada','Atos 22','Testemunho pessoal da graca que transforma','Testemunho da graca pessoal',
    'Paulo contou sua propria historia sem vergonha — da perseguicao a conversao. Como voces tem compartilhado o que Deus fez em cada um de voces?',
    'O testemunho pessoal de Paulo e simples e poderoso: \"era assim, aconteceu isso, agora sou assim\". O lar que conhece a historia de transformacao de cada um e um lar com mais gratidao e menos julgamento.',
    'Voces conhecem profundamente a historia espiritual um do outro — o antes, o encontro com Cristo, o depois?',
    'Voce compartilha regularmente o que Deus esta fazendo em voce com o conjuge — nao apenas as necessidades, mas as maravilhas?',
    'Como o testemunho de cada um pode ser mais presente na vida espiritual do lar?',
    'Compartilhem hoje a historia de transformacao de cada um — com detalhe e gratidao.',
    'Senhor, que os nossos testimonhos sejam vivos e presentes no lar. Que o que fizeste em nos seja celebrado. Amen.'
  ),
  dev(116,17,'II — A Noiva e formada','Atos 23','Protecao de Deus em meio a ameaca externa','Protegidos por Deus',
    'O sobrinho de Paulo descobriu a emboscada e avisou — Deus usa meios humanos comuns para proteger os seus. Como voces tem reconhecido a providencia de Deus na protecao do lar?',
    'A protecao de Paulo em Atos 23 veio atraves de meios simples — um sobrinho, uma conversa, uma decisao burocrática do tribuno. Deus nao precisa de miracles espetaculares para cuidar dos seus; ele usa o ordinario.',
    'Ha uma situacao em que o lar de voces foi protegido por meios que parecem coincidencia — mas que voces reconhecem como providencia?',
    'Voce tem reconhecido e agradecido a Deus pelas protecoes cotidianas — ou so percebe quando ha uma crise grande?',
    'Como cultivar uma cultura de gratidao pela protecao de Deus no cotidiano do lar?',
    'Partilhem uma historia em que Deus protegeu o lar de forma que parece providencia — e orem juntos de gratidao.',
    'Senhor, que percebamos tua protecao nos meios ordinarios do cotidiano. Que a gratidao seja o ritmo do lar. Amen.'
  ),
  dev(117,17,'II — A Noiva e formada','Atos 24','Paciencia sob acusacao injusta','Paciencia sob injustica',
    'Paulo ficou preso por dois anos por razoes politicas — sem julgamento justo. Como voces tem respondido quando sofrem injustica sem resolucao rapida?',
    'A paciencia de Paulo diante de Felix e o tempo indefinido de prisao e um teste de carater que nao tem resolucao rapida. A injustica que persiste e um dos testes mais dificeis da fe. O casal que mantem a integridade sem amargura sob injustica longa esta construindo um carater profundo.',
    'Ha alguma injustica que o lar de voces esta sofrendo sem resolucao — e como isso tem afetado a fe e o relacionamento?',
    'Voce tem mantido a integridade e a paz diante de situacoes injustas — ou a amargura tem contaminado o lar?',
    'Como a perseveranca de Paulo sem amargura pode ser um modelo para a forma como o lar responde a injustica prolongada?',
    'Orem juntos sobre uma injustica que o lar enfrenta — pedindo paciencia e integridade, nao necessariamente resolucao imediata.',
    'Senhor, que a injustica que sofremos nao nos amargure. Que a tua justica final seja a nossa paz no presente. Amen.'
  ),
  dev(118,17,'II — A Noiva e formada','Atos 25','Perseveranca e integridade diante de processos dificeis','Integridade sob pressao',
    'Paulo diante de Festo manteve sua integridade sem comprometer a mensagem para ganhar liberdade — o que isso ensina sobre honestidade quando ha muito em jogo?',
    'A integridade nao e barata quando ha custos reais. Paulo poderia ter negociado sua liberdade com um pouco de diplomatismo conveniente — mas nao o fez. O lar que mantem integridade quando ha custo esta construindo uma reputacao que o lar que compromete por conveniencia nunca terá.',
    'Ha uma area onde o lar de voces tem sido tentado a comprometer a integridade por conveniencia ou por evitar conflito?',
    'Voce tem sido consistentemente honesto nas situacoes dificeis — ou a pressao te leva a pequenas concessoes que comprometem a integridade?',
    'Como a integridade de Paulo diante das autoridades desafia a forma como voces navegam as pressoes do cotidiano?',
    'Conversem sobre uma area onde a integridade tem sido testada no lar e renovem juntos o compromisso de honestidade.',
    'Senhor, que a integridade seja o padrao do nosso lar mesmo quando custa. Amen.'
  ),
  mesa(119,17,'II — A Noiva e formada','Mesa da Alianca — Semana 17'),

  // SEMANA 18
  dev(120,18,'II — A Noiva e formada','Atos 26','Testemunho corajoso diante de quem tem autoridade sobre nos','Coragem diante da autoridade',
    'Paulo falou da sua fe diante do rei Agripa sem temer — como voces tem sido corajosos em compartilhar a fe diante de quem tem autoridade sobre voces?',
    'O discurso de Paulo diante de Agripa e um dos mais eloquentes do NT — e foi dado diante de uma autoridade que poderia decide o seu destino. A coragem de testemunhar nao depende de garantia de resultado.',
    'Ha contextos onde voces tem se calado sobre a fe por medo do que autoridades — chefes, familiares, líderes — possam pensar?',
    'Voce tem sido corajoso em declarar a fe diante de quem tem poder sobre voce — no trabalho, na familia extensa?',
    'Como o lar pode cultivar coragem no testemunho para alem do circulo de segurança?',
    'Comprometam-se a compartilhar a fe com alguem especifico nos proximos 7 dias.',
    'Senhor, da-nos a coragem de Paulo diante do rei. Que o medo da autoridade humana nao cale o nosso testemunho. Amen.'
  ),
  dev(121,18,'II — A Noiva e formada','Atos 27','Confianca em meio a tempestade literal da vida','Confiar na tempestade real',
    'Paulo em meio ao naufragio disse a todos que teriam coragem — ele havia recebido a promessa de Deus. Como voces tem sido fonte de esperanca nas tempestades reais do lar?',
    'A tempestade de Atos 27 e literal — mar, vento, desespero. Paulo nao minimizou o perigo; ele ancorou a esperanca na palavra de Deus. O lar que tem esse tipo de fe nao finge que a tempestade nao existe — ela confia que Deus falou e ira cumprir.',
    'Qual tempestade real o lar de voces esta atravessando agora — e em qual promessa de Deus voces estao ancorados?',
    'Voce tem sido para o conjuge a presenca que ancora a esperanca quando tudo parece naufragio?',
    'Como a palavra de Deus — uma promessa especifica da Escritura — pode ser a ancora para a tempestade atual do lar?',
    'Identifiquem uma promessa biblica especifica e orem juntos sobre ela como ancora para a situacao atual.',
    'Senhor, que tua palavra seja a nossa ancora nas tempestades. Que o naufragio nao nos afaste da tua promessa. Amen.'
  ),
  dev(122,18,'II — A Noiva e formada','Atos 28','O proposito de Deus continua apesar dos obstaculos','Proposito que persiste',
    'Paulo chegou a Roma em prisao — mas pregou o evangelho com toda a ousadia. Os obstaculos nao cancelaram o proposito. Como isso fala ao lar de voces?',
    'Atos termina com Paulo preso mas livre para pregar. O proposito de Deus nao depende de condicoes ideais — ele continua atraves dos obstaculos. O lar que crê nisso nao paralisa diante de impedimentos.',
    'Qual obstaculo o lar de voces esta encontrando que parece impedir o proposito de Deus — e como voces tem respondido?',
    'Voce tem liderado o lar com a confiança de que o proposito de Deus persiste mesmo quando as circunstancias sao adversas?',
    'Como a historia de Paulo em Roma desafia o lar a continuar mesmo quando as condicoes nao sao as esperadas?',
    'Orem juntos sobre um obstaculo especifico e declararem que o proposito de Deus continua.',
    'Senhor, que nenhum obstaculo cancele o teu proposito para o nosso lar. Que continuemos mesmo quando as condicoes sao adversas. Amen.'
  ),
  dev(123,18,'II — A Noiva e formada','Romanos 1','Consequencias de trocar a verdade de Deus pela mentira em casa','Verdade que protege o lar',
    'Paulo descreve a progressao de quem troca a verdade pela mentira — e as consequencias relacionais que se seguem. O lar de voces esta fundado na verdade de Deus?',
    'Romanos 1 traca uma teologia das consequencias: quando a verdade de Deus e trocada por mentira, o resultado e desintegracao relacional e moral. O lar fundado na verdade — sobre Deus, sobre o ser humano, sobre o casamento — tem uma protecao que o lar baseado em conveniencia nao tem.',
    'Ha areas onde o lar de voces tem aceitado narrativas sobre relacionamento, genero ou moralidade que contradizem a Escritura — por conveniencia ou por pressao cultural?',
    'Voce tem mantido a verdade da Palavra de Deus como fundamento das decisoes do lar — mesmo quando essa verdade e impopular?',
    'Como a verdade de Deus — sobre quem somos, o que e o casamento, como devemos viver — protege o lar de formas que a conveniencia cultural nao protege?',
    'Conversem sobre uma area onde a pressao cultural tem desafiado os valores do lar — e renovem o compromisso com a verdade.',
    'Senhor, que a tua verdade seja o fundamento do nosso lar. Que nao troquemos o que e real pelo que e conveniente. Amen.'
  ),
  dev(124,18,'II — A Noiva e formada','Romanos 2','Integridade que vai alem da aparencia religiosa do casal','Integridade real',
    'Paulo adverte que ter a lei e fazer a lei sao coisas muito diferentes — e o julgamento e sobre o que se faz, nao sobre o que se professa. Qual e a distancia entre o que o lar de voces professa e o que pratica?',
    'Romanos 2 derruba a confianca na posse da verdade sem a pratica da verdade. O perigo espiritual do lar religioso mas inconsistente e real — e Paulo o nomeia com precisao. Integridade e a coerencia entre o que se diz e o que se faz.',
    'Em qual area a distancia entre o que voces professam como lar cristao e o que realmente praticam e maior?',
    'Voce tem julgado o conjuge por algo que voce mesmo falha — e que Paulo chamaria de juizo sem integridade?',
    'O que mudaria no lar se a pratica diaria fosse consistente com os valores que voces professam?',
    'Cada um identifica uma area de inconsistencia pessoal — nao do conjuge — e pede graca para crescer nessa area.',
    'Senhor, que sejamos integros e nao apenas religiosos. Que o que professamos corresponda ao que praticamos. Amen.'
  ),
  dev(125,18,'II — A Noiva e formada','Romanos 3','Nenhum conjuge e justo por si mesmo diante de Deus','Igualdade diante da graca',
    'Nao ha justo, nem um — essa declaracao equaliza todos diante da necessidade de graca. Como isso muda a dinamica de poder no relacionamento de voces?',
    'Romanos 3 nivela o campo: todos pecaram e destituidos estao da gloria de Deus. Nenhum conjuge tem vantagem moral sobre o outro — ambos precisam da mesma graca. O lar que internaliza isso tem menos julgamento e mais misericordia mutua.',
    'Ha uma dinamica no relacionamento onde um dos dois se coloca implicitamente na posicao moral superior — e como isso afeta a cultura do lar?',
    'Voce tende a agir como se precisasse menos de graca do que o conjuge — e como isso aparece nas interacoes do cotidiano?',
    'Como a equalização que Romanos 3 declara — todos pecaram — poderia mudar a forma como voces se tratam nos momentos de falha?',
    'Orem juntos reconhecendo a necessidade de graca de cada um — com a mesma intensidade.',
    'Senhor, que lembremos sempre que ambos precisamos da mesma graca. Que a igualdade diante de ti gere misericordia entre nos. Amen.'
  ),
  mesa(126,18,'II — A Noiva e formada','Mesa da Alianca — Semana 18'),

  // SEMANA 19
  dev(127,19,'II — A Noiva e formada','Romanos 4','Promessa recebida pela fe, nunca por merito proprio','Fe sem merito',
    'Abraao creu a Deus e isso lhe foi imputado como justica — antes de qualquer obra. Como isso redefine o relacionamento entre desempenho e amor no casamento?',
    'A fe de Abraao e modelo porque ele creu na promessa de Deus apesar de todas as evidencias contrarias — sua idade, o corpo de Sara. O amor conjugal que nao depende de merito ou desempenho tem essa mesma qualidade: e uma escolha de fe, nao uma conclusao de avaliacao.',
    'Voce ama o conjuge de forma mais intensa quando ele tem bom desempenho — ou ha uma constancia que nao depende de resultado?',
    'Em quais momentos o amor de voces pelo conjuge tem sido condicionado ao merecimento — e o que isso diz sobre o fundamento desse amor?',
    'Como a fe sem merito de Abraao pode ser um modelo para amar sem exigir desempenho?',
    'Digam um ao outro: \"Eu te amo nao pelo que voce faz, mas por quem voce e\" — e digam isso de forma especifica.',
    'Senhor, que o nosso amor nao seja baseado em merito mas em escolha. Que amemos como tu nos amastes — antes de merecermos. Amen.'
  ),
  dev(128,19,'II — A Noiva e formada','Romanos 5','Reconciliacao com Deus como fundamento de toda outra relacao','Reconciliados para amar',
    'Sendo ainda inimigos, fomos reconciliados com Deus — o amor que nao esperou que forssemos amigos. Como isso transforma a forma como o casal enfrenta os momentos de inimizade mutua?',
    'A reconciliacao que Cristo realizou nao esperou que fossemos merecedores — ele morreu pelos impios. O amor conjugal que modela esse padrao e o amor que nao espera que o outro esteja \"do lado certo\" antes de se aproximar.',
    'Ha momentos de frieza ou inimizade velada no relacionamento — e como o modelo da reconciliacao de Cristo os desafia?',
    'Voce tem dado o primeiro passo em direicao ao conjuge nos momentos de distancia — ou espera que o outro se mova primeiro?',
    'Como a segurança da reconciliacao com Deus liberta voce para ser vulnerable e dar o primeiro passo no relacionamento?',
    'Se ha distancia entre voces agora, cada um da um passo em direcao ao outro hoje — sem esperar que o outro vá primeiro.',
    'Senhor, que a reconciliacao que nos deste seja o modelo da reconciliacao que praticamos. Que nao esperemos merecimento para nos aproximarmos. Amen.'
  ),
  dev(129,19,'II — A Noiva e formada','Romanos 6','Novo padrao de vida diario dentro do lar','Novo padrao de vida',
    'Paulo diz que os que morreram para o pecado nao podem mais continuar a viver nele — a identidade nova produz padrao novo. Como isso se traduz em habitos concretos do lar?',
    'A vida nova em Cristo nao e apenas um estado interno — e um padrao de comportamento externo. Morto para o pecado, vivo para Deus. O lar que leva essa realidade a serio vive de forma diferente — em decorrencia da identidade, nao por esforco moral.',
    'Qual padrao de comportamento no lar precisa ser alinhado com a nova identidade em Cristo que voces professam?',
    'Ha habitos no lar — de comunicacao, de resposta ao conflito, de uso do tempo — que contradizem a identidade nova que Cristo da?',
    'Como a identidade \"morto para o pecado\" pode ser lembrada na proxima vez que um padrao antigo aparecer no lar?',
    'Identifiquem um habito do lar que precisa ser alinhado com a nova identidade e comprometam-se a mudanca.',
    'Senhor, que vivamos de acordo com quem somos em Cristo. Que o lar testemunhe da vida nova que tu das. Amen.'
  ),
  dev(130,19,'II — A Noiva e formada','Romanos 7','Honestidade sobre a luta interior continua contra o pecado','Honestidade com a luta interior',
    'Paulo descreve a luta interna com honestidade chocante: o bem que quero nao faco, o mal que nao quero esse practico. Como essa honestidade de Paulo deveria aparecer no relacionamento de voces?',
    'Romanos 7 e o testemunho mais honesto de um apostolo sobre a luta interior. Essa honestidade nao e derrotismo — e realismo que abre espaco para a graca. O lar que permite essa honestidade sobre luta interior cria intimidade que a performance de perfeicao nao permite.',
    'Ha lutas internas que voce nao tem compartilhado com o conjuge por medo de julgamento — e que a honestidade de Paulo sugere que deveriam ser nomeadas?',
    'Voce cria espaco para que o conjuge seja honesto sobre as proprias lutas — sem julgamento ou resolucao imediata?',
    'Como a honestidade sobre a luta interior pode aprofundar a intimidade no relacionamento ao inves de comprometer a confianca?',
    'Compartilhem uma luta interior real com o conjuge — nao para resolver, mas para ser conhecido.',
    'Senhor, que a honestidade de Paulo sobre a luta interior seja a nossa tambem. Que o lar seja espaco seguro para ser real. Amen.'
  ),
  dev(131,19,'II — A Noiva e formada','Romanos 8','Seguranca inabalavel no amor de Deus sustentando o casal','Nada nos separa do amor',
    'Nada nos pode separar do amor de Deus — nem morte, nem vida, nem presentes, nem futuros. Como essa seguranca funda a seguranca que cada um oferece ao conjuge?',
    'Romanos 8 e o capitulo mais poderoso de toda a Escritura sobre a seguranca do amor de Deus. Essa seguranca nao e arrogancia — e a paz de quem sabe que o amor de Deus e mais firme do que qualquer circunstancia. O lar que repousa nessa segurança e capaz de oferecer seguranca ao outro.',
    'A seguranca que voce tem no amor de Deus esta transbordando para a segurança que o conjuge tem no seu amor?',
    'Ha medos ou insegurancas no relacionamento que seriam curados por uma compreensao mais profunda da seguranca do amor de Deus?',
    'Como Romanos 8.38-39 pode ser memorizado e relembrado nas proximas vezes que o lar for abalado por circunstancias?',
    'Leiam Romanos 8.38-39 juntos em voz alta — como declaracao de fe sobre o amor que sustenta o lar.',
    'Senhor, que a segurança do teu amor seja o fundamento da segurança que nos damos. Que nada nos separe de ti nem um do outro. Amen.'
  ),
  dev(132,19,'II — A Noiva e formada','Romanos 9','Confianca nos propositos soberanos de Deus para a familia','Propositos soberanos de Deus',
    'Paulo enfrenta a questao dificil da soberania de Deus com confianca na justica e na misericordia divinas — como voces navegam as decisoes soberanas de Deus que nao entendem para o lar?',
    'A soberania de Deus em Romanos 9 nao e um ensinamento que responde todas as perguntas — e um fundamento de confiança quando as respostas nao vem. O lar que confia na soberania de Deus mesmo sem entender todos os caminhos encontra paz que a explicacao nao oferece.',
    'Ha alguma decisao soberana de Deus para o lar — uma porta fechada, uma espera, um nao — que voces ainda nao aceitaram com confianca?',
    'Voce tem processado os limites da sua compreensao com honestidade intelectual e confiança espiritual — ou com ressentimento silencioso?',
    'Como a soberania de Deus em Romanos 9 pode ser fonte de paz ao inves de fonte de confusao para o lar?',
    'Orem juntos sobre algo que Deus tem decidido que voces nao escolheriam — e expressem confianca na sua sabedoria.',
    'Senhor soberano, confiamos em teus propositos mesmo quando nao os entendemos. Que o lar descanse na tua sabedoria. Amen.'
  ),
  mesa(133,19,'II — A Noiva e formada','Mesa da Alianca — Semana 19'),

  // SEMANA 20
  dev(134,20,'II — A Noiva e formada','Romanos 10','A importancia de falar o evangelho dentro de casa','Evangelho dentro de casa',
    'Como crerão naquele de quem nao ouviram? A fe vem pelo ouvir — como o evangelho e falado e ouvido dentro do lar de voces?',
    'Romanos 10 e um capitulo sobre comunicacao do evangelho — que vem pelo ouvir, pelo anuncio. O lar cristao onde o evangelho e falado — em historias, em oracao, em conversa — e um lar onde a fe cresce naturalmente.',
    'O evangelho e regularmente falado dentro do lar de voces — nao apenas vivido silenciosamente, mas declarado com palavras?',
    'Voce fala sobre Jesus de forma natural dentro de casa — com o conjuge, com os filhos — ou a fe fica restrita as praticas formais?',
    'Como o lar pode cultivar uma cultura onde o evangelho e falado com naturalidade no cotidiano?',
    'Esta semana, conversem sobre o que cada um tem experimentado de Deus — de forma especifica e pessoal, nao apenas generica.',
    'Senhor, que o evangelho seja falado no nosso lar com a mesma naturalidade com que falamos do cotidiano. Amen.',
    'Como voce tem falado sobre Jesus para os filhos de forma que eles possam ouvir e crer — nao apenas observar?'
  ),
  dev(135,20,'II — A Noiva e formada','Romanos 11','Esperanca na fidelidade de Deus mesmo em meio ao fracasso','Fidelidade de Deus no fracasso',
    'Paulo mostra que Deus nao rejeitou o seu povo mesmo quando o povo falhou — a fidelidade de Deus excede a nossa infidelidade. Como isso fundamenta a esperanca do lar?',
    'A misericordia que Deus mostra em Romanos 11 — guardar um remanescente, nao rejeitar — e o fundamento da esperanca quando o lar falhou. A fidelidade de Deus nao depende da nossa consistencia.',
    'Ha um fracasso no lar — de promessa, de relacionamento, de fe — que voces precisam trazer diante da fidelidade de Deus?',
    'Voce fundamenta a esperanca do lar na propria consistencia — que e fragil — ou na fidelidade de Deus — que e firme?',
    'Como a fidelidade de Deus mesmo no fracasso do povo fala ao lar sobre a possibilidade de recomeço?',
    'Identificem um fracasso do lar e orem sobre ele com a esperança da fidelidade de Deus.',
    'Senhor fiel, que a tua fidelidade seja maior do que os nossos fracassos. Que esperemos em ti mesmo quando falhamos. Amen.'
  ),
  dev(136,20,'II — A Noiva e formada','Romanos 12','Dedicacao pratica e uso dos dons a servico do lar','Dons a servico do lar',
    'Apresentai os vossos corpos como sacrificio vivo — Paulo nao esta falando apenas de culto formal, mas de toda a vida. Como o lar de voces tem sido um sacrificio vivo?',
    'Romanos 12 e um capitulo de etica pratica: dons usados, amor genuino, paciencia na tribulacao, hospitalidade, vencer o mal com o bem. Cada um desses elementos e uma pratica do lar antes de ser uma pratica da Igreja.',
    'Quais dons de cada um de voces estao sendo usados no lar — nao apenas na Igreja — para o bem do outro e da familia?',
    'Voce tem exercido amor genuino no lar — \"sem fingimento\" como Paulo diz — ou ha uma performance de amor que esconde distancia real?',
    'Como vencer o mal com o bem se traduz concretamente na forma como voces respondem aos conflitos dentro do lar?',
    'Cada um identifica um dom que tem e como pode usa-lo mais intencionalmente no servico ao lar esta semana.',
    'Senhor, que os nossos corpos e dons sejam sacrificio vivo no lar. Que o bem venca o mal em cada interacao. Amen.'
  ),
  dev(137,20,'II — A Noiva e formada','Romanos 13','Respeito e amor mutuo como base da convivencia diaria','Amor como lei do lar',
    'O amor ao proximo e o cumprimento de toda a lei — e o conjuge e o proximo mais imediato. Como o amor como principio organizador muda as regras do lar?',
    'Romanos 13 e a etica da nova era: o amor que cumpre toda a lei nao precisa de uma lista de regras — porque o amor ja considera o bem do outro em tudo. O lar que organiza a convivencia ao redor do amor tem menos regras e mais cultura.',
    'O lar de voces funciona mais por regras implicitas — expectativas, obrigacoes — ou por amor genuino que considera o outro?',
    'Voce tem amado o conjuge de forma que o amor se traduz em gestos concretos de consideracao no cotidiano?',
    'Como a lei do amor pode substituir gradualmente os sistemas de cobranca e expectativa no lar?',
    'Identifiquem uma regra implicita no lar que poderia ser substituida por uma pratica de amor consciente.',
    'Senhor, que o amor seja a lei do nosso lar. Que nao precisemos de listas quando amamos de verdade. Amen.'
  ),
  dev(138,20,'II — A Noiva e formada','Romanos 14','Paciencia com as diferencas de conviccao dentro do casal','Paciencia com as diferencas',
    'Paulo fala sobre o fraco e o forte na fe — e sobre a necessidade de nao julgar nem desprezar quem esta em uma posicao diferente. Ha diferencas de conviccao entre voces que criam tensao?',
    'Romanos 14 e um texto sobre diferenca de maturidade espiritual e de conviccao — e sobre a necessidade de acolher sem julgamento. Casais frequentemente tem ritmos espirituais diferentes, conviccoes diferentes em areas nao essenciais. Isso pode gerar tensao ou oportunidade de aprendizado.',
    'Quais diferencas de conviccao ou de ritmo espiritual entre voces tem sido fonte de tensao — e como voces tem respondido?',
    'Voce tende a julgar as diferencas do conjuge como falhas ou a acolhe-las como parte de quem o outro e?',
    'Como a paciencia de Romanos 14 — nao julgar, nao desprezar — pode ser praticada concretamente nas diferencas entre voces?',
    'Conversem sobre uma diferenca de ritmo ou conviccao — e practiquem o acolhimento sem pressao para uniformidade.',
    'Senhor, que a paciencia seja a nossa resposta as diferencas. Que acolhamos sem exigir uniformidade. Amen.'
  ),
  dev(139,20,'II — A Noiva e formada','Romanos 15','Unidade que acolhe a diferenca ao inves de exigir uniformidade','Unidade que acolhe',
    'Cristo acolheu a todos — judeus e gentios — para gloria de Deus. Como essa unidade na diversidade se aplica ao casal que vem de historias e familias diferentes?',
    'Romanos 15 e um capitulo sobre a unidade que nao apaga as diferencas mas as reconcilia numa missao comum. O casamento que acolhe as diferencas de historia, temperamento e background sem exigir que o outro seja igual cria uma unidade mais rica.',
    'Quais diferencas de historia familiar ou de temperamento voces tem tentado eliminar ao inves de integrar na unidade do casal?',
    'Voce tem valorizado o que o conjuge traz de diferente — como complemento — ou tem visto as diferencas principalmente como obstaculos?',
    'Como a unidade de Romanos 15 — que inclui a diversidade — pode ser o modelo para o casamento de voces?',
    'Cada um nomeia uma diferenca do conjuge que inicialmente era dificil mas que agora ve como presente.',
    'Senhor, que a nossa unidade acolha as diferencas. Que nos complementemos ao inves de nos uniformizarmos. Amen.'
  ),
  mesa(140,20,'II — A Noiva e formada','Mesa da Alianca — Semana 20'),

  // SEMANA 21
  dev(141,21,'II — A Noiva e formada','Romanos 16','O valor da colaboracao de homens e mulheres na obra comum','Colaboracao na obra',
    'Paulo nomeia mulheres como companheiras na obra — Febe, Prisca, Maria, Junia. O lar de voces valoriza e sustenta a contribuicao de cada um?',
    'Romanos 16 e uma lista de colaboradores — e inclui mulheres de forma notavel para o contexto. A obra do Reino e colaborativa. O casal que valoriza os dons e a contribuicao de ambos e mais fecundo do que o que concentra tudo em um.',
    'Ha dons do conjuge que voce nao tem valorizado ou apoiado suficientemente — que precisam ser reconhecidos?',
    'Voce tem criado condicoes para que o conjuge floresça no que Deus o chamou a fazer — ou inconscientemente inibe o outro?',
    'Como o lar pode celebrar mais ativamente a contribuicao unica de cada um para a obra comum?',
    'Digam um ao outro um dom especifico que percebem no conjuge e que querem ver mais desenvolvido.',
    'Senhor, que o nosso lar seja espaco de colaboracao — onde os dons de cada um sao celebrados e utilizados. Amen.'
  ),
  dev(142,21,'II — A Noiva e formada','1 Corintios 1','Unidade acima de comparacoes e faccoes dentro de casa','Unidade sem faccoes',
    'Paulo repreende as divisoes na Igreja de Corinto — cada grupo seguia um lider diferente. Voces ja se dividiram em faccoes dentro do lar — cada um seguindo sua propria agenda?',
    'O problema de Corinto era de lealdades divididas — cada um afirmando seguir o melhor lider. No lar, isso aparece quando cada conjuge defende sua propria perspectiva como superior e a unidade fragmenta. A cruz de Cristo e o ponto de reunificacao.',
    'Ha algum tema — financas, criacao de filhos, priorizacoes — onde voces persistentemente ficam em lados opostos sem encontrar unidade?',
    'Voce tende a reforcar sua perspectiva com aliados — familia, amigos — ao inves de buscar unidade direto com o conjuge?',
    'Como a sabiduría da cruz — que inverte a sabedoria do mundo — pode ser o caminho de unidade quando ha impasse?',
    'Identifiquem um tema de divisao persistente e comprometam-se a aborda-lo buscando unidade, nao vitoria.',
    'Senhor, que a cruz seja o nosso ponto de reunificacao. Que a unidade seja mais valorizada do que estar certo. Amen.'
  ),
  dev(143,21,'II — A Noiva e formada','1 Corintios 2','Depender do Espirito, nao da esperteza propria, nas decisoes do lar','Depender do Espirito',
    'Paulo nao veio a Corinto com sabedoria de palavras, mas com demonstracao do Espirito — como o lar de voces tem dependido do Espirito nas decisoes mais importantes?',
    'O Espirito revela as coisas profundas de Deus — e isso inclui direcao para o lar. Depender da propria inteligencia e da analise estrategica ao inves do discernimento espiritual e uma armadilha sutil para casais educados e competentes.',
    'Nas decisoes mais importantes do lar, voces tem buscado o discernimento do Espirito — ou confiado principalmente na propria inteligencia e analise?',
    'Voce tem espaço na sua rotina para o discernimento espiritual — silencio, oracao, Palavra — antes de tomar decisoes?',
    'Como o lar pode cultivar uma cultura de discernimento espiritual nas decisoes cotidianas — nao apenas nas grandes?',
    'Antes de uma decisao pendente, orem juntos pedindo especificamente o discernimento do Espirito.',
    'Senhor Espirito, guia as decisoes do nosso lar. Que a nossa sabedoria seja tua, nao nossa propria. Amen.'
  ),
  dev(144,21,'II — A Noiva e formada','1 Corintios 3','Crescimento gradual do casal, sem rivalidade entre os dois','Crescimento sem rivalidade',
    'Um planta, outro rega, mas Deus da o crescimento — como voces reconhecem que o crescimento do lar depende de Deus, nao apenas dos seus esforcos?',
    'Paulo e Apolos sao colaboradores, nao rivais — cada um tem seu papel e Deus e o que da o crescimento. O lar que entende isso para de rivalizar sobre quem contribui mais e passa a colaborar com confianca.',
    'Ha alguma rivalidade implicita entre voces sobre quem esta crescendo mais espiritualmente — ou quem contribui mais para o lar?',
    'Voce tem celebrado o crescimento do conjuge sem ciume — vendo-o como parte do crescimento do casal?',
    'Como a perspectiva de que Deus da o crescimento liberta voces da pressao de produzir resultados imediatos?',
    'Celebrem juntos uma area de crescimento que observam um no outro — sem comparar com o proprio crescimento.',
    'Senhor, que celebremos o crescimento um do outro. Que saibamos que tu es o que da o crescimento e nao competamos. Amen.'
  ),
  dev(145,21,'II — A Noiva e formada','1 Corintios 4','Humildade de quem serve sem precisar de holofote','Servir sem holofote',
    'Paulo diz que nao importa o que os homens julgam — e o Senhor que julga. Como a aprovacao externa tem afetado as decisoes do lar de voces?',
    'A humildade de Paulo em 1 Corintios 4 e a humildade de quem serve sem depender do reconhecimento humano. O lar que serve sem precisar de holofote — na comunidade, nas redes sociais, na familia extensa — tem uma liberdade que o lar que serve para ser visto nao tem.',
    'Ha alguma area do servico do lar que esta sendo afetada pelo desejo de reconhecimento — do que outros vao pensar ou dizer?',
    'Voce tem servido ao conjuge e ao lar de forma que seria feita mesmo se ninguem soubesse — ou o reconhecimento e parte da motivacao?',
    'Como o lar pode cultivar uma cultura de servico genuino sem dependencia de aprovacao externa?',
    'Identifiquem um gesto de servico que sera feito esta semana sem que ninguem externo saiba.',
    'Senhor, que sirvamos sem holofote. Que o teu julgamento seja o unico que importa no nosso lar. Amen.'
  ),
  dev(146,21,'II — A Noiva e formada','1 Corintios 5','Seriedade com o pecado sexual dentro da propria vida','Seriedade com a pureza',
    'Paulo repreende a Igreja por tolerar pecado sexual em seu meio sem atitude — como o lar de voces lida seriamente com a pureza sexual?',
    'A seriedade de Paulo com o pecado sexual nao e puritanismo; e protecao da saude espiritual da comunidade. O lar que leva a sério a pureza sexual — nao por legalismo, mas por amor a Deus e ao conjuge — e um lar com protecao real.',
    'Ha algum padrao de comportamento sexual — on-line ou fora — que o lar sabe que precisa ser abordado com mais seriedade?',
    'Voce tem guardado a sua mente e os seus olhos com a seriedade que o amor pelo conjuge exige — ou tem tolerado pequenas concessoes?',
    'Como o lar pode criar um ambiente de seguranca e transparencia onde questoes de pureza possam ser faladas com honestidade?',
    'Conversem com honestidade sobre um limite que querem estabelecer juntos para a protecao da pureza do lar.',
    'Senhor, que a pureza seja valor real no nosso lar. Que amemos o conjuge o suficiente para guardar nossa fidelidade com seriedade. Amen.'
  ),
  mesa(147,21,'II — A Noiva e formada','Mesa da Alianca — Semana 21'),

  // SEMANA 22
  dev(148,22,'II — A Noiva e formada','1 Corintios 6','O corpo pertence a Deus, inclusive na vida sexual do casal','O corpo como templo',
    'O corpo e templo do Espirito Santo — como essa verdade redefine a forma como voces tratam a intimidade conjugal?',
    'Paulo em 1 Corintios 6 ensina que o corpo pertence ao Senhor — o que tem implicacoes para a vida sexual. O casamento e o espaco dado por Deus para a expressao da sexualidade — e dentro dele o corpo e honrado, nao usado.',
    'Como a verdade de que o corpo e templo do Espirito Santo molda a forma como voces entendem e praticam a intimidade conjugal?',
    'Ha alguma maneira pela qual a vida sexual do casal nao esta refletindo o respeito ao corpo como templo — da propria pessoa ou do conjuge?',
    'Como voces podem cultivar uma visao saudavel e teologicamente enraizada da sexualidade conjugal — como presente de Deus, nao como performance ou obrigacao?',
    'Conversem honestamente sobre o que cada um precisa para que a intimidade no lar seja expressa com respeito e amor genuino.',
    'Senhor, que honremos o corpo — o nosso e o do conjuge — como teu templo. Que a intimidade seja presente, nao pressao. Amen.'
  ),
  dev(149,22,'II — A Noiva e formada','1 Corintios 7','O capitulo mais direto do NT sobre deveres e vida conjugal','Deveres e graca conjugal',
    'Paulo fala diretamente sobre o casamento — deveres mutuos, concessao, separacao temporaria para oracao. O que chama a atencao de voces neste capitulo?',
    'Primeiro Corintios 7 e o texto mais detalhado do NT sobre vida conjugal pratica. Paulo equilibra o ideal e o real: ha chamados ao celibato e ao casamento, ha deveres mutuos, ha concessoes necessarias. O lar que conhece esse texto tem uma visao mais madura do que o lar que o ignora.',
    'Qual elemento de 1 Corintios 7 mais desafia ou esclarece a visao de voces sobre o casamento?',
    'Os deveres mutuos de que Paulo fala — autoridade sobre o proprio corpo pertencendo ao conjuge — como isso se traduz na vida pratica de voces?',
    'Como voces tem equilibrado os chamados individuais com o chamado compartilhado do casamento?',
    'Leiam juntos 1 Corintios 7.3-5 e conversem sobre como aplicar isso de forma pratica e respeitosa no lar.',
    'Senhor, que a nossa vida conjugal honre os deveres que descreveste com graca e amor mutuo. Amen.'
  ),
  dev(150,22,'II — A Noiva e formada','1 Corintios 8','Renunciar direitos pessoais por amor ao outro','Renunciar direitos por amor',
    'Paulo abre mao do direito de comer carne sacrificada para nao fazer tropegar o irmao mais fraco. Que direitos voce tem abdicado por amor ao conjuge?',
    'Renunciar a um direito legítimo por amor e um dos atos mais maduros de fe. O lar onde cada um esta disposto a abdicar de direitos — nao porque e errado te-los, mas porque o amor do outro e mais importante — e um lar com cultura extraordinaria.',
    'Ha um direito — de tempo, de espaco, de preferencia — que voce esta segurando e que seria amor solta-lo pelo bem do conjuge?',
    'Voce tende a reivindicar seus direitos no lar — mesmo quando eles sao legítimos — antes de considerar o impacto sobre o conjuge?',
    'Como a disposicao de Paulo de abdicar do seu direito por amor pode transformar um conflito especifico do lar?',
    'Cada um identifica um direito que poderia abdicar por amor ao conjuge esta semana.',
    'Senhor, que o amor pelo conjuge seja maior do que o apego aos nossos direitos. Que abdicamos de boa vontade. Amen.'
  ),
  dev(151,22,'II — A Noiva e formada','1 Corintios 9','Sacrificio pessoal por uma causa maior que o proprio conforto','Sacrificio por algo maior',
    'Paulo correu a corrida de forma a ganhar — com disciplina e sacrificio. O casal de voces tem corrido juntos com essa intensidade?',
    'Paulo descreve seu ministerio como atletismo espiritual — sacrificio, disciplina, correr para vencer. O lar que tem esse nivel de comprometimento com o chamado nao e o lar que busca o caminho mais facil, mas o que tem proposito suficiente para pagar o custo.',
    'Ha algo no chamado comum de voces que exige sacrificio pessoal que voces ainda nao estao dispostos a pagar?',
    'Voce tem sido disciplinado — em fe, em oração, em carater — de forma que sustenta o chamado do lar?',
    'Como o casal pode se encorajar mutuamente a correr a corrida com mais intensidade e proposito?',
    'Definam juntos uma area de disciplina espiritual que querem cultivar para fortalecer o chamado do lar.',
    'Senhor, que corramos a corrida com voce. Que o sacrificio pelo chamado seja voluntario e alegre. Amen.'
  ),
  dev(152,22,'II — A Noiva e formada','1 Corintios 10','Aprender com os erros do passado para nao repeti-los em casa','Aprender com o passado',
    'Essas coisas aconteceram como exemplos para nos — a historia de Israel e ensinamento para o presente. O lar de voces tem aprendido com os erros do passado?',
    'Paulo usa a historia de Israel como catecismo de avisos: nao idolatrar, nao tentar a Deus, nao murmurar. Aprender com o passado — o proprio e o coletivo — e sabedoria. O lar que repete os mesmos erros sem aprender esta desperdicando os ensinamentos da propria historia.',
    'Ha padroes do passado — no historico do relacionamento ou das familias de origem — que o lar tem repetido sem perceber?',
    'Voce tem sido honesto sobre como os padroes da sua familia de origem afetam a forma como voce se comporta no lar?',
    'Como o lar pode criar uma cultura de aprendizado com os erros — sem vergonha, mas com disposicao de mudar?',
    'Conversem sobre um padrao que voces reconhecem que e herdado e que querem conscientemente romper.',
    'Senhor, que aprendamos com o passado e nao o repitamos. Que a historia do lar seja de aprendizado e crescimento. Amen.'
  ),
  dev(153,22,'II — A Noiva e formada','1 Corintios 11','Ordem e reverencia na vida em comum do casal','Ordem e reverencia em casa',
    'Paulo fala sobre a Ceia do Senhor e a necessidade de se examinar antes de participar. Como o lar de voces pratica a auto-examinacao e a reverencia na vida espiritual?',
    'O ensino sobre a Ceia em 1 Corintios 11 e fundamentalmente sobre reconhecimento — do corpo, da importancia do gesto, da propria indignidade. A reverencia nao e sisudez — e consciencia de que ha algo sagrado acontecendo. O lar que trata as praticas espirituais com reverencia cria uma atmosfera diferente.',
    'Como o lar de voces pratica as disciplinas espirituais — Ceia, oracao, leitura — com reverencia genuina ou de forma apressada e automatica?',
    'Ha alguma pratica espiritual do lar que tem sido feita de forma tao automatica que perdeu o peso e a seriedade?',
    'Como voces podem renovar a reverencia nas praticas espirituais do lar — tornando-as mais significativas?',
    'Antes da proxima vez que participarem da Ceia do Senhor, orem juntos de preparacao e exame.',
    'Senhor, que a reverencia seja o tom das nossas praticas espirituais. Que o sagrado seja tratado com o peso que merece. Amen.'
  ),
  mesa(154,22,'II — A Noiva e formada','Mesa da Alianca — Semana 22'),

  // SEMANA 23
  dev(155,23,'II — A Noiva e formada','1 Corintios 12','Complementaridade de dons e papeis dentro do casamento','Complementares por design',
    'O corpo tem muitos membros, mas e um so corpo — como a complementaridade dos dons de cada um do casal fortalece o todo?',
    'O ensino de 1 Corintios 12 sobre o corpo e diretamente aplicavel ao casamento: o olho nao pode dizer ao pe que nao precisa dele. A complementaridade e design — nao acidente, nao problema. O casal que celebra as diferencas de dons ao inves de resenti-las descobre sua forca coletiva.',
    'Os dons de cada um de voces sao vistos como complementares ou como fonte de tensao por serem diferentes?',
    'Ha um dom do conjuge que voce subestima — e que ao ser mais valorizado fortaleceria o lar?',
    'Como o lar pode usar mais intencionalmente os dons distintos de cada um para o ben comum?',
    'Cada um nomeia dois dons do conjuge e como eles fortalecem o lar.',
    'Senhor, obrigado por nos fazer diferentes e complementares. Que valorizemos o que o outro traz. Amen.'
  ),
  dev(156,23,'II — A Noiva e formada','1 Corintios 13','O hino do amor: a definicao mais completa de amor para noivos','O hino do amor',
    'Sem amor eu nada sou — Paulo coloca o amor como o que da valor a tudo mais. Qual parte do hino do amor mais desafia a forma como voces amam?',
    'Primeiro Corintios 13 e o texto mais citado em casamentos — e raramente o mais lido com honestidade. O amor que Paulo descreve e exigente: paciente, bondoso, sem ciumes, sem se vangloriar, nao se porta inconvenientemente. Cada clausula e um espelho.',
    'Qual das qualidades do amor em 1 Corintios 13 e mais dificil para voces praticarem consistentemente?',
    'O amor sofre e e benigno — na ordem apresentada. Como voce tem suportado com bondade o que o conjuge traz de dificil?',
    'Como o amor que \"tudo sofre, tudo cre, tudo espera, tudo suporta\" se traduz em pratica real no cotidiano do lar?',
    'Leiam juntos 1 Corintios 13 em voz alta, substituindo \"o amor\" pelo nome do conjuge — e orem sobre o que emerge.',
    'Senhor, que o amor que descreveste seja o amor que praticamos. Que 1 Corintios 13 seja espelho e mapa, nao apenas poesia. Amen.'
  ),
  dev(157,23,'II — A Noiva e formada','1 Corintios 14','Edificacao mutua como prioridade acima da autoafirmacao','Edificar um ao outro',
    'Tudo seja feito para edificacao — Paulo coloca o bom do outro como criterio. Como o que voces dizem e fazem no lar tem edificado o conjuge?',
    'O criterio de Paulo para o uso dos dons e edificacao — o bem do outro. O lar que usa esse criterio para comunicacao, para decisoes, para uso do tempo e um lar onde cada um se sente construido e nao demolido.',
    'O que voce diz e faz regularmente no lar — edifica o conjuge ou tende a diminuir, criticar ou ignorar?',
    'Ha um habito de comunicacao no lar que voce sabe que demole ao inves de edificar — e que precisa mudar?',
    'Como o criterio de edificacao pode ser aplicado a decisao de como voce responde ao conjuge nos proximos 7 dias?',
    'Comprometam-se a uma semana de comunicacao intencional focada em edificacao — sem critica negativa.',
    'Senhor, que tudo o que fazemos no lar seja para edificacao. Que o conjuge seja construido por nos, nao demolido. Amen.'
  ),
  dev(158,23,'II — A Noiva e formada','1 Corintios 15','Esperanca da ressurreicao que muda como vivemos hoje juntos','Ressurreicao muda o presente',
    'Se os mortos nao ressuscitam, comamos e bebamos, pois amanha morreremos — a ressurreicao muda tudo sobre como o casal vive hoje. Como essa esperanca afeta as escolhas do lar?',
    'A teologia da ressurreicao de 1 Corintios 15 nao e apenas sobre o futuro — e sobre como o futuro muda o presente. O lar que vive com essa esperanca nao esta apenas sobrevivendo; esta investindo no que tem valor eterno.',
    'Como a esperanca da ressurreicao concretamente muda as escolhas e prioridades do lar de voces?',
    'Ha areas onde o lar tem vivido como se so o presente importasse — sem considerar o que tem valor eterno?',
    'Como o primeiro dia de uma nova semana pode ser vivido com a expectativa de quem cre na ressurreicao?',
    'Conversem sobre como a esperanca eterna muda uma decisao pratica especifica que o lar enfrenta agora.',
    'Senhor da ressurreicao, que a nossa esperanca no futuro transforme o nosso presente. Que o lar invista no que dura para sempre. Amen.'
  ),
  dev(159,23,'II — A Noiva e formada','1 Corintios 16','Generosidade pratica e comunhao continua no relacionamento','Generosidade pratica',
    'Paulo instruiu a Igreja a separar todo domingo uma parte para o sustento dos santos — a generosidade e disciplina regular, nao impulso ocasional. Como o lar pratica generosidade com regularidade?',
    'A coleta para os santos em 1 Corintios 16 mostra que a generosidade e uma pratica regular e planejada — nao apenas espontanea. O lar que constroi generosidade como habito regular tem uma cultura diferente do que da apenas quando conveniado.',
    'O lar de voces tem uma pratica regular de generosidade — com dinheiro, com tempo, com espaco — ou e apenas ocasional?',
    'Como voces tem usado os recursos do lar para o bem de outros de forma sistematica — nao apenas quando sobra?',
    'Que pratica de generosidade regular o lar poderia estabelecer para esta temporada?',
    'Comprometam-se a uma pratica especifica de generosidade regular — com um valor, uma frequencia e um destino.',
    'Senhor, que a generosidade seja habito do nosso lar, nao impulso. Que demos com regularidade e alegria. Amen.'
  ),
  dev(160,23,'II — A Noiva e formada','2 Corintios 1','Consolar um ao outro como fomos consolados por Deus','Consolar como fomos consolados',
    'O Deus de toda a consolacao nos consola em todas as nossas tribulacoes, para que possamos consolar os outros — como a consolacao que voces recebem de Deus tem sido transmitida ao conjuge?',
    'A consolacao que Paulo descreve em 2 Corintios 1 e transformadora: o que recebemos de Deus nos equipa para oferecer ao outro. O lar onde os dois sao consolados por Deus e onde a consolacao transborda na direcao do outro e um lar com capacidade de suportar muito.',
    'Como a consolacao que Deus te deu em uma area de dor tem te equipado para consolar o conjuge na dor dele?',
    'Voce tem sido para o conjuge a presenca consoladora que Deus e para voce — ou tende a resolver ao inves de consolar?',
    'Qual dor atual do conjuge pede consolacao mais do que solucao — e como voce pode oferecer isso?',
    'Orem juntos sobre uma area de dor de cada um — e pratiquem consolar ao inves de resolver.',
    'Senhor Deus de toda consolacao, que o que recebemos de ti transborde para o outro. Que consolemos como fomos consolados. Amen.'
  ),
  mesa(161,23,'II — A Noiva e formada','Mesa da Alianca — Semana 23'),

  // SEMANA 24
  dev(162,24,'II — A Noiva e formada','2 Corintios 2','Restaurar quem se arrependeu, sem guardar rancor em casa','Restaurar sem guardar rancor',
    'Paulo instrui a Igreja a restaurar quem se arrependeu — nao a puni-lo indefinidamente. Como o lar pratica restauracao genuina apos o arrependimento?',
    'A restauracao que Paulo pede em 2 Corintios 2 e pratica e deliberada: confirmem o amor por ele, acolham. O lar que restaura sem guardar rancor oculto tem uma graca que transforma o clima emocional de toda a casa.',
    'Ha algum arrependimento do conjuge que voce aceitou verbalmente mas ainda nao liberou no coracao — ainda guardando como registro implicito?',
    'Como voce pode demonstrar restauracao genuina — nao apenas perdao verbal, mas abertura real — apos uma falha resolvida?',
    'O lar de voces tem uma cultura de restauracao genuina ou de perguntas sarcasticas que lembram o passado resolvido?',
    'Se ha algo que foi perdoado mas que ainda aparece na comunicacao, comprometam-se juntos a realmente soltar.',
    'Senhor, que o perdao que concedemos seja acompanhado de restauracao real. Que nao guardemos o que ja perdoamos. Amen.'
  ),
  dev(163,24,'II — A Noiva e formada','2 Corintios 3','A nova alianca transforma o casal de dentro para fora','Nova alianca transforma',
    'Somos carta de Cristo, escrita nao com tinta mas com o Espirito do Deus vivo, nao em tabuas de pedra mas em tabuas de carnes — em coracoes. O lar de voces e uma carta viva?',
    'O ministerio do Novo Pacto em 2 Corintios 3 opera de dentro para fora — nao regras externas, mas transformacao interior. O lar que experimetna essa transformacao nao depende de listas de regras para funcionar bem; depende de coracoes transformados.',
    'Qual evidencia externa mostraria que a nova alianca esta operando de dentro para fora no lar de voces?',
    'Voce tem buscado mais regras e estruturas externas para o lar — ou tem investido na transformacao interior que gera a cultura que voce quer?',
    'Como o lar pode ser uma carta visivel de Cristo para quem esta ao redor — sem que precisem explicar nada?',
    'Identificem uma transformacao interior que tem produzido mudanca exterior no lar — e celebrem isso.',
    'Senhor do Novo Pacto, que a transformacao que operas em nos seja visivel no lar. Que sejamos carta de Cristo que qualquer um pode ler. Amen.'
  ),
  dev(164,24,'II — A Noiva e formada','2 Corintios 4','A forca de Deus revelada na fraqueza reconhecida do casal','Forca na fraqueza',
    'Temos este tesouro em vasos de barro — para que o poder seja de Deus e nao de nos. Como a fraqueza reconhecida do lar tem revelado a forca de Deus?',
    'Os vasos de barro de 2 Corintios 4 nao sao um problema a resolver; sao o design pelo qual a gloria de Deus aparece. O lar que reconhece sua fraqueza com honestidade e o lar atraves do qual Deus aparece com mais clareza.',
    'Em qual area de fraqueza do lar a forca de Deus tem sido mais visivelmente revelada — algo que voces nao conseguiriam por propria forca?',
    'Voce tende a esconder as fraquezas do lar por vergonha — ou a declara-las com a confianca de quem sabe que Deus se manifesta atraves delas?',
    'Como a fraqueza reconhecida pode se tornar testemunho — ao inves de vergonha — no circulo de voces?',
    'Partilhem com alguem de confianca uma area de fraqueza do lar e como Deus tem agido atraves dela.',
    'Senhor, que a nossa fraqueza seja a tua oportunidade. Que o tesouro brilhe atraves dos vasos de barro. Amen.'
  ),
  dev(165,24,'II — A Noiva e formada','2 Corintios 5','Identidade nova em Cristo moldando a vida do lar','Nova criatura no lar',
    'Se alguem esta em Cristo, nova criatura e — as coisas velhas passaram e eis que tudo se tornou novo. Como a novidade de identidade em Cristo molda o cotidiano do lar de voces?',
    'A nova criacao de 2 Corintios 5 nao e apenas um estado interno — e uma nova maneira de ver tudo, inclusive o conjuge. \"Nao mais conhecemos ninguem segundo a carne\" — isso muda como o conjuge e visto.',
    'Como voce ve o conjuge — segundo a carne, com suas falhas e historias, ou como nova criatura em Cristo?',
    'Qual aspecto da identidade nova em Cristo o lar ainda nao internalizou — e que ao ser internalizado mudaria algo concreto?',
    'Como a missao de reconciliacao que Cristo nos deu se traduz em como o lar trata os conflitos internos e externos?',
    'Orem juntos declarando a identidade nova — nova criatura — sobre si mesmo e sobre o conjuge.',
    'Senhor, que vejamos um ao outro como novas criaturas em ti. Que o velho nao defina o que tu renovaste. Amen.'
  ),
  dev(166,24,'II — A Noiva e formada','2 Corintios 6','Principio decisivo para escolha e convivencia do futuro conjuge','Com quem me uno?',
    'Nao vos prendais em jugo desigual com os incrédulos — Paulo coloca um principio claro sobre uniao espiritual. Como isso fala ao casal que ja se uniu — sobre alinhamento espiritual?',
    'Para casais ja unidos em fe, 2 Corintios 6 fala sobre a importancia de crescerem juntos em alinhamento espiritual — nao apenas de serem «os dois cristaos», mas de caminharem juntos na fe de forma ativa. A desigualdade espiritual que cresce dentro de um casamento ja estabelecido e um risco real.',
    'O alinhamento espiritual entre voces tem crescido — voces estao caminhando na mesma direcao em termos de fe, valores e praticas?',
    'Ha uma distancia espiritual crescendo entre voces que precisa ser nomeada e abordada com honestidade?',
    'Como voces podem fortalecer o alinhamento espiritual entre si — de forma intencional e pratica?',
    'Conversem sobre o estado do alinhamento espiritual de voces — com honestidade e proposito de crescimento conjunto.',
    'Senhor, que caminhemos juntos espiritualmente — nao apenas como crentes individuais, mas como lar que cresce unido. Amen.'
  ),
  dev(167,24,'II — A Noiva e formada','2 Corintios 7','Conflito bem resolvido fortalece, nao enfraquece, a relacao','Conflito que fortalece',
    'Paulo ficou triste de ter causado tristeza com sua carta — mas se alegrou porque a tristeza produziu arrependimento. Como os conflitos no lar de voces tem produzido crescimento?',
    'A tristeza segundo Deus produz arrependimento que nao traz remorso — Paulo distingue tristeza saudavel da que paralisa. O conflito bem conduzido — que produz mudanca real sem destruicao — e um dos maiores formadores do relacionamento.',
    'Voces tem conflitos que produzem arrependimento real e mudanca — ou conflitos que apenas geram feridas e distancia?',
    'Como voce pode abordar o proximo conflito de forma que seja formador — produzindo crescimento mutuo ao inves de destruicao?',
    'Ha um conflito passado que produziu crescimento no relacionamento — que vale ser lembrado e celebrado?',
    'Conversem sobre um conflito que fortaleceu o relacionamento — o que ele ensinou e como o lar cresceu atraves dele.',
    'Senhor, que os nossos conflitos produzam arrependimento real e crescimento. Que a tristeza segundo Deus seja nossa resposta. Amen.'
  ),
  mesa(168,24,'II — A Noiva e formada','Mesa da Alianca — Semana 24'),

  // SEMANA 25
  dev(169,25,'II — A Noiva e formada','2 Corintios 8','Generosidade que da alem da propria capacidade, com alegria','Generosidade alem do limite',
    'Os macedonios deram alem das suas forcas — de boa vontade, porque primeiro se deram ao Senhor. O lar de voces tem dado de boa vontade, ou apenas do que sobra com facilidade?',
    'A generosidade macedonia em 2 Corintios 8 ultrapassa os calculos — eles foram alem da propria capacidade por escolha. O lar que experimenta esse nivel de generosidade descobre uma liberdade que a frugalidade calculada nao oferece.',
    'Ha alguma area de generosidade onde voces sabem que Deus esta chamando o lar a dar alem do confortavel?',
    'O lar de voces deu ao Senhor primeiro — antes de calcular o que sobra — ou a generosidade e residual?',
    'Como voces podem aumentar o nivel de generosidade do lar — de forma que reflita a graca que receberam?',
    'Orem juntos sobre um aumento especifico na generosidade do lar — e comprometam-se a um valor concreto.',
    'Senhor, que a graca que recebemos se traduza em generosidade que vai alem do calculado. Amen.'
  ),
  dev(170,25,'II — A Noiva e formada','2 Corintios 9','Generosidade que Deus multiplica dentro e fora de casa','Deus multiplica o que doamos',
    'Quem semeia com largueza, com largueza tambem ceifara — a promessa da multiplicacao da generosidade. Como essa verdade fundamenta a cultura financeira do lar de voces?',
    'A promessa de 2 Corintios 9 nao e comercial — e teologica: Deus enriquece para que possamos dar mais. O lar que confia nessa logica invierte a equacao natural: dar primeiro, confiar na multiplicacao.',
    'O lar de voces tem vivido pela logica de dar primeiro e confiar na multiplicacao — ou pela logica de guardar primeiro e dar do que sobra?',
    'Ha uma area especifica de generosidade onde o lar poderia confiar mais na promessa da multiplicacao de Deus?',
    'Como a promessa de que Deus multiplica o que doamos muda a cultura financeira do lar?',
    'Definam juntos um ato de generosidade especifico que exercitara confiança na multiplicacao de Deus.',
    'Senhor, que confiemos na tua promessa de multiplicar. Que demos com alegria e sem calcular o retorno. Amen.'
  ),
  dev(171,25,'II — A Noiva e formada','2 Corintios 10','Lutar as batalhas certas do casamento, com as armas certas','Batalhas certas, armas certas',
    'As armas da nossa milicia nao sao carnais mas poderosas em Deus — como voces tem discernido as batalhas reais do lar e as armas certas para trava-las?',
    'O casal que luta batalhas erradas — o conjuge como inimigo, o conflito domestico como guerra pessoal — desperdiça energia. O casal que identifica as batalhas espirituais reais e usa as armas certas — oracao, Palavra, unidade — e muito mais eficaz.',
    'Quais batalhas o lar tem travado com as armas erradas — conflito humano ao inves de guerra espiritual?',
    'Ha um problema recorrente no lar que talvez seja uma batalha espiritual que precisa ser travada em oracao, nao em conflito pessoal?',
    'Como voces podem identificar as batalhas espirituais reais do lar e se unir para trava-las com as armas certas?',
    'Identifiquem uma batalha espiritual do lar e orem juntos sobre ela de forma especifica e direta.',
    'Senhor, que identifiquemos as batalhas reais e usemos as armas que tu nos deste. Que oremos onde brigariamos. Amen.'
  ),
  dev(172,25,'II — A Noiva e formada','2 Corintios 11','Discernimento contra falsas promessas de facilidade no lar','Discernimento contra ilusoes',
    'Paulo adverte contra os que se apresentam como apostolos de Cristo mas sao falsos — como o lar cultiva discernimento contra vozes e modelos que prometem o que nao podem entregar?',
    'Os falsos apostolos de Corinto ofereciam um caminho mais facil, mais impressionante, mais agradavel. O lar que nao tem discernimento e atraido por promessas de casamento facil, de espiritualidade instantanea, de crescimento sem custo.',
    'Ha vozes — redes sociais, influencias culturais, modelos de casamento — que tem atraido o lar para uma versao de relacionamento que nao e biblica?',
    'Como voces tem cultivado discernimento contra os padroes culturais de casamento que prometem facilidade sem fundamento?',
    'Qual ideia sobre casamento ou familia que voces absorveram culturalmente precisaria ser avaliada a luz da Escritura?',
    'Conversem sobre um padrao cultural que tem influenciado o lar de forma que merece avaliacao critica.',
    'Senhor, da-nos discernimento para reconhecer o falso mesmo quando parece atraente. Que a tua Palavra seja o nosso padrao. Amen.'
  ),
  dev(173,25,'II — A Noiva e formada','2 Corintios 12','A graca de Deus e suficiente na fraqueza pessoal do casal','A graca basta',
    'A minha graca te basta, pois o meu poder se aperfeiçoa na fraqueza — qual e o espinho no lado de voces — individual ou como casal — que tem ensinado essa verdade?',
    'O espinho de Paulo nao e revelado — e isso e pedagogico. A fragilidade que nao some mas que se torna veiculo da graca de Deus e o ensinamento de 2 Corintios 12. O lar que aprendeu a dizer \"a graca basta\" em relacao a uma fraqueza que nao passa tem encontrado um fundamento que nada pode remover.',
    'Ha uma fraqueza persistente — no lar, no relacionamento, em um dos conjuges — que voces ainda nao conseguiram aceitar como veiculo da graca de Deus?',
    'Como a afirmacao \"a graca te basta\" fala especificamente a uma area de luta persistente no lar de voces?',
    'O que mudaria no lar se voces parassem de orar para que a fraqueza fosse removida e comecassem a confiar que a graca e suficiente nela?',
    'Orem juntos sobre uma fraqueza persistente — nao pedindo remocao, mas confiando na suficiencia da graca.',
    'Senhor, que a tua graca seja suficiente para nos. Que a nossa fraqueza seja o lugar onde o teu poder se manifesta. Amen.'
  ),
  dev(174,25,'II — A Noiva e formada','2 Corintios 13','Autoexame antes de apontar o defeito do outro','Examinar-se antes de apontar',
    'Examinai-vos para ver se estais na fe — Paulo comeca o exame por si mesmo, nao pelo outro. Como o lar pratica o autoexame antes do exame mutuo?',
    'O chamado ao autoexame de 2 Corintios 13 e um antidoto ao julgamento projetado. O lar que comeca o exame por si mesmo — antes de avaliar o conjuge — tem uma humildade que cria seguranca para o outro.',
    'Qual tendencia voce tem de ver o problema do conjuge com mais clareza do que o seu proprio problema equivalente?',
    'Como o habito de autoexame regular — antes de apontar o outro — poderia mudar a cultura de comunicacao do lar?',
    'O que o autoexame honesto revelaria sobre a sua propria contribuicao para as tensoes atuais no lar?',
    'Cada um faz um autoexame escrito ou mental — sem apontar o outro — e compartilha com o conjuge o que encontrou.',
    'Senhor, que antes de examinar o outro nos examinemos. Que a humildade comece sempre por nos mesmos. Amen.'
  ),
  mesa(175,25,'II — A Noiva e formada','Mesa da Alianca — Semana 25'),

  // SEMANA 26
  dev(176,26,'II — A Noiva e formada','Galatas 1','Guardar a pureza do evangelho dentro da propria casa','Pureza do evangelho em casa',
    'Se alguem vos anunciar outro evangelho diferente do que ja recebestes, seja anatemizado — como o lar de voces guarda a pureza do evangelho contra versoes diluidas?',
    'Paulo nao cede nem um pouco em relacao ao evangelho — a versao que salva e a que inclui a cruz, a graca, a ressurreicao. O lar que diluí o evangelho para agradar ou para facilitar perde o poder que o evangelho carrega.',
    'Ha versoes diluidas do evangelho — uma graca sem arrependimento, um Jesus sem exigencias, uma fe sem transformacao — que o lar de voces tem aceitado por influencia cultural?',
    'Como voce tem mantido a pureza do evangelho no que ensina e vive dentro do lar — especialmente diante dos filhos?',
    'Qual elemento do evangelho o lar mais precisa recuperar ou aprofundar neste momento?',
    'Conversem sobre qual aspecto do evangelho precisa ser mais claramente presente na cultura espiritual do lar.',
    'Senhor, que guardemos o evangelho que nos salvou sem diluir. Que a graca seja real e a cruz nao seja ornamento. Amen.'
  ),
  dev(177,26,'II — A Noiva e formada','Galatas 2','Liberdade da aprovacao por desempenho dentro do relacionamento','Livre da aprovacao por desempenho',
    'Paulo repreendeu Pedro publicamente porque Pedro se importava mais com a opiniao dos circuncidados do que com a verdade do evangelho. Como o desejo de aprovacao distorce o amor no lar de voces?',
    'Pedro cedeu ao medo da opiniao dos outros — e Paulo chamou isso de hipocrisia. O lar que opera por medo de aprovacao — do outro conjuge, da comunidade, da familia — nao age a partir de liberdade mas de ansiedade.',
    'Voce tem tomado decisoes no lar a partir do medo de nao ser aprovado pelo conjuge — ao inves de agir a partir de liberdade em Cristo?',
    'Ha uma area onde o desejo de aprovacao do conjuge ou de outros tem impedido a autenticidade no relacionamento?',
    'Como a liberdade da aprovacao — fundamentada na aceitacao de Deus em Cristo — pode mudar como voce se comporta no lar?',
    'Conversem sobre uma area onde o medo de aprovacao tem limitado a autenticidade entre voces.',
    'Senhor, que a tua aprovacao seja suficiente. Que vivamos no lar a partir de liberdade, nao de medo de julgamento. Amen.'
  ),
  dev(178,26,'II — A Noiva e formada','Galatas 3','Identidade em Cristo acima de qualquer merito conjugal','Identidade acima do desempenho',
    'Nao ha judeu nem grego, escravo nem livre, homem nem mulher — todos sao um em Cristo. Como essa identidade unificada em Cristo reposiciona as hierarquias no lar?',
    'A igualdade fundamental em Cristo de Galatas 3 nao cancela as diferecas — mas reposiciona a hierarquia de valor. Nenhum conjuge vale mais por seu desempenho, educacao, renda ou espiritualidade. Ambos sao igualmente filhos de Deus em Cristo.',
    'Ha alguma hierarquia implicita no lar — de quem vale mais, quem contribui mais — que contradiz a igualdade fundamental em Cristo?',
    'Como a identidade como filhos de Deus — acima de qualquer outra categoria — muda a forma como voces se relacionam?',
    'Voce age com o conjuge de uma forma que reflete que ele e igualmente filho de Deus — com o mesmo valor que voce?',
    'Digam um ao outro: «Voce e filho/filha de Deus — e isso e mais do que qualquer coisa que voce fez ou deixou de fazer».',
    'Senhor, que a identidade em Cristo seja mais definitiva do que qualquer desempenho no lar. Amen.'
  ),
  dev(179,26,'II — A Noiva e formada','Galatas 4','Liberdade da graca contra o legalismo dentro do lar','Graca contra legalismo conjugal',
    'Agora que conheceis a Deus, como vos converteis de novo aos fracas e pobres rudimentos? — o legalismo e tentador porque da sensacao de controle. O lar de voces tem lista de regras que substituem a graca?',
    'O legalismo conjugal e a tentacao de controlar o conjuge atraves de expectativas rigidas e implicitas — uma lista de deveres que define o merecimento do amor. Paulo chama a Igreja de volta a liberdade. O lar que opera pela graca e mais seguro do que o que opera por listas.',
    'Ha expectativas implicitas no lar de voces que funcionam como uma lei que o conjuge precisa cumprir para ser aceito?',
    'Voce ama o conjuge condicionalmente — quando ele cumpre as expectativas — ou com a graca incondicional que recebeu de Deus?',
    'Como o lar pode substituir gradualmente a cultura de expectativas rigidas por uma cultura de graca?',
    'Identifiquem uma expectativa implicita que tem funcionado como lei no lar — e conversem sobre como solta-la.',
    'Senhor, que a graca seja a atmosfera do nosso lar. Que libertemos um ao outro das listas que nenhum de nos pode cumprir perfeitamente. Amen.'
  ),
  dev(180,26,'II — A Noiva e formada','Galatas 5','Fruto do Espirito como alvo diario de carater do casal','Fruto do Espirito no lar',
    'O fruto do Espirito e amor, alegria, paz, longanimidade, benignidade, bondade, fidelidade, mansidao, temperanca. Qual desses frutos mais falta no lar de voces?',
    'O fruto do Espirito nao e uma lista de realizacoes; e o resultado natural de uma vida conectada a Cristo. O lar que permanece em Cristo produz esse fruto gradualmente — como arvore boa que da bons frutos.',
    'Qual fruto do Espirito voces mais precisam ver crescer no lar agora — e como voces podem colaborar com o Espirito nesse crescimento?',
    'Ha algum fruto oposto — conflito, tristeza, impaciencia, dureza, infidelidade, arrogancia — que tem caracterizado o lar mais do que o fruto do Espirito?',
    'Como o lar pode criar condicoes — praticas, habitos, ritmos — para que o fruto do Espirito cresca?',
    'Cada um escolhe um fruto do Espirito para cultivar intencionalmente esta semana e comunica ao conjuge qual e.',
    'Espirito, que o teu fruto cresca no nosso lar. Que a conexao com a videira produza o que nao conseguimos por esforco proprio. Amen.'
  ),
  dev(181,26,'II — A Noiva e formada','Galatas 6','Ajudar o outro a se levantar, nunca humilhar quem caiu','Levantar quem caiu',
    'Se alguem for surpreendido em alguma falta, restaurai-o com espirito de mansidao — como o lar trata as quedas do conjuge?',
    'A instrucao de Paulo e clara: restaurar, nao humilhar. E com mansidao, observando a si mesmo para nao cair tambem. O lar que sabe restaurar sem humilhar cria um ambiente seguro para falhar e aprender.',
    'Como voce tem respondido quando o conjuge cae em uma falha — com mansidao restauradora ou com critica que humilha?',
    'Ha alguma queda passada do conjuge que ainda esta sendo usada como arma — ao inves de ter sido usada como oportunidade de restauracao?',
    'Como o lar pode criar uma cultura onde e seguro falhar — porque ha restauracao garantida com mansidao?',
    'Conversem sobre como voces querem ser tratados quando caem — e comprometam-se a esse padrao mutuamente.',
    'Senhor, que restauremos com mansidao. Que o lar seja lugar seguro para cair e para ser levantado. Amen.'
  ),
  mesa(182,26,'II — A Noiva e formada','Mesa da Alianca — Semana 26','Cantares 4.1-16 — a beleza e a intimidade da alianca'),
];

let content = '';
for (const d of days) {
  content += '  ' + JSON.stringify(d) + ',\n';
}

fs.appendFileSync(outPath, content);
console.log('Part 3 done, days 92-182, file size:', fs.statSync(outPath).size);
