const fs = require('fs');
const path = require('path');

const filePath = path.join(__dirname, 'src/data/devocionalConfessional.ts');

const setembro = `
function gerarDiasSetembro(): DiaConfessional[] {
  const dias: DiaCompacto[] = [
    {
      dia: 244, data: '1 de setembro', tema: 'A Igreja: Visível e Invisível',
      capitulo: 'CB 1689 Cap. XXV.1–2', versiculo: 'Efésios 1.22-23',
      versiculoTexto: 'E sujeitou todas as coisas a seus pés e o constituiu cabeça sobre todas as coisas para a igreja, que é o seu corpo, a plenitude daquele que a tudo enche em tudo.',
      confissaoTexto: 'A Igreja Católica, que é invisível, consiste do número total dos eleitos que já foram, são ou serão reunidos sob Cristo, sua cabeça. A Igreja Visível consiste de todos os que em todo o mundo professam a fé verdadeira.',
      cfwRef: 'CFW XXV.1', cfwComparacao: 'CFW é mais detalhado sobre a visibilidade; CB 1689 segue mesma estrutura com ênfase batista na congregação local.',
      exposicao: 'A distinção entre Igreja Invisível (todos os eleitos de todos os tempos) e Igreja Visível (todos os professantes) é fundamento eclesiológico reformado. Cristo é Cabeça de ambas — da invisível por eleição eterna, da visível por governo e palavra. A Igreja não é clube humano nem estrutura hierárquica — é corpo de Cristo, plenitude do que enche tudo. Essa grandiosidade deve marcar nossa visão da congregação local.',
      reforco: 'Todo crente é membro da Igreja Invisível pela eleição e da Igreja Visível pela profissão. A saúde da congregação local reflete o cuidado com ambas as dimensões.',
      aplicacoes: {
        digital: 'Leia Efésios 1.22-23 e medite: "Em que medida minha vida local reflete a grandiosidade do Corpo de Cristo?"',
        familia: 'Conversem: "O que significa pertencer à Igreja de Cristo — não apenas a uma congregação local?" Ore pela Igreja universal.',
        filhos: 'Explique às crianças: "A Igreja é a família de Deus — todos que creem em Jesus no mundo inteiro são nossa família."',
        homens: 'O homem reformado entende que sua congregação local é expressão visível de realidade eterna. Sua presença, fidelidade e serviço importam cosmicamente.',
        mulheres: 'A mulher que entende a Igreja como Corpo de Cristo serve com dignidade — não por obrigação religiosa, mas por amor à família eterna de Deus.',
        igreja: 'A Igreja que ensina CB 1689 Cap. XXV forma membros com visão eclesiológica correta — que valorizam a congregação local como expressão da Igreja universal.',
      },
      oracao: 'Senhor, obrigado pela Igreja — visível e invisível. Que eu valorize minha congregação local como expressão do Corpo de Cristo. Que setembro me forme eclesiologicamente para amar e servir a Igreja com fidelidade. Amém.',
      reflexao: 'Você vê sua congregação como expressão visível do Corpo eterno de Cristo, ou apenas como grupo de pessoas com interesses religiosos comuns?',
      aplicacao: 'Escreva o nome de três membros da sua congregação pelos quais você orará durante setembro. Ore por eles hoje.',
      notas: [
        'BANNERMAN, James. <em>The Church of Christ</em>. Edinburgh: Banner of Truth, 1960. A eclesiologia reformada mais completa — fundamento para todo o mês.',
        'CLOWNEY, Edmund. <em>The Church</em>. Downers Grove: IVP, 1995. Apresentação bíblica e teológica da Igreja — acessível e profunda.',
      ],
      notaInicio: 1,
    },
    {
      dia: 245, data: '2 de setembro', tema: 'Cristo: Único Cabeça da Igreja',
      capitulo: 'CB 1689 Cap. XXV.3', versiculo: 'Colossenses 1.18',
      versiculoTexto: 'E ele é a cabeça do corpo, da igreja. Ele é o princípio, o primogênito dentre os mortos, para que em tudo tenha a preeminência.',
      confissaoTexto: 'O Senhor Jesus Cristo é o cabeça da Igreja, tendo o Pai colocado em suas mãos todo o poder necessário para o chamado, instituição, ordem e governo da Igreja.',
      cfwRef: 'CFW XXV.6', cfwComparacao: 'CFW critica o Papa como "Anticristo"; CB 1689 afirma o senhorio de Cristo sem o mesmo linguajar histórico, mas com igual firmeza.',
      exposicao: 'Cristo e somente Cristo é Cabeça da Igreja. Não o papa, não o bispo, não o pastor — Cristo. Essa afirmação reformada e batista é profundamente libertadora: a Igreja não depende da sabedoria humana para sobreviver, crescer ou ser governada. Cristo governa sua Igreja por sua Palavra e Espírito. Toda liderança eclesiástica humana é delegada, não absoluta — subordinada à Cabeça que vive e reina para sempre.',
      reforco: 'Quando a Igreja substitui Cristo por qualquer outra autoridade — tradição, carisma humano, estrutura hierárquica — ela se perverte. Cristo governa por Palavra e Espírito.',
      aplicacoes: {
        digital: 'Medite em Col 1.18: "Em que áreas da vida da sua Igreja Cristo está sendo deslocado por autoridades humanas?"',
        familia: 'Conversem: "Como Cristo governa nossa família-igreja? Sua Palavra e Espírito têm a última palavra em nossas decisões?"',
        filhos: 'Ensine: "Jesus é o chefe da Igreja — como um rei que governa seu reino com amor e sabedoria."',
        homens: 'O homem que lidera na Igreja o faz como servo de Cristo — não como senhor. Toda liderança saudável começa com submissão à Cabeça.',
        mulheres: 'A mulher que serve na Igreja serve a Cristo, não a homens. Seu serviço tem dignidade porque Cristo, não o costume humano, é quem o valoriza.',
        igreja: 'A congregação que constantemente reafirma o senhorio de Cristo sobre sua vida institucional — decisões, programas, finanças — permanece eclesiologicamente saudável.',
      },
      oracao: 'Senhor Jesus, você é a Cabeça — não eu, não nosso pastor, não nossa tradição. Que sua Palavra e Espírito governem nossa congregação com sabedoria e graça. Amém.',
      reflexao: 'Em que áreas práticas da vida da sua Igreja o senhorio de Cristo precisa ser mais claramente reconhecido?',
      aplicacao: 'Ore especificamente pela liderança da sua congregação — que ela se submeta ao governo de Cristo pela Palavra.',
      notas: [
        'GRUDEM, Wayne. <em>Systematic Theology</em>. Grand Rapids: Zondervan, 1994. Cap. 44 — A Natureza da Igreja. Apresentação clara do senhorio de Cristo.',
      ],
      notaInicio: 20,
    },
    {
      dia: 246, data: '3 de setembro', tema: 'Governo Congregacional: Os Santos Governam',
      capitulo: 'CB 1689 Cap. XXV.4–5', versiculo: '1 Pedro 2.9',
      versiculoTexto: 'Mas vós sois geração eleita, sacerdócio real, nação santa, povo adquirido para que anuncieis as virtudes daquele que vos chamou das trevas para a sua maravilhosa luz.',
      confissaoTexto: 'Às igrejas particulares assim constituídas está confiada, segundo a mente de Cristo, toda a autoridade ou poder para o cumprimento do culto e da disciplina que ele lhes ordenou.',
      cfwRef: 'CFW XXXI', cfwComparacao: 'CFW prevê sínodos e concílios; CB 1689 enfatiza a autonomia congregacional — cada Igreja local sob Cristo governa a si mesma.',
      exposicao: 'O governo congregacional não é democracia religiosa — é teocracia exercida pela congregação reunida. Cada membro é sacerdote real (1Pe 2.9); cada congregação tem autoridade para ordenar seu culto e exercer disciplina conforme a Palavra. Isso não é independentismo anárquico — é governo eclesiástico onde Cristo governa por meio dos santos reunidos em seu nome, não por meio de hierarquias externas.',
      reforco: 'A saúde do congregacionalismo depende de membros maduros, doutrinados e espiritualmente comprometidos — não de profissionais religiosos.',
      aplicacoes: {
        digital: 'Leia 1Pe 2.9 e reflita: "Como sacerdote real, que responsabilidade tenho na vida da minha congregação?"',
        familia: 'Conversem sobre a responsabilidade de cada membro na saúde da congregação. A Igreja não é "do pastor" — é do povo de Deus.',
        filhos: 'Ensine: "Na nossa Igreja, todos os membros são responsáveis — todos oramos, todos participamos, todos cuidamos uns dos outros."',
        homens: 'O homem numa congregação congregacionalista tem responsabilidade de voto, discernimento e participação — não pode ser membro passivo.',
        mulheres: 'A mulher como sacerdotisa real participa ativamente da vida da congregação — oração, discernimento, cuidado pastoral entre irmãs.',
        igreja: 'A congregação que educa seus membros sobre o governo congregacional produz participação madura e responsável — não apenas presença passiva.',
      },
      oracao: 'Senhor, obrigado por me fazer sacerdote real em tua Igreja. Que eu assuma essa responsabilidade com maturidade — participando, discernindo e cuidando da minha congregação com fidelidade. Amém.',
      reflexao: 'Você exerce ativamente sua responsabilidade como membro da congregação, ou transfere para a liderança toda a responsabilidade eclesiástica?',
      aplicacao: 'Identifique uma área da vida da sua congregação onde você pode contribuir mais ativamente. Dê o primeiro passo esta semana.',
      notas: [
        'HAMMETT, John. <em>Biblical Foundations for Baptist Churches</em>. Grand Rapids: Kregel, 2005. A defesa mais completa do congregacionalismo batista — essencial para setembro.',
      ],
      notaInicio: 38,
    },
    {
      dia: 247, data: '4 de setembro', tema: 'Disciplina Eclesiástica: Amor que Corrige',
      capitulo: 'CB 1689 Cap. XXV.5', versiculo: 'Mateus 18.15-17',
      versiculoTexto: 'Se teu irmão pecar contra ti, vai e repreende-o entre tu e ele só... Se não te ouvir, toma ainda contigo uma ou duas pessoas... Se não os ouvir a eles, dize-o à Igreja.',
      confissaoTexto: 'A Igreja tem poder de admitir membros e de excluir aqueles que, pela censura eclesiástica, mereçam ser retirados da comunhão.',
      cfwRef: 'CFW XXIX–XXX', cfwComparacao: 'CFW e CB 1689 concordam sobre a necessidade da disciplina; a diferença está no processo: CB 1689 congrega os santos, CFW opera por concílios presbiterianos.',
      exposicao: 'A disciplina eclesiástica não é punição — é amor pastoral que busca restauração do pecador e pureza da congregação. Mateus 18 apresenta processo gradual: confronto privado, testemunhas, Igreja. A exclusão é último recurso — e sempre com objetivo restaurador (1Co 5). Congregações sem disciplina não são mais misericordiosas — são mais desonestas com a realidade do pecado e do Evangelho.',
      reforco: 'A disciplina exercida com amor, processo correto e objetivo restaurador é marca de Igreja saudável — não de Igreja autoritária.',
      aplicacoes: {
        digital: 'Leia Mt 18.15-17 e 1Co 5. Medite: "Minha congregação tem processo de disciplina saudável e amoroso?"',
        familia: 'Conversem: "Como a disciplina entre irmãos — correta e amorosa — protege a família de Deus?"',
        filhos: 'Ensine: "Na família de Deus, quando alguém erra, os outros ajudam com amor — não fingem que está tudo bem."',
        homens: 'O homem que lidera na Igreja tem responsabilidade de exercer e apoiar a disciplina — mesmo quando é desconfortável.',
        mulheres: 'A mulher que entende a disciplina como amor pastoral apoia o processo em vez de resistir por piedade mal-entendida.',
        igreja: 'A congregação que pratica disciplina saudável demonstra que leva a sério tanto o Evangelho quanto o amor fraternal.',
      },
      oracao: 'Senhor, dá-nos coragem para exercer disciplina como amor — e humildade para recebê-la quando necessário. Que nossa congregação seja saudável e honesta diante de tua santidade. Amém.',
      reflexao: 'Como sua congregação lida com o pecado público entre membros? O processo é bíblico, amoroso e restaurador?',
      aplicacao: 'Ore por membros da sua congregação que estejam em processo de restauração — pela graça de Deus neles e na Igreja.',
      notas: [
        'DEVER, Mark. <em>Nine Marks of a Healthy Church</em>. Wheaton: Crossway, 2004. Cap. 9 — Disciplina Eclesiástica. A defesa mais equilibrada e bíblica do tema.',
      ],
      notaInicio: 56,
    },
    {
      dia: 248, data: '5 de setembro', tema: 'Pastores e Diáconos: Dons para a Igreja',
      capitulo: 'CB 1689 Cap. XXVI.1–2', versiculo: 'Efésios 4.11-12',
      versiculoTexto: 'E ele mesmo concedeu uns para apóstolos, outros para profetas, outros para evangelistas, outros para pastores e mestres, para o aperfeiçoamento dos santos, para a obra do ministério, para a edificação do corpo de Cristo.',
      confissaoTexto: 'Tendo Cristo dado dons aos homens, ele estabeleceu alguns na Igreja: primeiro apóstolos, profetas e evangelistas (que já cessaram), e pastores e mestres que continuam até o fim do mundo.',
      cfwRef: 'CFW XXIII', cfwComparacao: 'CFW prevê presbíteros e diáconos com distinções mais elaboradas; CB 1689 foca em pastores/mestres e diáconos como dois ofícios permanentes.',
      exposicao: 'Os ofícios eclesiásticos não são invenção humana — são dons de Cristo à sua Igreja (Ef 4.11). Os dons apostólicos e proféticos foram fundacionais e cessaram com o fechamento do cânon. Mas pastores (bispos/presbíteros) e diáconos continuam como ofícios permanentes. O pastor não é CEO eclesiástico — é servo-líder que aperfeiçoa os santos para o ministério. O diácono serve as necessidades práticas da congregação com coração espiritual.',
      reforco: 'A Igreja que honra seus pastores e diáconos como dons de Cristo — e não como funcionários — cresce em saúde espiritual.',
      aplicacoes: {
        digital: 'Leia Ef 4.11-12 e reflita: "Meus pastores e diáconos são vistos como dons de Cristo para minha edificação?"',
        familia: 'Conversem sobre os pastores e diáconos da congregação. Ore por eles pelo nome.',
        filhos: 'Ensine às crianças os nomes dos pastores e diáconos da congregação. Ore por eles juntos.',
        homens: 'O homem reformado apoia, honra e ora por sua liderança eclesiástica — não critica, fofoca ou mina sua autoridade.',
        mulheres: 'A mulher que honra o ministério pastoral como dom de Cristo recebe a pregação e o pastoreio com coração aberto e edificante.',
        igreja: 'A congregação que ora regularmente por seus pastores e diáconos — pelo nome, com especificidade — fortalece o ministério.',
      },
      oracao: 'Senhor, obrigado pelos pastores e diáconos que deste à nossa congregação. Capacita-os, sustenta-os e usa-os para nosso aperfeiçoamento. Que eu honre teu dom com oração e apoio fiel. Amém.',
      reflexao: 'Você ora regularmente pelos pastores e diáconos da sua congregação? Como você pode apoiá-los mais concretamente?',
      aplicacao: 'Escreva uma nota de encorajamento ao seu pastor ou diácono expressando gratidão pelo ministério dele.',
      notas: [
        'STRAUCH, Alexander. <em>Biblical Eldership</em>. Littleton: Lewis & Roth, 1995. O estudo mais completo do pastorado bíblico — indispensável para líderes e membros.',
        'NEWTON, Phil e SCHMUCKER, Matt. <em>Elders in the Congregational Life</em>. Grand Rapids: Kregel, 2014. Prático e bíblico.',
      ],
      notaInicio: 74,
    },
    {
      dia: 249, data: '6 de setembro', tema: 'Qualificações e Chamado ao Ministério',
      capitulo: 'CB 1689 Cap. XXVI.3–4', versiculo: '1 Timóteo 3.1-7',
      versiculoTexto: 'Esta palavra é fiel: se alguém aspira ao episcopado, excelente obra deseja. É necessário, portanto, que o bispo seja irrepreensível, marido de uma só mulher... apto para ensinar...',
      confissaoTexto: 'Nenhum homem deve assumir para si a honra do ministério, mas deve ser chamado por Deus; e todos que são assim chamados devem ser adequadamente qualificados pela Igreja.',
      cfwRef: 'CFW XXIII.4', cfwComparacao: 'CFW e CB 1689 concordam sobre qualificações e chamado; CB 1689 enfatiza o chamado congregacional como confirmação do chamado divino.',
      exposicao: '1 Timóteo 3 apresenta qualificações para o pastorado que são primariamente de caráter, não de habilidade. "Apto para ensinar" é a única qualificação exclusivamente ministerial — todo o resto é excelência cristã madura. O chamado ao ministério tem dimensão interior (sentido pessoal de chamado), exterior (qualificações observáveis) e eclesiástica (reconhecimento da congregação). Os três elementos são necessários — nenhum sozinho é suficiente.',
      reforco: 'A congregação que examina cuidadosamente as qualificações de seus candidatos ao ministério protege o rebanho e honra Cristo.',
      aplicacoes: {
        digital: 'Leia 1Tm 3.1-7 e Tt 1.5-9. Medite: "Que tipo de caráter espiritual minha congregação forma e reconhece para o ministério?"',
        familia: 'Conversem: "O que significa ser chamado por Deus ao ministério? Como a congregação participa desse processo?"',
        filhos: 'Pergunte: "Alguém na nossa família pode sentir chamado ao ministério? Como oramos por isso?"',
        homens: 'O homem que aspira ao pastorado deve examinar honestamente 1Tm 3.1-7 — não apenas sua vontade, mas seu caráter e o reconhecimento dos irmãos.',
        mulheres: 'A mulher que ora por candidatos ao ministério e apoia o processo de reconhecimento congregacional participa da saúde eclesiástica.',
        igreja: 'A congregação que forma e reconhece candidatos ao ministério segundo 1Tm 3 produz pastores de caráter sólido e liderança saudável.',
      },
      oracao: 'Senhor, levanta para nossa congregação pastores segundo teu coração — homens de caráter, aptos para ensinar, chamados por ti e reconhecidos por nós. Que o ministério seja exercido com fidelidade e excelência. Amém.',
      reflexao: 'Sua congregação tem processo claro para identificar, formar e reconhecer candidatos ao ministério segundo as qualificações bíblicas?',
      aplicacao: 'Ore pelos jovens da sua congregação que possam estar sendo chamados ao ministério. Identifique um e encoraje-o esta semana.',
      notas: [
        'ALEXANDER, Archibald. <em>Thoughts on Religious Experience</em>. Edinburgh: Banner of Truth, 1967. Clássico sobre discernimento do chamado interior ao ministério.',
      ],
      notaInicio: 93,
    },
    {
      dia: 250, data: '7 de setembro', tema: 'A Igreja Local: Coração da Eclesiologia Batista',
      capitulo: 'CB 1689 Cap. XXVI.5–6', versiculo: 'Atos 2.42-47',
      versiculoTexto: 'E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações... E todos os que criam estavam juntos...',
      confissaoTexto: 'As igrejas assim constituídas, cada qual com seu ministério completo para edificação e perfeição dos santos, têm poder de admitir membros e de exercer disciplina segundo a Palavra.',
      cfwRef: 'CFW XXV.4', cfwComparacao: 'CFW e CB 1689 concordam sobre a centralidade da Igreja local; CB 1689 ênfase batista: cada congregação é Igreja completa, não parte de hierarquia.',
      exposicao: 'Atos 2.42-47 é o retrato mais vívido da Igreja local saudável: doutrina apostólica, comunhão, ceia, oração, generosidade, alegria, testemunho. A Igreja local não é filial de denominação — é expressão completa do Corpo de Cristo em determinado lugar. Para a tradição batista confessional, a congregação local é a unidade eclesiológica fundamental — cada uma completa em si mesma sob Cristo, sua Cabeça.',
      reforco: 'A saúde da Igreja local depende da perseverança em quatro elementos fundamentais: doutrina, comunhão, ceia e oração.',
      aplicacoes: {
        digital: 'Leia At 2.42-47 e avalie: sua congregação persevera nos quatro elementos? O que está mais fraco?',
        familia: 'Conversem: "Como nossa família contribui para os quatro elementos de At 2.42-47 em nossa congregação?"',
        filhos: 'Ensine At 2.42-47 às crianças: "Os primeiros cristãos estudavam juntos, comiam juntos, oravam juntos e se ajudavam. Nós fazemos isso!"',
        homens: 'O homem que persevera nos quatro elementos de At 2.42-47 sustenta a saúde da sua congregação com fidelidade.',
        mulheres: 'A mulher que contribui para a comunhão genuína e a oração fiel fortalece dois dos quatro pilares da Igreja primitiva.',
        igreja: 'A congregação que regularmente avalia sua fidelidade a At 2.42-47 mantém perspectiva correta sobre saúde eclesiástica.',
      },
      oracao: 'Senhor, que nossa congregação persevere na doutrina apostólica, na comunhão genuína, na ceia fiel e na oração constante. Que sejamos Igreja conforme At 2.42-47 — não por nostalgia, mas por obediência e amor. Amém.',
      reflexao: 'Qual dos quatro elementos de At 2.42-47 está mais fraco na sua congregação? O que você pode fazer para fortalecê-lo?',
      aplicacao: 'Comprometa-se a participar de um momento de comunhão genuína com membros da congregação esta semana — além do culto dominical.',
      notas: [
        'DEVER, Mark. <em>The Church: The Gospel Made Visible</em>. Nashville: B&H, 2012. A eclesiologia mais influente do baptismo confessional contemporâneo.',
      ],
      notaInicio: 112,
    },
    {
      dia: 251, data: '8 de setembro', tema: 'Comunhão dos Santos: Família Espiritual Real',
      capitulo: 'CB 1689 Cap. XXVI.1', versiculo: '1 João 1.3',
      versiculoTexto: 'O que vimos e ouvimos isso também vos anunciamos, para que também vós tenhais comunhão conosco; e a nossa comunhão é com o Pai e com seu Filho Jesus Cristo.',
      confissaoTexto: 'Todos os santos que são unidos a Jesus Cristo, seu Cabeça, pela sua união com ele têm comunhão em suas graças, sofrimentos, morte, ressurreição e glória.',
      cfwRef: 'CFW XXVI.1', cfwComparacao: 'CFW e CB 1689 concordam plenamente sobre a comunhão dos santos como participação em Cristo e uns nos outros.',
      exposicao: 'A comunhão dos santos não é sociabilidade religiosa — é participação na vida trinitária mediada por Cristo. 1Jo 1.3 revela a estrutura: nossa comunhão horizontal (entre santos) é derivada da comunhão vertical (com o Pai e o Filho). Impossível ter comunhão genuína com os santos sem comunhão com Cristo. E impossível afirmar comunhão com Cristo enquanto se evita a comunhão fraternal. As duas são inseparáveis.',
      reforco: 'Comunhão genuína pressupõe abertura espiritual, honestidade sobre fraquezas, oração mútua e cuidado prático — não apenas presença nos cultos.',
      aplicacoes: {
        digital: 'Leia 1Jo 1.1-7. Medite: "Minha comunhão com outros cristãos é genuína — baseada em Cristo — ou apenas social?"',
        familia: 'Conversem: "Quais famílias da nossa congregação têm comunhão conosco de forma mais profunda? Como aprofundamos isso?"',
        filhos: 'Ensine: "Os amigos da Igreja são especiais — são família de Deus. Nossa amizade com eles é diferente das outras amizades."',
        homens: 'O homem que cultiva comunhão genuína com outros homens da congregação — oração, honestidade, responsabilidade mútua — cresce em santidade.',
        mulheres: 'A mulher que investe em comunhão genuína com outras mulheres da congregação não apenas faz amizades — exerce ministério.',
        igreja: 'A congregação que ensina e pratica comunhão genuína segundo 1Jo 1 torna-se irresistível para o mundo que busca relacionamentos reais.',
      },
      oracao: 'Senhor, aprofunda nossa comunhão — primeiro contigo, Pai, Filho e Espírito, e então uns com os outros como santos unidos em ti. Que nossa comunhão seja real, não religiosa. Amém.',
      reflexao: 'Você tem comunhão genuína com outros cristãos — honestidade, oração mútua, cuidado prático — ou apenas convivência superficial nos cultos?',
      aplicacao: 'Convide um casal ou pessoa da congregação para um momento de comunhão genuína esta semana: refeição, oração, conversa real.',
      notas: [
        'BONHOEFFER, Dietrich. <em>Life Together</em>. New York: Harper, 1954. O texto mais belo sobre comunhão cristã genuína — indispensável para este dia.',
      ],
      notaInicio: 130,
    },
    {
      dia: 252, data: '9 de setembro', tema: 'Comunhão: Compartilhando Bens Espirituais e Materiais',
      capitulo: 'CB 1689 Cap. XXVI.2', versiculo: 'Romanos 12.13',
      versiculoTexto: 'Comunicando para as necessidades dos santos; praticando a hospitalidade.',
      confissaoTexto: 'Os santos são obrigados a sustentar a comunhão e a comunidade uns com os outros, tanto para fazer sua dívida pública quanto para se socorrer mutuamente em todas as suas necessidades externas.',
      cfwRef: 'CFW XXVI.2', cfwComparacao: 'CFW e CB 1689 concordam: a comunhão dos santos tem dimensão prática e econômica — não apenas espiritual.',
      exposicao: 'A comunhão dos santos tem dimensão material inescapável. Rm 12.13 usa "comunicar" (koinōneō) — a mesma raiz de "comunhão" — para descrever compartilhar recursos com necessitados. A Igreja primitiva não separava espiritualidade de economia fraterna (At 2.44-45; 4.32-35). A comunhão verdadeira resulta em generosidade concreta. Nenhuma congregação que ignora as necessidades materiais de seus membros pratica genuinamente a comunhão dos santos.',
      reforco: 'Comunhão sem generosidade concreta é ilusão espiritual. Amor que não se expressa em recursos quando necessário não é amor bíblico.',
      aplicacoes: {
        digital: 'Leia At 4.32-35. Medite: "Minha congregação pratica partilha econômica genuína entre membros necessitados?"',
        familia: 'Conversem: "Como nossa família pode ser mais generosa com membros da congregação que têm necessidades práticas?"',
        filhos: 'Ensine: "Quando um irmão precisa de ajuda, nós ajudamos. É assim que funciona a família de Deus."',
        homens: 'O homem que pratica generosidade econômica com a congregação demonstra que sua fé é real — não apenas doutrinária.',
        mulheres: 'A mulher que exerce hospitalidade cristã genuína — mesa aberta, lar acolhedor — pratica a comunhão dos santos de forma concreta.',
        igreja: 'A congregação que tem fundo diaconal ativo e cultura de partilha econômica pratica communio sanctorum de forma bíblica e testemunhal.',
      },
      oracao: 'Senhor, guarda-nos de comunhão apenas espiritual e desencarnada. Que amemos nossos irmãos com recursos concretos, hospitalidade real e generosidade que testemunha do Evangelho. Amém.',
      reflexao: 'Sua congregação tem membros com necessidades materiais não atendidas? Como você pode contribuir para isso mudar?',
      aplicacao: 'Identifique uma necessidade concreta de um membro da congregação e supra-a esta semana — anonimamente, se possível.',
      notas: [
        'MCKNIGH, Scot. <em>A Fellowship of Differents</em>. Grand Rapids: Zondervan, 2014. A comunidade cristã como contracultura de generosidade e pertencimento.',
      ],
      notaInicio: 148,
    },
    {
      dia: 253, data: '10 de setembro', tema: 'Comunhão de Igrejas: Cooperação sem Hierarquia',
      capitulo: 'CB 1689 Cap. XXVI.3', versiculo: 'Atos 15.1-2',
      versiculoTexto: 'Paulo e Barnabé tiveram não pequena contenda e discussão com eles... ordenaram que Paulo e Barnabé e alguns outros deles subissem a Jerusalém, aos apóstolos e presbíteros, sobre esta questão.',
      confissaoTexto: 'Esta comunhão que os santos têm com Cristo não os torna partícipes da substância divina, nem iguais a Cristo em qualquer aspecto; mas é uma comunhão espiritual que, sendo participação em seus benefícios, une os santos entre si.',
      cfwRef: 'CFW XXXI.2', cfwComparacao: 'CFW formaliza concílios e sínodos com autoridade; CB 1689 prefere cooperação voluntária entre igrejas autônomas — o Concílio de At 15 como modelo.',
      exposicao: 'At 15 mostra igrejas cooperando sobre questão doutrinária vital sem que isso crie hierarquia permanente. A tradição batista confessional usa esse modelo: igrejas autônomas que cooperam voluntariamente em missão, treinamento e questões doutrinais sem abrir mão de sua autonomia congregacional. Associações e convenções batistas são expressões dessa cooperação — não estruturas de governo sobre as igrejas locais.',
      reforco: 'Cooperação intereclesial saudável fortalece a missão sem comprometer a autonomia congregacional. Isolamento e super-hierarquia são os dois extremos a evitar.',
      aplicacoes: {
        digital: 'Leia At 15.1-29. Medite: "Minha congregação coopera com outras igrejas em missão? Como esse relacionamento é estruturado?"',
        familia: 'Conversem sobre a denominação ou associação da congregação. Por que cooperar com outras igrejas fortalece a missão?',
        filhos: 'Ensine: "Nossa Igreja tem amigos em outras igrejas — juntos fazemos coisas maiores do que faríamos sozinhos."',
        homens: 'O homem que entende cooperação intereclesial apoia a missão conjunta da associação sem confundir cooperação com submissão hierárquica.',
        mulheres: 'A mulher que participa de eventos e ministérios intereclesiais amplia sua experiência do Corpo de Cristo além da congregação local.',
        igreja: 'A congregação que coopera com outras igrejas confessionalmente alinhadas fortalece a missão sem sacrificar convicção doutrinária.',
      },
      oracao: 'Senhor, que nossa congregação coopere fielmente com o Corpo mais amplo de Cristo — em missão, formação e cuidado mútuo. Que a cooperação fortaleça e o isolamento seja evitado. Amém.',
      reflexao: 'Sua congregação tem relacionamentos saudáveis com outras igrejas? Como a cooperação poderia ser aprofundada?',
      aplicacao: 'Ore por uma congregação irmã pelo nome e por seu pastor esta semana. Considere enviar uma mensagem de encorajamento.',
      notas: [
        'NETTLES, Tom. <em>The Baptists: Key People Involved in Forming a Baptist Identity</em>. 3 vols. Ross-shire: Mentor, 2005–2007. A história da cooperação batista.',
      ],
      notaInicio: 166,
    },
    {
      dia: 254, data: '11 de setembro', tema: 'Comunhão Restrita: Limites e Liberdade',
      capitulo: 'CB 1689 Cap. XXVI.4', versiculo: '2 Coríntios 6.14',
      versiculoTexto: 'Não vos prendais a um jugo desigual com os infiéis; pois que sociedade tem a justiça com a injustiça? E que comunhão tem a luz com as trevas?',
      confissaoTexto: 'Esta comunhão não se estende aos infiéis ou ímpios, pois estes não têm parte na mesma fé, esperança, amor e alegria dos santos, nem no mesmo Espírito e vida.',
      cfwRef: 'CFW XXVI.3', cfwComparacao: 'CFW e CB 1689 concordam sobre os limites da comunhão; a fronteira é a fé confessional, não a denominação ou tradição.',
      exposicao: '2Co 6.14 não proíbe toda interação com não-crentes — proíbe vínculos de comunhão íntima que comprometam a identidade cristã. A comunhão dos santos é necessariamente restrita: requer a mesma fé, o mesmo Espírito, a mesma esperança. Isso não é sectarismo — é honestidade sobre o que constitui a comunhão genuína. A pergunta não é "quem posso tolerar?" mas "com quem compartilho a vida em Cristo?"',
      reforco: 'Fronteiras de comunhão saudáveis protegem a identidade cristã sem produzir isolamento do mundo que Cristo veio salvar.',
      aplicacoes: {
        digital: 'Leia 2Co 6.14-7.1. Medite: "Meus vínculos mais profundos são com crentes? Ou a comunhão cristã é periférica em minha vida?"',
        familia: 'Conversem: "Como equilibramos abertura ao mundo (missão) e fronteiras saudáveis de comunhão (santidade)?"',
        filhos: 'Ensine: "É bom ter amigos não-cristãos e convidá-los para conhecer Jesus. Mas nossos melhores amigos são da família de Deus."',
        homens: 'O homem que cultiva sua comunhão mais profunda com crentes mantém sua identidade espiritual enquanto permanece aberto ao mundo.',
        mulheres: 'A mulher que tem suas amizades mais íntimas dentro da congregação tem suporte espiritual genuíno para os desafios da vida.',
        igreja: 'A congregação que tem cultura de comunhão genuína entre membros atrai os de fora naturalmente — sem precisar diluir sua identidade.',
      },
      oracao: 'Senhor, ajuda-nos a amar o mundo sem sermos conformados a ele. Que nossa comunhão com os santos seja profunda e real, e que essa comunhão seja testemunho atraente para os que ainda não conhecem Cristo. Amém.',
      reflexao: 'Suas amizades mais profundas e influentes são com crentes ou com não-crentes? O que isso revela sobre suas prioridades espirituais?',
      aplicacao: 'Convide um não-crente para participar de um momento de comunhão com sua congregação — refeição, evento social, grupo pequeno.',
      notas: [
        'STOTT, John. <em>The Message of 2 Corinthians</em>. Leicester: IVP, 1973. Comentário claro sobre 2Co 6.14 e os limites da comunhão cristã.',
      ],
      notaInicio: 184,
    },
    {
      dia: 255, data: '12 de setembro', tema: 'Sacramentos: Sinais e Selos da Graça',
      capitulo: 'CB 1689 Cap. XXVII.1–2', versiculo: 'Romanos 4.11',
      versiculoTexto: 'E recebeu o sinal da circuncisão, selo da justiça da fé que tivera sendo ainda incircunciso, para que fosse pai de todos os que creem sendo incircuncisos, para que a justiça lhes seja também imputada.',
      confissaoTexto: 'Os sacramentos são sinais e selos santos da aliança da graça, imediatamente instituídos por Deus, para representar Cristo e seus benefícios, e para confirmar nosso interesse nele.',
      cfwRef: 'CFW XXVII.1', cfwComparacao: 'CFW e CB 1689 concordam na definição de sacramento como sinal e selo; diferem em número: CFW inclui 7 (posição histórica reformada vs. Roma); CB 1689 aceita apenas batismo e ceia.',
      exposicao: 'Rm 4.11 revela a estrutura do sacramento: circuncisão era sinal (representação visível) e selo (confirmação) da justiça pela fé. Os sacramentos do NT — batismo e ceia — funcionam da mesma forma: são sinais visíveis de realidades espirituais e selos que confirmam as promessas da aliança da graça. Não operam ex opere operato (automaticamente pelo rito), mas pela graça do Espírito que os acompanha quando recebidos com fé.',
      reforco: 'Sacramento sem fé é ritual vazio. Fé sem sacramento é desobediência à ordem de Cristo. Os dois são inseparáveis na vida da Igreja saudável.',
      aplicacoes: {
        digital: 'Leia Rm 4.1-12. Medite: "Como o batismo e a ceia funcionam como sinais e selos da aliança na minha vida?"',
        familia: 'Conversem sobre o batismo de cada membro da família. O que esse sinal significa? Como confirmou a fé de vocês?',
        filhos: 'Explique: "O batismo e a ceia são como cartas de amor que Jesus deixou para sua Igreja — nos lembram de tudo que ele fez por nós."',
        homens: 'O homem que entende os sacramentos como sinais e selos — não como rituais automáticos — participa com fé ativa e adoração genuína.',
        mulheres: 'A mulher que compreende o significado dos sacramentos participa da ceia com gratidão profunda — meditando em Cristo, não apenas cumprindo rito.',
        igreja: 'A congregação que ensina a teologia dos sacramentos antes de administrá-los produz participação madura e adoração genuína.',
      },
      oracao: 'Senhor, que batismo e ceia sejam para mim sinais viventes de tua graça — não rituais vazios, mas selos que confirmam tuas promessas ao meu coração crente. Amém.',
      reflexao: 'Você participa da ceia com fé ativa, meditando em Cristo e seus benefícios, ou como cumprimento automático de ritual religioso?',
      aplicacao: 'Antes da próxima ceia do Senhor, leia 1Co 11.23-32 e prepare seu coração com exame genuíno e fé ativa.',
      notas: [
        'LETHAM, Robert. <em>The Lord\'s Supper: Eternal Word in Broken Bread</em>. Phillipsburg: P&R, 2001. A teologia dos sacramentos mais equilibrada e acessível.',
      ],
      notaInicio: 202,
    },
    {
      dia: 256, data: '13 de setembro', tema: 'Apenas Dois Sacramentos: Batismo e Ceia',
      capitulo: 'CB 1689 Cap. XXVII.3–4', versiculo: 'Mateus 28.19',
      versiculoTexto: 'Portanto, ide, fazei discípulos de todas as nações, batizando-os em nome do Pai, e do Filho, e do Espírito Santo.',
      confissaoTexto: 'Há apenas dois sacramentos instituídos por Cristo nosso Senhor nos evangelhos: o Batismo e a Ceia do Senhor; estes não devem ser administrados por quem não seja ministro devidamente ordenado da Palavra.',
      cfwRef: 'CFW XXIX.1', cfwComparacao: 'CFW e CB 1689 concordam em dois sacramentos contra Roma (7). CFW e CB diferem em modo do batismo e sujeitos — mas não em número.',
      exposicao: 'Mt 28.19 e Lc 22.19-20 são os dois textos instituidores dos sacramentos do NT. Cristo instituiu apenas dois — não sete como Roma ensina. Os outros cinco "sacramentos" romanos (confirmação, penitência, unção, ordens, matrimônio) não têm instituição explícita de Cristo como sinal e selo da aliança. A Reforma retornou ao princípio regulador: só o que Cristo ordenou pertence ao culto e à vida da Igreja.',
      reforco: 'O princípio regulador do culto protege a Igreja de acréscimos humanos — somente o que Cristo ordenou pertence ao culto.',
      aplicacoes: {
        digital: 'Leia Mt 28.18-20 e Lc 22.14-20. Medite: "Cristo instituiu exatamente o que minha congregação pratica como sacramento?"',
        familia: 'Conversem: "Por que obedecemos exatamente ao que Cristo instituiu — sem acrescentar nem remover?" A suficiência das Escrituras.',
        filhos: 'Ensine: "Jesus deixou dois presentes especiais para sua Igreja: o batismo e a ceia. São os únicos dois."',
        homens: 'O homem reformado compreende o princípio regulador: a Igreja não inventa atos de culto — obedece à ordem de Cristo.',
        mulheres: 'A mulher que entende por que apenas dois sacramentos é posição bíblica defende essa convicção com clareza e graça.',
        igreja: 'A congregação que ensina o princípio regulador e sua aplicação nos sacramentos educa membros com discernimento litúrgico.',
      },
      oracao: 'Senhor, que nossa congregação obedeça exatamente ao que você ordenou — sem acrescentar invenções humanas nem remover sua ordem divina. Que batismo e ceia sejam praticados com fidelidade. Amém.',
      reflexao: 'Sua congregação acrescentou práticas ao culto que não têm fundamentação na ordem explícita de Cristo? Como o princípio regulador deveria orientar isso?',
      aplicacao: 'Estude a história dos "sete sacramentos" romanos e compare com Mt 28.19 e Lc 22.19-20. Registre suas conclusões.',
      notas: [
        'FRAME, John. <em>Worship in Spirit and Truth</em>. Phillipsburg: P&R, 1996. A defesa mais clara do princípio regulador aplicado ao culto.',
      ],
      notaInicio: 220,
    },
    {
      dia: 257, data: '14 de setembro', tema: 'Sacramentos e Eficácia: Palavra e Fé',
      capitulo: 'CB 1689 Cap. XXVII.5', versiculo: '1 Coríntios 3.7',
      versiculoTexto: 'Assim, nem o que planta é alguma coisa, nem o que rega, mas Deus, que dá o crescimento.',
      confissaoTexto: 'A graça exibida ou conferida pelos sacramentos de modo algum está ligada ou vinculada a qualquer qualidade ou eficácia neles; a virtude dos sacramentos depende somente da obra do Espírito.',
      cfwRef: 'CFW XXVII.3', cfwComparacao: 'CFW e CB 1689 rejeitam ex opere operato; ambos ensinam que a eficácia sacramental depende do Espírito e da fé — não do rito em si.',
      exposicao: '1Co 3.7 aplica-se perfeitamente aos sacramentos: nem o administrador, nem o rito, nem a fórmula são a fonte da graça — mas Deus, que age por seu Espírito. Isso refuta duas posições extremas: (1) sacramentalismo católico, que faz o rito automaticamente eficaz; (2) memorialismo puro, que esvazia os sacramentos de qualquer ação divina. Os sacramentos são meios de graça reais — mas a graça é de Deus, não do rito.',
      reforco: 'Sacramentos são meios reais de graça — mas a eficácia é de Deus pelo Espírito, não da perfeição do administrador ou da fórmula.',
      aplicacoes: {
        digital: 'Leia 1Co 3.5-9. Medite: "Dependo da espiritualidade do pastor para que o batismo e a ceia sejam eficazes? Por que não?"',
        familia: 'Conversem: "O que torna o batismo e a ceia eficazes? É o pastor? É nossa disposição? É o Espírito Santo?"',
        filhos: 'Explique: "Não é o pastor que faz o batismo funcionar — é Deus. O pastor obedece, mas Deus age."',
        homens: 'O homem que entende a eficácia sacramental não fica preocupado com a perfeição do administrador — mas com a própria fé e disposição.',
        mulheres: 'A mulher que confia no Deus por trás dos sacramentos — não no ritual — participa com fé robusta e não supersticiosa.',
        igreja: 'A congregação que ensina corretamente a eficácia sacramental evita tanto o sacramentalismo quanto o memorialismo esvaziado.',
      },
      oracao: 'Senhor Espírito, que tu ajes em nós quando participamos do batismo e da ceia. Que não confiemos no rito, mas em ti — que usas os meios para nos unir a Cristo e nutrir nossa fé. Amém.',
      reflexao: 'Você tende mais ao sacramentalismo (confiar no rito automaticamente) ou ao memorialismo esvaziado (ver os sacramentos como meros símbolos)? Como CB 1689 corrige ambos?',
      aplicacao: 'Leia CB 1689 Cap. XXVII completo. Escreva 3 pontos que mais desafiaram sua compreensão dos sacramentos.',
      notas: [
        'FESKO, J.V. <em>Word, Water, and Spirit</em>. Grand Rapids: Reformation Heritage, 2010. A teologia do batismo mais completa da tradição reformada-batista.',
      ],
      notaInicio: 238,
    },
    {
      dia: 258, data: '15 de setembro', tema: 'Sacramentos do AT e do NT: Continuidade e Mudança',
      capitulo: 'CB 1689 Cap. XXVII.6', versiculo: 'Colossenses 2.11-12',
      versiculoTexto: 'Nele também fostes circuncidados com circuncisão não feita por mão de homem... sendo sepultados com ele no batismo.',
      confissaoTexto: 'Os sacramentos do AT, na substância das coisas significadas e exibidas por eles, eram os mesmos que os do NT.',
      cfwRef: 'CFW XXVII.5', cfwComparacao: 'CFW e CB 1689 concordam sobre a continuidade substancial entre AT e NT nos sacramentos; a diferença está na relação batismo/circuncisão — determinante para o debate pedobatismo vs. credobatismo.',
      exposicao: 'Cl 2.11-12 revela que batismo e circuncisão apontam para a mesma realidade espiritual: morte ao velho homem e nova vida em Cristo. O AT tinha sacramentos (circuncisão, Páscoa) que eram sinais e selos da mesma aliança da graça — só que em forma mais velada, esperando o cumprimento em Cristo. O NT tem sacramentos mais claros (batismo, ceia) que celebram o cumprimento já acontecido. A substância é a mesma; a forma mudou.',
      reforco: 'A continuidade entre AT e NT nos sacramentos revela a unidade do plano de redenção de Deus — a mesma aliança da graça em roupagem diferente.',
      aplicacoes: {
        digital: 'Leia Cl 2.9-15. Medite: "Como o batismo cumpre e supera a circuncisão como sinal da aliança?"',
        familia: 'Conversem sobre a Páscoa do AT e a Ceia do NT. Como uma aponta para a outra? O que mudou? O que permanece?',
        filhos: 'Ensine: "No AT, Deus usava a circuncisão e a Páscoa para lembrar seu povo. No NT, Jesus nos deu o batismo e a ceia para lembrar tudo que ele fez."',
        homens: 'O homem que entende a continuidade entre AT e NT nos sacramentos tem base sólida para explicar por que praticamos batismo de crentes.',
        mulheres: 'A mulher que conhece o AT como preparação para Cristo vê os sacramentos com profundidade histórica e gratidão por viver após o cumprimento.',
        igreja: 'A congregação que ensina a continuidade aliancista dos sacramentos forma membros com compreensão bíblica robusta.',
      },
      oracao: 'Senhor, obrigado por revelares o mesmo plano de graça do Éden ao Apocalipse. Que batismo e ceia nos conectem à continuidade de tua aliança fiel. Amém.',
      reflexao: 'Você vê os sacramentos como invenções do NT ou como cumprimento do que Deus vinha anunciando desde o AT? Como essa perspectiva enriquece seu entendimento?',
      aplicacao: 'Leia Êx 12 (Páscoa) e 1Co 11.23-26 (Ceia). Liste as continuidades e as diferenças. O que a Páscoa ensina sobre a Ceia?',
      notas: [
        'ROBERTSON, O. Palmer. <em>The Christ of the Covenants</em>. Phillipsburg: P&R, 1980. A teologia da aliança mais influente para entender a continuidade entre AT e NT.',
      ],
      notaInicio: 256,
    },
    {
      dia: 259, data: '16 de setembro', tema: 'Síntese: Sacramentos na Vida da Igreja',
      capitulo: 'CB 1689 Cap. XXVII — Revisão', versiculo: '1 Coríntios 11.26',
      versiculoTexto: 'Porque todas as vezes que comerdes este pão e beberdes o cálice, anunciais a morte do Senhor, até que ele venha.',
      confissaoTexto: 'Os sacramentos são instituídos para representar Cristo e seus benefícios, confirmar nosso interesse nele, a diferença entre os que pertencem à Igreja e os que são do mundo, e o empenho solene para com Deus em obediência.',
      cfwRef: 'CFW XXVII.1', cfwComparacao: 'A síntese de XXVII revela concordância essencial entre CFW e CB 1689 sobre a natureza e função dos sacramentos — a diferença principal é sobre sujeitos e modo do batismo.',
      exposicao: '1Co 11.26 revela que a ceia do Senhor é proclamação — "anunciais a morte do Senhor". Os sacramentos têm função kerygmática: pregam o Evangelho de forma visível e tangível. Cada celebração da ceia é sermão sem palavras; cada batismo é proclamação pública de morte e ressurreição com Cristo. A Igreja que pratica os sacramentos fielmente prega o Evangelho não apenas pela boca, mas pela água, pelo pão e pelo cálice.',
      reforco: 'Sacramentos são pregação visível do Evangelho — tão sérios e significativos quanto o sermão, e igualmente dependentes da fé do participante.',
      aplicacoes: {
        digital: 'Leia 1Co 11.17-34 completo. Medite: "Minha participação na ceia é proclamação séria ou rotina religiosa?"',
        familia: 'Conversem: "Como explicamos para visitantes não-crentes o que significa o batismo e a ceia que praticamos?"',
        filhos: 'Pergunte às crianças: "O que acontece quando alguém é batizado na nossa Igreja? O que isso significa?"',
        homens: 'O homem que participa da ceia com seriedade e alegria — proclamando a morte do Senhor com convicção — edifica a congregação.',
        mulheres: 'A mulher que prepara seu coração para a ceia e medita em Cristo durante a celebração pratica adoração sacramental genuína.',
        igreja: 'A congregação que celebra os sacramentos com frequência, seriedade e ensino adequado pratica liturgia que prega o Evangelho.',
      },
      oracao: 'Senhor, que cada vez que participamos do batismo e da ceia proclamemos tua morte com convicção, tua ressurreição com alegria e tua vinda com esperança. Que os sacramentos sejam pregação viva em nossa congregação. Amém.',
      reflexao: 'Com que frequência sua congregação celebra a ceia? Com que nível de preparo, ensino e seriedade? Como poderia ser aprimorado?',
      aplicacao: 'Proponha ao seu pastor ou liderança uma discussão sobre a frequência e o preparo para a ceia na congregação à luz de 1Co 11.',
      notas: [
        'WALLACE, Ronald. <em>Calvin\'s Doctrine of the Word and Sacrament</em>. Edinburgh: Oliver & Boyd, 1953. A teologia sacramental mais rigorosa da tradição reformada.',
      ],
      notaInicio: 274,
    },
    {
      dia: 260, data: '17 de setembro', tema: 'Batismo: Instituição e Significado',
      capitulo: 'CB 1689 Cap. XXVIII.1', versiculo: 'Mateus 28.19',
      versiculoTexto: 'Ide, portanto, fazei discípulos de todas as nações, batizando-os em nome do Pai, e do Filho, e do Espírito Santo.',
      confissaoTexto: 'O batismo é ordenança do Novo Testamento, instituída por Jesus Cristo, para ser um sinal e selo da aliança da graça, da sua inserção em Cristo, da regeneração, da remissão de pecados.',
      cfwRef: 'CFW XXVIII.1', cfwComparacao: 'CFW e CB 1689 concordam sobre a instituição, significado e propósito do batismo. A diferença fundamental está em quem deve ser batizado — sujeitos do batismo.',
      exposicao: 'Mt 28.19 institui o batismo cristão como parte do mandato missionário: fazer discípulos, batizando-os, ensinando-os. A ordem importa: primeiro discipulado (fé), depois batismo (sinal), depois ensino (formação). O batismo não produz salvação — representa e confirma o que Deus já realizou na pessoa crente. É sinal de inserção em Cristo, de regeneração e remissão. É também compromisso público — identificação com Cristo perante a congregação e o mundo.',
      reforco: 'O batismo é obediência ao mandato de Cristo, não obra meritória. Sua importância é real — mas deriva do que representa, não do que produz.',
      aplicacoes: {
        digital: 'Leia Mt 28.18-20. Medite: "O batismo faz parte do meu chamado missionário? Como discipulo e preparo candidatos ao batismo?"',
        familia: 'Conversem sobre o batismo de cada membro da família. O que o batismo significou no momento e o que significa hoje?',
        filhos: 'Explique o que acontece no batismo da perspectiva bíblica: "É quando a pessoa diz publicamente: Eu pertenço a Jesus."',
        homens: 'O homem que entende o batismo como sinal de pertencimento a Cristo assume sua identidade pública como cristão com coragem.',
        mulheres: 'A mulher que foi batizada como profissão de fé tem marco público de identidade em Cristo — não apagado pelo tempo ou pela dificuldade.',
        igreja: 'A congregação que ensina adequadamente o batismo antes de administrá-lo produz membros que entendem e valorizam o que estão fazendo.',
      },
      oracao: 'Senhor, que o batismo seja mais do que rito de entrada — que seja sinal vivo de minha identidade em Cristo. Que eu viva conforme o que meu batismo declarou. Amém.',
      reflexao: 'Você sabe quando e por que foi batizado? Como esse momento ainda informa sua identidade em Cristo hoje?',
      aplicacao: 'Relembre e medite no seu batismo. Se possível, veja fotos ou fale com quem estava presente. Ore agradecendo pela identidade pública em Cristo.',
      notas: [
        'SCHREINER, Thomas e WRIGHT, Shawn (eds.). <em>Believer\'s Baptism</em>. Nashville: B&H, 2006. A defesa mais completa do batismo de crentes — essencial para os próximos dias.',
      ],
      notaInicio: 292,
    },
    {
      dia: 261, data: '18 de setembro', tema: 'Batismo de Crentes: A Posição Batista',
      capitulo: 'CB 1689 Cap. XXVIII.2', versiculo: 'Atos 2.41',
      versiculoTexto: 'De sorte que os que receberam a sua palavra foram batizados; e naquele dia agregaram-se a eles quase três mil almas.',
      confissaoTexto: 'Os que realmente professam arrependimento e fé em Cristo são os únicos sujeitos adequados deste sacramento.',
      cfwRef: 'CFW XXVIII.4', cfwComparacao: 'CFW inclui os filhos de crentes como sujeitos legítimos do batismo (pedobatismo). CB 1689 restringe ao batismo de crentes confessantes — posição credobatista.',
      exposicao: 'At 2.41 apresenta o padrão: "os que receberam a sua palavra foram batizados." Primeiro recepção da Palavra (fé/arrependimento), depois batismo. Esse padrão se repete consistentemente no NT: Filipe e o etíope (At 8.37), Cornélio (At 10.44-48), jailer de Filipos (At 16.33-34 — após a família "crer"). CB 1689 defende que somente crentes confessantes são sujeitos bíblicos do batismo, pois o sinal deve seguir a realidade espiritual que representa.',
      reforco: 'A posição batista não é arbitrária — é exegética: o NT consistentemente apresenta fé antes de batismo, não batismo antes de fé.',
      aplicacoes: {
        digital: 'Leia At 8.26-40. Medite: "Por que Filipe esperou que o etíope crente antes de batizá-lo? O que isso ensina sobre a ordem?"',
        familia: 'Conversem: "Por que não batizamos bebês em nossa tradição? Como formamos nossas crianças para que um dia professem fé?"',
        filhos: 'Ensine: "Quando você entender e acreditar em Jesus com seu próprio coração, pode ser batizado. Estamos orando por esse dia."',
        homens: 'O homem que entende e defende o credobatismo com graça e clareza contribui para a saúde doutrinária da congregação.',
        mulheres: 'A mãe que ora pelos filhos para que professem fé genuína — não apenas religio familiar — age com sabedoria espiritual.',
        igreja: 'A congregação que tem processo de catequese e entrevista pastoral antes do batismo protege a integridade do sacramento.',
      },
      oracao: 'Senhor, que nossos filhos e netos conheçam e professem fé genuína em Cristo — não apenas herança religiosa familiar. E que quando esse dia chegar, o batismo seja sinal verdadeiro de graça real. Amém.',
      reflexao: 'Sua congregação tem processo adequado para examinar a fé dos candidatos ao batismo? Como isso é feito com cuidado pastoral?',
      aplicacao: 'Converse com seu pastor sobre o processo de preparação e entrevista para o batismo na sua congregação. Entenda e apoie esse processo.',
      notas: [
        'WELLUM, Stephen e PARKER, Brent (eds.). <em>Progressive Covenantalism</em>. Nashville: B&H, 2016. A teologia aliancista que fundamenta o credobatismo confessional.',
      ],
      notaInicio: 310,
    },
    {
      dia: 262, data: '19 de setembro', tema: 'O Modo do Batismo: Imersão',
      capitulo: 'CB 1689 Cap. XXVIII.3', versiculo: 'Romanos 6.4',
      versiculoTexto: 'Fomos, pois, sepultados com ele pelo batismo na morte, para que, como Cristo ressuscitou dos mortos pela glória do Pai, assim também andemos nós em novidade de vida.',
      confissaoTexto: 'A imersão, ou mergulho da pessoa na água, é necessária para a administração correta deste ordinança.',
      cfwRef: 'CFW XXVIII.3', cfwComparacao: 'CFW aceita qualquer modo (aspersão, derramamento, imersão); CB 1689 especifica imersão como o modo correto — posição distintivamente batista.',
      exposicao: 'Rm 6.4 usa a metáfora de sepultamento e ressurreição: "sepultados com ele pelo batismo na morte... ressuscitou." A imersão total dramatiza visivelmente essa realidade: descida sob a água (sepultamento com Cristo), saída da água (ressurreição com Cristo). O próprio termo grego baptizō significa "imergir/mergulhar." CB 1689 afirma imersão não como mero preferência estética, mas como o modo que mais fielmente representa o simbolismo bíblico de morte e nova vida.',
      reforco: 'O modo do batismo não é questão de preferência cultural — é questão de fidelidade ao simbolismo bíblico de sepultamento e ressurreição.',
      aplicacoes: {
        digital: 'Leia Rm 6.1-11. Medite: "Como a imersão representa visualmente o que Rm 6 ensina sobre morte e ressurreição com Cristo?"',
        familia: 'Conversem: "Por que praticamos imersão? Não é apenas tradição — é o modo que melhor representa o que o batismo significa."',
        filhos: 'Explique de forma visual: "Quando alguém é batizado, vai debaixo da água como se estivesse morrendo com Jesus, e sai como quem ressuscitou com ele."',
        homens: 'O homem que entende o simbolismo da imersão explica com convicção e graça por que a posição batista sobre o modo não é arbitrária.',
        mulheres: 'A mulher que testemunhou ou participou de um batismo por imersão tem experiência do simbolismo vivo de Rm 6 — memória espiritual poderosa.',
        igreja: 'A congregação que pratica e ensina a imersão como sepultamento e ressurreição com Cristo celebra liturgia dramaticamente bíblica.',
      },
      oracao: 'Senhor, que o modo do meu batismo — imersão — fale de minha morte ao pecado e nova vida em ti. Que essa realidade seja diária — não apenas momento histórico. Amém.',
      reflexao: 'Você já assistiu ou participou de um batismo por imersão com o simbolismo de Rm 6 em mente? Como esse quadro visual afeta sua compreensão?',
      aplicacao: 'Na próxima celebração de batismo na sua congregação, medite em Rm 6.4 durante a cerimônia. Ore pelo batizando.',
      notas: [
        'CARSON, D.A. e WOODBRIDGE, John (eds.). <em>Scripture and Truth</em>. Grand Rapids: Zondervan, 1983. Para o princípio de seguir a Escritura mesmo em questões de forma e modo.',
      ],
      notaInicio: 328,
    },
    {
      dia: 263, data: '20 de setembro', tema: 'Batismo e Salvação: Distinção Crítica',
      capitulo: 'CB 1689 Cap. XXVIII.4', versiculo: '1 Pedro 3.21',
      versiculoTexto: 'O que também vos salva agora pelo antítipo — o batismo, não a limpeza da impureza da carne, mas a indagação de uma boa consciência para com Deus — pela ressurreição de Jesus Cristo.',
      confissaoTexto: 'A graça batismal não está atada ao momento do batismo; contudo pela administração correta desta ordinança, a graça e a salvação são prometidas e apresentadas àqueles que pertencem ao eleito.',
      cfwRef: 'CFW XXVIII.6', cfwComparacao: 'CFW e CB 1689 concordam: o batismo não produz regeneração automaticamente (contra batismo regenerador). A graça é de Deus, não do rito.',
      exposicao: '1Pe 3.21 é o texto mais delicado sobre batismo e salvação. Pedro afirma que o batismo "salva" — mas imediatamente esclarece: "não a limpeza da impureza da carne, mas a indagação de uma boa consciência para com Deus." O batismo salva não pelo ritual de lavar o corpo, mas como resposta de fé à graça de Deus. CB 1689 rejeita tanto o batismo regenerador (o rito produz graça automaticamente) quanto o memorialismo esvaziado (o rito não tem valor real). O batismo é sinal real de graça real — mas a graça antecede ou acompanha, nunca é causada pelo rito.',
      reforco: 'O batismo não regenera — mas representa e sela a regeneração que Deus opera pela fé. Confundir sinal com realidade é erro fatal.',
      aplicacoes: {
        digital: 'Leia 1Pe 3.18-22. Medite: "Em que sentido o batismo salva, segundo Pedro? Como isso é diferente do batismo regenerador?"',
        familia: 'Conversem: "Um bebê batizado na infância está salvo? Por quê? Como diferenciamos sinal de realidade?"',
        filhos: 'Ensine: "O batismo não faz ninguém cristão automaticamente. Jesus transforma o coração — o batismo mostra que isso aconteceu."',
        homens: 'O homem que entende essa distinção não confia em seu batismo para a salvação — confia em Cristo, de quem o batismo é sinal.',
        mulheres: 'A mulher que foi batizada como confissão de fé tem sinal externo de realidade interna — não um talismã religioso, mas um marco de identidade.',
        igreja: 'A congregação que ensina essa distinção protege seus membros do perigoso engano de confiar em ritual religioso em vez de Cristo.',
      },
      oracao: 'Senhor, que eu confie em Cristo — não no meu batismo. Que o sinal aponte sempre para a realidade: tua graça, tua obra, tua fidelidade na minha vida. Amém.',
      reflexao: 'Você confia em Cristo ou em seu batismo para a salvação? A distinção é mais importante do que parece.',
      aplicacao: 'Explique para alguém a diferença entre o batismo como sinal de salvação e o batismo como causa de salvação — usando 1Pe 3.21.',
      notas: [
        'WARE, Bruce. "Believer\'s Baptism View." Em WARE e MAHONEY (eds.). <em>Believer\'s Baptism</em>. Nashville: B&H, 2006. A posição mais clara sobre o tema.',
      ],
      notaInicio: 346,
    },
    {
      dia: 264, data: '21 de setembro', tema: 'Batismo: Entrada na Igreja Local',
      capitulo: 'CB 1689 Cap. XXVIII.5', versiculo: 'Atos 2.41-42',
      versiculoTexto: 'De sorte que os que receberam a sua palavra foram batizados; e naquele dia agregaram-se a eles quase três mil almas. E perseveravam na doutrina dos apóstolos...',
      confissaoTexto: 'Este sacramento é solenemente administrado pela Igreja visível, sendo o rito de entrada ou incorporação à mesma.',
      cfwRef: 'CFW XXVIII.1', cfwComparacao: 'CFW e CB 1689 concordam: batismo é entrada na Igreja visível. CB 1689 ênfase: entrada na congregação local específica.',
      exposicao: 'At 2.41-42 apresenta a sequência: recepção da Palavra → batismo → agregação à comunidade → perseverança nos quatro elementos. O batismo não é evento isolado — é incorporação. Não existe na tradição neotestamentária o "cristão não-batizado" ou o "batizado sem congregação." Batismo é entrada pública na Igreja visível local. Hoje, quando o batismo se desconecta da membresia congregacional, perde sua dimensão eclesiológica essencial.',
      reforco: 'Batismo sem incorporação à Igreja local é sinal sem a realidade que representa. Não existe cristão bíblico sem congregação.',
      aplicacoes: {
        digital: 'Leia At 2.41-47. Medite: "O meu batismo me incorporou a uma congregação local específica? Sou membro comprometido?"',
        familia: 'Conversem: "Somos membros comprometidos da nossa congregação — presença, contribuição, participação — ou apenas frequentadores ocasionais?"',
        filhos: 'Ensine: "Quando você for batizado, vai pertencer oficialmente à nossa família de Igreja — com responsabilidades e bênçãos."',
        homens: 'O homem que entende o batismo como incorporação à Igreja local assume membresia ativa — não apenas assiste cultos.',
        mulheres: 'A mulher que foi batizada como entrada na Igreja local tem responsabilidade de contribuir para a vida congregacional, não apenas consumir ministério.',
        igreja: 'A congregação que exige batismo para membresia e ensina essa conexão forma membros com visão eclesiológica correta.',
      },
      oracao: 'Senhor, que meu batismo não seja evento histórico isolado — que continue sendo sinal vivo de meu pertencimento e comprometimento com minha congregação. Amém.',
      reflexao: 'Você é membro ativo da sua congregação — com presença, contribuição e responsabilidade — ou apenas frequentador? Como seu batismo convoca à membresia comprometida?',
      aplicacao: 'Se você é membro de congregação, reafirme esse compromisso concretamente esta semana — com presença, serviço ou generosidade.',
      notas: [
        'DEVER, Mark e ALEXANDER, Paul. <em>The Deliberate Church</em>. Wheaton: Crossway, 2005. Sobre o papel do batismo na construção de congregações saudáveis.',
      ],
      notaInicio: 364,
    },
    {
      dia: 265, data: '22 de setembro', tema: 'Síntese do Batismo: Sinal Completo',
      capitulo: 'CB 1689 Cap. XXVIII — Revisão', versiculo: 'Gálatas 3.27',
      versiculoTexto: 'Porque todos os que fostes batizados em Cristo de Cristo vos revestistes.',
      confissaoTexto: 'O batismo representa nossa inserção em Cristo, nossa regeneração, remissão de pecados, entrega a Deus por Jesus Cristo, entrada na Igreja visível e o compromisso de andar em novidade de vida.',
      cfwRef: 'CFW XXVIII — síntese', cfwComparacao: 'CB 1689 e CFW concordam na riqueza do significado do batismo; divergem apenas em sujeitos e, secundariamente, em modo.',
      exposicao: 'Gl 3.27 resume o batismo em imagem poderosa: "revestir-se de Cristo." O batismo é vestimenta de identidade — o crente se reveste publicamente de Cristo diante da Igreja e do mundo. Toda a semana sobre batismo converge aqui: instituição divina (dia 260), sujeitos corretos (261), modo adequado (262), relação com salvação (263), entrada na Igreja (264). Tudo aponta para Cristo — revestido publicamente, professado abertamente, vivido cotidianamente.',
      reforco: 'O batismo não é formalidade religiosa — é declaração pública de identidade: "Eu pertenço a Cristo e a seu Corpo."',
      aplicacoes: {
        digital: 'Leia Gl 3.26-29. Medite: "Estar 'revestido de Cristo' — como isso se manifesta na sua vida cotidiana?"',
        familia: 'Conversem: "O que significa nossa família estar 'revestida de Cristo'? Como vivemos essa identidade juntos?"',
        filhos: 'Pergunte: "Se você usasse Cristo como roupa, como seria sua atitude na escola, com amigos, em casa?"',
        homens: 'O homem revestido de Cristo age com caráter de Cristo em todos os contextos — trabalho, família, congregação, mercado.',
        mulheres: 'A mulher revestida de Cristo irradia sua identidade com graça — não por performance religiosa, mas por transformação genuína.',
        igreja: 'A congregação que celebra batismos regularmente renova publicamente sua identidade em Cristo — testemunho vivo para a comunidade.',
      },
      oracao: 'Senhor Jesus, que eu viva revestido de ti — não de religiosidade, não de moralismo, mas de ti. Que meu batismo seja diário — morrendo ao pecado e vivendo em novidade de vida. Amém.',
      reflexao: 'Como você "veste" sua identidade em Cristo cotidianamente? O batismo que você teve está sendo vivido — ou ficou apenas na memória?',
      aplicacao: 'Escreva uma declaração de identidade em Cristo baseada em Gl 3.27. Leia diariamente por uma semana como afirmação do seu batismo.',
      notas: [
        'RIDDERBOS, Herman. <em>Paul: An Outline of His Theology</em>. Grand Rapids: Eerdmans, 1975. A teologia paulina do batismo e da identidade em Cristo.',
      ],
      notaInicio: 382,
    },
    {
      dia: 266, data: '23 de setembro', tema: 'A Ceia do Senhor: Instituição e Propósito',
      capitulo: 'CB 1689 Cap. XXIX.1', versiculo: 'Lucas 22.19-20',
      versiculoTexto: 'E, tomando o pão e dando graças, o partiu e lhes deu, dizendo: Isto é o meu corpo dado por vós; fazei isto em memória de mim. De igual modo, depois de cear, tomou o cálice, dizendo: Este cálice é a nova aliança no meu sangue, que é derramado por vós.',
      confissaoTexto: 'A ceia do Senhor foi instituída por Jesus Cristo na noite em que foi traído, para ser observada em sua Igreja até ao fim do mundo, para o contínuo memorial de seu sacrifício na morte.',
      cfwRef: 'CFW XXIX.1', cfwComparacao: 'CFW e CB 1689 concordam sobre a instituição, propósito e continuidade da ceia até o retorno de Cristo.',
      exposicao: 'Lc 22.19-20 revela as dimensões da Ceia: memorial ("em memória de mim"), aliança ("nova aliança no meu sangue") e esperança escatológica (1Co 11.26: "até que ele venha"). A ceia é refeição do povo da aliança — não ritual sacerdotal, não sacrifício repetido, não presença física de Cristo no pão. É memorial real de sacrifício real, celebrado por comunidade real, esperando retorno real. Três tempos em uma refeição: passado (morte de Cristo), presente (comunhão), futuro (retorno).',
      reforco: 'A Ceia é memorial, não sacrifício; é comunhão, não ritual automático; é proclamação, não magia religiosa.',
      aplicacoes: {
        digital: 'Leia Lc 22.14-23. Medite nos três tempos da ceia: memória do passado, comunhão no presente, esperança do futuro.',
        familia: 'Conversem: "O que lembramos na ceia? O que celebramos? O que esperamos?" Conecte os três tempos.',
        filhos: 'Explique: "A ceia nos faz lembrar que Jesus morreu por nós, nos une como família de Deus e nos diz que ele vai voltar."',
        homens: 'O homem que participa da ceia com as três dimensões em mente — passado, presente, futuro — experimenta adoração completa.',
        mulheres: 'A mulher que medita no memorial da morte de Cristo durante a ceia participa com gratidão profunda e esperança genuína.',
        igreja: 'A congregação que ensina as três dimensões da ceia antes de celebrá-la forma participantes conscientes e adoradores genuínos.',
      },
      oracao: 'Senhor Jesus, que a ceia seja para nós memorial vivo de tua morte, celebração real de nossa comunhão e esperança ardente de tua vinda. Que partamos o pão com fé, gratidão e expectativa. Amém.',
      reflexao: 'Quando você participa da ceia, qual dimensão está mais presente em sua meditação — o memorial do passado, a comunhão do presente ou a esperança do futuro?',
      aplicacao: 'Na próxima ceia, dedique um terço do tempo para cada dimensão: agradeça pela morte de Cristo, ore pela congregação e anseie pela vinda do Senhor.',
      notas: [
        'JEREMIAS, Joachim. <em>The Eucharistic Words of Jesus</em>. London: SCM, 1966. O estudo histórico mais completo sobre a instituição da ceia.',
      ],
      notaInicio: 400,
    },
    {
      dia: 267, data: '24 de setembro', tema: 'A Ceia e a Missa: Diferença Essencial',
      capitulo: 'CB 1689 Cap. XXIX.2', versiculo: 'Hebreus 9.25-26',
      versiculoTexto: 'Nem ainda para se oferecer muitas vezes, como o sumo sacerdote entra no lugar santíssimo cada ano com sangue alheio... pois assim lhe cumpriria padecer muitas vezes desde a fundação do mundo. Mas agora, na consumação dos séculos, uma vez se manifestou para aniquilar o pecado pelo seu sacrifício.',
      confissaoTexto: 'A Ceia não é sacrifício para remissão de pecados, nem qualquer sacrifício; pois Cristo foi oferecido uma única vez para sempre — a Ceia é memorial daquele único sacrifício.',
      cfwRef: 'CFW XXIX.2', cfwComparacao: 'CFW e CB 1689 concordam completamente na rejeição da missa romana como sacrifício repetido. Hb 9.25-28 é o texto central de ambos.',
      exposicao: 'Hb 9.25-26 é a refutação definitiva da missa romana: Cristo não pode ser "oferecido muitas vezes" — foi oferecido "uma vez para sempre" (Hb 9.12, 26, 28; 10.10, 12, 14). A missa romana que afirma repetir o sacrifício de Cristo contradiz diretamente Hebreus. A ceia evangelical é memorial — não sacrifício repetido. O sacerdócio de Cristo é definitivo e suficiente; nenhum sacerdote humano pode ou precisa repetir o que ele fez uma vez para sempre no Calvário.',
      reforco: 'O sacrifício de Cristo foi suficiente, definitivo e irrepetível. A ceia celebra esse fato — não o repete.',
      aplicacoes: {
        digital: 'Leia Hb 9.23-28. Medite: "O que 'uma vez para sempre' significa para sua confiança na suficiência da obra de Cristo?"',
        familia: 'Conversem: "Por que não precisamos de missa — de repetir o sacrifício de Cristo? O que Hebreus ensina sobre a suficiência de sua morte?"',
        filhos: 'Ensine: "Jesus morreu uma vez e foi suficiente para sempre. A ceia nos faz lembrar — não repetir."',
        homens: 'O homem reformado que compreende Hb 9 defende a suficiência do sacrifício de Cristo com convicção evangelística e ecuménica.',
        mulheres: 'A mulher que entende o "uma vez para sempre" de Cristo vive com segurança — não com ansiedade religiosa sobre a suficiência de sua salvação.',
        igreja: 'A congregação que ensina Hb 9-10 forma membros que entendem por que a Reforma protestou e por que a distinção ainda importa.',
      },
      oracao: 'Senhor Jesus, obrigado por teu sacrifício perfeito, definitivo e suficiente. Que eu nunca busque suplemento — em religiosidade, em obras, em rituais. Tu foste oferecido "uma vez para sempre" — e isso é mais do que suficiente. Amém.',
      reflexao: 'Você vive como se o sacrifício de Cristo fosse suficiente — com segurança e descanso — ou continua buscando suplementar sua salvação com obras religiosas?',
      aplicacao: 'Leia Hb 10.11-14 em voz alta. Medite especialmente no v.14: "Porque com uma só oferta ele aperfeiçoou para sempre os que são santificados." Ore com gratidão.',
      notas: [
        'OWEN, John. <em>The Death of Death in the Death of Christ</em>. Edinburgh: Banner of Truth, 1959. O tratado mais completo sobre a suficiência do sacrifício de Cristo.',
      ],
      notaInicio: 418,
    },
    {
      dia: 268, data: '25 de setembro', tema: 'Presença de Cristo na Ceia: Espiritual e Real',
      capitulo: 'CB 1689 Cap. XXIX.3–4', versiculo: 'João 6.63',
      versiculoTexto: 'O espírito é o que vivifica; a carne para nada aproveita; as palavras que eu vos disse são espírito e são vida.',
      confissaoTexto: 'O corpo e o sangue de Cristo não estão no pão e no vinho de modo corporal e carnal. Mas espiritualmente, Cristo está presente à fé dos crentes nessa ordenança, tão verdadeira e real como os elementos mesmos estão presentes aos seus sentidos corporais.',
      cfwRef: 'CFW XXIX.7', cfwComparacao: 'CFW e CB 1689 rejeitam tanto a transubstanciação romana quanto a consubstanciação luterana. Ambos afirmam presença espiritual real.',
      exposicao: 'Jo 6.63 é chave hermenêutica para a ceia: a presença de Cristo é espiritual, não física. A transubstanciação (pão vira corpo fisicamente — Roma) e a consubstanciação (Cristo está fisicamente "junto com" o pão — Lutero) contradizem João 6 e a natureza humana glorificada de Cristo (que está à direita do Pai, não fisicamente em mil altares simultaneamente). CB 1689 afirma presença espiritual real — Cristo presente pela fé e pelo Espírito, não pelo rito. Não menos real — mas de natureza diferente.',
      reforco: 'Presença espiritual não é presença diminuída — é presença do modo como Cristo, glorificado, se faz presente: pelo Espírito e pela fé.',
      aplicacoes: {
        digital: 'Leia Jo 6.52-63. Medite: "Como Cristo se faz presente na ceia de forma real mas espiritual?"',
        familia: 'Conversem: "O pão e o cálice viram literalmente o corpo e sangue de Cristo? O que a Bíblia ensina sobre como Cristo está presente?"',
        filhos: 'Explique: "Jesus não está fisicamente no pão — ele está no céu à direita do Pai. Mas quando participamos da ceia, nos aproximamos dele pela fé."',
        homens: 'O homem que compreende a presença espiritual de Cristo na ceia participa com fé ativa — não com superstição nem com indiferença.',
        mulheres: 'A mulher que se aproxima da ceia com fé genuína experimenta a presença real de Cristo — não pelo rito, mas pelo Espírito.',
        igreja: 'A congregação que ensina a presença espiritual real de Cristo forma participantes que não são supersticiosos nem indiferentes.',
      },
      oracao: 'Senhor Jesus, que pela fé e pelo Espírito eu me aproxime de ti na ceia com coração aberto. Que tua presença espiritual seja tão real quanto o pão em minha mão e o cálice em meus lábios. Amém.',
      reflexao: 'Você experimenta a presença real de Cristo na ceia? O que impede ou facilita essa experiência espiritual genuína?',
      aplicacao: 'Antes da próxima ceia, leia Jo 6.51-58 e ore pedindo fé para experimentar a presença espiritual de Cristo durante a celebração.',
      notas: [
        'LETHAM, Robert. <em>The Lord\'s Supper</em>. Phillipsburg: P&R, 2001. O tratamento mais equilibrado da presença de Cristo na ceia entre os reformados.',
      ],
      notaInicio: 436,
    },
    {
      dia: 269, data: '26 de setembro', tema: 'Ceia: Auto-Exame e Participação Digna',
      capitulo: 'CB 1689 Cap. XXIX.5', versiculo: '1 Coríntios 11.28',
      versiculoTexto: 'Examine-se, pois, o homem a si mesmo, e assim coma do pão e beba do cálice.',
      confissaoTexto: 'Todos os ignorantes e ímpios, sendo incapazes de se comunicar com Cristo, são indignos da mesa do Senhor e não podem participar desses santos mistérios sem grandes pecados contra ele.',
      cfwRef: 'CFW XXIX.8', cfwComparacao: 'CFW e CB 1689 concordam: participação indígna traz juízo (1Co 11.29). O auto-exame é obrigatório — não opcional.',
      exposicao: '1Co 11.28 ordena auto-exame antes da ceia — não para impedir a participação, mas para torná-la genuína. 1Co 11.29 é solene: "quem come e bebe indignamente, come e bebe juízo para si." Participação indigna não é ausência de perfeição (ninguém é perfeito) — é participar sem fé, sem discernimento do corpo de Cristo, sem exame honesto. O auto-exame saudável envolve: confessar pecados conhecidos, reconciliar-se com irmãos em conflito, examinar a fé, vir com gratidão e esperança.',
      reforco: 'Auto-exame antes da ceia não é tortura espiritual — é preparação amorosa para encontrar Cristo com coração honesto e fé genuína.',
      aplicacoes: {
        digital: 'Leia 1Co 11.23-34. Medite: "Meu processo de auto-exame antes da ceia é genuíno ou pro forma?"',
        familia: 'Conversem: "Como nossa família se prepara para a ceia do Senhor? Há um momento de auto-exame e confissão juntos?"',
        filhos: 'Explique por que as crianças ainda não batizadas não participam da ceia — é proteção, não exclusão.',
        homens: 'O homem que pratica auto-exame genuíno antes da ceia lidera a família nessa disciplina espiritual valiosa.',
        mulheres: 'A mulher que se examina honestamente antes da ceia — confessando pecados, reconciliando relacionamentos — participa com coração limpo.',
        igreja: 'A congregação que inclui momento de confissão e auto-exame no serviço da ceia forma participantes preparados e conscientes.',
      },
      oracao: 'Senhor, que eu me examine honestamente antes de cada ceia — não para me excluir por indignidade pessoal (ninguém é digno por si mesmo), mas para vir com fé genuína, coração confessado e gratidão real. Amém.',
      reflexao: 'Que pecados não confessados ou relacionamentos não reconciliados você precisa tratar antes de participar da próxima ceia?',
      aplicacao: 'Escreva uma oração de auto-exame para usar antes de cada ceia. Inclua: confissão, gratidão, petição pela congregação e esperança escatológica.',
      notas: [
        'THOMAS, Derek. <em>How the Gospel Brings Us All the Way Home</em>. Wheaton: Crossway, 2011. Cap. sobre a ceia — o auto-exame como disciplina de graça.',
      ],
      notaInicio: 454,
    },
    {
      dia: 270, data: '27 de setembro', tema: 'Ceia Fechada vs. Aberta: Quem Pode Participar',
      capitulo: 'CB 1689 Cap. XXIX.6', versiculo: '1 Coríntios 5.11',
      versiculoTexto: 'Mas agora vos escrevi que não vos associeis com alguém que, chamando-se irmão, for devasso, ou avarento, ou idólatra, ou maldizente, ou beberrão, ou roubador; com esse nem sequer comais.',
      confissaoTexto: 'A participação na ceia do Senhor requer batismo e a admissão da Igreja; os que negam as doutrinas essenciais ou vivem em pecado público não devem ser admitidos.',
      cfwRef: 'CFW XXIX.8', cfwComparacao: 'CFW e CB 1689 concordam sobre a necessidade de ceia fechada baseada em batismo e membresia; a prática varia entre congregações.',
      exposicao: '1Co 5.11 revela que "partir o pão" com alguém é ato de comunhão que implica afirmação mútua. A ceia fechada (ou delimitada) não é exclusivismo arrogante — é honestidade eclesial. Participar da ceia implica: ser crente batizado, ser membro em boa situação de uma congregação cristã, não estar sob disciplina eclesiástica, não viver em pecado público não arrependido. Isso protege a integridade do sinal e a saúde da congregação.',
      reforco: 'A ceia fechada protege tanto a integridade do sacramento quanto aqueles que participariam sem fé genuína — é ato pastoral, não elitismo.',
      aplicacoes: {
        digital: 'Leia 1Co 5.9-13. Medite: "A ceia é ato de comunhão com implicações de responsabilidade mútua — como isso muda minha perspectiva?"',
        familia: 'Conversem sobre a política de ceia da congregação. Por que crianças não batizadas não participam? Por que visitantes às vezes são convidados mas não admitidos?',
        filhos: 'Explique: "A ceia é para quem já acreditou em Jesus e foi batizado. Quando você fizer isso, poderá participar conosco."',
        homens: 'O homem que entende a ceia fechada defende essa prática com clareza pastoral — não com arrogância, mas com amor à integridade do sacramento.',
        mulheres: 'A mulher que entende por que a ceia é delimitada apoia essa prática em vez de se envergonhar dela diante de visitantes.',
        igreja: 'A congregação que pratica e ensina a ceia fechada com explicação pastoral honra o sacramento e protege os participantes.',
      },
      oracao: 'Senhor, que nossa congregação pratique a ceia com integridade — aberta ao genuíno crente batizado, fechada ao que ainda não fez essa profissão. Que essa fronteira seja pastoral e amorosa. Amém.',
      reflexao: 'Você entende e apoia a política de ceia da sua congregação? Como explicaria essa posição com clareza e graça para um visitante?',
      aplicacao: 'Converse com seu pastor sobre a política de ceia da congregação. Entenda os critérios e o fundamento bíblico para poder explicar com clareza.',
      notas: [
        'LEEMAN, Jonathan. <em>The Lord\'s Supper as the Sign and Seal of the New Covenant</em>. Nashville: SBTS Press, 2011. A defesa mais articulada da ceia delimitada.',
      ],
      notaInicio: 472,
    },
    {
      dia: 271, data: '28 de setembro', tema: 'A Ceia e a Esperança Escatológica',
      capitulo: 'CB 1689 Cap. XXIX.7', versiculo: '1 Coríntios 11.26',
      versiculoTexto: 'Porque todas as vezes que comerdes este pão e beberdes o cálice, anunciais a morte do Senhor, até que ele venha.',
      confissaoTexto: 'A Ceia do Senhor foi instituída para ser continuamente observada em sua Igreja até ao fim do mundo, para o contínuo memorial de seu sacrifício na morte, a confirmação da fé dos crentes, e para selar a aliança da graça.',
      cfwRef: 'CFW XXIX.1', cfwComparacao: 'CFW e CB 1689 concordam: a ceia é escatológica — "até que ele venha." A esperança do retorno de Cristo é inseparável de cada celebração.',
      exposicao: '"Até que ele venha" — três palavras que transformam cada celebração da ceia em antecipação escatológica. A ceia olha para trás (morte de Cristo), olha para cima (presença espiritual de Cristo) e olha para frente (retorno de Cristo). A refeição da aliança da nova criação — o banquete do Cordeiro (Ap 19.9) — é o que a ceia antecipa. Cada pão partido e cada cálice bebido são ensaio da refeição final, quando "beberemos do fruto da videira novo no reino de Deus" (Mc 14.25).',
      reforco: 'A ceia é refeição do povo que espera — não de nostálgicos do passado, mas de peregrinos orientados para o futuro glorioso em Cristo.',
      aplicacoes: {
        digital: 'Leia Ap 19.6-9 depois de 1Co 11.26. Medite: como a ceia antecipa o Banquete do Cordeiro?',
        familia: 'Conversem: "Quando Jesus voltar, haverá uma grande festa. A ceia é o ensaio. Como isso muda nossa perspectiva sobre a celebração?"',
        filhos: 'Ensine: "Cada vez que fazemos a ceia, é como dizer: Jesus vai voltar! Estamos esperando por ele!"',
        homens: 'O homem que participa da ceia com esperança escatológica viva não é cristão nostálgico — é peregrino aguardando o retorno do Rei.',
        mulheres: 'A mulher que celebra a ceia com esperança da segunda vinda vive com alegria que o mundo não pode dar nem tirar.',
        igreja: 'A congregação que celebra a ceia com as três dimensões — passado, presente, futuro — pratica liturgia escatologicamente completa.',
      },
      oracao: 'Vem, Senhor Jesus! Que cada ceia que celebramos seja antecipação ardente do banquete eterno. Que a esperança de tua vinda transforme nossa adoração presente em alegria escatológica. Amém.',
      reflexao: 'Quando você participa da ceia, você experimenta o "até que ele venha"? A esperança do retorno de Cristo está viva em sua adoração?',
      aplicacao: 'Leia Ap 19.6-9 antes da próxima ceia. Deixe a visão do banquete final inflamar sua esperança durante a celebração.',
      notas: [
        'LADD, George Eldon. <em>A Theology of the New Testament</em>. Grand Rapids: Eerdmans, 1974. A escatologia que fundamenta a dimensão futura dos sacramentos.',
      ],
      notaInicio: 490,
    },
    {
      dia: 272, data: '29 de setembro', tema: 'Síntese da Ceia: Refeição da Aliança',
      capitulo: 'CB 1689 Cap. XXIX — Revisão', versiculo: 'Lucas 22.20',
      versiculoTexto: 'De igual modo, depois de cear, tomou o cálice, dizendo: Este cálice é a nova aliança no meu sangue, que é derramado por vós.',
      confissaoTexto: 'O Senhor Jesus institui a ceia como memorial perpétuo de seu sacrifício, selando a nova aliança em seu sangue, para confirmação da fé dos crentes e sua nutrição espiritual.',
      cfwRef: 'CFW XXIX — síntese', cfwComparacao: 'CB 1689 e CFW concordam em toda a estrutura teológica da ceia; a divergência principal é sobre quem admitir (membresia batista vs. presbiteriana).',
      exposicao: 'Lc 22.20 identifica a ceia como "nova aliança no meu sangue." A ceia é refeição de aliança — como a Páscoa era refeição de aliança no AT. Em cada celebração, a congregação renova sua identidade como povo da nova aliança, nutrido pelo sangue de Cristo, comprometido com os termos da aliança (obediência), esperando o cumprimento final (retorno). A ceia não apenas lembra a aliança — a sela e a confirma na experiência do povo crente.',
      reforco: 'Cada ceia é renovação de aliança — o povo de Deus reafirma sua identidade, seu Senhor e sua esperança.',
      aplicacoes: {
        digital: 'Leia Jr 31.31-34 e Lc 22.14-20. Medite: como a ceia cumpre a promessa da nova aliança em Jeremias?',
        familia: 'Conversem: "Somos povo da nova aliança. Como vivemos isso no cotidiano familiar — não apenas quando participamos da ceia?"',
        filhos: 'Ensine: "A ceia é como assinar um contrato de amor com Jesus — mas um contrato de graça, onde ele faz tudo e nós recebemos."',
        homens: 'O homem que entende a ceia como refeição de aliança assume os compromissos da aliança com seriedade — obediência, amor, comunhão.',
        mulheres: 'A mulher que participa da ceia como renovação de aliança vive a semana seguinte com identidade reafirmada em Cristo.',
        igreja: 'A congregação que celebra a ceia com a linguagem da aliança — nova aliança, povo de Deus, nutrição espiritual — pratica liturgia teologicamente rica.',
      },
      oracao: 'Senhor, somos teu povo da nova aliança — comprado pelo teu sangue. Que a ceia nos una, nos nutra e nos comissione para viver a aliança cotidianamente. Amém.',
      reflexao: 'A ceia como refeição de aliança implica compromissos. Que compromissos da nova aliança você está renovando cada vez que participa?',
      aplicacao: 'Escreva 3 compromissos de aliança que você está assumindo para a semana — baseados em Hb 8.10-12 (a nova aliança em Jeremias). Releia antes da próxima ceia.',
      notas: [
        'DUMBRELL, William. <em>Covenant and Creation</em>. Grand Rapids: Baker, 1984. A teologia da aliança que fundamenta toda a eclesiologia e sacramentologia de setembro.',
      ],
      notaInicio: 508,
    },
    {
      dia: 273, data: '30 de setembro', tema: 'Síntese de Setembro: Igreja, Comunhão e Sacramentos',
      capitulo: 'CB 1689 Cap. XXV–XXIX — Revisão Final', versiculo: 'Efésios 4.4-6',
      versiculoTexto: 'Um só corpo e um só Espírito, como também fostes chamados em uma só esperança da vossa vocação; um só Senhor, uma só fé, um só batismo, um só Deus e Pai de todos, o qual é sobre todos, e por todos e em todos.',
      confissaoTexto: 'A Igreja de Cristo, governada por sua Palavra e Espírito, reunida em congregações locais, unida em comunhão dos santos, celebrando batismo e ceia como sinais da aliança — é a expressão visível do Corpo de Cristo no mundo.',
      cfwRef: 'CFW XXV–XXIX — síntese', cfwComparacao: 'CFW e CB 1689 compartilham a mesma visão central da Igreja como Corpo de Cristo, governada por ele, nutrida pelos sacramentos e unida em comunhão — divergindo em forma de governo e sujeitos do batismo.',
      exposicao: 'Ef 4.4-6 é o símbolo de unidade da Igreja: um Corpo, um Espírito, uma esperança, um Senhor, uma fé, um batismo, um Deus. Setembro percorreu essa unidade: a Igreja (Cap. XXV), sua comunhão (Cap. XXVI), seus sacramentos como base (Cap. XXVII), seu batismo como entrada (Cap. XXVIII) e sua ceia como sustento (Cap. XXIX). Tudo converge: a Igreja é o povo da aliança, unido em Cristo, nutrido pelos sacramentos, vivendo em comunhão, esperando o retorno do Rei.',
      reforco: 'Setembro construiu uma visão completa: a Igreja não é clube religioso — é povo da aliança de Deus, corpo de Cristo, templo do Espírito.',
      aplicacoes: {
        digital: 'Leia Ef 4.1-16. Medite: como os temas de setembro se conectam à visão de Paulo sobre a Igreja como Corpo de Cristo?',
        familia: 'Façam juntos uma linha do tempo de setembro: Igreja (dias 244-250), Comunhão (dias 251-254), Sacramentos (dias 255-259), Batismo (dias 260-265), Ceia (dias 266-272). Ore pela congregação local.',
        filhos: 'Pergunte: "O que vocês aprenderam sobre a Igreja em setembro?" Liste as respostas. Reforce: "A Igreja é a família de Deus — não é edifício, não é organização. É povo."',
        homens: 'O homem que completou setembro tem visão eclesiológica completa: Igreja visível e invisível, governo congregacional, comunhão dos santos, batismo e ceia. Essa visão forma liderança madura.',
        mulheres: 'A mulher que percorreu setembro foi formada na eclesiologia que sustenta a vida cristã coletiva — fundamento para servir, pertencer e crescer na família de Deus.',
        igreja: 'A Igreja que ensina CB 1689 Cap. XXV–XXIX forma membros com visão eclesiológica completa — capazes de valorizar, defender e construir congregações saudáveis.',
      },
      oracao: 'Bendito Deus, Pai de nosso Senhor Jesus Cristo — obrigado por setembro. Por Igreja visível e invisível, por comunhão dos santos, por batismo e ceia. Que outubro nos aprofunde nos últimos temas — escatologia, ressurreição e glorificação. Amém.',
      reflexao: 'Setembro revelou que a Igreja não é acessória ao Evangelho — é expressão do Evangelho. Como sua visão de Igreja e sacramentos foi transformada este mês?',
      aplicacao: 'Escreva uma carta de meia página resumindo o que setembro ensinou sobre Igreja e sacramentos. Guarde para reler em dezembro. Ore para que a visão eclesiológica recebida transforme sua prática congregacional.',
      notas: [
        'CLOWNEY, Edmund. <em>The Church</em>. Downers Grove: IVP, 1995. O livro que melhor sintetiza a eclesiologia de setembro em forma acessível e bíblica.',
        'FESKO, J.V. <em>Word, Water, and Spirit</em>. Grand Rapids: Reformation Heritage, 2010. A sacramentologia mais completa para consolidar setembro.',
      ],
      notaInicio: 526,
    },
  ];
  return dias.map(blocoW);
}
`;

const current = fs.readFileSync(filePath, 'utf8');
fs.writeFileSync(filePath, current + setembro, 'utf8');
console.log('✅ gerarDiasSetembro() appended successfully');
console.log('Lines:', (current + setembro).split('\n').length);
