const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'src/data/devocionalConfessional.ts');

const outubro = `
function gerarDiasOutubro(): DiaConfessional[] {
  const dias: DiaCompacto[] = [
    {
      dia: 274, data: '1 de outubro', tema: 'O Culto Religioso: Regulado pela Palavra',
      capitulo: 'CFW Cap. XXI.1', versiculo: 'João 4.23-24',
      versiculoTexto: 'Mas a hora vem, e agora é, em que os verdadeiros adoradores adorarão o Pai em espírito e em verdade; porque o Pai procura a quem assim o adore. Deus é Espírito, e importa que os que o adoram o adorem em espírito e em verdade.',
      confissaoTexto: 'A luz da natureza mostra que há um Deus que tem senhorio e soberania sobre tudo; é justo adorá-lo, amá-lo, temê-lo e chamá-lo. Mas o modo aceitável de adorar ao verdadeiro Deus é por ele mesmo instituído e tão limitado por sua própria vontade revelada que não deve ser adorado segundo imaginações ou invenções de homens.',
      cfwRef: 'CFW XXI.1', cfwComparacao: 'CB 1689 Cap. XXII.1 usa linguagem quase idêntica — o princípio regulador do culto é compartilhado por ambas as confissões.',
      exposicao: 'Jo 4.23-24 define o culto verdadeiro: em espírito (motivação interior genuína) e em verdade (conformidade com o que Deus revelou). CFW XXI.1 formula o "Princípio Regulador do Culto": somente o que Deus ordenou pertence ao culto — não o que parece piedoso, belo ou tradicional. Isso contrasta com o "Princípio Normativo" luterano/anglicano (o que Deus não proibiu é permitido). Para a tradição reformada, o silêncio da Escritura é proibição no culto.',
      reforco: 'O culto que agrada a Deus não é o que nós achamos belo ou significativo — é o que Deus ordenou em sua Palavra.',
      aplicacoes: {
        digital: 'Leia Jo 4.19-24. Medite: "O culto da minha congregação é regulado pela Palavra ou pela preferência estética e cultural?"',
        familia: 'Conversem: "Por que não podemos inventar formas de adoração que Deus não ordenou — mesmo que pareçam piedosas?"',
        filhos: 'Ensine: "Adorar a Deus do jeito que ele quer é mais importante do que adorar do jeito que achamos bonito."',
        homens: 'O homem que entende o Princípio Regulador avalia o culto pela Escritura — não pela emoção, tradição ou preferência pessoal.',
        mulheres: 'A mulher que adora em espírito e verdade não precisa de espetáculo para se sentir perto de Deus — a Palavra e os sacramentos são suficientes.',
        igreja: 'A congregação que aplica o Princípio Regulador ao culto mantém a adoração centrada em Cristo e seu Evangelho — não em experiências humanas.',
      },
      oracao: 'Senhor, ensina-nos a te adorar como tu queres ser adorado — em espírito e em verdade. Que outubro nos forme no culto correto, não apenas no culto preferido. Amém.',
      reflexao: 'Sua congregação avalia as práticas de culto pela Escritura? Há elementos que entram mais por tradição, estética ou preferência do que por ordenança divina?',
      aplicacao: 'Leia CFW XXI.1 e liste os elementos que Deus ordenou para o culto público. Compare com o que sua congregação pratica. Há acréscimos não ordenados?',
      notas: [
        'FRAME, John. <em>Worship in Spirit and Truth</em>. Phillipsburg: P&R, 1996. A defesa mais equilibrada do Princípio Regulador — acessível e rigoroso.',
      ],
      notaInicio: 1,
    },
    {
      dia: 275, data: '2 de outubro', tema: 'Elementos do Culto Público Ordenados por Deus',
      capitulo: 'CFW Cap. XXI.3–5', versiculo: 'Colossenses 3.16',
      versiculoTexto: 'A palavra de Cristo habite em vós ricamente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros com salmos, hinos e cânticos espirituais, com graça, cantando em vossos corações ao Senhor.',
      confissaoTexto: 'O culto religioso ordinário inclui: leitura das Escrituras, pregação e audição da Palavra, instrução, salmos, hinos, oração com ações de graça, administração dos sacramentos e coleta para os santos.',
      cfwRef: 'CFW XXI.3–5', cfwComparacao: 'CB 1689 Cap. XXII.5 lista elementos similares — pregação, leitura, oração, canto e sacramentos como o núcleo do culto ordenado.',
      exposicao: 'Cl 3.16 ordena que a Palavra habite ricamente — e que isso se expresse em ensino, admoestação e canto. CFW XXI.3-5 lista os elementos do culto público que têm mandato bíblico: leitura e pregação da Escritura, instrução e catequese, salmos e hinos, oração e ação de graças, sacramentos e oferta. Esses são os elementos ordenados. Tudo o mais — drama litúrgico, visualizações, danças litúrgicas, meditação contemplativa — não tem mandato e portanto não pertence ao culto público.',
      reforco: 'O culto simples que obedece aos elementos ordenados é mais rico do que o culto elaborado que acrescenta o não-ordenado.',
      aplicacoes: {
        digital: 'Leia Cl 3.12-17. Medite: "Meu culto pessoal inclui os elementos que Deus ordenou — Palavra, oração, canto de graças?"',
        familia: 'Conversem sobre os elementos do culto da congregação. Cada um tem fundamento na Escritura?',
        filhos: 'Ensine os elementos do culto: "Na Igreja fazemos: lemos a Bíblia, pregamos, oramos, cantamos e partimos o pão. Cada um desses vem da Bíblia."',
        homens: 'O homem que entende os elementos do culto participa com intencionalidade — sabe por que cada parte está ali.',
        mulheres: 'A mulher que conhece o propósito de cada elemento do culto adora com mente e coração — não apenas emoção.',
        igreja: 'A congregação que explica ao rebanho o fundamento bíblico de cada elemento do culto forma adoradores maduros e comprometidos.',
      },
      oracao: 'Senhor, que nosso culto seja rico nos elementos que tu ordenaste — Palavra, oração, canto, sacramentos — e simples no que tu não ordenaste. Que a simplicidade do culto bíblico seja nossa beleza. Amém.',
      reflexao: 'Cada elemento do culto da sua congregação tem fundamento claro na Escritura? Há práticas que entraram sem mandato bíblico?',
      aplicacao: 'Liste os elementos do culto da sua congregação. Para cada um, identifique o texto bíblico que o ordena. O que não tem texto, pergunte ao seu pastor.',
      notas: [
        'TERRY, Milton. <em>Biblical Hermeneutics</em>. Grand Rapids: Zondervan, 1974. Para entender como derivar o que Deus ordenou versus o que apenas permitiu.',
      ],
      notaInicio: 18,
    },
    {
      dia: 276, data: '3 de outubro', tema: 'Oração: O Coração do Culto',
      capitulo: 'CFW Cap. XXI.3', versiculo: 'Filipenses 4.6',
      versiculoTexto: 'Não andeis ansiosos de coisa alguma; em tudo, porém, sejam conhecidas diante de Deus as vossas petições pela oração e pela súplica, com ações de graças.',
      confissaoTexto: 'A oração é uma parte especial do culto religioso natural, e para que seja aceita por Deus, deve ser feita em nome de Cristo, com a assistência do seu Espírito, de acordo com a sua vontade, com entendimento, reverência, humildade, fervor, fé, amor e perseverança.',
      cfwRef: 'CFW XXI.3', cfwComparacao: 'CB 1689 Cap. XXII.3 define a oração nos mesmos termos — em nome de Cristo, pelo Espírito, conforme a Palavra.',
      exposicao: 'Fp 4.6 enumera os componentes da oração: petição (pedidos específicos), súplica (humildade no pedir) e ação de graças (gratidão como contexto). CFW XXI.3 detalha as condições da oração aceitável: em nome de Cristo (não por mérito próprio), pelo Espírito (não por força da vontade), conforme a vontade revelada (não qualquer desejo), com entendimento (não repetição mecânica), reverência, humildade, fervor, fé, amor e perseverança. A oração não é técnica — é relacionamento.',
      reforco: 'Oração aceitável não é perfomance religiosa — é comunicação filial com o Pai, em nome do Filho, pelo poder do Espírito.',
      aplicacoes: {
        digital: 'Leia Fp 4.4-7. Medite: "Minha oração é comunicação real com o Pai ou repetição mecânica de fórmulas religiosas?"',
        familia: 'Conversem sobre a vida de oração familiar. Há regularidade? Há especificidade? Há ação de graças?',
        filhos: 'Pratique oração com as crianças usando os três elementos de Fp 4.6: peça, suplique com humildade, agradeça.',
        homens: 'O homem que ora regularmente em família — com especificidade, fervor e ação de graças — lidera espiritualmente.',
        mulheres: 'A mulher que ora com fervor e perseverança — não apenas em momentos de crise — tem vida espiritual robusta.',
        igreja: 'A congregação cuja oração pública é específica, reverente e cheia de graças forma membros com vida de oração madura.',
      },
      oracao: 'Pai, ensina-nos a orar — não com palavras bonitas, mas com coração real. Que outubro nos forme como família de oração: com petições específicas, humildade genuína e gratidão constante. Amém.',
      reflexao: 'Sua oração é específica e perseverante — ou vaga e ocasional? O que isso revela sobre o seu relacionamento real com Deus?',
      aplicacao: 'Esta semana, ore com os sete elementos de CFW XXI.3: entendimento (sabe o que pede), reverência, humildade, fervor, fé, amor e perseverança. Avalie qual é mais fraco.',
      notas: [
        'MILLER, Paul. <em>A Praying Life</em>. Colorado Springs: NavPress, 2009. O livro mais prático e transformador sobre a vida de oração no contexto cotidiano.',
      ],
      notaInicio: 35,
    },
    {
      dia: 277, data: '4 de outubro', tema: 'Canto nos Cultos: Salmos, Hinos e Cânticos',
      capitulo: 'CFW Cap. XXI.5', versiculo: 'Efésios 5.19',
      versiculoTexto: 'Falando entre vós com salmos, hinos e cânticos espirituais, cantando e salmodiando ao Senhor no vosso coração.',
      confissaoTexto: 'O canto de salmos com graça no coração é parte especial do culto religioso ordinário de Deus.',
      cfwRef: 'CFW XXI.5', cfwComparacao: 'CB 1689 Cap. XXII.5 inclui o canto como elemento do culto; CFW XXI.5 especifica "salmos" — gerando debate histórico sobre exclusividade sálmica vs. hinos.',
      exposicao: 'Ef 5.19 e Cl 3.16 listam "salmos, hinos e cânticos espirituais" como a gramática do canto cristão. CFW XXI.5 foi historicamente interpretado por alguns como prescrevendo exclusivamente os Salmos bíblicos (exclusive psalmody). A tradição reformada majoritária reconhece que "salmos, hinos e cânticos" incluem composições inspiradas pelo conteúdo bíblico — mas defende que o Saltério tem prioridade litúrgica por ser o hinário inspirado de Deus. O canto é teologia cantada — o que cantamos forma o que cremos.',
      reforco: 'O canto não é entretenimento espiritual — é confissão de fé em melodia. O que a congregação canta forma sua teologia tanto quanto o que ouve pregado.',
      aplicacoes: {
        digital: 'Leia Ef 5.15-21. Medite: "As letras do que canto na congregação refletem a Escritura? Ou são emocionalmente apelativas mas teologicamente vazias?"',
        familia: 'Cantem juntos um salmo ou hino esta semana — não como performance, mas como oração cantada.',
        filhos: 'Ensine uma letra de hino ou salmo às crianças. Explique o que significa. A memória da infância carrega a teologia para a vida adulta.',
        homens: 'O homem que canta no culto com convicção — não apenas por obrigação — contribui para a adoração coletiva da congregação.',
        mulheres: 'A mulher que escolhe hinos com conteúdo teológico rico para sua vida pessoal é formada pela Palavra cantada.',
        igreja: 'A congregação que avalia seu hinário pela riqueza bíblica e teológica — não apenas pelo apelo emocional — forma adoradores maduros.',
      },
      oracao: 'Senhor, que o canto de nossa congregação seja teologia em melodia — rico na tua Palavra, cheio de gratidão, profundo em doutrina. Que cantemos o que cremos e creiamons o que cantamos. Amém.',
      reflexao: 'As letras que sua congregação canta são teologicamente ricas ou emocionalmente apelativas? O que você canta é o que você crê?',
      aplicacao: 'Escolha três hinos do hinário da congregação. Analise a letra: é bíblica? É doutrinariamente precisa? Edifica ou apenas emociona?',
      notas: [
        'PRICE, Charles e SPINKS, Bryan. <em>The Sacrifice of Praise</em>. Edinburgh: T&T Clark, 1997. A teologia do canto na tradição reformada — histórica e sistemática.',
      ],
      notaInicio: 52,
    },
    {
      dia: 278, data: '5 de outubro', tema: 'O Dia do Senhor: Sábado Cristão',
      capitulo: 'CFW Cap. XXI.7', versiculo: 'Apocalipse 1.10',
      versiculoTexto: 'Achei-me em espírito no dia do Senhor, e ouvi detrás de mim uma grande voz, como de trombeta.',
      confissaoTexto: 'Da lei natural geral temos que uma parte proporcional do tempo deve ser reservada para o culto de Deus; e em sua Palavra, por mandamento positivo e moral obrigando a todos os tempos, ele designou especialmente um dia em sete para ser sábado para si mesmo.',
      cfwRef: 'CFW XXI.7', cfwComparacao: 'CB 1689 Cap. XXII.7 usa linguagem quase idêntica — o domingo como sábado cristão é posição compartilhada por CFW e CB 1689.',
      exposicao: 'Ap 1.10 usa "dia do Senhor" — expressão que na tradição cristã primitiva designava o primeiro dia da semana, dia da ressurreição. CFW XXI.7 defende que o mandamento moral do sábado se aplica aos cristãos, transferido do sétimo para o primeiro dia em razão da ressurreição de Cristo. Não é abolição do sábado — é cumprimento e transformação. O domingo não é dia de lazer religioso — é sábado cristão: descanso do trabalho secular e dedicação ao culto, à comunhão e às obras de misericórdia.',
      reforco: 'O domingo não é "dia livre" que inclui culto. É sábado cristão — dia separado para Deus — que permite lazer legítimo como descanso, não como fuga do sagrado.',
      aplicacoes: {
        digital: 'Leia Ap 1.9-11. Medite: "Como você trata o domingo — como sábado cristão separado para Deus, ou como folga que inclui um culto?"',
        familia: 'Conversem sobre como a família usa o domingo. Há descanso do trabalho secular? Há culto? Há obras de misericórdia?',
        filhos: 'Ensine que o domingo é especial: "É o dia em que nos reunimos para adorar a Jesus ressuscitado. É diferente dos outros dias."',
        homens: 'O homem que separa o domingo para Deus — desligando do trabalho, reunindo-se com a congregação, descansando genuinamente — lidera a família no ritmo bíblico.',
        mulheres: 'A mulher que protege o domingo da invasão do trabalho, das compras e das obrigações seculares cuida do ritmo espiritual da família.',
        igreja: 'A congregação que ensina a teologia do domingo como sábado cristão forma membros com ritmo espiritual semanal saudável.',
      },
      oracao: 'Senhor do sábado, que o primeiro dia da semana seja para nós dia de encontro contigo — em culto, em descanso, em comunhão e em obras de amor. Que não deixemos o domingo ser consumido pelo que deveria esperar. Amém.',
      reflexao: 'Como você usa o domingo? Ele é diferente dos outros dias da semana de forma intencional e espiritual?',
      aplicacao: 'Planeje o próximo domingo como "sábado cristão": inclua culto, descanso do trabalho, refeição com a família ou congregação, e uma obra de misericórdia.',
      notas: [
        'PIPA, Joseph. <em>The Lord\'s Day</em>. Ross-shire: Mentor, 1997. A defesa mais completa do domingo como sábado cristão na tradição reformada.',
      ],
      notaInicio: 69,
    },
    {
      dia: 279, data: '6 de outubro', tema: 'Como Guardar o Dia do Senhor',
      capitulo: 'CFW Cap. XXI.8', versiculo: 'Isaías 58.13-14',
      versiculoTexto: 'Se retirares o teu pé do sábado, de fazeres a tua própria vontade no meu dia santo... então te deleitarás no Senhor.',
      confissaoTexto: 'Este sábado é guardado santo para o Senhor quando os homens, depois de devida preparação do coração e arranjo prévio de seus negócios comuns, não somente observam um descanso santo, mas também empregam todo o tempo no exercício público e privado de sua adoração e nos deveres de necessidade e misericórdia.',
      cfwRef: 'CFW XXI.8', cfwComparacao: 'CB 1689 Cap. XXII.8 é quase idêntico — o domingo bem guardado inclui descanso, culto público, devoção privada e obras de necessidade.',
      exposicao: 'Is 58.13-14 apresenta a promessa do sábado bem guardado: deleite no Senhor. Guardar o domingo não é lista de proibições — é prioridade de presença. CFW XXI.8 define positivamente: (1) preparação prévia do coração; (2) descanso das ocupações seculares; (3) culto público; (4) devoção privada e familiar; (5) obras de necessidade e misericórdia. O domingo guardado corretamente liberta para a eternidade — não aprisiona no legalismo.',
      reforco: 'O domingo bem guardado não é fardo religioso — é libertação semanal do ciclo de produção e consumo que escraviza o mundo.',
      aplicacoes: {
        digital: 'Leia Is 58.13-14. Medite: "O que seria 'deleitar-me no Senhor' no próximo domingo, concretamente?"',
        familia: 'Conversem sobre as cinco dimensões do domingo de CFW XXI.8. Quais sua família já pratica? Quais estão ausentes?',
        filhos: 'Pergunte: "O que você mais gosta de fazer no domingo? Como isso se conecta com adorar a Jesus?"',
        homens: 'O homem que prepara o coração no sábado — organizando os negócios para não invadir o domingo — lidera a família na guarda do dia.',
        mulheres: 'A mulher que planeja o domingo para que seja diferente — com espaço para culto, descanso e comunhão — cuida do ritmo espiritual da família.',
        igreja: 'A congregação que ensina como guardar o domingo — não apenas comparecer ao culto — forma membros com ritmo semanal transformador.',
      },
      oracao: 'Senhor, que o domingo seja para nós deleite e não fardo. Ajuda-nos a prepará-lo bem, a descansar genuinamente, a adorar com fervor e a servir com amor. Que o domingo seja o pico da semana. Amém.',
      reflexao: 'Das cinco dimensões do domingo (preparação, descanso, culto, devoção, misericórdia), qual está mais ausente na sua prática atual?',
      aplicacao: 'Esta semana, prepare o domingo com antecedência: organize as obrigações do sábado para não invadir o domingo. Ore na véspera pedindo coração preparado.',
      notas: [
        'DANIELS, Richard. <em>The Sabbath and Puritan Practice</em>. Edinburgh: Banner of Truth, 2004. Como os puritanos guardavam o domingo — prático e histórico.',
      ],
      notaInicio: 86,
    },
    {
      dia: 280, data: '7 de outubro', tema: 'Síntese: Culto e Domingo',
      capitulo: 'CFW Cap. XXI — Revisão', versiculo: 'Salmo 84.10',
      versiculoTexto: 'Porque um dia nos teus átrios é melhor do que mil. Prefiro estar à porta da casa do meu Deus do que habitar nas tendas da impiedade.',
      confissaoTexto: 'O culto regulado pela Palavra e o domingo guardado como sábado cristão são os dois grandes pilares do ritmo espiritual semanal do crente e da congregação.',
      cfwRef: 'CFW XXI — síntese', cfwComparacao: 'CFW e CB 1689 concordam integralmente em CFW/CB Cap. XXI/XXII — culto regulado e domingo como sábado cristão.',
      exposicao: 'Sl 84.10 expressa o desejo do adorador genuíno: um dia na presença de Deus vale mais do que mil em qualquer outro lugar. O capítulo XXI da Westminster une dois pilares: culto regulado (o que pertence ao culto) e sábado cristão (quando e como adorar coletivamente). Os dois se sustentam mutuamente: o culto regulado define o que fazemos no domingo; o sábado define que o domingo é para isso. Sem um, o outro perde sentido.',
      reforco: 'Culto regulado e sábado cristão não são legalismo — são a estrutura da semana cristã que protege a adoração de ser consumida por tudo o mais.',
      aplicacoes: {
        digital: 'Leia Sl 84 completo. Medite: "Tenho o desejo do salmista — que um dia no átrio de Deus seja meu maior prazer?"',
        familia: 'Façam juntos uma revisão da semana: como o domingo afetou os outros seis dias? O descanso e o culto produziram fruto?',
        filhos: 'Pergunte: "Qual foi a melhor parte do último culto para você? O que você aprendeu?" Reforce que o domingo é especial.',
        homens: 'O homem que ama o culto e guarda o domingo ensina com o exemplo — mais do que qualquer instrução verbal.',
        mulheres: 'A mulher que transmite amor pelo culto aos filhos — desde pequenos — planta semente que produz fruto por gerações.',
        igreja: 'A congregação que forma membros com amor ao culto e ao domingo produz adoradores que buscam a Deus além das obrigações.',
      },
      oracao: 'Senhor, que o culto seja para nós deleite — não obrigação. Que o domingo seja o dia mais esperado da semana. Que possamos dizer com o Salmista: um dia em teus átrios vale mais do que mil em qualquer outro lugar. Amém.',
      reflexao: 'O domingo é o dia mais esperado da sua semana — como o Salmista descreve — ou é mais um item da agenda?',
      aplicacao: 'Escreva o que tornaria o próximo domingo o melhor da sua vida espiritual. Planeje e execute. Avalie ao final do dia.',
      notas: [
        'DEVER, Mark. <em>The Church: The Gospel Made Visible</em>. Nashville: B&H, 2012. O culto congregacional como centro da vida cristã — eclesiologia e liturgia integradas.',
      ],
      notaInicio: 103,
    },
    {
      dia: 281, data: '8 de outubro', tema: 'Juramentos: Apelar ao Nome de Deus',
      capitulo: 'CFW Cap. XXII.1', versiculo: 'Deuteronômio 6.13',
      versiculoTexto: 'Ao Senhor teu Deus temerás, e a ele servirás, e pelo seu nome jurarás.',
      confissaoTexto: 'Um juramento lícito é parte do culto religioso; nele, em assuntos de peso e momento, a pessoa jura solenemente pela glória de Deus, confirmando o que afirma com verdade, julgamento e justiça.',
      cfwRef: 'CFW XXII.1', cfwComparacao: 'CB 1689 Cap. XXIII.1 usa linguagem idêntica — o juramento lícito é ato de culto que apela à onisciência e justiça de Deus como testemunha.',
      exposicao: 'Dt 6.13 permite — e em certas circunstâncias ordena — jurar pelo nome de Deus como ato de culto. O juramento lícito não é blasfêmia ou superstição — é reconhecer publicamente que Deus é testemunha e juiz de todas as coisas. CFW XXII.1 define três características do juramento legítimo: (1) em assuntos de peso (não em trivialidades); (2) em verdade (não confirmação de mentira); (3) com julgamento (discernimento sobre quando é apropriado) e justiça (conteúdo moralmente correto). Jesus em Mt 5.33-37 não proibiu juramentos legais — proibiu o hábito casual de jurar.',
      reforco: 'Jurar pelo nome de Deus é ato solene que reconhece sua onisciência e autoridade. Fazê-lo levianamente é profanar o nome divino.',
      aplicacoes: {
        digital: 'Leia Mt 5.33-37. Medite: "Jesus proibiu todo juramento ou o uso casual e leviano do nome de Deus para confirmar palavras?"',
        familia: 'Conversem sobre a diferença entre o juramento solene (em tribunal, em votos) e o hábito casual de usar o nome de Deus para enfatizar falas.',
        filhos: 'Ensine: "Dizer \'juro por Deus\' para convencer um amigo é usar o nome de Deus sem respeito. Fale sempre a verdade — sem precisar jurar."',
        homens: 'O homem que mantém sua palavra sem precisar jurar demonstra integridade — "que o teu sim seja sim" é o padrão do discipulado.',
        mulheres: 'A mulher de palavra — que não precisa de juramentos para ser acreditada — é testemunho do caráter de Cristo em sua vida.',
        igreja: 'A congregação que ensina a seriedade do nome de Deus forma membros que falam com integridade e reverência ao sagrado.',
      },
      oracao: 'Senhor, que nosso sim seja sim e nosso não seja não. Que falemos com tanta integridade que juramentos sejam desnecessários na vida ordinária. E quando a solenidade exigir, que invoquemos teu nome com reverência. Amém.',
      reflexao: 'Você usa o nome de Deus casualmente para dar ênfase às suas falas? Como isso difere do juramento solene que CFW XXII permite?',
      aplicacao: 'Por uma semana, observe quantas vezes você ou outras pessoas usam "juro por Deus" ou expressões similares de forma casual. Reflita sobre o peso do nome de Deus.',
      notas: [
        'VOS, Geerhardus. <em>Biblical Theology</em>. Grand Rapids: Eerdmans, 1948. O desenvolvimento bíblico do juramento e do uso do nome de Deus — AT e NT.',
      ],
      notaInicio: 120,
    },
    {
      dia: 282, data: '9 de outubro', tema: 'Votos: Compromissos Voluntários com Deus',
      capitulo: 'CFW Cap. XXII.5–7', versiculo: 'Eclesiastes 5.4-5',
      versiculoTexto: 'Quando fizeres voto a Deus, não tardes em cumpri-lo, porque não há prazer nos loucos; cumpre o que prometeste. Melhor é que não votes do que votes e não cumpras.',
      confissaoTexto: 'Os votos devem ser feitos somente a Deus, não a santo algum ou a qualquer outra criatura; devem ser feitos voluntariamente, em fé e consciência do dever, com gratidão por mercê recebida ou obtenção do que se deseja.',
      cfwRef: 'CFW XXII.5', cfwComparacao: 'CB 1689 Cap. XXIII.5 usa linguagem equivalente — votos são somente a Deus, voluntários e vinculantes.',
      exposicao: 'Ec 5.4-5 revela a seriedade do voto: melhor não fazer do que fazer e não cumprir. CFW XXII.5-7 define os votos cristãos: somente a Deus (não a santos, nem à Igreja como condição de salvação); voluntários (não coagidos); em fé e gratidão. Os votos de membro de Igreja, de casamento, de batismo — todos são votos solenes a Deus que vinculam a consciência. Votos monásticos de celibato absoluto ou pobreza perpétua que contradizem a Palavra de Deus não são vinculantes.',
      reforco: 'Todo voto feito a Deus é sério e vinculante. A levianidade nos votos — casamento, membresia, batismo — revela falta de entendimento do que é prometer a Deus.',
      aplicacoes: {
        digital: 'Leia Ec 5.1-7. Medite: "Há votos que você fez a Deus — de casamento, membresia, batismo — e não está cumprindo fielmente?"',
        familia: 'Conversem sobre os votos de casamento. Como vocês os renovam e fortalecem regularmente?',
        filhos: 'Ensine: "Uma promessa é séria. Não prometemos coisas que não vamos cumprir — especialmente a Deus."',
        homens: 'O homem que renova regularmente seus votos de casamento e membresia — com intenção e oração — honra a seriedade do compromisso.',
        mulheres: 'A mulher que leva a sério seus votos — de casamento, de membresia — demonstra que entende a solenidade do que prometeu a Deus.',
        igreja: 'A congregação que instrui os membros sobre os votos de membresia antes de recebê-los protege a integridade da comunidade.',
      },
      oracao: 'Senhor, que meus votos sejam palavras sérias — não formalidades religiosas. Que cumpra o que prometi: no casamento, na membresia, na consagração do batismo. Dá-me fidelidade proporcional à seriedade dos meus votos. Amém.',
      reflexao: 'Quais votos você fez a Deus? Está cumprindo-os fielmente? Há renovação intencional desses compromissos?',
      aplicacao: 'Liste os votos que você fez a Deus (casamento, membresia, dedicação ao ministério). Renove cada um em oração hoje — com especificidade sobre o que cumprirá.',
      notas: [
        'WATSON, Thomas. <em>The Ten Commandments</em>. Edinburgh: Banner of Truth, 1965. O tratamento puritano clássico do terceiro mandamento — nome de Deus e votos.',
      ],
      notaInicio: 137,
    },
    {
      dia: 283, data: '10 de outubro', tema: 'O Nome de Deus: Reverência que Governa a Linguagem',
      capitulo: 'CFW Cap. XXII.2–3', versiculo: 'Êxodo 20.7',
      versiculoTexto: 'Não tomarás o nome do Senhor teu Deus em vão, porque o Senhor não terá por inocente o que tomar o seu nome em vão.',
      confissaoTexto: 'O nome de Deus somente pode ser usado em juramentos e votos com reverência, em verdade, em julgamento e em justiça. Tomar o nome de Deus em vão — em blasfêmia, em juramento falso, em uso casual — é pecado grave.',
      cfwRef: 'CFW XXII.2–3', cfwComparacao: 'CB 1689 Cap. XXIII.2-3 é paralelo — o terceiro mandamento governa todo uso do nome de Deus, incluindo juramentos, votos e linguagem cotidiana.',
      exposicao: 'Êx 20.7 — o terceiro mandamento — proíbe tomar o nome de Deus "em vão": sem peso, sem sentido, sem reverência. CFW XXII.2-3 conecta juramentos e votos ao terceiro mandamento: qualquer uso do nome de Deus deve ter peso proporcional à majestade de quem é nomeado. Isso inclui: blasfêmia, juramento falso, uso casual do nome de Deus em conversas, e também o uso religioso correto mas vazio — recitar o nome de Deus em culto sem reverência genuína.',
      reforco: 'O nome de Deus não é apenas uma palavra — é a revelação de quem ele é. Usá-lo sem reverência é negar na prática quem ele é.',
      aplicacoes: {
        digital: 'Leia Êx 20.7 e Mt 5.33-37. Medite: "Como você usa o nome de Deus no dia a dia — com reverência ou como palavras de preenchimento?"',
        familia: 'Conversem sobre a linguagem familiar. O nome de Deus e de Jesus são usados com reverência em casa?',
        filhos: 'Ensine o terceiro mandamento: "O nome de Deus é especial — não usamos ele como palavrão ou expressão casual. Usamos com cuidado e respeito."',
        homens: 'O homem que governa sua linguagem — evitando blasfêmia, juramento casual, uso vazio do nome de Deus — dá testemunho de reverência genuína.',
        mulheres: 'A mulher que usa o nome de Deus somente com reverência e propósito edifica os filhos no respeito ao sagrado.',
        igreja: 'A congregação que adora com reverência genuína — usando o nome de Deus com peso e intenção — pratica o terceiro mandamento liturgicamente.',
      },
      oracao: 'Senhor, santificado seja o teu nome — em minha boca, em minha casa, em minha congregação. Que nunca pronuncie teu nome sem o peso do que ele representa. Amém.',
      reflexao: 'Como você usa o nome de Deus e de Jesus na sua linguagem cotidiana? Há reverência ou casualidade?',
      aplicacao: 'Observe sua linguagem por um dia inteiro: quantas vezes você usa o nome de Deus ou expressões religiosas sem peso ou reverência? Confesse e corrija.',
      notas: [
        'SPROUL, R.C. <em>The Holiness of God</em>. Wheaton: Tyndale, 1985. O livro que mais profundamente restaura a reverência ao nome e à pessoa de Deus.',
      ],
      notaInicio: 154,
    },
    {
      dia: 284, data: '11 de outubro', tema: 'Juramentos Ilícitos e Falsos',
      capitulo: 'CFW Cap. XXII.4', versiculo: 'Mateus 5.37',
      versiculoTexto: 'Seja, porém, o vosso falar: Sim, sim; Não, não; porque o que passa disto vem do mal.',
      confissaoTexto: 'Não se deve jurar por nada que não seja Deus; é pecado e não deve ser tolerado, especialmente quando se trata de juro falso ou vão; e não obriga ao pecado cumprir juramento feito em tais termos.',
      cfwRef: 'CFW XXII.4', cfwComparacao: 'CB 1689 Cap. XXIII.4 é idêntico — não se jura por criatura, e juramento que obrigue ao pecado não vincula.',
      exposicao: 'Mt 5.37 apresenta o padrão do discipulado: "sim, sim; não, não." Não significa que Jesus aboliu o juramento solene (ele mesmo respondeu sob juramento ao sumo sacerdote — Mt 26.63-64), mas que a integridade cotidiana deve dispensar juramentos. CFW XXII.4 acrescenta duas proibições: (1) não se jura por criaturas (a lua, a própria vida, a honra) — apenas por Deus; (2) juramento que obrigue ao pecado não vincula — Herodes pecou ao manter o juramento que resultou na morte de João Batista (Mc 6.26).',
      reforco: 'Integridade dispensa juramentos. Mas quando necessário, somente por Deus — e nunca em termos que obriguem ao pecado.',
      aplicacoes: {
        digital: 'Leia Mt 5.33-37. Medite: "Minha integridade cotidiana é suficiente para que meu sim seja sim — sem precisar jurar?"',
        familia: 'Conversem: "Como ensinamos os filhos a ser pessoas de palavra — que não precisam reforçar suas promessas com juramentos?"',
        filhos: 'Ensine: "Uma pessoa honesta não precisa dizer \'juro\' para ser acreditada. Seja sempre honesto e sua palavra valerá."',
        homens: 'O homem cuja palavra é confiável — que não usa juramentos para compensar falta de credibilidade — tem integridade que o Evangelho produz.',
        mulheres: 'A mulher que é conhecida por sua honestidade — que seu sim é sim — tem testemunho de caráter que supera qualquer argumento.',
        igreja: 'A congregação que forma pessoas de palavra — honestas, confiáveis, sem necessidade de juramentos para ser acreditadas — testemunha do caráter de Cristo.',
      },
      oracao: 'Senhor, que minha palavra seja confiável — que meu sim seja sim e meu não seja não. Que a integridade do meu caráter dispense juramentos na vida cotidiana. Amém.',
      reflexao: 'As pessoas ao seu redor confiam na sua palavra sem precisar de confirmações ou juramentos? O que isso revela sobre sua integridade?',
      aplicacao: 'Por uma semana, comprometa-se a nunca usar o nome de Deus ou juramentos para enfatizar suas falas. Deixe sua palavra falar por si mesma.',
      notas: [
        'GURNALL, William. <em>The Christian in Complete Armour</em>. Edinburgh: Banner of Truth, 1964. O tratado puritano clássico sobre o caráter cristão — inclui integridade e linguagem.',
      ],
      notaInicio: 171,
    },
    {
      dia: 285, data: '12 de outubro', tema: 'Síntese: Juramentos, Votos e o Nome de Deus',
      capitulo: 'CFW Cap. XXII — Revisão', versiculo: 'Números 30.2',
      versiculoTexto: 'Quando um homem fizer voto ao Senhor ou jurar juramento, ligando a sua alma com algum laço, não quebrará a sua palavra; conforme tudo o que saiu da sua boca, assim o cumprirá.',
      confissaoTexto: 'A reverência ao nome de Deus, a seriedade dos juramentos solenes e a fidelidade aos votos são expressões da verdade que Deus mesmo é — e que o crente é chamado a refletir.',
      cfwRef: 'CFW XXII — síntese', cfwComparacao: 'CFW e CB 1689 convergem plenamente no capítulo sobre juramentos e votos — a reverência ao nome e a seriedade dos compromissos.',
      exposicao: 'Nm 30.2 formula o princípio: o que saiu da boca deve ser cumprido. Essa seriedade com a palavra reflete o caráter de Deus que não pode mentir (Hb 6.18), cujas promessas são sim e amém em Cristo (2Co 1.20). Os crentes são chamados a refletir esse caráter de verdade. Toda a semana sobre CFW XXII converge aqui: reverência ao nome de Deus, juramentos solenes e verdadeiros, votos cumpridos fielmente — tudo expressão de que servimos ao Deus que é Verdade.',
      reforco: 'Integridade na linguagem, seriedade nos juramentos e fidelidade aos votos não são virtudes autônomas — são reflexos do caráter do Deus que servimos.',
      aplicacoes: {
        digital: 'Leia 2Co 1.18-20. Medite: "Como as promessas de Deus em Cristo fundamentam meu próprio compromisso com a integridade?"',
        familia: 'Conversem sobre como a fidelidade de Deus às suas promessas inspira fidelidade da família às suas.',
        filhos: 'Ensine: "Deus nunca quebra uma promessa. Nós queremos ser como Deus — e por isso também cumprimos o que prometemos."',
        homens: 'O homem que cumpre seus compromissos — no casamento, na membresia, no trabalho, na amizade — reflete o caráter do Deus de promessas.',
        mulheres: 'A mulher fiel em seus votos e compromissos é imagem do Deus fiel — testemunho poderoso em um mundo de promessas descartáveis.',
        igreja: 'A congregação que cultiva cultura de integridade — onde palavra é palavra — é sal e luz num mundo de linguagem inflada e comprometimentos vagos.',
      },
      oracao: 'Senhor da verdade, que eu reflita teu caráter na minha linguagem — integridade que dispensa juramentos e fidelidade que honra os votos. Que outubro me forme como pessoa de palavra. Amém.',
      reflexao: 'Sua integridade com palavras e compromissos reflete o caráter do Deus que nunca quebra sua palavra? Onde há discrepância?',
      aplicacao: 'Leia CFW XXII completo. Identifique um compromisso que você está honrando bem e um que precisa de atenção. Ore sobre o segundo e tome ação concreta.',
      notas: [
        'BRIDGES, Jerry. <em>The Practice of Godliness</em>. Colorado Springs: NavPress, 1983. Integridade e caráter como reflexo do caráter de Deus — prático e bíblico.',
      ],
      notaInicio: 188,
    },
    {
      dia: 286, data: '13 de outubro', tema: 'O Magistrado Civil: Ordenança Divina',
      capitulo: 'CFW Cap. XXIII.1', versiculo: 'Romanos 13.1',
      versiculoTexto: 'Toda alma esteja sujeita às potestades superiores; porque não há potestade que não venha de Deus; e as potestades que há foram ordenadas por Deus.',
      confissaoTexto: 'Deus, o Senhor soberano e supremo do mundo, estabeleceu o magistrado civil para, sob si mesmo e para seu próprio louvor, o bem do povo e a manutenção de uma paz e honestidade públicas.',
      cfwRef: 'CFW XXIII.1', cfwComparacao: 'CB 1689 Cap. XXIV.1 usa linguagem equivalente — o governo civil é ordenança divina para o bem da sociedade e a glória de Deus.',
      exposicao: 'Rm 13.1 é o texto fundacional: toda autoridade civil procede de Deus — não como sanção divina a qualquer regime específico, mas como reconhecimento de que a estrutura de governo é ordenança da criação para a vida em sociedade. CFW XXIII.1 precisa o propósito: louvor a Deus, bem do povo, paz e honestidade públicas. O governo civil não é instituição neutra — tem propósito teleológico definido por Deus. Quando cumpre seu propósito, merece submissão. Quando o perverte sistematicamente, surgem questões de resistência legítima.',
      reforco: 'O governo civil não é inimigo da Igreja — é ordenança de Deus para a sociedade. Cristãos honram Deus honrando autoridades legítimas.',
      aplicacoes: {
        digital: 'Leia Rm 13.1-7. Medite: "Sua atitude em relação às autoridades civis reflete Rm 13 — ou é determinada primariamente por preferência política?"',
        familia: 'Conversem: "Como cristãos devemos nos relacionar com o governo — mesmo quando discordamos de políticas específicas?"',
        filhos: 'Ensine: "Deus quer que respeitemos os líderes do nosso país — professores, policiais, governadores. Eles têm autoridade que vem de Deus."',
        homens: 'O homem que honra as autoridades civis e ora pelos governantes — mesmo pelos que critica — demonstra maturidade espiritual e política.',
        mulheres: 'A mulher que ensina os filhos a respeitar a autoridade civil — mesmo discordando de políticas — forma caráter e não rebeldia.',
        igreja: 'A congregação que ora pelos governantes (1Tm 2.1-2) e ensina submissão às autoridades civis cumpre seu dever profético e cívico.',
      },
      oracao: 'Senhor soberano, governas sobre todos os reinos e governos. Que submetamos às autoridades que ordenaste — não por medo, mas por consciência. Que oremos pelos governantes e sejamos cidadãos que honram teu nome. Amém.',
      reflexao: 'Sua relação com as autoridades civis é determinada pela Escritura ou pela política? Você ora pelos governantes — mesmo pelos que discorda?',
      aplicacao: 'Ore hoje pelos governantes do seu país pelo nome — presidente, governador, prefeito. Peça que Deus os guie a cumprir o propósito de Rm 13.4.',
      notas: [
        'VAN DRUNEN, David. <em>Natural Law and the Two Kingdoms</em>. Grand Rapids: Eerdmans, 2010. A teologia das duas esferas — civil e eclesiástica — na tradição reformada.',
      ],
      notaInicio: 205,
    },
    {
      dia: 287, data: '14 de outubro', tema: 'O Cristão no Governo Civil',
      capitulo: 'CFW Cap. XXIII.2', versiculo: '1 Timóteo 2.1-2',
      versiculoTexto: 'Exorto, pois, antes de tudo, que se façam súplicas, orações, intercessões, e ações de graças, por todos os homens; pelos reis e por todos os que estão em eminência, para que vivamos vida tranquila e sossegada, em toda a piedade e honestidade.',
      confissaoTexto: 'É lícito aos cristãos aceitar e executar o cargo de magistrado, quando a isso forem chamados; devendo, no exercício desse cargo, especialmente manter a piedade, a justiça e a paz.',
      cfwRef: 'CFW XXIII.2', cfwComparacao: 'CB 1689 Cap. XXIV.2 é paralelo — cristãos podem e devem participar do governo civil, exercendo-o com piedade e justiça.',
      exposicao: '1Tm 2.1-2 ordena oração pelos governantes — e CFW XXIII.2 vai além: cristãos podem e devem servir no governo civil. O anabatismo histórico, que proibia participação cristã no governo, é rejeitado pela tradição reformada. Cristãos no governo são sal e luz nas estruturas civis. O exercício do cargo deve ser marcado por piedade (referência a Deus), justiça (aplicação imparcial da lei) e paz (promoção do bem-estar da sociedade). Esses critérios devem orientar também o voto e o engajamento cívico.',
      reforco: 'Participação cristã no governo civil é vocation legítima — não compromisso da fé, mas expressão dela em serviço à sociedade.',
      aplicacoes: {
        digital: 'Leia 1Tm 2.1-4. Medite: "Você ora por todos os governantes — não apenas pelos que aprova?"',
        familia: 'Conversem sobre cidadania cristã: votar, servir em conselhos, participar de associações de bairro — como expressão do amor ao próximo.',
        filhos: 'Ensine: "Cristãos podem ser políticos, policiais, juízes — e devem ser os melhores, porque amam a Deus e ao próximo."',
        homens: 'O homem que exerce influência cívica — votando, servindo, engajando responsavelmente — cumpre sua vocação como cidadão cristão.',
        mulheres: 'A mulher que participa da vida cívica — votando com informação e princípios bíblicos, servindo na comunidade — exerce seu chamado no mundo.',
        igreja: 'A congregação que forma membros para a cidadania responsável — não para o pietismo privatista — cumpre seu papel profético na sociedade.',
      },
      oracao: 'Senhor, que cristãos no governo civil exerçam seus cargos com piedade, justiça e paz. Que nossa participação cívica seja expressão de amor ao próximo — não de poder para si mesmo. Amém.',
      reflexao: 'Você vê sua participação cívica (voto, serviço comunitário, influência local) como expressão da fé ou como separada dela?',
      aplicacao: 'Identifique uma forma de servir à sua comunidade civil neste mês — conselho escolar, associação de bairro, trabalho voluntário. Conecte isso à sua fé.',
      notas: [
        'KUYPER, Abraham. <em>Lectures on Calvinism</em>. Grand Rapids: Eerdmans, 1931. A visão reformada da soberania de Deus sobre todas as esferas — incluindo política e governo.',
      ],
      notaInicio: 222,
    },
    {
      dia: 288, data: '15 de outubro', tema: 'Limites da Autoridade Civil: Obedecer a Deus, Não aos Homens',
      capitulo: 'CFW Cap. XXIII.3', versiculo: 'Atos 5.29',
      versiculoTexto: 'Respondendo Pedro e os apóstolos, disseram: Mais importa obedecer a Deus do que aos homens.',
      confissaoTexto: 'O magistrado civil não pode assumir para si a administração da Palavra e dos sacramentos, nem o poder das chaves do reino dos céus; muito menos deve interferir nos assuntos de fé.',
      cfwRef: 'CFW XXIII.3', cfwComparacao: 'CB 1689 Cap. XXIV.3 é paralelo — separação entre as esferas civil e eclesiástica protege tanto a Igreja quanto o Estado.',
      exposicao: 'At 5.29 estabelece o limite da obediência civil: quando o Estado contradiz o mandamento de Deus, obedecer a Deus tem prioridade. CFW XXIII.3 articula a separação das esferas: o Estado não pode administrar sacramentos, exercer disciplina eclesiástica ou coagir a consciência em matéria de fé. A Igreja não é departamento do Estado; o Estado não é braço da Igreja. Essa separação protege ambos: a Igreja da corrupção pelo poder político; o Estado da teocracia que perverte o Evangelho.',
      reforco: 'A separação entre Igreja e Estado não é secularismo — é proteção bíblica da integridade de ambos. Nenhum deve absorver o outro.',
      aplicacoes: {
        digital: 'Leia At 4.18-20 e 5.27-29. Medite: "Em que circunstâncias o cristão deve desobedecer ao Estado? Como isso se distingue de rebeldia política?"',
        familia: 'Conversem: "Como respondemos quando o governo tenta interferir no ensino religioso da família ou na liberdade de culto?"',
        filhos: 'Ensine: "Obedecemos ao governo em quase tudo. Mas se o governo mandar fazer algo que a Bíblia proíbe, obedecemos a Deus."',
        homens: 'O homem que entende os limites da autoridade civil — e está disposto a obedecer a Deus quando o conflito surge — tem convicção, não rebeldia.',
        mulheres: 'A mulher que conhece seus direitos de liberdade religiosa — e está disposta a defendê-los de forma pacífica e legal — protege a família.',
        igreja: 'A congregação que conhece seus limites constitucionais e bíblicos — e está preparada para defender sua liberdade sem conflito desnecessário — age com sabedoria.',
      },
      oracao: 'Senhor, que saibamos quando obedecer ao Estado com gratidão e quando obedecer a ti com coragem. Que nunca confundamos submissão devida com cumplicidade com o mal. Amém.',
      reflexao: 'Há situações no seu contexto onde o Estado está invadindo a esfera da consciência e da fé? Como CFW XXIII.3 orienta a resposta cristã?',
      aplicacao: 'Leia Rm 13.1-7 e At 5.29 juntos. Escreva o princípio que governa quando obedecer ao Estado e quando obedecer a Deus tem prioridade.',
      notas: [
        'SCHAEFFER, Francis. <em>A Christian Manifesto</em>. Wheaton: Crossway, 1981. A resposta cristã ao Estado que ultrapassa seus limites — teologicamente fundamentada.',
      ],
      notaInicio: 239,
    },
    {
      dia: 289, data: '16 de outubro', tema: 'O Cristão e a Política: Sal e Luz',
      capitulo: 'CFW Cap. XXIII.4', versiculo: 'Mateus 5.13-14',
      versiculoTexto: 'Vós sois o sal da terra... Vós sois a luz do mundo.',
      confissaoTexto: 'É dever do povo orar pelos magistrados, honrar as suas pessoas, pagar-lhes tributos e outros direitos, obedecer às suas ordens lícitas e ser sujeito à sua autoridade pela consciência.',
      cfwRef: 'CFW XXIII.4', cfwComparacao: 'CB 1689 Cap. XXIV.4 é paralelo — o dever cívico do crente inclui oração, honra, tributos e obediência.',
      exposicao: 'Mt 5.13-14 descreve a presença cristã no mundo como transformadora — sal que preserva, luz que ilumina. CFW XXIII.4 define os deveres cívicos concretos: orar pelos governantes, honrá-los (mesmo sem necessariamente aprová-los), pagar impostos, obedecer às ordens lícitas. A resistência à autoridade deve ser pela consciência — não por conveniência ou preferência política. Cristãos que evitam impostos, desrespeitam agentes públicos ou desobedecem leis convenientes não refletem CFW XXIII.4.',
      reforco: 'Dever cívico não é opcional para cristãos — oração pelos governantes, pagamento de impostos, obediência a leis lícitas são expressões de fé, não concessões.',
      aplicacoes: {
        digital: 'Leia Rm 13.6-7 e 1Pe 2.13-17. Medite: "Você honra as autoridades civis mesmo quando discorda delas — ou só quando convém?"',
        familia: 'Conversem sobre impostos, leis de trânsito, regulamentações. Como a família honra as leis civis como expressão de fé?',
        filhos: 'Ensine: "Pagar impostos, obedecer ao professor, respeitar as regras do condomínio — tudo faz parte de honrar as autoridades que Deus ordenou."',
        homens: 'O homem que cumpre suas obrigações cívicas — incluindo as que custam — demonstra que sua fé governa sua conduta, não apenas sua teologia.',
        mulheres: 'A mulher que honra as autoridades civis — mesmo as imperfeitas — ensina aos filhos submissão a Deus que governa por meio dessas autoridades.',
        igreja: 'A congregação que forma membros como cidadãos exemplares — honestos, pagadores de impostos, respeitadores das leis — testemunha do Evangelho na sociedade.',
      },
      oracao: 'Senhor, que sejamos sal e luz na vida cívica — honrando autoridades, pagando tributos, cumprindo deveres. Que nosso engajamento político reflita o caráter de Cristo, não a cultura de trincheira. Amém.',
      reflexao: 'Você cumpre seus deveres cívicos como expressão de fé — ou apenas os convenientes? Há áreas de desonestidade cívica que contradizem sua confissão?',
      aplicacao: 'Identifique um dever cívico que você não está cumprindo plenamente (impostos, leis, respeito a autoridades). Trate disso como questão de fé, não apenas de moral cívica.',
      notas: [
        'STOTT, John. <em>Issues Facing Christians Today</em>. Grand Rapids: Zondervan, 1990. Engajamento cristão responsável nas questões políticas e sociais.',
      ],
      notaInicio: 256,
    },
    {
      dia: 290, data: '17 de outubro', tema: 'Síntese: O Magistrado Civil e o Reino de Cristo',
      capitulo: 'CFW Cap. XXIII — Revisão', versiculo: 'Daniel 2.44',
      versiculoTexto: 'E nos dias desses reis, o Deus do céu suscitará um reino que não será jamais destruído... mas fragmentará e consumirá todos esses reinos, e ele mesmo subsistirá para sempre.',
      confissaoTexto: 'O governo civil é ordenança divina temporária que serve ao reino de Cristo — não como seu substituto, mas como espaço em que a Igreja cumpre sua missão.',
      cfwRef: 'CFW XXIII — síntese', cfwComparacao: 'CFW e CB 1689 concordam: o governo civil é legítimo, limitado e temporário — o reino de Cristo é eterno e transcende todo governo humano.',
      exposicao: 'Dn 2.44 revela a perspectiva escatológica de todo governo civil: são temporários; o reino de Deus é eterno. CFW XXIII inteiro deve ser lido nessa perspectiva: o magistrado civil tem autoridade real mas limitada; serve ao propósito divino mas não é o fim; deve ser honrado mas não adorado. O cristão vive em dois reinos simultaneamente — o reino de Cristo e o reino civil — e navega entre eles com sabedoria, fidelidade e perspectiva escatológica.',
      reforco: 'Nenhum governo humano é eterno. O cristão honra o governo civil sem idolatrá-lo — porque sabe que o reino de Cristo é o destino final da história.',
      aplicacoes: {
        digital: 'Leia Dn 2.31-45. Medite: "Como a perspectiva do reino eterno de Cristo liberta você da ansiedade política?"',
        familia: 'Conversem: "Por que cristãos não precisam entrar em pânico com eleições ou mudanças políticas? O reino de Cristo não depende delas."',
        filhos: 'Ensine: "Os presidentes e reis passam. O rei Jesus fica para sempre. Ele governa sobre todos eles."',
        homens: 'O homem que tem perspectiva escatológica sobre a política age com sabedoria e convicção — sem desespero ou idolatria política.',
        mulheres: 'A mulher que descansa no reino eterno de Cristo não é dominada pela ansiedade política — mas vive e age com paz e propósito.',
        igreja: 'A congregação que prega o reino de Cristo como destino da história forma membros que não idolatram nem desprezam o governo civil.',
      },
      oracao: 'Rei Jesus, que teu reino venha — sobre toda autoridade, nação e estrutura. Que enquanto esperamos, honremos o governo que ordenaste e proclamemos o reino que não terá fim. Amém.',
      reflexao: 'A ansiedade política que você sente revela idolatria — esperança depositada no governo civil que só o reino de Cristo pode cumprir?',
      aplicacao: 'Leia Sl 2 e Ap 19.11-16. Medite na soberania de Cristo sobre todos os reinos. Ore pelos governantes do seu país com perspectiva escatológica.',
      notas: [
        'CLOWNEY, Edmund. <em>The Church and the State</em>. Phillipsburg: P&R, 1995. A teologia das duas esferas na perspectiva do reino de Cristo — equilibrada e bíblica.',
      ],
      notaInicio: 273,
    },
    {
      dia: 291, data: '18 de outubro', tema: 'O Casamento: Instituição de Deus',
      capitulo: 'CFW Cap. XXIV.1', versiculo: 'Gênesis 2.24',
      versiculoTexto: 'Portanto, deixará o homem o seu pai e a sua mãe, e se unirá à sua mulher; e serão uma só carne.',
      confissaoTexto: 'O casamento deve ser entre um homem e uma mulher; não lhe é lícito ao homem ter ao mesmo tempo mais de uma esposa, nem à mulher mais de um marido.',
      cfwRef: 'CFW XXIV.1', cfwComparacao: 'CB 1689 Cap. XXV.1 usa linguagem quase idêntica — o casamento é entre um homem e uma mulher, instituído por Deus desde a criação.',
      exposicao: 'Gn 2.24 é citado por Jesus (Mt 19.5) e Paulo (Ef 5.31) como fundamento do casamento — "desde o princípio." CFW XXIV.1 afirma a definição criacional: um homem, uma mulher, exclusividade, permanência. O casamento não é construção cultural — é ordenança da criação. Isso tem implicações: (1) definição não pode ser alterada por legislação humana; (2) a norma criacional orienta tanto as relações dentro do casamento quanto a visão cristã sobre políticas públicas familiares.',
      reforco: 'O casamento cristão não é apenas contrato social — é expressão de ordenança criacional que reflete a relação de Cristo com a Igreja.',
      aplicacoes: {
        digital: 'Leia Gn 2.18-25 e Ef 5.22-33. Medite: "Seu casamento está sendo vivido à luz de sua definição criacional e seu significado redentor?"',
        familia: 'Conversem sobre o que significa ser "uma só carne" — unidade de propósito, de recursos, de cama, de oração e de missão.',
        filhos: 'Ensine: "O casamento foi ideia de Deus desde o princípio — um homem e uma mulher para sempre. É algo muito especial."',
        homens: 'O homem casado que entende o casamento como ordenança divina — não como contrato social — investe nele com fidelidade e alegria.',
        mulheres: 'A mulher que vê o casamento como instituição de Deus — não como escolha cultural — tem fundamento para perseverar nos momentos difíceis.',
        igreja: 'A congregação que ensina a teologia do casamento — sua origem, propósito e significado redentor — forma casais com visão correta e motivação profunda.',
      },
      oracao: 'Senhor, autor do casamento, obrigado pela instituição que tu mesmo criaste. Que o nosso casamento reflita tua sabedoria e tua graça — e que seja testemunho do amor de Cristo pela Igreja. Amém.',
      reflexao: 'Você trata o casamento como instituição de Deus — com a seriedade e alegria que isso implica — ou como contrato que pode ser renegociado conforme a conveniência?',
      aplicacao: 'Leia Gn 2.24 e Ef 5.22-33. Escreva o que o casamento como ordenança de Deus exige de você concretamente — hoje, esta semana.',
      notas: [
        'KOSTENBERGER, Andreas e JONES, David. <em>God, Marriage, and Family</em>. Wheaton: Crossway, 2004. A teologia bíblica mais completa do casamento e família.',
      ],
      notaInicio: 290,
    },
    {
      dia: 292, data: '19 de outubro', tema: 'Propósitos do Casamento: Ajuda, Prole e Santidade',
      capitulo: 'CFW Cap. XXIV.2', versiculo: 'Malaquias 2.15',
      versiculoTexto: 'E não fez ele um só, tendo em si plenitude de espírito? E por que um? Porque buscava uma posteridade para Deus. Guardai-vos, pois, em vosso espírito, e ninguém seja desleal à mulher da sua mocidade.',
      confissaoTexto: 'O casamento foi ordenado para o auxílio mútuo de marido e mulher, para o aumento da raça humana com prole legítima e para evitar a impureza.',
      cfwRef: 'CFW XXIV.2', cfwComparacao: 'CB 1689 Cap. XXV.2 lista os mesmos três propósitos — auxílio mútuo, prole legítima e santidade sexual.',
      exposicao: 'Ml 2.15 revela um propósito central do casamento: "posteridade para Deus." CFW XXIV.2 lista três propósitos: (1) ajuda mútua — Adão precisava de ajuda; o casamento é parceria de completude; (2) prole legítima — filhos nascidos na aliança do casamento; (3) evitar a impureza — o casamento é o contexto para a expressão saudável da sexualidade. Os três propósitos se condicionam: ajuda mútua sem santidade sexual é amizade; sexualidade sem prole como possibilidade é contracepção absolutizada; prole sem ajuda mútua é parentalidade sem parceria.',
      reforco: 'O casamento é rico o suficiente para três propósitos — todos igualmente divinos. Reduzir a apenas um empobrece a instituição.',
      aplicacoes: {
        digital: 'Leia Ml 2.14-16. Medite: "Seu casamento está cumprindo os três propósitos? Qual está mais fraco?"',
        familia: 'Conversem sobre os três propósitos do casamento. Em qual de vocês dois são mais fortes? Em qual precisam crescer?',
        filhos: 'Ensine: "Papai e mamãe se ajudam um ao outro, cuidam de vocês e se amam com fidelidade. Isso é o que Deus quis no casamento."',
        homens: 'O marido que intencionalmente busca os três propósitos — ajuda mútua, responsabilidade com a prole e fidelidade sexual — está no caminho bíblico.',
        mulheres: 'A esposa que investe na ajuda mútua — não apenas na criação dos filhos ou na gestão do lar — honra o primeiro propósito do casamento.',
        igreja: 'A congregação que ensina os propósitos do casamento — antes e depois da cerimônia — forma casais com visão e não apenas romance.',
      },
      oracao: 'Senhor, que nosso casamento cumpra teus três propósitos — ajuda mútua genuína, abertura à prole e santidade sexual. Que cada propósito receba atenção e cuidado intencionais. Amém.',
      reflexao: 'Dos três propósitos (ajuda mútua, prole, santidade sexual), qual está mais fraco no seu casamento agora? O que você pode fazer esta semana?',
      aplicacao: 'Converse com seu cônjuge sobre os três propósitos do casamento. Avaliem juntos qual está mais forte e qual precisa de mais investimento.',
      notas: [
        'DORIANI, Dan. <em>The Life of a God-Made Man</em>. Wheaton: Crossway, 2001. O propósito do casamento na perspectiva do homem cristão — prático e bíblico.',
      ],
      notaInicio: 307,
    },
    {
      dia: 293, data: '20 de outubro', tema: 'Com Quem Casar: Crente com Crente',
      capitulo: 'CFW Cap. XXIV.3', versiculo: '2 Coríntios 6.14',
      versiculoTexto: 'Não vos prendais a um jugo desigual com os infiéis.',
      confissaoTexto: 'É lícito a todos os que podem dar um consentimento deliberado casar; mas é dever dos cristãos casar somente com o Senhor.',
      cfwRef: 'CFW XXIV.3', cfwComparacao: 'CB 1689 Cap. XXV.3 é idêntico — casamento só com crente é dever do cristão, não mera recomendação.',
      exposicao: '2Co 6.14 — "jugo desigual" — é o texto clássico sobre casamento interreligioso. CFW XXIV.3 é claro: cristãos devem casar "somente no Senhor" (1Co 7.39). Isso não é sectarismo — é reconhecimento de que o casamento cristão tem propósito espiritual (ajuda mútua na fé, prole para Deus, missão conjunta) que não pode ser plenamente cumprido sem compatibilidade espiritual. Casos de crente que já é casado com não-crente (1Co 7.12-16) são tratados diferentemente — a aliança existente deve ser honrada.',
      reforco: 'Casar "somente no Senhor" não é legalismo — é reconhecer que casamento cristão tem dimensão espiritual que requer parceiro espiritual.',
      aplicacoes: {
        digital: 'Leia 1Co 7.39 e 2Co 6.14. Medite: "A compatibilidade espiritual é sua prioridade no relacionamento amoroso — ou é secundária à atração e compatibilidade de personalidade?"',
        familia: 'Conversem sobre como orientar os filhos a buscar parceiros espiritualmente compatíveis — sem legalismo, mas com clareza.',
        filhos: 'Ensine: "Quando crescerem e quiserem namorar e casar, olhem para alguém que ama Jesus tanto quanto vocês. Isso vai fazer diferença para o resto da vida."',
        homens: 'O pai que orienta os filhos sobre casamento crente com crente — com clareza e graça — cumpre seu papel na formação espiritual deles.',
        mulheres: 'A mãe que fala com filhas sobre a importância da compatibilidade espiritual prepara para decisões que afetam toda a vida.',
        igreja: 'A congregação que ensina CFW XXIV.3 — e cria comunidade onde jovens cristãos se encontram — serve à saúde espiritual das famílias futuras.',
      },
      oracao: 'Senhor, que os jovens de nossa congregação busquem parceiros que te amem. E que os casais já formados em jugo desigual encontrem graça e sabedoria para honrar o casamento e alcançar o cônjuge para ti. Amém.',
      reflexao: 'Se você é solteiro: a compatibilidade espiritual é sua prioridade em relacionamentos? Se casado com crente: você ora e serve junto ao cônjuge como companheiro espiritual?',
      aplicacao: 'Ore pelos jovens solteiros da sua congregação pelo nome — pedindo que Deus os guie a parceiros espiritualmente compatíveis no tempo certo.',
      notas: [
        'TRIPP, Paul David. <em>What Did You Expect?</em>. Wheaton: Crossway, 2010. Expectativas bíblicas para o casamento — inclui a importância da compatibilidade espiritual.',
      ],
      notaInicio: 324,
    },
    {
      dia: 294, data: '21 de outubro', tema: 'Divórcio: O Que Deus Une',
      capitulo: 'CFW Cap. XXIV.5–6', versiculo: 'Mateus 19.6',
      versiculoTexto: 'Assim, não são mais dois, mas uma só carne. Portanto, o que Deus ajuntou, não o separe o homem.',
      confissaoTexto: 'O casamento somente pode ser dissolvido por adultério ou abandono malicioso e incorrigível — não por simples incompatibilidade; e nesse caso, o inocente pode dissolver o vínculo e contrair novo casamento.',
      cfwRef: 'CFW XXIV.5', cfwComparacao: 'CB 1689 Cap. XXV.5-6 é paralelo — adultério e abandono como causas de divórcio; permanência como norma criacional.',
      exposicao: 'Mt 19.6 é o princípio: o que Deus uniu, o homem não separa. Jesus reconheceu exceção — adulteração (porneia) — em Mt 19.9. CFW XXIV.5 reconhece duas causas de dissolução: adultério e abandono malicioso (1Co 7.15). A norma é permanência; o divórcio é permissão por dureza de coração (Mt 19.8). A cultura contemporânea de divórcio por incompatibilidade contradiz diretamente a visão bíblica. Cristãos divorciados merecem misericórdia — mas a norma criacional permanece como ideal a ser buscado.',
      reforco: 'A permanência do casamento não é ingenuidade romântica — é fidelidade à ordenança de Deus que requer graça e compromisso constantes.',
      aplicacoes: {
        digital: 'Leia Mt 19.3-9. Medite: "Quais aspectos do seu casamento precisam de mais investimento para que a permanência não seja apenas formal?"',
        familia: 'Conversem sobre o que fortalece o casamento contra as pressões que levam ao divórcio: oração conjunta, comunidade, aconselhamento preventivo.',
        filhos: 'Ensine: "Casamento é para sempre — como a aliança de Deus com seu povo. Não é sempre fácil, mas é para sempre."',
        homens: 'O marido que investe ativamente no casamento — tempo, oração, comunicação, afeto — constrói o que resiste às tempestades.',
        mulheres: 'A esposa que busca ajuda quando o casamento está em dificuldade — aconselhamento, mentoria, comunidade — é sábia e corajosa.',
        igreja: 'A congregação que oferece aconselhamento pré-matrimonial, grupos de casais e suporte para casamentos em crise investe na saúde espiritual de suas famílias.',
      },
      oracao: 'Senhor, que nosso casamento seja permanente — não pela falta de dificuldades, mas pela graça que sustenta o compromisso além das dificuldades. Que o que uniste não seja separado pela nossa fraqueza ou pela pressão cultural. Amém.',
      reflexao: 'Que investimentos você está fazendo agora para que o casamento seja forte daqui a dez anos? O futuro do casamento é construído hoje.',
      aplicacao: 'Marque uma atividade intencional de fortalecimento do casamento este mês: fim de semana de casal, série de estudo bíblico juntos, aconselhamento preventivo.',
      notas: [
        'ADAMS, Jay. <em>Marriage, Divorce, and Remarriage in the Bible</em>. Phillipsburg: P&R, 1980. O tratamento mais exegético das questões de divórcio e recasamento.',
      ],
      notaInicio: 341,
    },
    {
      dia: 295, data: '22 de outubro', tema: 'O Casamento como Imagem de Cristo e a Igreja',
      capitulo: 'CFW Cap. XXIV — Teologia', versiculo: 'Efésios 5.32',
      versiculoTexto: 'Grande é este mistério; mas eu me refiro a Cristo e à Igreja.',
      confissaoTexto: 'O casamento é ordenança de Deus que, além de seus propósitos práticos, é tipo e imagem da aliança de amor entre Cristo e sua Igreja — o marido amando como Cristo, a esposa respondendo como a Igreja.',
      cfwRef: 'CFW XXIV — teologia', cfwComparacao: 'Ef 5.22-33 é a base teológica que CFW XXIV pressupõe — o casamento como misterioso reflexo da relação Cristo-Igreja.',
      exposicao: 'Ef 5.32 revela a profundidade do casamento: é "grande mistério" que aponta para Cristo e a Igreja. Paulo não está apenas usando o casamento como ilustração — está revelando que o casamento foi criado com esse propósito tipológico. O marido ama como Cristo amou — entrega total, sacrificial, santificadora. A esposa responde como a Igreja — confiança, submissão voluntária, reciprocidade. Esse quadro transforma o casamento de contrato social em sacramento do amor de Deus.',
      reforco: 'O casamento cristão tem missão além de si mesmo: é proclamação viva do Evangelho — o amor de Cristo por sua Igreja tornado visível.',
      aplicacoes: {
        digital: 'Leia Ef 5.22-33. Medite: "Meu casamento proclama o amor de Cristo pela Igreja? Ou contradiz esse testemunho?"',
        familia: 'Conversem: "Como o amor sacrificial de Cristo orienta o amor do marido? Como a resposta da Igreja orienta a esposa?"',
        filhos: 'Ensine: "Quando veem papai e mamãe se amando e se respeitando, estão vendo uma imagem de como Jesus ama a Igreja."',
        homens: 'O marido que ama como Cristo amou — dando-se, santificando, servindo — prega o Evangelho sem palavras todos os dias.',
        mulheres: 'A esposa que responde ao amor do marido com confiança e respeito mútuo reflete a Igreja em seu melhor — amada e respondendo em amor.',
        igreja: 'A congregação cujos casais refletem Ef 5.22-33 é comunidade que proclama o Evangelho com a vida — não apenas com palavras.',
      },
      oracao: 'Senhor Jesus, que nosso casamento seja imagem do teu amor pela Igreja — sacrificial, fiel, santificador. Que ele proclame o Evangelho antes que digamos uma palavra. Amém.',
      reflexao: 'Seu casamento está proclamando o amor de Cristo? Se um vizinho não-crente observasse, veria algo diferente dos casamentos ao redor?',
      aplicacao: 'Leia Ef 5.22-33 com o cônjuge. Conversem sobre o que significaria viver esse texto mais plenamente — e escolham uma mudança concreta para esta semana.',
      notas: [
        'PIPER, John e GRUDEM, Wayne (eds.). <em>Recovering Biblical Manhood and Womanhood</em>. Wheaton: Crossway, 1991. A teologia da masculinidade e feminilidade no casamento — a referência da tradição complementarista.',
      ],
      notaInicio: 358,
    },
    {
      dia: 296, data: '23 de outubro', tema: 'Síntese: O Casamento na Visão Cristã',
      capitulo: 'CFW Cap. XXIV — Revisão', versiculo: 'Hebreus 13.4',
      versiculoTexto: 'Honroso seja o matrimônio em todos, e o leito sem mácula; mas Deus julgará os fornicadores e adúlteros.',
      confissaoTexto: 'O casamento — instituição de Deus, entre homem e mulher, permanente, fiel e tipológico — é o ambiente onde sexualidade, família e missão se integram em ordenança santa.',
      cfwRef: 'CFW XXIV — síntese', cfwComparacao: 'CFW e CB 1689 concordam integralmente em XXIV/XXV — o casamento como aliança santa, permanente e tipológica.',
      exposicao: 'Hb 13.4 une o positivo e o negativo: honra ao casamento (santidade e alegria da aliança) e juízo sobre a imoralidade sexual (realidade da responsabilidade). A semana sobre casamento percorreu: definição (um homem, uma mulher), propósitos (auxílio, prole, santidade), compatibilidade espiritual, permanência, tipologia do amor de Cristo. Tudo converge: o casamento cristão é micro-missão — proclama o Evangelho com a vida, santifica os cônjuges, produz prole para Deus.',
      reforco: 'O casamento honrado é sinal visível do reino — tanto sua santidade quanto sua alegria proclamam o Evangelho.',
      aplicacoes: {
        digital: 'Leia Hb 13.4. Medite: "Meu casamento é honrado — com alegria, fidelidade e intencionalidade — ou é mero hábito compartilhado?"',
        familia: 'Conversem sobre como honrar o casamento ativamente — não apenas evitar o divórcio, mas investir na alegria e na profundidade.',
        filhos: 'Observe como os pais mostram amor um pelo outro. Esse exemplo é mais formador do que qualquer instrução verbal.',
        homens: 'O marido que honra o casamento publicamente — com respeito à esposa, fidelidade visível, alegria compartilhada — testemunha do Evangelho.',
        mulheres: 'A esposa que fala bem do marido, que o honra publicamente e que investe no casamento com alegria reflete Hb 13.4 na vida real.',
        igreja: 'A congregação que celebra casamentos, apoioa casais em crise e forma novos casais com fundamento bíblico cuida do tecido mais básico da comunidade.',
      },
      oracao: 'Senhor, que o nosso casamento seja honrado — em santidade e em alegria. Que proclame o Evangelho com a qualidade do amor que vivemos. Amém.',
      reflexao: 'Como você está ativamente honrando seu casamento — não apenas mantendo-o, mas investindo na sua alegria, profundidade e testemunho?',
      aplicacao: 'Planeje este mês uma ação intencional de honra ao cônjuge — surpresa, carta, gesto de serviço. E ore juntos sobre o casamento de vocês.',
      notas: [
        'TRIPP, Paul David. <em>Marriage: 6 Gospel Commitments Every Couple Needs to Make</em>. Wheaton: Crossway, 2021. O casamento visto pelo Evangelho — prático, honesto e esperançoso.',
      ],
      notaInicio: 375,
    },
    {
      dia: 297, data: '24 de outubro', tema: 'Família: Célula da Sociedade e da Igreja',
      capitulo: 'CFW Cap. XXIV — Família', versiculo: 'Deuteronômio 6.6-7',
      versiculoTexto: 'E estas palavras que hoje te ordeno estarão no teu coração; e as ensinarás a teus filhos, e delas falarás assentado em tua casa, e andando pelo caminho, e ao deitar-te, e ao levantar-te.',
      confissaoTexto: 'A família fundada no casamento é a unidade básica da Igreja e da sociedade, responsável pela transmissão da fé, pela formação do caráter e pela continuidade das gerações.',
      cfwRef: 'CFW XXIV — família', cfwComparacao: 'Dt 6 e Ef 6.4 fundamentam a responsabilidade parental que CFW XXIV pressupõe — o casamento produz família; a família produz fé nas gerações.',
      exposicao: 'Dt 6.6-7 instrui que a transmissão da fé acontece na vida cotidiana da família — "andando pelo caminho, ao deitar-te, ao levantar-te." A formação espiritual não é evento — é ritmo familiar. O casamento que CFW XXIV defende não é fim em si mesmo — é início da família que transmite a fé. Pais que constroem casamento bíblico constroem também o ambiente mais poderoso de formação espiritual dos filhos: o lar onde a fé é praticada, discutida e vivida 24 horas.',
      reforco: 'O lar é a escola primária da fé — mais poderosa do que a escola dominical, mais formadora do que qualquer programa eclesiástico.',
      aplicacoes: {
        digital: 'Leia Dt 6.4-9. Medite: "Como a fé está sendo transmitida no cotidiano do meu lar — não apenas nos momentos formais de devoção?"',
        familia: 'Conversem sobre o ritmo espiritual familiar: café da manhã, janta, deitar. Onde a fé está sendo praticada visivelmente?',
        filhos: 'Pratique com as crianças conversar sobre Deus nos momentos ordinários — no carro, na refeição, no banho. A fé vive na vida comum.',
        homens: 'O pai que lidera devoção familiar — mesmo que imperfeita e breve — cumpre Dt 6 mais do que o pai que deixa isso para a Igreja.',
        mulheres: 'A mãe que faz perguntas espirituais nas conversas cotidianas — sobre a escola, os amigos, as emoções — está formando fé organicamente.',
        igreja: 'A congregação que equipa pais para serem os principais discipuladores dos filhos — não substitutos deles — cumpre seu papel de apoio, não de terceirização.',
      },
      oracao: 'Senhor, que nosso lar seja escola de fé — onde tua Palavra é transmitida no caminhar, no sentar, no deitar e no levantar. Que a fé viva na vida comum, não apenas nos momentos formais. Amém.',
      reflexao: 'Onde e como a fé está sendo transmitida organicamente no cotidiano do seu lar? Há momentos intencionais — mas também integração à vida comum?',
      aplicacao: 'Escolha três momentos do dia para introduzir conversa sobre a fé com os filhos esta semana — não em formato de devoção, mas em conversa natural.',
      notas: [
        'TRIPP, Tedd e TRIPP, Margy. <em>Instructing a Child\'s Heart</em>. Wapwallopen: Shepherd Press, 2008. Como transmitir fé no cotidiano familiar — prático e bíblico.',
      ],
      notaInicio: 392,
    },
    {
      dia: 298, data: '25 de outubro', tema: 'A Igreja: Visível e Invisível — Westminster',
      capitulo: 'CFW Cap. XXV.1–2', versiculo: 'Hebreus 12.23',
      versiculoTexto: 'A assembleia dos primogênitos que estão inscritos nos céus, e a Deus, o Juiz de todos, e aos espíritos dos justos aperfeiçoados.',
      confissaoTexto: 'A Igreja Católica, que é invisível, consiste do número total dos eleitos que foram, são e serão reunidos sob Cristo, sua cabeça. A Igreja Visível, que é também católica, consiste de todos os que professam a verdadeira religião.',
      cfwRef: 'CFW XXV.1–2', cfwComparacao: 'CB 1689 Cap. XXVI.1 segue a mesma estrutura — Igreja invisível (eleitos) e visível (professantes); a diferença está na ênfase batista na congregação local.',
      exposicao: 'Hb 12.23 revela a Igreja invisível: os "primogênitos inscritos nos céus" — todos os eleitos de todos os tempos. CFW XXV.1-2 distingue Igreja invisível (todos os eleitos sob Cristo) e visível (todos os professantes mundialmente). A distinção é crucial: a visível inclui joio e trigo (Mt 13.24-30); a invisível é só trigo. Nenhuma congregação local é idêntica à Igreja invisível — toda congregação tem membros não-regenerados. Isso exige humildade eclesiológica: não temos acesso perfeito a quem são os eleitos.',
      reforco: 'A Igreja invisível é objeto de certeza — todos os eleitos serão glorificados. A visível é objeto de fidelidade — professantes que devemos pastorear com cuidado.',
      aplicacoes: {
        digital: 'Leia Hb 12.18-24. Medite: "Você é membro da Igreja invisível (pelos sinais de graça genuína) ou apenas da visível (por profissão formal)?"',
        familia: 'Conversem: "Como sabemos se somos parte da Igreja invisível? O que a Escritura diz sobre os sinais de eleição?"',
        filhos: 'Ensine: "A Igreja real é todos que amam Jesus de verdade em todo o mundo e em todos os tempos — muito maior do que nossa congregação."',
        homens: 'O homem que pensa sobre sua congregação com humildade eclesiológica — sabendo que não vê o coração — cuida do rebanho com graça e discernimento.',
        mulheres: 'A mulher que entende a distinção Igreja visível/invisível não julga o coração dos outros, mas cuida dos frutos que pode observar.',
        igreja: 'A congregação que se reconhece como parte da Igreja visível — sem presumir ser idêntica à invisível — pratica humildade eclesiástica.',
      },
      oracao: 'Senhor, obrigado por incluirmos na Igreja invisível dos eleitos — e obrigado pela Igreja visível que nos sustenta com Palavra e sacramentos. Que sejamos fiéis a ambas. Amém.',
      reflexao: 'Há evidências de graça genuína na sua vida — marcas da Igreja invisível — ou você é membro apenas formal da Igreja visível?',
      aplicacao: 'Leia CFW XXV.1-2 e 1Jo 3.14. Examine sua vida pelos sinais de pertencimento à Igreja invisível que João descreve.',
      notas: [
        'BANNERMAN, James. <em>The Church of Christ</em>. Edinburgh: Banner of Truth, 1960. A eclesiologia reformada mais completa — fundamento para toda a semana sobre a Igreja.',
      ],
      notaInicio: 409,
    },
    {
      dia: 299, data: '26 de outubro', tema: 'Cristo: Cabeça da Igreja',
      capitulo: 'CFW Cap. XXV.3', versiculo: 'Colossenses 1.18',
      versiculoTexto: 'E ele é a cabeça do corpo, da Igreja. Ele é o princípio, o primogênito dentre os mortos, para que em tudo tenha a preeminência.',
      confissaoTexto: 'O Senhor Jesus Cristo é o único cabeça da Igreja. O papa de Roma não pode ser de modo algum cabeça da Igreja, mas é aquele anticristo, o homem do pecado e o filho da perdição, que se exalta na Igreja contra Cristo e contra tudo o que se chama Deus.',
      cfwRef: 'CFW XXV.6', cfwComparacao: 'CB 1689 Cap. XXVI.4 afirma o senhorio de Cristo com linguagem mais suave sobre Roma; CFW XXV.6 é explícita sobre o papado como anticristo.',
      exposicao: 'Cl 1.18 proclama: Cristo tem a preeminência em tudo — especialmente sobre a Igreja, seu corpo. CFW XXV.6 é historicamente inflamada sobre o papado — produto direto da Reforma do século XVI. A afirmação central permanece válida além da polêmica: nenhum homem pode ser cabeça da Igreja de Cristo. Não o papa, não o bispo, não o pastor, não o denominação. Cristo governa sua Igreja por sua Palavra e Espírito — toda liderança humana é delegada, não absoluta.',
      reforco: 'O senhorio de Cristo sobre a Igreja não é doutrina abstrata — é princípio prático que deve governar toda decisão eclesiástica.',
      aplicacoes: {
        digital: 'Leia Cl 1.15-20. Medite: "Em que áreas da vida da minha congregação Cristo tem a preeminência — e em que áreas ela está sendo usurpada por outro senhor?"',
        familia: 'Conversem: "Como Cristo governa nossa família por sua Palavra? Sua Palavra tem a última palavra em nossas decisões?"',
        filhos: 'Ensine: "Jesus é o chefe da Igreja — como um rei que governa seu reino com amor, sabedoria e justiça."',
        homens: 'O homem que lidera na Igreja o faz como servo de Cristo — não como senhor. Toda liderança saudável começa com submissão à Cabeça.',
        mulheres: 'A mulher que serve na Igreja serve a Cristo, não a homens ou estruturas. Seu serviço tem dignidade porque vem da Cabeça.',
        igreja: 'A congregação que regularmente reafirma o senhorio de Cristo — em decisões, programas, conflitos — permanece eclesiologicamente saudável.',
      },
      oracao: 'Senhor Jesus, tu és a Cabeça — não nossa tradição, não nosso pastor, não nossa estrutura. Que tua Palavra governe nossa congregação com autoridade. Que resistamos à usurpação de qualquer outro senhor. Amém.',
      reflexao: 'Em que decisões recentes da sua congregação Cristo foi claramente a Cabeça — e em quais outras autoridades tiveram mais peso?',
      aplicacao: 'Leia Cl 1.15-20 antes da próxima reunião congregacional ou de liderança. Ore pedindo que Cristo governe aquela discussão como Cabeça.',
      notas: [
        'CLOWNEY, Edmund. <em>The Church</em>. Downers Grove: IVP, 1995. A eclesiologia que coloca o senhorio de Cristo no centro de tudo — acessível e profunda.',
      ],
      notaInicio: 426,
    },
    {
      dia: 300, data: '27 de outubro', tema: 'Marcas da Igreja Verdadeira',
      capitulo: 'CFW Cap. XXV.4–5', versiculo: '1 Timóteo 3.15',
      versiculoTexto: 'Para que, se eu tardar, saibas como te deves portar na casa de Deus, que é a Igreja do Deus vivo, coluna e firmamento da verdade.',
      confissaoTexto: 'As igrejas particulares são mais ou menos puras conforme a doutrina do Evangelho é ensinada e abarcada, os sacramentos administrados e o culto público realizado nelas de forma mais ou menos pura.',
      cfwRef: 'CFW XXV.4', cfwComparacao: 'CB 1689 Cap. XXVI.4-5 usa linguagem equivalente — a pureza da Igreja local é medida pela fidelidade à Palavra, sacramentos e culto.',
      exposicao: '1Tm 3.15 chama a Igreja de "coluna e firmamento da verdade" — guardiã e proclamadora da verdade de Deus. A Reforma identificou três marcas da Igreja verdadeira: (1) pregação fiel da Palavra; (2) administração correta dos sacramentos; (3) exercício da disciplina eclesiástica. CFW XXV.4 foca nas duas primeiras; a disciplina está em CFW XXX. Congregações variam em pureza — nenhuma é perfeita — mas devem buscar as marcas.',
      reforco: 'Não existe congregação perfeita — mas existe congregação mais ou menos fiel às marcas. Essas marcas são o critério para escolher e avaliar uma congregação.',
      aplicacoes: {
        digital: 'Leia 1Tm 3.14-16. Medite: "Minha congregação está crescendo em fidelidade às marcas — pregação, sacramentos, culto?"',
        familia: 'Conversem: "Por que as marcas da Igreja verdadeira são critério mais importante do que o estilo musical, o tamanho ou o prestígio da congregação?"',
        filhos: 'Ensine: "Uma boa Igreja é aquela que ensina a Bíblia fielmente, batiza e celebra a ceia corretamente. Essas coisas importam mais do que o prédio ou a música."',
        homens: 'O homem que avalia sua congregação pelas marcas — e age para fortalecê-las — cuida da saúde espiritual de todos.',
        mulheres: 'A mulher que escolhe sua congregação pelas marcas — e não por conveniência ou preferência estética — tem eclesiologia madura.',
        igreja: 'A congregação que avalia regularmente sua fidelidade às marcas — e busca aprofundá-las — está no caminho da reforma contínua.',
      },
      oracao: 'Senhor, que nossa congregação seja coluna e firmamento da verdade — fiel na pregação, nos sacramentos e no culto. Que as marcas da Igreja verdadeira sejam nossas prioridades, não o crescimento numérico ou o prestígio. Amém.',
      reflexao: 'Das três marcas (pregação fiel, sacramentos corretos, disciplina), qual está mais forte e qual mais fraca na sua congregação?',
      aplicacao: 'Converse com um líder da sua congregação sobre as marcas da Igreja verdadeira. Como a congregação se avalia nessas marcas? Onde há espaço para crescimento?',
      notas: [
        'DEVER, Mark. <em>Nine Marks of a Healthy Church</em>. Wheaton: Crossway, 2004. A expansão contemporânea das marcas da Igreja — prática e bíblica.',
      ],
      notaInicio: 443,
    },
    {
      dia: 301, data: '28 de outubro', tema: 'A Igreja e os Meios de Graça',
      capitulo: 'CFW Cap. XXV.3', versiculo: 'Romanos 10.17',
      versiculoTexto: 'De sorte que a fé é pelo ouvir, e o ouvir pela palavra de Deus.',
      confissaoTexto: 'Fora da Igreja não há possibilidade ordinária de salvação; portanto é dever de todos que dela se não encontrem membros, incorporar-se a ela.',
      cfwRef: 'CFW XXV.2', cfwComparacao: 'CB 1689 não usa a formulação "fora da Igreja não há salvação" com tanta ênfase — mas afirma a necessidade da congregação local como meio ordinário de graça.',
      exposicao: 'Rm 10.17 revela como a fé ordinariamente vem: pelo ouvir a Palavra. A Igreja é o lugar onde a Palavra é pregada — portanto, o meio ordinário pelo qual Deus produz e sustenta a fé. CFW XXV.2 usa a fórmula clássica: "extra ecclesiam nulla salus" (fora da Igreja não há salvação ordinária). Isso não significa que Deus não pode salvar sem a Igreja — mas que ele escolheu a Igreja como meio ordinário. "Cristão sem Igreja" não é categoria bíblica.',
      reforco: 'A congregação local não é opcional para o crente — é o meio ordinário pelo qual Deus sustenta a fé, a comunhão e o crescimento.',
      aplicacoes: {
        digital: 'Leia Rm 10.13-17. Medite: "Como a pregação da Palavra na congregação tem sustentado e nutrido sua fé?"',
        familia: 'Conversem: "Por que participar regularmente de uma congregação fiel não é opcional — é necessário para o crescimento espiritual?"',
        filhos: 'Ensine: "Ir à Igreja não é só obrigação — é onde aprendemos a Bíblia, onde somos amados pelos irmãos e onde Deus nos nutre."',
        homens: 'O homem que leva a família à congregação regularmente — mesmo quando é inconveniente — prioriza os meios ordinários de graça.',
        mulheres: 'A mulher que nutre a fé dos filhos por meio da vida congregacional — não apenas pelo lar — usa todos os meios que Deus proveu.',
        igreja: 'A congregação que se apresenta como meio necessário de graça — não como clube opcional — chama seus membros à fidelidade.',
      },
      oracao: 'Senhor, obrigado pela Igreja — onde tua Palavra é pregada e tua graça é dispensada. Que nunca trate a congregação como opcional. Que aprecie os meios ordinários que providenciaste para nossa nutrição espiritual. Amém.',
      reflexao: 'Você trata a congregação como meio necessário de graça — frequentando com fidelidade — ou como recurso opcional que usa quando conveniente?',
      aplicacao: 'Por um mês, comprometa-se a não faltar ao culto principal sem motivo grave. Avalie ao final do mês o impacto na sua vida espiritual.',
      notas: [
        'HORTON, Michael. <em>People and Place</em>. Louisville: WJK, 2008. A eclesiologia dos meios de graça — por que a congregação local é central, não periférica.',
      ],
      notaInicio: 460,
    },
    {
      dia: 302, data: '29 de outubro', tema: 'A Igreja Militante e Triunfante',
      capitulo: 'CFW Cap. XXV.6', versiculo: 'Apocalipse 7.9',
      versiculoTexto: 'Depois destas coisas vi, e eis uma grande multidão que ninguém podia enumerar, de todas as nações, e tribos, e povos, e línguas, em pé diante do trono e diante do Cordeiro.',
      confissaoTexto: 'A Igreja consiste às vezes em um número maior, às vezes menor, de pessoas visíveis. Em alguns períodos tem estado muito obscurecida e odiada pelos inimigos; todavia, sempre será preservada — porque as portas do inferno não prevalecerão contra ela.',
      cfwRef: 'CFW XXV.5', cfwComparacao: 'CB 1689 Cap. XXVI.5 usa linguagem equivalente — a Igreja persevera apesar de perseguição, apostasia e fraqueza aparente.',
      exposicao: 'Ap 7.9 revela o destino final da Igreja: multidão incontável de todas as nações diante do trono. CFW XXV.5 reconhece a realidade histórica: a Igreja tem tido períodos de grandeza e de obscuridade, de expansão e de perseguição. Mas a promessa de Cristo prevalece: "as portas do inferno não prevalecerão contra ela" (Mt 16.18). A Igreja militante (em luta na terra) e a Igreja triunfante (glorificada no céu) são a mesma Igreja — em estágios diferentes da mesma jornada.',
      reforco: 'A Igreja pode parecer fraca ou ameaçada — mas é inexpugnável. Cristo garantiu sua preservação. A fidelidade local contribui para o triunfo eterno.',
      aplicacoes: {
        digital: 'Leia Ap 7.9-17. Medite: "Como a visão da Igreja triunfante de Ap 7 fortalece sua fidelidade à Igreja militante local?"',
        familia: 'Conversem sobre a perseguição histórica e atual da Igreja. Como a promessa de Mt 16.18 sustenta os perseguidos?',
        filhos: 'Ensine: "Em alguns países, as pessoas são presas por seguir Jesus. Mas a Igreja de Cristo nunca será destruída — Jesus prometeu."',
        homens: 'O homem fiel à congregação mesmo nos momentos de fraqueza institucional contribui para a continuidade da Igreja que Cristo prometeu preservar.',
        mulheres: 'A mulher que ora pela Igreja perseguida — pelo nome de países e líderes — une a Igreja militante local à luta global.',
        igreja: 'A congregação que tem perspectiva histórica — que conhece períodos de obscuridade e de expansão — não desespera nas dificuldades presentes.',
      },
      oracao: 'Senhor Jesus, as portas do inferno não prevalecerão contra tua Igreja. Que essa certeza nos torne corajosos na luta presente e esperançosos no triunfo futuro. Que sejamos fiéis à Igreja militante porque conhecemos a triunfante. Amém.',
      reflexao: 'Você conhece a história da perseguição da Igreja? Como o passado da Igreja militante e a visão da triunfante fortalecem sua fidelidade hoje?',
      aplicacao: 'Pesquise um país onde a Igreja está sendo perseguida hoje. Ore por essa Igreja pelo nome. Doe para uma organização de ajuda à Igreja perseguida.',
      notas: [
        'STARK, Rodney. <em>The Triumph of Christianity</em>. New York: HarperOne, 2011. A história da expansão da Igreja contra todas as probabilidades — perspectiva histórica motivadora.',
      ],
      notaInicio: 477,
    },
    {
      dia: 303, data: '30 de outubro', tema: 'Síntese de Outubro: CFW Cap. XXI–XXV',
      capitulo: 'CFW Cap. XXI–XXV — Revisão Final', versiculo: 'Efésios 3.10-11',
      versiculoTexto: 'Para que agora, pela Igreja, a multiforme sabedoria de Deus se dê a conhecer aos principados e potestades nos lugares celestiais, segundo o eterno propósito que realizou em Cristo Jesus nosso Senhor.',
      confissaoTexto: 'Outubro percorreu a vida exterior do crente e da congregação: culto regulado pela Palavra, domingo como sábado cristão, juramentos e votos sérios, governo civil honrado, casamento santo e a Igreja como corpo de Cristo.',
      cfwRef: 'CFW XXI–XXV — síntese', cfwComparacao: 'CFW e CB 1689 concordam em substância em todos os capítulos de outubro — as diferenças são de ênfase e de governo eclesiástico, não de doutrina central.',
      exposicao: 'Ef 3.10-11 revela o propósito eterno de Deus para a Igreja: manifestar sua multiforme sabedoria aos poderes celestiais. A Igreja não existe apenas para os membros — existe para a glória de Deus diante de toda a criação. Outubro construiu a estrutura exterior dessa Igreja: culto que honra a Deus (XXI), linguagem e votos que refletem a integridade de Deus (XXII), participação no governo civil como serviço (XXIII), casamento como imagem do amor de Cristo (XXIV), e a Igreja como corpo eterno e inexpugnável (XXV). Novembro entrará em CFW XXVI–XXIX: comunhão, ceia, batismo e concílios.',
      reforco: 'Outubro construiu a vida exterior do crente e da Igreja. Novembro aprofundará os sacramentos e a comunhão que nutrem essa vida.',
      aplicacoes: {
        digital: 'Leia Ef 3.8-12. Medite: "Como minha vida — culto, linguagem, casamento, cidadania — está proclamando a multiforme sabedoria de Deus?"',
        familia: 'Façam juntos uma linha do tempo de outubro: Culto (274-280), Juramentos (281-285), Governo Civil (286-290), Casamento (291-297), Igreja (298-302). Ore por cada área.',
        filhos: 'Pergunte: "O que outubro ensinou sobre culto, casamento e Igreja? O que você vai lembrar?" Registre as respostas.',
        homens: 'O homem que completou outubro tem visão mais completa da vida exterior cristã — culto, linguagem, cidadania, casamento, Igreja. Novembro aprofundará a comunhão e os sacramentos.',
        mulheres: 'A mulher que percorreu outubro foi formada nas estruturas externas da fé que organizam a vida no mundo — culto, família e comunidade.',
        igreja: 'A Igreja que ensina CFW XXI–XXV forma membros que vivem a fé no mundo — não apenas privadamente — em cada esfera da vida.',
      },
      oracao: 'Senhor, obrigado por outubro — por culto, juramentos, governo civil, casamento e Igreja. Que novembro nos aprofunde na comunhão dos santos e nos sacramentos que nutrem tudo o que outubro construiu. Amém.',
      reflexao: 'Dos cinco temas de outubro (culto, juramentos/votos, governo civil, casamento, Igreja), qual transformou mais concretamente sua vida? Qual ainda precisa de atenção?',
      aplicacao: 'Escreva uma carta de meia página resumindo o que outubro ensinou sobre a vida cristã no mundo. Guarde para reler em dezembro. Ore para que novembro — comunhão, ceia, batismo — aprofunde o que outubro iniciou.',
      notas: [
        'HORTON, Michael. <em>The Christian Faith</em>. Grand Rapids: Zondervan, 2011. A síntese sistemática mais completa que integra todos os capítulos de outubro.',
        'BEEKE, Joel e JONES, Mark. <em>A Puritan Theology</em>. Grand Rapids: Reformation Heritage, 2012. O pano de fundo histórico de cada doutrina de outubro na tradição reformada.',
      ],
      notaInicio: 494,
    },
  ];
  return dias.map(blocoW);
}
`;

let content = fs.readFileSync(filePath, 'utf8');
fs.writeFileSync(filePath, content + outubro, 'utf8');
console.log('✅ gerarDiasOutubro() adicionada');
console.log('Linhas:', (content + outubro).split('\n').length);
