const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'src/data/devocionalConfessional.ts');

let content = fs.readFileSync(filePath, 'utf8');

// Corrigir temas dos meses no metadata
content = content.replace(
  `{ mes: 9, nome: 'Setembro',   temaGeral: 'Igreja, Comunhão dos Santos e Sacramentos — Batista 1689 Cap. XXV–XXIX' }`,
  `{ mes: 9, nome: 'Setembro',   artigos: 'CFW 14.1  →  CFW Cap. XIV–XX (síntese)', temaGeral: 'A fé salvadora recebe Cristo em todas as suas obras; o arrependimento genuíno acompanha toda conversão; as boas obras são fruto — não raiz — da salvação; os santos perseveram porque Deus os guarda; a certeza da graça é privilégio bíblico; a lei moral guia o crente; e a liberdade cristã liberta da culpa sem abolir a obediência — Westminster Cap. XIV–XX.' }`
);
content = content.replace(
  `{ mes: 10, nome: 'Outubro',   temaGeral: 'Escrituras, Trindade e Decretos — Westminster Cap. I–VII' }`,
  `{ mes: 10, nome: 'Outubro',   artigos: 'CFW 21.1  →  CFW Cap. XXI–XXV (síntese)', temaGeral: 'O culto religioso deve ser regulado pela Palavra de Deus; o dia do Senhor é sábado cristão de descanso e adoração; juramentos e votos são vinculantes diante de Deus; o magistrado civil é ordenança divina; e o casamento é aliança entre um homem e uma mulher — Westminster Cap. XXI–XXV.' }`
);
content = content.replace(
  `{ mes: 11, nome: 'Novembro',  temaGeral: 'Mediador, Chamado, Justificação e Fé — Westminster Cap. VIII–XIV' }`,
  `{ mes: 11, nome: 'Novembro',  artigos: 'CFW 26.1  →  CFW Cap. XXVI–XXIX (síntese)', temaGeral: 'A comunhão dos santos é participação real em Cristo e uns nos outros; a ceia do Senhor é memorial do sacrifício único de Cristo e antecipação escatológica; o batismo é sinal e selo da aliança da graça; e concílios eclesiásticos têm autoridade delegada, não absoluta — Westminster Cap. XXVI–XXIX.' }`
);
content = content.replace(
  `{ mes: 12, nome: 'Dezembro',  temaGeral: 'Arrependimento, Igreja, Sacramentos e Estado Final — Westminster Cap. XV–XXXIII' }`,
  `{ mes: 12, nome: 'Dezembro',  artigos: 'CFW 30.1  →  CFW Cap. XXX–XXXIII (síntese)', temaGeral: 'A disciplina eclesiástica é expressão do amor pastoral de Cristo por sua Igreja; sínodos e concílios servem ao governo eclesiástico ordenado; o estado do homem após a morte aguarda a ressurreição; e no último dia Cristo julgará vivos e mortos — consumando a redenção e a glória eterna do seu povo — Westminster Cap. XXX–XXXIII.' }`
);

// Remover a função gerarDiasSetembro errada e substituir
const startMarker = '\nfunction gerarDiasSetembro(): DiaConfessional[] {';
const idx = content.indexOf(startMarker);
if (idx === -1) { console.error('ERRO: função não encontrada'); process.exit(1); }

// Manter tudo antes da função
const before = content.substring(0, idx);

const newFn = `
function gerarDiasSetembro(): DiaConfessional[] {
  const dias: DiaCompacto[] = [
    {
      dia: 244, data: '1 de setembro', tema: 'A Fé Salvadora: Dom de Deus que Recebe Cristo',
      capitulo: 'CFW Cap. XIV.1', versiculo: 'Efésios 2.8',
      versiculoTexto: 'Porque pela graça sois salvos, por meio da fé; e isto não vem de vós; é dom de Deus.',
      confissaoTexto: 'A graça de fé, pela qual os eleitos são habilitados a crer para a salvação de suas almas, é obra do Espírito de Cristo em seus corações, e é ordinariamente operada pelo ministério da Palavra.',
      cfwRef: 'CFW XIV.1', cfwComparacao: 'CB 1689 Cap. XIV.1 usa linguagem quase idêntica — ambas enfatizam a fé como dom do Espírito, não conquista humana.',
      exposicao: 'Ef 2.8 é estruturalmente preciso: a salvação é pela graça, através da fé — e "isto" (todo o conjunto: graça + fé) não vem de vós, é dom de Deus. A Westminster detalha: a fé salvadora é obra do Espírito de Cristo no coração, operada ordinariamente pelo ministério da Palavra. Fé não é esforço heroico — é recepção habilitada pelo Espírito. Essa distinção protege tanto da auto-confiança (fé como mérito) quanto do fatalismo (se é dom, não preciso crer).',
      reforco: 'A fé é dom — mas dom que se exerce ativamente. Deus dá a fé e a pessoa crê. Os dois são verdadeiros e inseparáveis.',
      aplicacoes: {
        digital: 'Leia Ef 2.1-10. Medite: "Minha fé é confiança ativa em Cristo ou sentimento religioso flutuante?"',
        familia: 'Conversem: "Como sabemos que nossa fé é salvadora — não apenas crença intelectual ou herança familiar?"',
        filhos: 'Ensine: "Fé não é fingir que acredita. É confiar de verdade em Jesus como seu Salvador."',
        homens: 'O homem que entende a fé como dom exercido ativamente não oscila entre auto-suficiência e passividade espiritual.',
        mulheres: 'A mulher que descansa na fé como dom do Espírito — não como conquista própria — tem paz que não depende de desempenho religioso.',
        igreja: 'A congregação que prega a fé como dom do Espírito operado pela Palavra valoriza o ministério da pregação como meio de graça.',
      },
      oracao: 'Senhor, obrigado pela fé que tu mesmo produziste em mim. Que setembro me aprofunde na compreensão desta graça — para que creia mais plenamente em Cristo como meu único fundamento. Amém.',
      reflexao: 'Sua fé está ancorada em Cristo e sua obra, ou oscila conforme seu desempenho espiritual do dia?',
      aplicacao: 'Leia CFW XIV completo. Escreva a diferença entre fé como dom e fé como mérito — e como isso muda sua vida prática.',
      notas: [
        'LLOYD-JONES, D. Martyn. <em>Faith on Trial</em>. Grand Rapids: Baker, 1965. O estudo mais vivo e penetrante da fé salvadora na tradição reformada.',
      ],
      notaInicio: 1,
    },
    {
      dia: 245, data: '2 de setembro', tema: 'Fé que Age: Recebendo e Repousando em Cristo',
      capitulo: 'CFW Cap. XIV.2', versiculo: 'João 1.12',
      versiculoTexto: 'Mas, a todos quantos o receberam, deu-lhes o poder de serem feitos filhos de Deus, a saber, aos que creem no seu nome.',
      confissaoTexto: 'Por esta fé, o cristão crê ser verdadeiro tudo o que é revelado na Palavra, por causa da autoridade de Deus que fala nela; e age diversamente segundo o conteúdo de cada porção particular — obedecendo aos mandamentos, tremendo às ameaças, abraçando as promessas de Deus para esta vida e para a vindoura. Mas os atos principais desta fé são: receber, repouser e apoiar-se em Cristo somente para justificação, santificação e vida eterna.',
      cfwRef: 'CFW XIV.2', cfwComparacao: 'CB 1689 Cap. XIV.2 é paralelo — ambas definem fé como recepção ativa de Cristo, não mera concordância intelectual.',
      exposicao: 'Jo 1.12 usa dois verbos paralelos: "receber" e "crer" — são sinônimos complementares. A fé salvadora não é apenas assentir que Cristo existe, mas recebê-lo ativamente: repouser nele, apoiar-se nele para justificação, santificação e vida eterna. CFW XIV.2 detalha que a fé age diferentemente conforme o texto: obedece mandamentos, treme às ameaças, abraça promessas. Fé não é passividade religiosa — é engajamento ativo com toda a Palavra de Deus.',
      reforco: 'A fé que salva não é apenas conhecer sobre Cristo — é recebê-lo, repouser nele e apoiar-se nele como único fundamento.',
      aplicacoes: {
        digital: 'Leia Jo 1.9-13. Medite: "Você recebeu Cristo — ou apenas sabe sobre ele?"',
        familia: 'Conversem: "Como a fé se expressa de forma diferente diante de mandamentos, ameaças e promessas da Escritura?"',
        filhos: 'Pergunte: "Você confia em Jesus como um amigo que nunca falha — ou só acredita que ele existiu?"',
        homens: 'O homem que repousa em Cristo — não em sua própria espiritualidade — tem fundamento que não range nas tempestades.',
        mulheres: 'A mulher que apoia-se em Cristo para justificação não carrega o peso de ter que se justificar diante de Deus ou das pessoas.',
        igreja: 'A congregação que prega Cristo como objeto da fé — não a fé como virtude em si mesma — mantém o Evangelho no centro.',
      },
      oracao: 'Senhor Jesus, que eu te receba cada dia — não apenas como doutrina, mas como Pessoa. Que minha fé seja descanso real em ti, não desempenho religioso para impressionar a mim mesmo. Amém.',
      reflexao: 'Você descansa em Cristo ou em sua própria fé? Há diferença — e ela é crucial.',
      aplicacao: 'Ore intencionalmente usando os três atos de CFW XIV.2: receba Cristo em oração, repouste nele, apóie-se nele para um desafio específico desta semana.',
      notas: [
        'HORTON, Michael. <em>Pilgrim Theology</em>. Grand Rapids: Zondervan, 2011. Cap. sobre a fé — a distinção entre fé como instrumento e fé como mérito.',
      ],
      notaInicio: 18,
    },
    {
      dia: 246, data: '3 de setembro', tema: 'Fé Fraca e Fé Plena: A Mesma Graça em Graus',
      capitulo: 'CFW Cap. XIV.3', versiculo: 'Marcos 9.24',
      versiculoTexto: 'E logo o pai do menino, clamando com lágrimas, disse: Creio, Senhor! Ajuda a minha incredulidade.',
      confissaoTexto: 'Esta fé, ainda que em diferentes pessoas seja diferente em graus, seja fraca ou forte, contudo é em sua espécie, sendo fraca, o mesmo princípio salvador, e triunfa eventualmente sobre a incredulidade.',
      cfwRef: 'CFW XIV.3', cfwComparacao: 'CB 1689 Cap. XIV.3 é paralelo — fé fraca ainda é fé salvadora; o objeto (Cristo) não muda conforme a intensidade da fé.',
      exposicao: 'Marcos 9.24 é a oração mais honesta do NT: "Creio! Ajuda minha incredulidade." O pai crê — e reconhece que sua fé é mista com dúvida. CFW XIV.3 valida essa experiência: fé fraca ainda é fé salvadora. O que salva não é a intensidade da fé, mas o objeto da fé — Cristo. Fé como grão de mostarda (Mt 17.20) move montanhas não porque é grande, mas porque Cristo é grande. A dúvida que luta para crer é diferente da incredulidade que recusa crer.',
      reforco: 'Fé fraca em Cristo salva mais do que fé forte em si mesmo. O que importa não é a intensidade, mas o objeto.',
      aplicacoes: {
        digital: 'Leia Mc 9.14-29. Medite: "Você ora como o pai — honestamente sobre suas dúvidas — ou esconde a incredulidade por vergonha?"',
        familia: 'Conversem sobre momentos em que a fé de cada um foi fraca. Como Cristo sustentou mesmo nessa fraqueza?',
        filhos: 'Ensine: "Não precisa ter fé perfeita. Deus usa até a fé pequena — o que importa é confiar em Jesus."',
        homens: 'O homem que admite sua fé fraca diante de Deus — como o pai de Marcos 9 — está mais próximo de Cristo do que o que finge fé perfeita.',
        mulheres: 'A mulher que luta com dúvidas e continua orando tem fé viva — a luta mesma é evidência de fé genuína.',
        igreja: 'A congregação que acolhe os que duvidam — em vez de exigir performance de certeza — reflete a graça de Cristo ao pai de Marcos 9.',
      },
      oracao: 'Senhor, creio — ajuda minha incredulidade. Que minha fé fraca encontre em ti um Salvador forte. Que setembro fortaleça o que é fraco em minha confiança em ti. Amém.',
      reflexao: 'Você se envergonha da sua fé fraca ou traz essa fraqueza honestamente a Cristo? A diferença determina se você encontrará ajuda ou fingirá que não precisa.',
      aplicacao: 'Identifique uma área onde sua fé está fraca. Ore a oração de Marcos 9.24 sobre essa área específica — honestamente, sem performance.',
      notas: [
        'SPURGEON, C.H. <em>Faith\'s Checkbook</em>. Chicago: Moody, 1987. Devocionais diários sobre fé — acessíveis e profundos para fortalecer a fé fraca.',
      ],
      notaInicio: 35,
    },
    {
      dia: 247, data: '4 de setembro', tema: 'Arrependimento: Dom que Acompanha a Fé',
      capitulo: 'CFW Cap. XV.1–2', versiculo: 'Atos 11.18',
      versiculoTexto: 'Tendo ouvido isto, tranquilizaram-se e glorificaram a Deus, dizendo: Logo, também aos gentios concedeu Deus o arrependimento para a vida.',
      confissaoTexto: 'O arrependimento para a vida é graça evangélica, cuja doutrina deve ser pregada por todo ministro do Evangelho tão bem como a da fé em Cristo.',
      cfwRef: 'CFW XV.1', cfwComparacao: 'CB 1689 Cap. XV.1 é paralelo — arrependimento é graça evangélica, não obra meritória que precede a graça.',
      exposicao: 'At 11.18 revela que o arrependimento é "concedido" por Deus — não produzido pelo esforço humano. CFW XV.1 o chama de "graça evangélica" — não é pré-condição para o Evangelho, mas fruto do Evangelho. Fé e arrependimento são inseparáveis: não pode haver conversão genuína sem ambos. Mas o arrependimento correto não é autopunição — é mudança de mente sobre o pecado, sobre si mesmo e sobre Cristo, que produz mudança de direção.',
      reforco: 'Arrependimento sem fé é desespero. Fé sem arrependimento é ilusão. Os dois são simultâneos na conversão genuína.',
      aplicacoes: {
        digital: 'Leia At 11.15-18. Medite: "Meu arrependimento é graça evangélica — ou ainda confundo com autopunição religiosa?"',
        familia: 'Conversem: "Como o arrependimento genuíno se parece na vida prática — diferente de apenas sentir-se mal com o pecado?"',
        filhos: 'Ensine: "Arrepender não é só ficar triste. É mudar de direção — sair do caminho errado e ir para o certo."',
        homens: 'O homem que distingue arrependimento genuíno (mudança de mente e direção) de culpa religiosa (autopunição) cresce em liberdade espiritual.',
        mulheres: 'A mulher que entende o arrependimento como graça — não como punição — confessa o pecado com esperança, não com desespero.',
        igreja: 'A congregação que prega o arrependimento como graça evangélica — parte do Evangelho, não antessala do Evangelho — mantém a mensagem equilibrada.',
      },
      oracao: 'Senhor, concede-me arrependimento genuíno — não autopunição religiosa, mas mudança real de mente e coração. Que eu me arrependa para a vida, não para o desespero. Amém.',
      reflexao: 'Seu arrependimento leva a Cristo (graça evangélica) ou a si mesmo (autopunição)? A diferença é entre esperança e desespero.',
      aplicacao: 'Leia CFW XV completo. Identifique a diferença entre arrependimento legal (medo do inferno) e arrependimento evangélico (desgosto do pecado, amor a Cristo).',
      notas: [
        'BOSTON, Thomas. <em>Human Nature in Its Fourfold State</em>. Edinburgh: Banner of Truth, 1964. Cap. sobre arrependimento — o clássico puritano mais completo.',
      ],
      notaInicio: 52,
    },
    {
      dia: 248, data: '5 de setembro', tema: 'Arrependimento Genuíno: Natureza e Expressão',
      capitulo: 'CFW Cap. XV.2–3', versiculo: '2 Coríntios 7.10',
      versiculoTexto: 'Porque a tristeza segundo Deus produz arrependimento para a salvação, sem deixar remorso; mas a tristeza do mundo produz morte.',
      confissaoTexto: 'O pecador, pelo arrependimento, vem a ter um senso de manifold evil do seu pecado, humilhação e desgosto por ele, com esperança da misericórdia de Deus em Cristo, de tal forma que vira de seu pecado para Deus com pleno propósito e esforço de nova obediência.',
      cfwRef: 'CFW XV.2', cfwComparacao: 'CB 1689 Cap. XV.2 é quase idêntico — o arrependimento genuíno envolve desgosto do pecado, esperança em Cristo e novo propósito de obediência.',
      exposicao: '2Co 7.10 distingue dois tipos de tristeza: a tristeza segundo Deus (que produz arrependimento para a salvação) e a tristeza do mundo (que produz morte — como Judas, que teve remorso mas não fé). CFW XV.2 detalha o arrependimento genuíno: (1) senso da maldade do pecado; (2) humilhação e desgosto; (3) esperança na misericórdia divina em Cristo; (4) virada do pecado para Deus com propósito de nova obediência. Sem o item 3 (esperança em Cristo), o arrependimento vira desespero.',
      reforco: 'Arrependimento genuíno tem quatro elementos: ver o pecado, detestar o pecado, esperar em Cristo, voltar-se para Deus. Nenhum pode faltar.',
      aplicacoes: {
        digital: 'Leia 2Co 7.8-11. Medite: "Sua tristeza pelo pecado é segundo Deus (leva a Cristo) ou tristeza do mundo (leva ao remorso)?',
        familia: 'Conversem: "Como ensinamos nossos filhos a se arrependerem genuinamente — sem apenas pedir desculpa por pressão?"',
        filhos: 'Ensine os 4 elementos do arrependimento de forma simples: ver, detestar, esperar em Jesus, mudar de direção.',
        homens: 'O homem que pratica arrependimento genuíno não fica preso no ciclo de pecado-remorso-esforço — mas no ciclo de pecado-desgosto-Cristo-nova obediência.',
        mulheres: 'A mulher que tem esperança na misericórdia de Deus como parte do arrependimento não se afoga no auto-julgamento após o pecado.',
        igreja: 'A congregação que inclui confissão genuína e assurance do perdão no culto pratica liturgia de arrependimento saudável.',
      },
      oracao: 'Senhor, que meu arrependimento seja segundo tua graça — não remorso estéril, mas desgosto genuíno do pecado e esperança renovada em Cristo. Que a tristeza santa me leve sempre a ti, nunca para dentro de mim mesmo. Amém.',
      reflexao: 'Após pecar, você vai a Cristo com esperança ou se afoga em remorso? A diferença revela se você entende o Evangelho.',
      aplicacao: 'Da próxima vez que pecar, pratique os 4 elementos de CFW XV.2 conscientemente: reconheça, deteste, espere em Cristo, proponha mudança.',
      notas: [
        'WATSON, Thomas. <em>The Doctrine of Repentance</em>. Edinburgh: Banner of Truth, 1987. O tratado puritano mais completo e prático sobre o arrependimento genuíno.',
      ],
      notaInicio: 69,
    },
    {
      dia: 249, data: '6 de setembro', tema: 'Nenhum Pecado Além do Perdão',
      capitulo: 'CFW Cap. XV.4–5', versiculo: 'Isaías 55.7',
      versiculoTexto: 'Deixe o ímpio o seu caminho, e o homem iniquo os seus pensamentos, e se converta para o Senhor, e ele se compadecerá dele; e para o nosso Deus, porque é abundante em perdoar.',
      confissaoTexto: 'Como não há pecado tão pequeno que não mereça condenação, assim também não há pecado tão grande que possa trazer condenação sobre os que verdadeiramente se arrependem.',
      cfwRef: 'CFW XV.4', cfwComparacao: 'CB 1689 Cap. XV.4 é idêntico — a extensão do perdão é proporcional à graça de Deus, não ao tamanho do pecado.',
      exposicao: 'Is 55.7 apresenta a lógica da graça: o ímpio que se converte ao Senhor encontra compaixão — porque Deus "é abundante em perdoar." CFW XV.4 é duplamente consolador: nenhum pecado é pequeno o suficiente para não precisar de perdão; nenhum pecado é grande o suficiente para impossibilitar o perdão para quem genuinamente se arrepende. A barreira para o perdão nunca é o tamanho do pecado — é a dureza do coração que recusa o arrependimento.',
      reforco: 'O que impede o perdão não é a gravidade do pecado — é a ausência de arrependimento. Para quem se arrepende, nenhum pecado está além da graça.',
      aplicacoes: {
        digital: 'Leia Is 55.6-9. Medite: "Há algum pecado em sua vida sobre o qual você duvida do perdão divino? Por quê?"',
        familia: 'Conversem: "Como respondemos quando alguém diz que seu pecado é grande demais para ser perdoado? O que a Escritura diz?"',
        filhos: 'Ensine: "Não existe pecado grande demais para Jesus perdoar. Ele perdoou Pedro, Paulo e pode te perdoar também."',
        homens: 'O homem que carrega culpa de pecados passados crendo serem imperdoáveis está duvidando do Evangelho — não apenas de si mesmo.',
        mulheres: 'A mulher que recebe a assurance do perdão — mesmo depois de pecados graves — vive com libertade que testemunha da graça.',
        igreja: 'A congregação que prega o alcance irrestrito do perdão para os que se arrependem é refúgio para os que carregam pesada culpa.',
      },
      oracao: 'Senhor abundante em perdoar — recebo tua graça hoje. Que nenhum pecado passado ou presente me mantenha distante de ti. Tua abundância supera minha falha. Amém.',
      reflexao: 'Há pecado específico sobre o qual você ainda duvida do perdão de Deus? Qual promessa da Escritura responde a essa dúvida?',
      aplicacao: 'Liste os pecados sobre os quais você carrega culpa persistente. Aplique Is 55.7 e 1Jo 1.9 a cada um. Ore recebendo o perdão que Cristo comprou.',
      notas: [
        'BRIDGES, Jerry. <em>Respectable Sins</em>. Colorado Springs: NavPress, 2007. Sobre pecados que tendemos a minimizar — e o perdão que os cobre todos.',
      ],
      notaInicio: 86,
    },
    {
      dia: 250, data: '7 de setembro', tema: 'Arrependimento Específico: Pecados Particulares',
      capitulo: 'CFW Cap. XV.5–6', versiculo: 'Salmo 51.4',
      versiculoTexto: 'Contra ti, somente contra ti, pequei, e fiz o mal diante dos teus olhos; para que sejas reconhecido justo quando falares, e puro quando julgares.',
      confissaoTexto: 'É dever de todo homem confessar seus pecados particulares privatamente a Deus, e orar pelo perdão dos mesmos; ao confessar pecado particular a um irmão ofendido, ou em assembléia pública, juntamente com a abstenção daquele pecado.',
      cfwRef: 'CFW XV.5', cfwComparacao: 'CB 1689 Cap. XV.5 é paralelo — confissão privada a Deus, reconciliação com o ofendido, mas não confissão auricular obrigatória (contra Roma).',
      exposicao: 'Salmo 51 é o modelo do arrependimento específico: Davi não confessa "pecado em geral" — confessa o pecado específico de Bate-Seba. CFW XV.5 estrutura o arrependimento em três dimensões: (1) confissão privada a Deus — sempre; (2) confissão ao irmão ofendido — quando há ofensa interpessoal; (3) confissão pública — quando o pecado escandalizou a congregação. Nenhuma dessas dimensões é a confissão auricular obrigatória de Roma — o perdão vem de Deus, não do confessor.',
      reforco: 'Confissão genérica ("sou pecador") sem confissão específica é frequentemente desonestidade espiritual disfarçada de humildade.',
      aplicacoes: {
        digital: 'Leia Sl 51 completo. Medite: "Minha confissão a Deus é específica como a de Davi — ou vaga e genérica?"',
        familia: 'Conversem sobre a diferença entre pedir desculpa social e confessar pecado genuinamente. Como as duas se parecem?',
        filhos: 'Pratique com as crianças confessar pecados específicos — não apenas "perdão por tudo que fiz de errado."',
        homens: 'O homem que confessa pecados específicos a Deus — e quando necessário, ao ofendido — demonstra maturidade espiritual.',
        mulheres: 'A mulher que pratica confissão específica e regular a Deus mantém o coração limpo e o relacionamento com Deus vivo.',
        igreja: 'A congregação que inclui momento de confissão específica no culto — seguida de assurance do perdão — pratica liturgia transformadora.',
      },
      oracao: 'Senhor, que minha confissão seja honesta e específica — como a de Davi. Que eu não me esconda atrás de generalidades piedosas, mas traga à luz o que está nas sombras. Tua misericórdia supera minha vergonha. Amém.',
      reflexao: 'Quando foi a última vez que você confessou pecado específico a Deus — não apenas pediu perdão genérico? Qual é a diferença na sua experiência?',
      aplicacao: 'Reserve 15 minutos hoje para confissão específica a Deus. Use Sl 51 como modelo. Se há irmão ofendido, dê o primeiro passo na reconciliação.',
      notas: [
        'CALVIN, John. <em>Institutes of the Christian Religion</em>. III.4. Grand Rapids: Eerdmans, 1960. A rejeição mais clara da confissão auricular romana e a defesa da confissão a Deus.',
      ],
      notaInicio: 103,
    },
    {
      dia: 251, data: '8 de setembro', tema: 'Boas Obras: Fruto, Não Raiz',
      capitulo: 'CFW Cap. XVI.1–2', versiculo: 'Efésios 2.10',
      versiculoTexto: 'Porque somos feitura sua, criados em Cristo Jesus para as boas obras, as quais Deus preparou para que andássemos nelas.',
      confissaoTexto: 'Boas obras são somente as que Deus ordenou em sua Santa Palavra, e não as que homens inventaram segundo sua própria imaginação, devoção cega ou boas intenções.',
      cfwRef: 'CFW XVI.1', cfwComparacao: 'CB 1689 Cap. XVI.1 é paralelo — boas obras definidas pela Palavra de Deus, não pela inventividade humana.',
      exposicao: 'Ef 2.10 revela a sequência correta: somos salvos pela graça (v.8-9), PARA as boas obras (v.10). As obras são consequência da salvação, não sua causa. CFW XVI.1 acrescenta definição crucial: boas obras são as que Deus ordenou na Palavra — não as que o homem inventa por devoção, tradição ou boas intenções. Isso tem implicações práticas: o que Deus não ordenou não é "boa obra" apenas porque parece piedoso.',
      reforco: 'Boas obras são: (1) ordenadas por Deus na Palavra; (2) fruto da salvação, não sua raiz; (3) para a glória de Deus, não para mérito próprio.',
      aplicacoes: {
        digital: 'Leia Ef 2.8-10. Medite: "As boas obras que pratico estão enraizadas no que Deus ordenou ou no que parece piedoso para mim?"',
        familia: 'Conversem: "Como distinguimos obras que Deus ordenou de obras que inventamos por tradição ou costume religioso?"',
        filhos: 'Ensine: "Fazemos boas obras porque amamos Jesus — não para ganhar o céu. Jesus já ganhou o céu para nós."',
        homens: 'O homem que entende as boas obras como fruto da salvação serve com alegria — não com ansiedade de ter que merecer algo.',
        mulheres: 'A mulher que age por amor a Cristo — não por obrigação religiosa — experimenta o serviço como expressão de identidade, não como fardo.',
        igreja: 'A congregação que ensina boas obras como fruto da salvação e as define pela Palavra evita tanto o legalismo quanto o antinomismo.',
      },
      oracao: 'Senhor, que minhas obras sejam fruto genuíno de tua graça em mim — não esforço para me justificar. Que eu ande nas boas obras que preparaste, não nas que invento por piedade própria. Amém.',
      reflexao: 'Suas boas obras estão enraizadas na gratidão pela salvação ou ainda carregam peso de tentar merecer aprovação de Deus?',
      aplicacao: 'Liste três obras que você pratica regularmente. Avalie: são ordenadas por Deus na Palavra? São fruto de gratidão ou tentativa de mérito?',
      notas: [
        'PIPER, John. <em>Future Grace</em>. Sisters: Multnomah, 1995. A teologia das boas obras motivadas pela fé na graça futura — não pelo medo ou pelo mérito.',
      ],
      notaInicio: 120,
    },
    {
      dia: 252, data: '9 de setembro', tema: 'Boas Obras e a Glória de Deus',
      capitulo: 'CFW Cap. XVI.2–3', versiculo: 'Mateus 5.16',
      versiculoTexto: 'Assim brilhe a vossa luz diante dos homens, para que vejam as vossas boas obras e glorifiquem a vosso Pai que está nos céus.',
      confissaoTexto: 'Fazendo boas obras, os crentes fortalecem sua assurance, edificam seus irmãos, adornam a profissão do Evangelho, tapam a boca dos adversários e glorificam a Deus.',
      cfwRef: 'CFW XVI.2', cfwComparacao: 'CB 1689 Cap. XVI.2 lista os mesmos propósitos das boas obras — especialmente a glorificação de Deus como fim último.',
      exposicao: 'Mt 5.16 revela o propósito final das boas obras: que os homens glorifiquem o Pai. As obras dos crentes são testemunho do Evangelho — não publicidade pessoal. CFW XVI.2 lista cinco frutos das boas obras: (1) fortalecem a assurance do próprio crente; (2) edificam os irmãos; (3) adornam o Evangelho; (4) silenciam os críticos; (5) glorificam a Deus. Quando as obras visam qualquer outro fim — reconhecimento, admiração, compensação — desviam do propósito.',
      reforco: 'Boas obras que buscam atenção humana são publicidade pessoal. Boas obras que escondem o agente para destacar Deus são adoração.',
      aplicacoes: {
        digital: 'Leia Mt 5.14-16. Medite: "Minhas boas obras levam as pessoas a glorificar a mim ou a Deus?"',
        familia: 'Conversem: "Como nossa família pode servir de forma que testemunhe do Evangelho — não apenas de nossa bondade?"',
        filhos: 'Ensine: "Quando você ajuda alguém, diga que faz porque Jesus te amou primeiro. Não fique esperando elogio."',
        homens: 'O homem que serve sem buscar reconhecimento — de forma que Cristo seja exaltado — lidera pelo exemplo do Servo-Rei.',
        mulheres: 'A mulher que serve em silêncio, sem publicidade, adora a Deus com as mãos — mesmo quando ninguém vê.',
        igreja: 'A congregação que serve a comunidade de forma que o Evangelho seja adorado — não apenas a Igreja seja elogiada — cumpre Mt 5.16.',
      },
      oracao: 'Senhor, que minhas obras luzam — mas que a luz aponte para ti, não para mim. Que cada ato de serviço seja ato de adoração que leva outros a glorificar teu nome. Amém.',
      reflexao: 'Quando você serve, fica esperando reconhecimento? O que isso revela sobre o verdadeiro motivo do seu serviço?',
      aplicacao: 'Esta semana, pratique um ato de serviço completamente anônimo — onde apenas Deus sabe. Observe o que acontece no seu coração.',
      notas: [
        'KELLER, Timothy. <em>Generous Justice</em>. New York: Dutton, 2010. Boas obras como expressão do Evangelho na comunidade — prático e teologicamente fundamentado.',
      ],
      notaInicio: 137,
    },
    {
      dia: 253, data: '10 de setembro', tema: 'Boas Obras Não Merecem Salvação',
      capitulo: 'CFW Cap. XVI.5–6', versiculo: 'Lucas 17.10',
      versiculoTexto: 'Assim também vós, quando tiverdes feito tudo o que vos foi ordenado, dizei: Somos servos inúteis; fizemos somente o que éramos obrigados a fazer.',
      confissaoTexto: 'Não podemos pelas nossas melhores obras merecer o perdão dos pecados ou a vida eterna da mão de Deus, por causa da grande desproporção que há entre elas e a glória que há de vir; e por causa do infinito espaço que há entre nós e Deus.',
      cfwRef: 'CFW XVI.5', cfwComparacao: 'CB 1689 Cap. XVI.5 é idêntico — nenhuma obra humana, mesmo as dos crentes regenerados, pode merecer diante de Deus.',
      exposicao: 'Lc 17.10 é desconcertante: mesmo depois de obedecer a tudo, somos "servos inúteis." CFW XVI.5 explica o porquê: há desproporção infinita entre qualquer obra humana e a glória de Deus, e entre a criatura finita e o Criador infinito. Isso não deprecia as boas obras — elas têm valor real. Mas value não é mérito. As obras dos crentes são aceitas por Deus em Cristo — não por seu próprio peso. O fundamento sempre é Cristo, não nossa obediência.',
      reforco: 'As obras dos crentes são aceitas em Cristo — não por mérito próprio. Isso liberta do perfeccionismo e da auto-justificação.',
      aplicacoes: {
        digital: 'Leia Lc 17.7-10. Medite: "Você ainda espera que suas boas obras criem crédito com Deus? Como Lc 17.10 corrige isso?"',
        familia: 'Conversem: "Por que não podemos merecer o céu — mesmo com muitas boas obras? O que isso ensina sobre a graça?"',
        filhos: 'Ensine: "Mesmo que você fizesse tudo certo, ainda precisaria de Jesus. Ninguém é bom o suficiente — só Jesus é."',
        homens: 'O homem que entende que suas obras são aceitas em Cristo — não por seu próprio mérito — serve com paz, sem peso de performance.',
        mulheres: 'A mulher que descansa na aceitação em Cristo — não no desempenho de suas obras — é liberta do perfeccionismo paralisante.',
        igreja: 'A congregação que prega a aceitação em Cristo — não pelo historial de obras — forma membros sem culpa crônica e sem orgulho religioso.',
      },
      oracao: 'Senhor, que eu sirva como servo grato — não como empregado tentando pagar uma dívida. Toda aceitação que tenho é em Cristo, não em mim. Que sirva com alegria, não com ansiedade de merecer. Amém.',
      reflexao: 'Você serve esperando que Deus "deva" bênçãos em troca? Isso é teologia de mérito — incompatível com o Evangelho.',
      aplicacao: 'Ore Lc 17.10 como oração de humildade: "Sou servo inútil — fiz apenas o que era minha obrigação. Toda aceitação é em Cristo." Ore isso até que seja libertador, não deprimente.',
      notas: [
        'BUCHANAN, James. <em>The Doctrine of Justification</em>. Edinburgh: Banner of Truth, 1961. A distinção mais clara entre aceitação pela fé e tentativa de mérito pelas obras.',
      ],
      notaInicio: 154,
    },
    {
      dia: 254, data: '11 de setembro', tema: 'Perseverança dos Santos: Deus Guarda os Seus',
      capitulo: 'CFW Cap. XVII.1', versiculo: 'João 10.28-29',
      versiculoTexto: 'E dou-lhes a vida eterna, e nunca hão de perecer, e ninguém as arrebatará da minha mão. Meu Pai, que mas deu, é maior do que todos; e ninguém pode arrebatá-las da mão de meu Pai.',
      confissaoTexto: 'Os que Deus aceitou em seu Amado, eficazmente chamados e santificados pelo seu Espírito, não podem nem cair totalmente nem cair definitivamente da graça; mas certamente perseverarão na graça até o fim e serão salvos eternamente.',
      cfwRef: 'CFW XVII.1', cfwComparacao: 'CB 1689 Cap. XVII.1 é idêntico — perseverança dos santos é garantia de Deus, não desempenho humano. Ambas rejeitam a apostasia dos eleitos.',
      exposicao: 'Jo 10.28-29 apresenta dupla segurança: ninguém arranca da mão do Filho; ninguém arranca da mão do Pai. CFW XVII.1 é claro: os que Deus aceitou em Cristo, chamou e santificou não podem cair totalmente nem definitivamente. Isso não é licença para o pecado — é fundamento para a segurança espiritual. A perseverança não depende da força do crente, mas da fidelidade de Deus que prometeu guardar seus filhos. O crente persevera porque Deus preserva.',
      reforco: 'Perseverança é garantia de Deus, não conquista humana. O crente persevera porque Deus o preserva — não o contrário.',
      aplicacoes: {
        digital: 'Leia Jo 10.27-30. Medite: "Sua segurança espiritual está na sua força de agarrar a Deus ou na força de Deus que te segura?"',
        familia: 'Conversem: "Como a doutrina da perseverança dos santos afeta nossa paz em momentos de fraqueza espiritual?"',
        filhos: 'Ensine: "Uma vez que você pertence a Jesus, ele nunca te solta. Ele é mais forte do que o diabo e mais fiel do que nós."',
        homens: 'O homem que descansa na preservação de Deus — não em sua própria consistência — tem paz que sobrevive às suas próprias falhas.',
        mulheres: 'A mulher que sabe que Deus a guarda — mesmo em seus piores dias — tem segurança que o mundo e o diabo não podem tirar.',
        igreja: 'A congregação que prega perseverança como obra de Deus — não obra do crente — liberta da ansiedade espiritual e do perfeccionismo.',
      },
      oracao: 'Pai, obrigado por segurar minha mão quando minhas forças falham. Minha segurança não é minha fidelidade — é tua. Que setembro me aprofunde nessa paz que o mundo não pode dar nem tirar. Amém.',
      reflexao: 'Sua paz espiritual depende do quanto você está indo bem espiritualmente, ou da fidelidade de Deus que prometeu guardar seus filhos?',
      aplicacao: 'Leia CFW XVII.1 e Jo 10.27-30 em voz alta. Ore agradecendo pela segurança que não depende do seu desempenho.',
      notas: [
        'SCHREINER, Thomas e WARE, Bruce (eds.). <em>Still Sovereign</em>. Grand Rapids: Baker, 2000. A defesa exegética e teológica mais completa da perseverança dos santos.',
      ],
      notaInicio: 171,
    },
    {
      dia: 255, data: '12 de setembro', tema: 'Perseverança: Fundamentos na Eleição e na Obra de Cristo',
      capitulo: 'CFW Cap. XVII.2', versiculo: 'Romanos 8.38-39',
      versiculoTexto: 'Porque estou certo de que nem a morte, nem a vida, nem os anjos, nem os principados, nem as potestades, nem o presente, nem o porvir, nem a altura, nem a profundidade, nem alguma outra criatura nos poderá separar do amor de Deus, que está em Cristo Jesus nosso Senhor.',
      confissaoTexto: 'Esta perseverança dos santos não depende do livre-arbítrio deles, mas da imutabilidade do decreto de eleição, procedendo do amor livre e imutável de Deus Pai; da eficácia do mérito e intercessão de Jesus Cristo; e da habitação do Espírito Santo.',
      cfwRef: 'CFW XVII.2', cfwComparacao: 'CB 1689 Cap. XVII.2 lista os mesmos fundamentos trinitários da perseverança — eleição do Pai, mérito e intercessão do Filho, habitação do Espírito.',
      exposicao: 'Rm 8.38-39 é o pico da argumentação de Paulo: nada pode separar o crente do amor de Deus em Cristo. CFW XVII.2 analisa os três fundamentos trinitários dessa garantia: (1) o decreto imutável do Pai que elegeu; (2) o mérito e a intercessão contínua do Filho que nunca falha (Hb 7.25); (3) a habitação permanente do Espírito Santo. A perseverança está fundada na Trindade — não na força de vontade do crente.',
      reforco: 'Três fundamentos inabaláveis garantem a perseverança: o decreto do Pai, a intercessão do Filho, a habitação do Espírito. A fraqueza do crente não os cancela.',
      aplicacoes: {
        digital: 'Leia Rm 8.31-39. Medite: "Qual das três fundações trinitárias da perseverança te dá mais paz hoje?"',
        familia: 'Conversem: "Se a perseverança não depende do nosso livre-arbítrio, isso nos torna descuidados com a santidade? Por quê não?"',
        filhos: 'Ensine: "Jesus está orando por você agora mesmo no céu. Ele nunca para de orar por seus filhos."',
        homens: 'O homem que medita na intercessão contínua de Cristo (Hb 7.25) tem fundamento que não é abalado pela própria inconsistência.',
        mulheres: 'A mulher que descansa na habitação permanente do Espírito — não na intensidade dos seus sentimentos espirituais — tem paz estável.',
        igreja: 'A congregação que prega a perseverança com fundamento trinitário forma membros com segurança robusta e santidade motivada pelo amor.',
      },
      oracao: 'Pai, Filho e Espírito — obrigado pela perseverança que é tua obra trinitária em mim. Que eu descanse no teu decreto, na intercessão de Cristo e na presença do Espírito — e não no meu desempenho. Amém.',
      reflexao: 'Dos três fundamentos (decreto do Pai, intercessão do Filho, habitação do Espírito), qual você menos considera em sua vida espiritual?',
      aplicacao: 'Leia Hb 7.25 ("vivendo sempre para interceder por eles") e medite: Jesus está intercedendo por você agora. Ore em resposta a essa realidade.',
      notas: [
        'MURRAY, John. <em>Redemption Accomplished and Applied</em>. Grand Rapids: Eerdmans, 1955. Cap. sobre perseverança — a análise mais precisa dos fundamentos trinitários.',
      ],
      notaInicio: 188,
    },
    {
      dia: 256, data: '13 de setembro', tema: 'Perseverança e Queda Temporária',
      capitulo: 'CFW Cap. XVII.3', versiculo: 'Salmo 51.10-12',
      versiculoTexto: 'Cria em mim, ó Deus, um coração puro, e renova em mim um espírito reto. Não me lances fora de diante da tua face, e não retires de mim o teu Espírito Santo. Restitui-me o gozo da tua salvação.',
      confissaoTexto: 'Contudo, os santos podem cair em pecados graves pela tentação de Satanás e do mundo, e pela permanência da corrupção neles. Mas pelo poder de Deus serão preservados na fé para a salvação.',
      cfwRef: 'CFW XVII.3', cfwComparacao: 'CB 1689 Cap. XVII.3 é idêntico — os santos caem gravemente, mas não perdem a salvação; experimentam disciplina e restauração.',
      exposicao: 'Sl 51 é a prova viva de CFW XVII.3: Davi cometeu adultério e homicídio — pecados gravíssimos. Perdeu a alegria da salvação (v.12), não a salvação em si. O Espírito Santo se retirou em termos de alegria e comunhão — não em termos de regeneração (compare Ez 36.27). A perseverança não significa que os santos nunca caem gravemente — significa que Deus os restaura. A queda temporária é possível; a apostasia definitiva dos eleitos, não.',
      reforco: 'Os eleitos caem — às vezes gravemente. Mas Deus os disciplina e restaura. A queda é real; o abandono definitivo, impossível.',
      aplicacoes: {
        digital: 'Leia Sl 51 completo. Medite: "Davi caiu gravemente mas foi restaurado. Qual é sua resposta quando você cai — desespero ou Sl 51?"',
        familia: 'Conversem: "Como a perseverança dos santos não é licença para o pecado, mas esperança para a restauração?"',
        filhos: 'Ensine: "Quando você peca e se arrepende, Jesus te restaura — como restaurou Davi. Ele nunca desiste dos seus."',
        homens: 'O homem que caiu gravemente e acredita que perdeu tudo precisa ouvir CFW XVII.3: Deus restaura os seus — mesmo os que caíram como Davi.',
        mulheres: 'A mulher que carrega vergonha de queda passada precisa da assurance de CFW XVII.3: o Deus que preservou Davi a preserva também.',
        igreja: 'A congregação que ministra a quem caiu gravemente — com restauração, não rejeição — reflete a perseverança que Deus exercita com seus filhos.',
      },
      oracao: 'Senhor, restituí-me o gozo da tua salvação — como Davi. Quando eu cair, lembra-me que tua fidelidade é maior que minha falha. Restaura, disciplina, mas não abandona. Amém.',
      reflexao: 'Quando você cai em pecado grave, sua primeira reação é o Sl 51 (buscar restauração) ou o desespero (acreditar que está perdido)?',
      aplicacao: 'Ore Sl 51.10-12 como oração de restauração após qualquer pecado desta semana — mesmo os "menores". Pratique a restauração imediata.',
      notas: [
        'BRIDGES, Jerry. <em>The Discipline of Grace</em>. Colorado Springs: NavPress, 1994. Como a graça governa a santidade mesmo depois de quedas — prático e evangelicamente sólido.',
      ],
      notaInicio: 205,
    },
    {
      dia: 257, data: '14 de setembro', tema: 'Certeza da Graça: Assurance é Privilégio Bíblico',
      capitulo: 'CFW Cap. XVIII.1', versiculo: '1 João 5.13',
      versiculoTexto: 'Escrevi-vos estas coisas para que saibais que tendes a vida eterna — vós que credes no nome do Filho de Deus.',
      confissaoTexto: 'Os que verdadeiramente creem, amam e obedecem ao Evangelho podem nesta vida ter certeza de que estão em graça e que perseverarão na graça até à salvação. Esta certeza não é mera opinião provável, mas uma certeza infalível de fé.',
      cfwRef: 'CFW XVIII.1', cfwComparacao: 'CB 1689 Cap. XVIII.1 é idêntico — assurance é possível e esperada para o crente genuíno, não presunção arrogante.',
      exposicao: '1Jo 5.13 revela que João escreveu especificamente para que os crentes SAIBAM que têm vida eterna. A assurance não é arrogância — é obediência ao propósito de 1 João. CFW XVIII.1 distingue assurance de mera opinião: não é "acho que estou salvo" mas certeza infalível fundada em promessa divina. Três fundamentos: (1) as promessas divinas na Escritura; (2) a evidência de graça no próprio caráter; (3) o testemunho do Espírito com nosso espírito (Rm 8.16).',
      reforco: 'Assurance não é presunção — é confiança nas promessas de Deus, não na nossa bondade. Duvidar da salvação não é humildade — frequentemente é descrença.',
      aplicacoes: {
        digital: 'Leia 1Jo 5.9-13. Medite: "Você sabe que tem vida eterna — como João esperava que soubesse?"',
        familia: 'Conversem: "Como distinguimos assurance genuína (fundada em Cristo) de falsa segurança (fundada em experiência ou herança familiar)?"',
        filhos: 'Pergunte: "Você sabe que pertence a Jesus? Como você sabe?" Ensine os fundamentos da assurance.',
        homens: 'O homem que tem assurance genuína serve a Deus com gratidão — não com ansiedade de quem ainda está tentando conseguir salvação.',
        mulheres: 'A mulher com assurance vive com paz que testemunha do Evangelho — não com ansiedade religiosa que afasta os de fora.',
        igreja: 'A congregação que prega assurance como privilégio esperado — não como arrogância a ser temida — forma membros com paz e segurança espiritual.',
      },
      oracao: 'Senhor, que eu saiba que tenho vida eterna — porque tu prometeste, não porque sou bom. Que minha assurance se funde nas tuas promessas imutáveis, não na flutuação dos meus sentimentos. Amém.',
      reflexao: 'Você tem certeza da sua salvação? Se não, qual é o fundamento da incerteza — dúvida das promessas de Deus ou consciência de pecado não confessado?',
      aplicacao: 'Leia 1Jo 5.13, Rm 8.16 e Jo 10.28-29. Escreva os fundamentos da sua assurance. Ore com base nesses fundamentos, não nos seus sentimentos.',
      notas: [
        'LLOYD-JONES, D. Martyn. <em>Assurance</em>. Edinburgh: Banner of Truth, 1972. O tratamento mais completo e pastoralmente rico da assurance da salvação.',
      ],
      notaInicio: 222,
    },
    {
      dia: 258, data: '15 de setembro', tema: 'Fundamentos da Assurance: Promessa, Fruto e Espírito',
      capitulo: 'CFW Cap. XVIII.2', versiculo: 'Romanos 8.16',
      versiculoTexto: 'O mesmo Espírito testifica com o nosso espírito que somos filhos de Deus.',
      confissaoTexto: 'Esta certeza é fundada sobre: a verdade divina das promessas de salvação; a evidência interna das graças às quais essas promessas são feitas; o testemunho do Espírito de adoção, que testifica com nosso espírito que somos filhos de Deus.',
      cfwRef: 'CFW XVIII.2', cfwComparacao: 'CB 1689 Cap. XVIII.2 lista os mesmos três fundamentos — promessas, frutos de graça, testemunho do Espírito.',
      exposicao: 'Rm 8.16 é o terceiro fundamento da assurance: o Espírito testifica com nosso espírito. CFW XVIII.2 organiza os três: (1) as promessas divinas na Escritura — objetivo e externo; (2) a evidência de graças no caráter — subjetivo mas observável; (3) o testemunho do Espírito — direto e interno. O primeiro é o mais firme e deve dominar. O segundo e terceiro confirmam. Quando faltam o segundo e o terceiro, o crente deve recorrer ao primeiro com mais força — a promessa de Deus permanece mesmo quando os sentimentos falham.',
      reforco: 'Quando os sentimentos falham, recorra às promessas. Quando os frutos estão fracos, olhe para Cristo. A assurance não depende de você estar bem — mas de Deus ser fiel.',
      aplicacoes: {
        digital: 'Leia Rm 8.14-17. Medite: "Qual dos três fundamentos é mais fraco na sua vida hoje? O que fazer?"',
        familia: 'Conversem sobre quando a assurance esteve fraca na vida de cada um. O que restaurou a certeza?',
        filhos: 'Ensine: "Como sabemos que somos filhos de Deus? Pela Bíblia que promete, pela mudança que vemos e pelo Espírito que nos diz."',
        homens: 'O homem que conhece os três fundamentos da assurance não oscila com as flutuações espirituais — recorre ao fundamento mais firme quando os outros enfraquecem.',
        mulheres: 'A mulher que aprendeu a recorrer às promessas quando os sentimentos falham tem assurance estável que não depende de como está se sentindo hoje.',
        igreja: 'A congregação que prega os três fundamentos da assurance forma membros capazes de pastorear seus próprios corações nas dúvidas.',
      },
      oracao: 'Espírito Santo, testifica com meu espírito que sou filho de Deus. Quando meus sentimentos calarem, que as promessas gritem. Quando meus frutos forem fracos, que a promessa de Cristo seja suficiente. Amém.',
      reflexao: 'Qual dos três fundamentos você mais usa para sua assurance? Qual você mais negligencia? Como equilibrar os três?',
      aplicacao: 'Escreva três versículos de promessa (fundamento 1), três evidências de graça em sua vida (fundamento 2) e ore pedindo o testemunho do Espírito (fundamento 3).',
      notas: [
        'PACKER, J.I. <em>Knowing God</em>. Downers Grove: IVP, 1973. Cap. 19-20 — O Espírito de adoção e o testemunho do Espírito. O mais claro e devocional.',
      ],
      notaInicio: 239,
    },
    {
      dia: 259, data: '16 de setembro', tema: 'Assurance e Santificação: A Certeza que Liberta para Servir',
      capitulo: 'CFW Cap. XVIII.3–4', versiculo: '1 João 3.3',
      versiculoTexto: 'E todo o que tem esta esperança nele purifica-se a si mesmo, assim como ele é puro.',
      confissaoTexto: 'Esta certeza infalível não inclina os homens para a dissolução, mas antes produz neles cuidado com os frutos espirituais, e é o fundamento de uma obediência evangélica genuína.',
      cfwRef: 'CFW XVIII.3', cfwComparacao: 'CB 1689 Cap. XVIII.3 é idêntico — assurance motiva santidade, não licença para o pecado.',
      exposicao: '1Jo 3.3 revela o paradoxo evangélico: a esperança da salvação (assurance) purifica — não relaxa. CFW XVIII.3 responde à objeção mais comum: "Se estou seguro, por que me esforçar?" A resposta: quem genuinamente conhece a assurance a usa como motor de santidade, não como licença. A assurance falsa (fundada em herança ou ritual) produz negligência. A assurance genuína (fundada em Cristo) produz amor e obediência.',
      reforco: 'Assurance genuína produz cuidado com os frutos espirituais, obediência evangélica e esforço pela santidade — exatamente o oposto do que os críticos temem.',
      aplicacoes: {
        digital: 'Leia 1Jo 3.1-3. Medite: "Sua assurance te motiva a mais santidade ou te torna descuidado? O que isso revela?"',
        familia: 'Conversem: "Como a certeza da salvação muda a motivação para servir — de medo de perder para amor pelo que temos?"',
        filhos: 'Ensine: "Porque Jesus já nos salvou, queremos agradá-lo — não para ser salvos, mas porque amamos quem nos salvou."',
        homens: 'O homem que usa a assurance como motivação para santidade — não como desculpa para relaxar — demonstra que sua certeza é genuína.',
        mulheres: 'A mulher que cresce em santidade como resposta de amor à assurance da salvação tem motivação que não se esgota.',
        igreja: 'A congregação que conecta assurance e santidade — certeza que motiva obediência — evita tanto o legalismo (obediência por medo) quanto o antinomismo (graça sem obediência).',
      },
      oracao: 'Senhor, que a certeza da tua salvação não me relaxe, mas me inflamar para te amar mais. Que a segurança que tenho em Cristo seja o motor da minha santidade — não uma desculpa para a negligência. Amém.',
      reflexao: 'Sua assurance está produzindo mais santidade ou mais descuido espiritual? A resposta revela se sua assurance é genuína.',
      aplicacao: 'Liste três áreas de santidade onde você quer crescer. Escreva como a assurance (certeza da salvação) motiva esse crescimento — não como medo de perder, mas como amor pelo que tem.',
      notas: [
        'OWEN, John. <em>Of the Mortification of Sin in Believers</em>. Edinburgh: Banner of Truth, 1958. A mortificação como resposta da assurance — o clássico puritano inigualável.',
      ],
      notaInicio: 256,
    },
    {
      dia: 260, data: '17 de setembro', tema: 'A Lei de Deus: Regra de Vida para o Crente',
      capitulo: 'CFW Cap. XIX.1–3', versiculo: 'Salmo 119.105',
      versiculoTexto: 'Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho.',
      confissaoTexto: 'Deus deu ao povo de Israel a lei moral, contida nos Dez Mandamentos, para ser uma regra perfeita de justiça; ela obriga a todos os homens para sempre.',
      cfwRef: 'CFW XIX.1–2', cfwComparacao: 'CB 1689 Cap. XIX.1-2 é paralelo — a lei moral é dada a Adão e reafirmada a Israel nos Dez Mandamentos como regra permanente.',
      exposicao: 'Sl 119.105 canta a lei como lâmpada e luz — não como grilhão. Para o crente regenerado, a lei mudou de função: não é mais acusadora (Gl 3.24) mas guia (Rm 7.12). CFW XIX distingue três usos da lei: (1) expor o pecado (uso pedagógico); (2) restringir o mal na sociedade (uso civil); (3) guiar o crente na santidade (uso normativo — o "terceiro uso"). Os crentes usam primariamente o terceiro uso — a lei como mapa da vontade de Deus, não como escada para a salvação.',
      reforco: 'Para o crente, a lei é regra de vida — não meio de justificação. A mesma lei que condena o incrédulo guia o regenerado.',
      aplicacoes: {
        digital: 'Leia Sl 119.97-105. Medite: "Você tem a lei de Deus como amada lâmpada ou como pesado fardo?"',
        familia: 'Conversem: "Como usamos os Dez Mandamentos na nossa família — como regra de graça para a vida, não como lista de ameaças?"',
        filhos: 'Ensine que os Dez Mandamentos são o resumo da vontade de Deus para uma vida boa. Memorize-os juntos.',
        homens: 'O homem que estuda e obedece a lei de Deus como regra de vida — não como meio de justificação — cresce em sabedoria prática.',
        mulheres: 'A mulher que ama a lei de Deus como o Salmista — como lâmpada, não como grilhão — tem bússola confiável para a vida.',
        igreja: 'A congregação que prega a lei com seus três usos distintos forma membros que a usam corretamente — nem como escada para a salvação nem como algo para ignorar.',
      },
      oracao: 'Senhor, que tua lei seja lâmpada para meus pés — guia que amo, não fardo que temo. Como regenerado, que eu use a lei para me orientar na santidade, não para me justificar diante de ti. Amém.',
      reflexao: 'Você usa a lei como guia para a santidade ou ainda a experimenta como ameaça ao seu valor diante de Deus? A diferença revela se você entende a justificação.',
      aplicacao: 'Leia os Dez Mandamentos (Êx 20.1-17). Para cada um, escreva como ele guia sua vida hoje — não como regra para se justificar, mas como expressão da vontade de Deus para o seu bem.',
      notas: [
        'BARCELLOS, Richard. <em>In Defense of the Decalogue</em>. Enumclaw: Winepress, 2001. A defesa batista confessional mais completa dos Dez Mandamentos como regra moral permanente.',
      ],
      notaInicio: 273,
    },
    {
      dia: 261, data: '18 de setembro', tema: 'A Lei Cerimonial e Civil: Cumpridas em Cristo',
      capitulo: 'CFW Cap. XIX.3–4', versiculo: 'Colossenses 2.16-17',
      versiculoTexto: 'Portanto, ninguém vos julgue pelo comer, ou pelo beber, ou por causa de alguma festa, ou lua nova, ou sábados, que são sombra das coisas futuras; mas o corpo é de Cristo.',
      confissaoTexto: 'As leis cerimoniais eram ordenanças típicas, prefigurando Cristo, e agora são abolidas. As leis judiciais civis, dadas ao povo de Israel como um corpo político, expiraram com esse Estado e não obrigam outros povos.',
      cfwRef: 'CFW XIX.3–4', cfwComparacao: 'CB 1689 Cap. XIX.3-4 é idêntico — as três categorias (moral, cerimonial, civil) são aplicadas de forma diferente no NT.',
      exposicao: 'Cl 2.16-17 revela que as leis cerimoniais eram "sombra das coisas futuras — o corpo é de Cristo." Com a vinda de Cristo, as sombras cederam lugar à realidade. Sacrifícios, purificações, festas — tudo apontava para Cristo e foi cumprido nele. CFW XIX.3-4 também liberta dos "teônomos" que querem aplicar a lei civil de Israel diretamente às nações modernas — essa lei expirou com o Estado teocrático de Israel. A lei moral permanece; as outras duas foram transformadas ou abolidas.',
      reforco: 'A lei cerimonial foi cumprida em Cristo (não precisa ser repetida); a lei civil de Israel expirou (não se aplica diretamente); a lei moral permanece (orienta eternamente).',
      aplicacoes: {
        digital: 'Leia Cl 2.13-17 e Hb 10.1-4. Medite: "Como Cristo cumpriu o que as leis cerimoniais apontavam?"',
        familia: 'Conversem: "Por que cristãos não seguem as leis alimentares do AT? O que mudou com Cristo?"',
        filhos: 'Ensine: "No AT, Deus usava regras especiais como dicas de Jesus que viria. Quando Jesus veio, as dicas não são mais necessárias."',
        homens: 'O homem que distingue lei moral, cerimonial e civil usa o AT com hermenêutica correta — nem ignorando nem aplicando de forma errada.',
        mulheres: 'A mulher que entende essa distinção lê o AT com clareza — sem sentir que precisa seguir regras alimentares ou sacrificiais.',
        igreja: 'A congregação que ensina as três categorias da lei forma membros com hermenêutica robusta para ler o AT corretamente.',
      },
      oracao: 'Senhor Jesus, tu és o cumprimento de todas as sombras. Que eu leia o AT com olhos de graça — vendo como cada ordenança apontava para ti e foi cumprida em ti. Amém.',
      reflexao: 'Você sabe distinguir lei moral (permanente), cerimonial (cumprida em Cristo) e civil (expirada com Israel)? Isso importa para como você lê o AT.',
      aplicacao: 'Escolha três passagens do AT com lei cerimonial ou civil. Pergunte: "Como isso aponta para Cristo?" e "Qual é sua aplicação no NT?"',
      notas: [
        'MEREDITH KLINE. <em>Kingdom Prologue</em>. Eugene: Wipf and Stock, 2006. A teologia da aliança que melhor explica as três categorias da lei e seu destino em Cristo.',
      ],
      notaInicio: 290,
    },
    {
      dia: 262, data: '19 de setembro', tema: 'A Lei e o Evangelho: Aliados, Não Oponentes',
      capitulo: 'CFW Cap. XIX.5–6', versiculo: 'Romanos 3.31',
      versiculoTexto: 'Destruímos, pois, a lei pela fé? De modo nenhum! Antes, confirmamos a lei.',
      confissaoTexto: 'A lei é de grande utilidade tanto para os regenerados como para os não regenerados. Para os regenerados, não como aliança de obras para obtenção de justificação, mas como regra de vida, revelando a vontade de Deus e a obrigação do crente.',
      cfwRef: 'CFW XIX.6', cfwComparacao: 'CB 1689 Cap. XIX.6 é paralelo — a lei não é destruída pelo Evangelho, mas confirmada; o crente a usa como regra de vida.',
      exposicao: 'Rm 3.31 responde à acusação de antinomismo: o Evangelho da justificação pela fé não destrói a lei — a confirma. CFW XIX.6 articula a lei de Deus como "regra de vida" para o crente: revela a vontade de Deus, informa a obrigação, e — quando violada — mostra a necessidade de renovar o recurso ao Mediador. Lei e Evangelho não são oponentes; são aliados. A lei mostra o padrão; o Evangelho mostra como alcançá-lo em Cristo.',
      reforco: 'Lei sem Evangelho é escravidão. Evangelho sem lei é licença. Juntos — lei como padrão, Evangelho como poder — produzem santidade genuína.',
      aplicacoes: {
        digital: 'Leia Rm 3.27-31. Medite: "Como o Evangelho confirma a lei em vez de abolir? O que isso significa para sua vida prática?"',
        familia: 'Conversem: "Em nossa família, usamos a lei como motivação para esforço ou como padrão que nos leva a Cristo?"',
        filhos: 'Ensine: "A lei nos mostra o que é certo; o Evangelho nos dá força para fazer o certo. Precisamos dos dois."',
        homens: 'O homem que integra lei e Evangelho — padrão divino e poder de Cristo — cresce em santidade sem cair em legalismo ou antinomismo.',
        mulheres: 'A mulher que usa a lei como espelho (mostra o que precisa ser mudado) e o Evangelho como poder (transforma o que a lei mostra) tem prática espiritual completa.',
        igreja: 'A congregação que prega lei e Evangelho juntos — cada um em seu lugar — evita os dois extremos que destroem a espiritualidade saudável.',
      },
      oracao: 'Senhor, que eu ame tua lei como revelação da tua vontade — e que o Evangelho me dê o poder que a lei não tem para me transformar. Que os dois trabalhem juntos na minha santificação. Amém.',
      reflexao: 'Você usa a lei para se justificar (legalismo), a ignora completamente (antinomismo) ou a usa como padrão que te leva a Cristo (terceiro uso)? Onde você está?',
      aplicacao: 'Leia CFW XIX completo. Escreva em suas próprias palavras: por que a lei não destrói o Evangelho e o Evangelho não destrói a lei.',
      notas: [
        'HORTON, Michael. <em>The Law of Perfect Freedom</em>. Chicago: Moody, 1993. A síntese mais acessível da relação entre lei e Evangelho na tradição reformada.',
      ],
      notaInicio: 307,
    },
    {
      dia: 263, data: '20 de setembro', tema: 'Liberdade Cristã: Libertos da Culpa, Não da Obediência',
      capitulo: 'CFW Cap. XX.1', versiculo: 'Gálatas 5.1',
      versiculoTexto: 'Estai, pois, firmes na liberdade com que Cristo nos libertou, e não vos submetais de novo ao jugo da escravidão.',
      confissaoTexto: 'A liberdade cristã consiste em: libertação da culpa do pecado, da ira condenatória de Deus e da dureza da lei; livre acesso a Deus; obediência a Deus não por temor servil, mas por amor filial.',
      cfwRef: 'CFW XX.1', cfwComparacao: 'CB 1689 Cap. XXI.1 é paralelo — a liberdade cristã é do pecado, da lei como condenação, não da lei como regra de vida.',
      exposicao: 'Gl 5.1 é grito de libertação: Cristo nos libertou — fiquemos firmes nessa liberdade. CFW XX.1 define o que liberdade cristã É e o que NÃO é. É libertação de: culpa do pecado, ira condenatória de Deus, dureza da lei como meio de justificação. Não é libertação de: obediência à lei, disciplina espiritual, submissão a autoridades legítimas. A liberdade cristã não é libertinagem — é a liberdade dos filhos de Deus que obedecem por amor, não por medo.',
      reforco: 'Liberdade cristã é liberdade DA culpa, não liberdade PARA o pecado. O liberto da lei como condenação é livre PARA obedecer a lei como filho.',
      aplicacoes: {
        digital: 'Leia Gl 5.1-6. Medite: "Em que áreas da sua vida você ainda está sob jugo de escravidão — culpa, medo, legalismo — em vez de liberdade filial?"',
        familia: 'Conversem: "A obediência na nossa família é motivada por medo ou por amor? Como transformamos a cultura de obediência?"',
        filhos: 'Ensine: "Não obedecemos a Deus para não ser punidos. Obedecemos porque o amamos — como obedecer a um pai que amamos."',
        homens: 'O homem que obedece a Deus por amor filial — não por medo servil — tem espiritualidade que cresce em vez de esgotar.',
        mulheres: 'A mulher liberta da culpa crônica — que serve por amor, não por ansiedade religiosa — irradia a graça que recebeu.',
        igreja: 'A congregação que prega a liberdade cristã corretamente — liberdade da culpa para obedecer por amor — forma membros com espiritualidade madura e alegre.',
      },
      oracao: 'Senhor Jesus, obrigado pela liberdade que conquistaste para mim — da culpa, da ira e da dureza da lei. Que eu viva como filho livre, obedecendo por amor, não como escravo obedecendo por medo. Amém.',
      reflexao: 'Sua obediência a Deus é filial (amor que quer agradar o Pai) ou servil (medo de ser punido)? Como você sabe?',
      aplicacao: 'Identifique uma área de obediência onde você age por medo em vez de amor. Ore pedindo que o Espírito transforme a motivação — de medo para amor filial.',
      notas: [
        'LUTHER, Martin. <em>On the Freedom of a Christian</em>. 1520. O texto fundacional sobre liberdade cristã — liberto de tudo para servir a todos por amor.',
      ],
      notaInicio: 324,
    },
    {
      dia: 264, data: '21 de setembro', tema: 'Liberdade de Consciência: Só Deus é Senhor',
      capitulo: 'CFW Cap. XX.2', versiculo: 'Atos 5.29',
      versiculoTexto: 'Respondendo Pedro e os apóstolos, disseram: Mais importa obedecer a Deus do que aos homens.',
      confissaoTexto: 'Só Deus é Senhor da consciência, e a deixou livre de doutrinas e mandamentos de homens que sejam contrários a sua Palavra, ou além dela, em matéria de fé ou culto.',
      cfwRef: 'CFW XX.2', cfwComparacao: 'CB 1689 Cap. XXI.2 é paralelo — a consciência não pode ser vinculada além do que Deus revelou na Escritura.',
      exposicao: 'At 5.29 é a expressão máxima da liberdade de consciência: quando há conflito entre a ordem de Deus e a ordem humana, obedecer a Deus. CFW XX.2 tem dois movimentos: (1) positivo — só Deus é Senhor da consciência (nenhum homem, padre, papa ou tradição pode vincular a consciência além da Escritura); (2) negativo — crenças contrárias à Escritura ou além dela não podem ser impostas à consciência. Isso não é libertinagem — é submissão a Deus que recusa submissão a Deus-substitutos.',
      reforco: 'Liberdade de consciência não é fazer o que quiser — é submeter a consciência somente a Deus e recusar submeter ao que Deus não ordenou.',
      aplicacoes: {
        digital: 'Leia At 5.27-29. Medite: "Há mandamentos humanos — tradição, pressão social, expectativas religiosas — que você obedece como se fossem mandamentos de Deus?"',
        familia: 'Conversem: "Como distinguimos obediência a autoridades legítimas de submissão indevida a tradições humanas como se fossem lei divina?"',
        filhos: 'Ensine: "Só Deus pode mandar na tua consciência. Os pais te guiam — mas é Deus quem tu obedeces porque o amas."',
        homens: 'O homem que entende a liberdade de consciência recusa tanto o libertinismo (consciência sem autoridade) quanto o clericalismo (consciência vinculada a homens).',
        mulheres: 'A mulher que submete sua consciência somente a Deus — e recusa a vinculação por tradições humanas — tem liberdade cristã genuína.',
        igreja: 'A congregação que não impõe ao rebanho mais do que a Escritura ordena — em doutrina, culto e vida — respeita a liberdade de consciência dos membros.',
      },
      oracao: 'Senhor, és o único Senhor da minha consciência. Guarda-me de submeter minha consciência a homens como se fossem Deus — e de usar liberdade como desculpa para rejeitar tua autoridade. Que obedeca somente a ti. Amém.',
      reflexao: 'Há práticas religiosas ou tradições humanas que você obedece como se fossem mandamentos divinos? Como a liberdade de consciência desafia isso?',
      aplicacao: 'Leia CFW XX.2 e reflita: há áreas onde você vincula a consciência a tradições além da Escritura? Ou onde usa liberdade como licença? Ore por discernimento.',
      notas: [
        'FRAME, John. <em>The Doctrine of the Christian Life</em>. Phillipsburg: P&R, 2008. A ética reformada mais completa — inclui capítulo fundamental sobre liberdade de consciência.',
      ],
      notaInicio: 341,
    },
    {
      dia: 265, data: '22 de setembro', tema: 'Liberdade Cristã Não é Licença para o Pecado',
      capitulo: 'CFW Cap. XX.3', versiculo: '1 Pedro 2.16',
      versiculoTexto: 'Como livres, e não usando a liberdade para cobertura da malícia, mas como servos de Deus.',
      confissaoTexto: 'Os que, sob o pretexto da liberdade cristã, praticam qualquer pecado ou nutre qualquer concupiscência, destroem o fim da liberdade cristã, que é que, sendo livres das mãos dos nossos inimigos, o sirvamos sem temor em santidade e justiça diante dele todos os dias.',
      cfwRef: 'CFW XX.3', cfwComparacao: 'CB 1689 Cap. XXI.3 é idêntico — liberdade cristã usada como cobertura para o pecado é abuso e contradição do próprio Evangelho.',
      exposicao: '1Pe 2.16 apresenta o paradoxo: livre — mas servo de Deus. A liberdade cristã tem propósito: servir a Deus sem temor em santidade. Quem usa a graça como licença para o pecado distorce o Evangelho. Paulo o previu em Rm 6.1: "Perseveremos no pecado para que a graça se multiplique? De modo nenhum!" A liberdade da condenação é para libertação DO pecado — não libertação PARA o pecado. Liberdade cristã genuína se manifesta em santidade voluntária, não em desobediência justificada pela graça.',
      reforco: 'Usar a graça como desculpa para o pecado é a maior perversão do Evangelho — demonstra que a graça não foi recebida genuinamente.',
      aplicacoes: {
        digital: 'Leia Rm 6.1-14. Medite: "Há áreas onde você usa a graça como justificativa para permanecer em padrões de pecado?"',
        familia: 'Conversem: "Como explicamos para nossos filhos que graça não é cheque em branco para fazer o que quiser?"',
        filhos: 'Ensine: "Jesus nos libertou do pecado — não para fazer o que quisermos, mas para fazer o que é certo e amar a Deus."',
        homens: 'O homem que usa a segurança da salvação para justificar comportamentos pecaminosos está revelando que não compreendeu o Evangelho.',
        mulheres: 'A mulher que cresce em santidade como resposta de amor à liberdade que Cristo deu demonstra que entendeu a graça.',
        igreja: 'A congregação que prega a liberdade cristã com sua finalidade correta — santidade e serviço — não produz antinomismo.',
      },
      oracao: 'Senhor, que jamais use tua graça como desculpa para o pecado. Que a liberdade que me deste me liberte DO pecado para servir a ti em santidade. Que setembro termine com essa clareza no coração. Amém.',
      reflexao: 'Há áreas específicas onde você usa a graça como cobertura para o pecado? O que CFW XX.3 e Rm 6.1-2 dizem sobre isso?',
      aplicacao: 'Leia Rm 6.1-23 completo. Escreva em suas palavras o argumento de Paulo: por que o crente que entende a graça não usa a graça como licença para o pecado.',
      notas: [
        'BRIDGES, Jerry. <em>The Gospel for Real Life</em>. Colorado Springs: NavPress, 2002. O Evangelho aplicado à luta contra o antinomismo prático — acessível e poderoso.',
      ],
      notaInicio: 358,
    },
    {
      dia: 266, data: '23 de setembro', tema: 'Síntese: Fé, Arrependimento e Boas Obras',
      capitulo: 'CFW Cap. XIV–XVI — Revisão', versiculo: 'Tito 2.11-12',
      versiculoTexto: 'Porque a graça de Deus se manifestou salvadora para todos os homens, ensinando-nos que, renunciando à impiedade e às paixões mundanas, vivamos sensatamente, e com justiça e piedade neste século presente.',
      confissaoTexto: 'A fé que recebe Cristo, o arrependimento que se afasta do pecado, e as boas obras que expressam obediência — os três são inseparáveis na vida do crente genuíno.',
      cfwRef: 'CFW XIV–XVI — síntese', cfwComparacao: 'CFW e CB 1689 concordam plenamente na tríade inseparável: fé, arrependimento e boas obras como marcas da salvação genuína.',
      exposicao: 'Tt 2.11-12 é a síntese perfeita: a graça que salva (fé) também ensina (produz arrependimento e boas obras). Os três — fé, arrependimento, boas obras — são inseparáveis. Fé sem arrependimento não é fé salvadora. Arrependimento sem fé leva ao desespero. Boas obras sem fé são moralismo. Mas quando os três estão presentes e integrados, temos o perfil do crente genuíno: recebe Cristo pela fé, afasta-se do pecado pelo arrependimento, vive em obediência pelas boas obras.',
      reforco: 'Fé, arrependimento e boas obras não se alternam — são simultâneos. Remover qualquer um distorce os outros dois.',
      aplicacoes: {
        digital: 'Leia Tt 2.11-14. Medite: "A graça que recebi está produzindo os três — fé, arrependimento e boas obras — de forma integrada?"',
        familia: 'Conversem: "Como a graça nos ensina — ativamente transforma nossa vida — em vez de ser apenas algo que recebemos passivamente?"',
        filhos: 'Ensine: "A graça de Deus faz três coisas: nos salva, nos ensina a dizer não ao mal e nos ajuda a viver bem."',
        homens: 'O homem que integra fé, arrependimento e obediência tem perfil espiritual maduro — não é apenas crente, apenas moralista ou apenas emocional.',
        mulheres: 'A mulher que vive os três aspectos — crendo, arrependendo-se e obedecendo — cresce em integralidade espiritual que é testemunho poderoso.',
        igreja: 'A congregação que prega os três inseparáveis — fé, arrependimento, boas obras — sem privilegiar um em detrimento dos outros forma discípulos completos.',
      },
      oracao: 'Senhor, que a graça que recebi produza em mim os três: fé que recebe Cristo, arrependimento que afasta do pecado e boas obras que expressam obediência. Que os três cresçam juntos em minha vida. Amém.',
      reflexao: 'Dos três — fé, arrependimento e boas obras — qual está mais fraco em sua vida agora? O que isso indica sobre o que precisa de cuidado?',
      aplicacao: 'Avalie sua semana passada nos três aspectos. Onde a fé foi forte? Onde o arrependimento foi genuíno? Onde as boas obras floresceram? Ore específicamente sobre o mais fraco.',
      notas: [
        'HORTON, Michael. <em>The Christian Faith</em>. Grand Rapids: Zondervan, 2011. A síntese sistemática mais completa que integra fé, arrependimento e obediência na tradição reformada.',
      ],
      notaInicio: 375,
    },
    {
      dia: 267, data: '24 de setembro', tema: 'Síntese: Perseverança e Assurance',
      capitulo: 'CFW Cap. XVII–XVIII — Revisão', versiculo: 'Filipenses 1.6',
      versiculoTexto: 'Tendo por certo isto mesmo: que aquele que em vós começou a boa obra a aperfeiçoará até ao dia de Jesus Cristo.',
      confissaoTexto: 'A mesma graça que começou a obra de salvação no crente garante sua continuação até o fim — e o crente pode ter certeza dessa garantia pela fé, pelos frutos e pelo testemunho do Espírito.',
      cfwRef: 'CFW XVII–XVIII — síntese', cfwComparacao: 'CFW e CB 1689 concordam: perseverança (XVII) e assurance (XVIII) são inseparáveis — quem Deus preserva pode ter certeza dessa preservação.',
      exposicao: 'Fp 1.6 une perseverança e assurance em uma frase: "aquele que começou a boa obra a aperfeiçoará." A perseverança é garantida por quem a começou — não por quem a sustenta. E o crente pode ter certeza (assurance) dessa garantia porque ela não depende dele, mas de Deus. CFW XVII e XVIII são capítulos irmãos: perseverança é a realidade objetiva; assurance é a experiência subjetiva dessa realidade. Um sem o outro coxeia.',
      reforco: 'Perseverança sem assurance é segurança ansiosa. Assurance sem perseverança é presunção. Juntos formam a paz espiritual madura.',
      aplicacoes: {
        digital: 'Leia Fp 1.3-11. Medite: "Você confia que aquele que começou a obra em você a aperfeiçoará — ou ainda sente que depende de você completar?"',
        familia: 'Conversem: "Como a certeza de que Deus completa o que começou muda nossa forma de enfrentar falhas e quedas espirituais?"',
        filhos: 'Ensine: "Quando você erra, Deus não desiste de você. Ele prometeu completar o que começou — e ele cumpre suas promessas."',
        homens: 'O homem que descansa em Fp 1.6 — que é Deus quem completa a obra — serve com paz e sem pânico diante de suas falhas.',
        mulheres: 'A mulher que tem assurance baseada na perseverança de Deus — não na sua consistência — tem paz que não oscila com as estações espirituais.',
        igreja: 'A congregação que conecta perseverança e assurance — e prega ambas com base em Deus, não no crente — liberta da ansiedade espiritual crônica.',
      },
      oracao: 'Senhor, obrigado por seres fiel para completar o que começaste em mim. Que eu descanse em Fp 1.6 — não na minha fidelidade, mas na tua. Que a assurance que tenho seja firme porque tu és firme. Amém.',
      reflexao: 'Você experimenta perseverança com assurance (paz) ou com ansiedade (incerteza de chegar ao fim)? O que isso revela sobre em quê você fundamenta sua segurança?',
      aplicacao: 'Memorize Fp 1.6. Use-o como ancla sempre que a assurance oscilar — recorde que aquele que começou é fiel para completar.',
      notas: [
        'BEEKE, Joel. <em>Assurance of Faith</em>. New York: Peter Lang, 1991. O estudo histórico e teológico mais completo da assurance na tradição reformada — de Calvino aos puritanos.',
      ],
      notaInicio: 392,
    },
    {
      dia: 268, data: '25 de setembro', tema: 'Síntese: Lei e Liberdade Cristã',
      capitulo: 'CFW Cap. XIX–XX — Revisão', versiculo: 'Romanos 8.2',
      versiculoTexto: 'Porque a lei do Espírito de vida, em Cristo Jesus, me livrou da lei do pecado e da morte.',
      confissaoTexto: 'A lei de Deus guia o crente como regra de vida; a liberdade cristã liberta da lei como condenação; os dois — lei e liberdade — são aliados, não oponentes, na vida do crente maduro.',
      cfwRef: 'CFW XIX–XX — síntese', cfwComparacao: 'CFW e CB 1689 concordam: lei e liberdade cristã são complementares — a liberdade é da lei como condenação, não da lei como guia.',
      exposicao: 'Rm 8.2 apresenta a resolução: a lei do Espírito de vida libertou DA lei do pecado e da morte. O crente não está mais sob a lei como condenação — está sob a lei como guia, empoderado pelo Espírito. CFW XIX e XX se integram: a lei diz o que fazer (padrão); o Espírito dá poder para fazê-lo (libertação). O crente que entende essa integração não teme a lei (legalismo) nem a ignora (antinomismo) — a usa como padrão de amor ao Deus que o libertou.',
      reforco: 'Lei e liberdade cristã não são oponentes — são complementos. A liberdade da condenação da lei liberta para obedecer a lei com amor.',
      aplicacoes: {
        digital: 'Leia Rm 8.1-4. Medite: "A lei do Espírito que te libertou produz obediência à lei de Deus — não abolição dela."',
        familia: 'Conversem: "Em nossa família, usamos a lei de Deus como padrão de amor ou como ameaça? Como a liberdade cristã transforma isso?"',
        filhos: 'Ensine: "A lei de Deus nos mostra o que é bom. O Espírito Santo nos ajuda a fazer o que é bom. Precisamos dos dois."',
        homens: 'O homem que integra lei (padrão) e liberdade (empoderamento pelo Espírito) tem prática espiritual madura — nem legalista nem libertino.',
        mulheres: 'A mulher que obedece à lei de Deus como expressão de amor — não como tentativa de merecer aprovação — experimenta a liberdade cristã genuína.',
        igreja: 'A congregação que prega lei e liberdade cristã de forma integrada evita os dois extremos e forma discípulos espiritualmente equilibrados.',
      },
      oracao: 'Espírito Santo, empodere-me para obedecer à lei de Deus que amo — como expressão da liberdade que recebi, não como escravidão que temo. Que lei e liberdade sejam aliados em minha santificação. Amém.',
      reflexao: 'Você usa a lei de Deus como padrão de amor (cristão maduro) ou a teme como condenadora (ainda não compreendeu a liberdade cristã)?',
      aplicacao: 'Leia Rm 8.1-14. Escreva como o Espírito resolve a tensão entre lei e liberdade — e como isso se manifesta em sua vida hoje.',
      notas: [
        'SPROUL, R.C. <em>Free from the Law</em>. Phillipsburg: P&R, 1994. A síntese mais clara da liberdade cristã em relação à lei — acessível para toda a família.',
      ],
      notaInicio: 409,
    },
    {
      dia: 269, data: '26 de setembro', tema: 'Aplicação: Examinando a Própria Espiritualidade',
      capitulo: 'CFW Cap. XIV–XX — Aplicação', versiculo: '2 Coríntios 13.5',
      versiculoTexto: 'Examinai-vos a vós mesmos, para ver se estais na fé; provai-vos a vós mesmos.',
      confissaoTexto: 'Os crentes são chamados a examinar a si mesmos quanto à fé genuína, arrependimento real, perseverança crescente, assurance fundamentada nas promessas, uso correto da lei e liberdade cristã sem licença.',
      cfwRef: 'CFW XIV–XX — aplicação', cfwComparacao: 'O auto-exame exigido por 2Co 13.5 integra todos os temas de setembro — fé, arrependimento, boas obras, perseverança, assurance, lei e liberdade.',
      exposicao: '2Co 13.5 chama ao auto-exame: "estais na fé?" Paulo não presume que os coríntios estão automaticamente bem. O auto-exame não é auto-tortura — é discernimento espiritual honesto. A semana passada construiu as categorias: fé genuína (XIV), arrependimento real (XV), boas obras corretas (XVI), perseverança de Deus (XVII), assurance fundada (XVIII), lei como guia (XIX), liberdade sem licença (XX). O auto-exame de setembro usa essas categorias como lentes.',
      reforco: 'Auto-exame bíblico não é paranoia espiritual — é higiene espiritual que usa as promessas de Deus como padrão, não a performance como medida.',
      aplicacoes: {
        digital: 'Leia 2Co 13.5. Medite sobre cada tema de setembro: fé, arrependimento, boas obras, perseverança, assurance, lei, liberdade.',
        familia: 'Façam um "check-in espiritual" familiar — não para julgar, mas para orar uns pelos outros nas áreas mais fracas.',
        filhos: 'Ensine que se examinar é saudável — como ir ao médico. Não é para punição, mas para cuidado.',
        homens: 'O homem que se examina regularmente — com as categorias corretas — mantém a saúde espiritual e cresce em maturidade.',
        mulheres: 'A mulher que pratica auto-exame bíblico — usando promessas, não performance como padrão — cresce sem ser esmagada.',
        igreja: 'A congregação que inclui auto-exame na liturgia — especialmente antes da ceia — forma membros com saúde espiritual sustentável.',
      },
      oracao: 'Senhor, que eu me examine honestamente — usando tuas promessas como padrão, não minha performance. Mostra-me o que está fraco e o que está crescendo. E em ambos os casos, leva-me a Cristo. Amém.',
      reflexao: 'Ao examinar os temas de setembro em sua vida — fé, arrependimento, boas obras, perseverança, assurance, lei, liberdade — qual está mais forte? Qual está mais fraco?',
      aplicacao: 'Faça o auto-exame de 2Co 13.5 usando os 7 temas de setembro como categorias. Escreva uma avaliação honesta de cada uma. Ore sobre o mais fraco.',
      notas: [
        'EDWARDS, Jonathan. <em>Religious Affections</em>. New Haven: Yale, 1959. O tratado mais profundo sobre como distinguir graça genuína de contrafação religiosa — o auto-exame puritano por excelência.',
      ],
      notaInicio: 426,
    },
    {
      dia: 270, data: '27 de setembro', tema: 'Westminster e CB 1689: Convergência e Distinção',
      capitulo: 'CFW Cap. XIV–XX vs. CB 1689 Cap. XIV–XX', versiculo: 'Efésios 4.3',
      versiculoTexto: 'Procurando guardar a unidade do Espírito pelo vínculo da paz.',
      confissaoTexto: 'CFW e CB 1689 compartilham os fundamentos doutrinários de setembro — fé, arrependimento, boas obras, perseverança, assurance, lei, liberdade — com diferenças secundárias que não impedem a comunhão entre crentes confessionais.',
      cfwRef: 'CFW XIV–XX comparado com CB 1689 XIV–XXI', cfwComparacao: 'As diferenças principais entre CFW e CB 1689 nos capítulos de setembro são mínimas em fundo doutrinário — principalmente de nuance e ênfase, não de substância.',
      exposicao: 'Ef 4.3 chama à unidade — que os reformados e batistas confessionais compartilham em setembro. CFW e CB 1689 concordam em: fé como dom do Espírito (XIV), arrependimento como graça evangélica (XV), boas obras como fruto da salvação (XVI), perseverança pela fidelidade de Deus (XVII), assurance baseada em promessa, frutos e Espírito (XVIII), lei moral como regra permanente (XIX), liberdade cristã como liberdade da condenação (XX). As diferenças nos capítulos sobre sacramentos e governo eclesiástico são reais mas não impedem o reconhecimento mútuo como irmãos.',
      reforco: 'A convergência entre CFW e CB 1689 em setembro é maior do que as diferenças. Crentes confessionais das duas tradições são irmãos no mesmo Evangelho.',
      aplicacoes: {
        digital: 'Medite em Ef 4.1-6. Como a unidade do Espírito se manifesta entre crentes de tradições confessionais diferentes?',
        familia: 'Conversem: "Temos amigos em igrejas presbiterianas ou reformadas? Como vemos a relação com eles à luz dos temas de setembro?"',
        filhos: 'Ensine: "Há cristãos em outras igrejas que creem nas mesmas coisas importantes que nós. São nossos irmãos em Cristo."',
        homens: 'O homem que conhece tanto a CB 1689 quanto a CFW tem perspectiva ecumênica madura — sabe onde concordar e onde diferir com integridade.',
        mulheres: 'A mulher formada nas confissões tem clareza doutrinária que permite comunhão genuína além das fronteiras denominacionais.',
        igreja: 'A congregação que conhece tanto CB 1689 quanto CFW pode cooperar com igrejas irmãs com clareza sobre o que compartilha e o que diverge.',
      },
      oracao: 'Senhor, que a unidade do Espírito que compartilhamos com outros crentes confessionais seja visível em nossa postura de irmandade — discordando onde a Escritura exige, concordando onde o Evangelho une. Amém.',
      reflexao: 'Você tem relacionamentos genuínos com crentes confessionais de outras tradições (presbiterianos, reformados)? O que você compartilha? O que difere?',
      aplicacao: 'Leia um capítulo paralelo de CFW e CB 1689 (por ex., sobre fé ou arrependimento). Identifique concordâncias e diferenças. Ore pela unidade do Corpo de Cristo.',
      notas: [
        'REEVES, Michael e CHESTER, Tim. <em>Why the Reformation Still Matters</em>. Wheaton: Crossway, 2016. A herança compartilhada entre todas as tradições confessionais reformadas.',
      ],
      notaInicio: 443,
    },
    {
      dia: 271, data: '28 de setembro', tema: 'Aplicação Prática: Vivendo CFW XIV–XX',
      capitulo: 'CFW Cap. XIV–XX — Vida Prática', versiculo: 'Colossenses 3.16',
      versiculoTexto: 'A palavra de Cristo habite em vós ricamente, em toda a sabedoria, ensinando-vos e admoestando-vos uns aos outros com salmos, hinos e cânticos espirituais, com graça, cantando em vossos corações ao Senhor.',
      confissaoTexto: 'As doutrinas de setembro não são exercício acadêmico — são realidades que devem habitar ricamente no crente, produzindo transformação concreta na fé, no arrependimento, nas obras, na perseverança e na liberdade.',
      cfwRef: 'CFW XIV–XX — praxis', cfwComparacao: 'CFW e CB 1689 ensinam que doutrina correta deve produzir vida correta — a ortopraxia é consequência da ortodoxia.',
      exposicao: 'Cl 3.16 instrui que a Palavra de Cristo habite "ricamente" — não de forma superficial ou ocasional. As doutrinas de setembro devem morar no crente como hóspedes permanentes que transformam a casa. Fé que habita ricamente produz confiança genuína. Arrependimento que habita ricamente produz confissão regular. Assurance que habita ricamente produz paz constante. A doutrina que não transforma não habitou ricamente — apenas passou de visita.',
      reforco: 'Doutrina que não transforma o caráter, as relações e o serviço cotidiano não foi genuinamente absorvida — ficou no nível do conhecimento, não da habitação.',
      aplicacoes: {
        digital: 'Leia Cl 3.12-17. Medite: "Qual das doutrinas de setembro transformou mais concretamente minha vida neste mês?"',
        familia: 'Conversem: "Como as doutrinas de setembro mudaram nossas conversas, nossas orações, nosso serviço uns aos outros?"',
        filhos: 'Pergunte: "O que você aprendeu em setembro que vai usar amanhã na escola ou com amigos?"',
        homens: 'O homem que integra as doutrinas de setembro à vida prática — trabalho, liderança familiar, serviço na congregação — é discípulo maduro.',
        mulheres: 'A mulher que deixa as verdades de setembro habitarem ricamente em sua vida — transformando relacionamentos, prioridades e serviço — cresce em sabedoria prática.',
        igreja: 'A congregação que aplica as doutrinas de setembro — fé que confia, arrependimento que restaura, obras que glorificam, assurance que liberta — é Igreja viva e missionária.',
      },
      oracao: 'Senhor, que as doutrinas de setembro habitem ricamente em mim — não como conhecimento acumulado, mas como realidades transformadoras. Que outubro me encontre mais parecido com Cristo do que setembro me achou. Amém.',
      reflexao: 'Das sete doutrinas de setembro, qual transformou mais concretamente sua vida? Qual ficou apenas no nível do conhecimento?',
      aplicacao: 'Escreva uma lista de 7 transformações práticas que setembro deveria produzir — uma para cada doutrina. Avalie quais já estão acontecendo.',
      notas: [
        'DEGROMEND, Sam. <em>Formed for the Glory of God</em>. Downers Grove: IVP, 2012. Como a doutrina forma o caráter — o elo entre ortodoxia e ortopraxia.',
      ],
      notaInicio: 460,
    },
    {
      dia: 272, data: '29 de setembro', tema: 'Oração Formada pela Doutrina de Setembro',
      capitulo: 'CFW Cap. XIV–XX — Oração', versiculo: 'Efésios 3.16-17',
      versiculoTexto: 'Para que, segundo as riquezas da sua glória, vos conceda que sejais corroborados com poder pelo seu Espírito no homem interior; que Cristo habite pela fé nos vossos corações.',
      confissaoTexto: 'A oração formada pelas doutrinas de setembro é oração que pede fé genuína, arrependimento real, boas obras corretas, perseverança fiel, assurance fundada, uso correto da lei e liberdade sem licença.',
      cfwRef: 'CFW XXI.3 — sobre a oração', cfwComparacao: 'CFW XXI instrui sobre oração como parte do culto religioso; as doutrinas de setembro formam o conteúdo e a estrutura da oração madura.',
      exposicao: 'Ef 3.16-17 é a oração de Paulo pelos efésios: que o Espírito fortaleça o homem interior, que Cristo habite pela fé. As doutrinas de setembro formam a gramática da oração madura: pede-se fé que recebe Cristo (XIV), arrependimento que afasta do pecado (XV), boas obras que expressam obediência (XVI), perseverança que Deus garante (XVII), assurance que o Espírito confirma (XVIII), obediência à lei como guia (XIX) e liberdade que não é licença (XX). A doutrina que não alimenta a oração ainda não foi absorvida.',
      reforco: 'Doutrina que não alimenta a oração ficou no cérebro — não chegou ao coração. A verdade de Deus deve mover à adoração e à petição.',
      aplicacoes: {
        digital: 'Leia Ef 3.14-21. Ore a oração de Paulo pelos efésios aplicando cada doutrina de setembro.',
        familia: 'Façam juntos uma oração de família cobrindo os 7 temas de setembro — cada membro orando por um tema.',
        filhos: 'Ensine as crianças a orar com conteúdo doutrinário — não apenas lista de pedidos, mas adoração baseada em quem Deus é.',
        homens: 'O homem cuja oração é formada pela doutrina ora com profundidade que sustenta a fé nos momentos de seca espiritual.',
        mulheres: 'A mulher que ora com gramática doutrinária — pedindo as coisas que Deus prometeu, nos termos que a Escritura usa — tem vida de oração robusta.',
        igreja: 'A congregação que ora com conteúdo doutrinário — em vez de apenas necessidades imediatas — pratica a oração que Paulo ensina em Ef 3.',
      },
      oracao: 'Pai de glória, fortifica-me pelo Espírito no homem interior. Que a fé de setembro, o arrependimento genuíno, as obras corretas, a perseverança garantida, a assurance fundada, a lei amada e a liberdade exercida com santidade — habitam em mim pela fé. Em Cristo. Amém.',
      reflexao: 'Sua oração é formada pela doutrina — pede as coisas que Deus prometeu — ou é lista de desejos pessoais sem fundamento na Palavra?',
      aplicacao: 'Escreva uma oração de 7 parágrafos — um para cada tema de setembro. Use versículos-chave de cada capítulo. Ore com esse texto como guia por uma semana.',
      notas: [
        'MILLER, Paul. <em>A Praying Life</em>. Colorado Springs: NavPress, 2009. Como a doutrina alimenta e transforma a vida de oração — o mais prático dos livros sobre oração.',
      ],
      notaInicio: 477,
    },
    {
      dia: 273, data: '30 de setembro', tema: 'Síntese de Setembro: CFW Cap. XIV–XX',
      capitulo: 'CFW Cap. XIV–XX — Revisão Final', versiculo: 'Filipenses 3.12',
      versiculoTexto: 'Não que já o tenha alcançado, ou que já seja perfeito; mas prossigo para o ganhar, pois também fui ganho por Cristo Jesus.',
      confissaoTexto: 'Setembro percorreu a vida cristã madura conforme a Westminster: fé que recebe Cristo, arrependimento que afasta do pecado, boas obras que glorificam a Deus, perseverança que Deus garante, assurance que o Espírito confirma, lei moral que guia e liberdade cristã que liberta para servir.',
      cfwRef: 'CFW XIV–XX — síntese final', cfwComparacao: 'A Westminster e a CB 1689 convergem plenamente em setembro — as doutrinas da vida cristã são o coração compartilhado de toda a tradição reformada-batista confessional.',
      exposicao: 'Fp 3.12 é o lema do peregrino cristão: "não perfeito, mas prosseguindo." Setembro não produziu perfeição — produziu direção. As sete doutrinas percorridas não são pontos chegados, mas bússolas para o caminho. Fé que cresce, arrependimento que se aprofunda, obras que se multiplicam, perseverança que se demonstra, assurance que se fortalece, lei que se ama mais, liberdade que se exerce com mais sabedoria. Outubro entrará em CFW XXI–XXV: culto, sábado, juramentos, governo civil e casamento.',
      reforco: 'Setembro construiu a vida cristã interior: fé, arrependimento, obediência, perseverança, certeza, orientação e liberdade. Outubro construirá a vida cristã exterior: culto, comunidade e ordem.',
      aplicacoes: {
        digital: 'Leia Fp 3.7-14. Medite: "Em qual das sete doutrinas de setembro você mais avançou? Em qual mais precisa prosseguir?"',
        familia: 'Façam juntos uma linha do tempo de setembro: Fé (244-246), Arrependimento (247-250), Boas Obras (251-253), Perseverança (254-256), Assurance (257-259), Lei (260-262), Liberdade (263-265), Sínteses (266-272). Ore pela congregação.',
        filhos: 'Pergunte: "O que setembro ensinou que você vai lembrar para sempre?" Registre as respostas.',
        homens: 'O homem que completou setembro tem as ferramentas internas da vida cristã madura: fé, arrependimento, obediência, perseverança, certeza, orientação e liberdade.',
        mulheres: 'A mulher que percorreu setembro foi formada no interior da vida cristã — as realidades que sustentam a fidelidade cotidiana quando as circunstâncias são difíceis.',
        igreja: 'A Igreja que ensina CFW XIV–XX forma crentes com vida interior robusta — que perseveram não por força própria, mas pelo Deus que garante, assura e liberta.',
      },
      oracao: 'Pai, obrigado por setembro — por fé, arrependimento, boas obras, perseverança, assurance, lei e liberdade. Que outubro nos leve ao culto, ao sábado, às relações e à ordem que Cristo quer para sua Igreja. Não perfeitos — mas prosseguindo. Em Cristo. Amém.',
      reflexao: 'Setembro foi sobre a vida cristã interior. Como as sete doutrinas estão produzindo fruto em sua vida exterior — relacionamentos, serviço, comunidade?',
      aplicacao: 'Escreva uma carta de meia página resumindo o que setembro ensinou. Guarde para reler em dezembro. Ore pedindo que outubro — culto, sábado, governo civil e casamento — construa sobre os fundamentos de setembro.',
      notas: [
        'BEEKE, Joel e JONES, Mark. <em>A Puritan Theology</em>. Grand Rapids: Reformation Heritage, 2012. A síntese mais completa da teologia puritana que forma o pano de fundo de todos os capítulos de setembro.',
        'HELM, Paul. <em>The Christian\'s Great Interest</em> (ed.). Edinburgh: Banner of Truth, 1991. William Guthrie — o clássico escocês sobre a assurance e a vida cristã genuína.',
      ],
      notaInicio: 494,
    },
  ];
  return dias.map(blocoW);
}
`;

// Replace the old function with the new one
const startIdx = content.indexOf('\nfunction gerarDiasSetembro(): DiaConfessional[] {');
if (startIdx === -1) { console.error('ERRO: função não encontrada'); process.exit(1); }

const beforeFn = content.substring(0, startIdx);
fs.writeFileSync(filePath, beforeFn + newFn, 'utf8');
console.log('✅ gerarDiasSetembro() substituída com CFW XIV-XX');
console.log('Linhas:', (beforeFn + newFn).split('\n').length);
