// gerar_dezembro.cjs — CFW Cap. XXX–XXXIII (dias 334–364)
const fs = require('fs');
const path = require('path');
const filePath = path.join(__dirname, 'src/data/devocionalConfessional.ts');
let content = fs.readFileSync(filePath, 'utf8');

const dezembro = `
function gerarDiasDezembroA(): DiaConfessional[] {
  const dias: DiaCompacto[] = [
    // ── CFW XXX — Disciplina Eclesiástica ──────────────────────────────────
    {
      dia: 334, data: '1 de dezembro', tema: 'Disciplina Eclesiástica: Poder das Chaves',
      capitulo: 'CFW Cap. XXX.1', versiculo: 'Mateus 16.19',
      devocional: 'CFW XXX.1 afirma que o Senhor Jesus, como rei e cabeça de sua Igreja, instituiu o governo eclesiástico pelas mãos de oficiais da Igreja, distintos do magistrado civil. O "poder das chaves" (Mt 16.19; 18.18) inclui a disciplina eclesiástica: a autoridade de ligar e desligar, de admitir e excluir da comunhão. Essa autoridade não é civil nem pessoal — é eclesiástica, exercida pelos presbíteros em nome de Cristo, para a pureza da Igreja e a restauração do transgressor.',
      cfwRef: 'CFW XXX.1', cfwComparacao: 'CB 1689 Cap. XXVI.9-15 trata da disciplina com linguagem similar; a diferença está no governo (presbiterial vs. congregacional), não no princípio disciplinar.',
      reforco: 'Disciplina eclesiástica não é castigo humano — é exercício do poder de Cristo para proteger o rebanho e restaurar o transgressor.',
      aplicacao: 'Você conhece o processo de disciplina de sua iglesia? Entendê-lo é essencial para saber como a Igreja cuida de seus membros.',
      notas: [
        'BANNERMAN, James. <em>The Church of Christ</em>. Edinburgh: Banner of Truth, 1960. A obra mais completa sobre ecclesiologia e disciplina na tradição reformada.',
      ],
      notaInicio: 80,
    },
    {
      dia: 335, data: '2 de dezembro', tema: 'Censuras Eclesiásticas: Repreensão e Suspensão',
      capitulo: 'CFW Cap. XXX.2', versiculo: 'Mateus 18.15-17',
      devocional: 'CFW XXX.2 lista as censuras eclesiásticas: repreensão, suspensão da Ceia e excomunhão — aplicadas conforme a gravidade da ofensa e o arrependimento do transgressor. O processo de Mateus 18 é progressivo: conversa pessoal, testemunhas, Igreja — excomunhão somente como último recurso. A meta não é punir, mas restaurar: "para que o seu espírito seja salvo" (1Co 5.5). A Igreja que nunca exerce disciplina não ama seus membros; a que a exerce mecanicamente, sem busca de restauração, perverte o poder das chaves.',
      cfwRef: 'CFW XXX.2', cfwComparacao: 'CB 1689 Cap. XXVI.13-15 descreve o mesmo processo progressivo — repreensão, exclusão da Ceia, excomunhão; com ênfase congregacional no processo decisório.',
      reforco: 'Disciplina sem amor é violência; amor sem disciplina é negligência. A Igreja reformada une ambos seguindo Mateus 18.',
      aplicacao: 'Leia Mateus 18.15-17 devagar. Este processo pressupõe que você conhece seus irmãos de congregação o suficiente para "ir falar com ele" quando erra. Você conhece?',
      notas: [],
    },
    {
      dia: 336, data: '3 de dezembro', tema: 'Excomunhão: Ato de Amor Extremo',
      capitulo: 'CFW Cap. XXX.3', versiculo: '1 Coríntios 5.5',
      devocional: 'CFW XXX.3 define a excomunhão como exclusão da comunhão da Igreja — o mais severo dos exercícios do poder das chaves. Paulo a aplica ao incestuoso de Corinto: "para a destruição da carne, para que o espírito seja salvo" (1Co 5.5). Paradoxalmente, excomungar é ato de amor: ao retirar a proteção da comunhão da Igreja, a pessoa é exposta às consequências do pecado sem a anestesia da aceitação religiosa — na esperança de que o arrependimento venha. A restauração é sempre o objetivo. A excomunhão é pena de morte espiritual temporária, não sentença eterna.',
      cfwRef: 'CFW XXX.3', cfwComparacao: 'CB 1689 Cap. XXVI.15 é equivalente — excomunhão como último recurso disciplinar, com esperança de restauração.',
      reforco: 'Igreja que nunca excomungou em séculos provavelmente não tem disciplina real — e isso prejudica os membros e desonra Cristo.',
      aplicacao: 'Ore por alguém que você conhece que está vivendo em pecado sem arrependimento, afastado da Igreja. Ore para que Deus o restaure.',
      notas: [],
    },
    {
      dia: 337, data: '4 de dezembro', tema: 'Restauração: O Fim da Disciplina é a Graça',
      capitulo: 'CFW Cap. XXX.4', versiculo: '2 Coríntios 2.7-8',
      devocional: 'CFW XXX.4 afirma que os que se arrependem devem ser absolvidos das censuras eclesiásticas e restaurados à comunhão. Paulo instrui os coríntios: "deveis antes perdoar e consolar... confirmar o amor para com ele" (2Co 2.7-8). A disciplina que não termina em restauração falhou em seu propósito. A Igreja que pune sem perdoar ou que exige penitência pública humilhante além do que a Escritura exige perverte as chaves. A abundância do perdão de Cristo deve modelar a generosidade da restauração eclesiástica.',
      cfwRef: 'CFW XXX.4', cfwComparacao: 'CB 1689 Cap. XXVI.15 inclui a mesma dimensão restaurativa — o arrependimento cessa a disciplina e a comunhão é restaurada.',
      reforco: 'Comunidades que dificultam a restauração após a disciplina contradizem o Evangelho de graça que professam.',
      aplicacao: 'Você conhece alguém que foi disciplinado pela Igreja e se arrependeu mas sente dificuldade de ser recebido de volta? Acolha-o ativamente.',
      notas: [],
    },
    // ── CFW XXXI — Concílios e Sínodos ─────────────────────────────────────
    {
      dia: 338, data: '5 de dezembro', tema: 'Concílios: Autoridade Derivada e Limitada',
      capitulo: 'CFW Cap. XXXI.1', versiculo: 'Atos 15.2',
      devocional: 'CFW XXXI.1 afirma que sínodos e concílios devem ser compostos por presbíteros e outras pessoas representativas das igrejas, para considerar e determinar controvérsias de fé e casos de consciência. O modelo é o Concílio de Jerusalém (At 15): representantes reunidos, deliberação pela Escritura, decisão que vincula as igrejas. A autoridade dos concílios não é absoluta — é derivada de Cristo e limitada pela Palavra. Concílio que contradiz a Escritura perde sua autoridade.',
      cfwRef: 'CFW XXXI.1', cfwComparacao: 'CB 1689 Cap. XXVI.14-15 limita a autoridade aos presbíteros locais — a diferença presbiteriana/congregacional está precisamente no papel dos concílios supralocais.',
      reforco: 'A estrutura presbiteriana (sessões, presbitérios, sínodos, assembleia geral) expressa a catolicidade da Igreja — nenhuma congregação é uma ilha.',
      aplicacao: 'Sua denominação tem estrutura conciliar? Conheça como as decisões são tomadas — isso afeta diretamente sua congregação local.',
      notas: [
        'HODGE, Charles. <em>Church Polity</em>. Philadelphia: Presbyterian Board, 1878. A defesa clássica do presbiterianismo e da autoridade conciliar.',
      ],
      notaInicio: 81,
    },
    {
      dia: 339, data: '6 de dezembro', tema: 'Quando Obedecer e Quando Resistir aos Concílios',
      capitulo: 'CFW Cap. XXXI.3', versiculo: 'Gálatas 1.8',
      devocional: 'CFW XXXI.3 é notável: afirma que os decretos de sínodos e concílios devem ser recebidos com reverência e submissão — mas não são infalíveis. Se contradizem a Palavra de Deus, devem ser recusados. Paulo não vacila: "se nós mesmos, ou um anjo do céu, vos anunciar evangelho diferente do que vos anunciamos, seja anátema" (Gl 1.8). A Reforma foi possível porque homens como Lutero em Worms reconheceram: "minha consciência está cativa à Palavra de Deus — não posso retratar." Sola Scriptura implica que nenhum concílio humano tem a última palavra.',
      cfwRef: 'CFW XXXI.3', cfwComparacao: 'CB 1689 Cap. XXVI.9 é equivalente — a Escritura como árbitro final sobre qualquer decisão eclesiástica ou conciliar.',
      reforco: 'Confiar em concílios acima da Escritura é papismo sem Papa; ignorar concílios completamente é independentismo sem freio — ambos são erros.',
      aplicacao: 'Você conhece as decisões doutrinárias de sua denominação? Saber onde a Igreja se posicionou ajuda a discernir onde obedece à Escritura e onde pode errar.',
      notas: [],
    },
    {
      dia: 340, data: '7 de dezembro', tema: 'Concílios e a Unidade da Igreja',
      capitulo: 'CFW Cap. XXXI.1 — Unidade', versiculo: 'Efésios 4.3',
      devocional: 'Os concílios existem para preservar a unidade da fé — "guardando a unidade do Espírito pelo vínculo da paz" (Ef 4.3). A fragmentação do protestantismo em milhares de denominações sem nenhuma estrutura de prestação de contas mútua contradiz a catolicidade da Igreja. Os concílios não eliminam a diversidade, mas criam estrutura para que a fé seja debatida, disputas resolvidas e erros corrigidos — sem que cada congregação seja juiz de si mesma. O Concílio de Niceia (325), de Calcedônia (451) e de Westminster (1643-1649) são exemplos de como concílios guardam a fé.',
      cfwRef: 'CFW XXXI.1 — unidade', cfwComparacao: 'CB 1689 é mais reservado quanto ao papel dos concílios supralocais — refletindo a ênfase batista na autonomia congregacional.',
      reforco: 'O protestantismo sem concílios produz individualismo eclesiástico — cada pastor decide sua doutrina sem prestação de contas.',
      aplicacao: 'Pesquise as decisões do Concílio de Niceia. Você beneficia dessa decisão conciliar toda vez que recita o Credo Niceno.',
      notas: [],
    },
    {
      dia: 341, data: '8 de dezembro', tema: 'Presbiterianismo: Governo de Cristo pelos Presbíteros',
      capitulo: 'CFW Cap. XXXI — Governo', versiculo: '1 Timóteo 5.17',
      devocional: 'CFW XXXI pressupõe o governo presbiteriano: presbíteros (pastores e diáconos) governam a Igreja em colegiado, não monárquica (episcopado) nem democraticamente (congregacionalismo). "Os presbíteros que governam bem sejam considerados dignos de dupla honra" (1Tm 5.17). O governo colegiado dos presbíteros distribui a autoridade de Cristo sem concentrá-la em um homem ou em uma votação congregacional. É governo de Cristo por meio de oficiais escolhidos, ordenados e responsáveis uns perante os outros.',
      cfwRef: 'CFW XXXI — governo', cfwComparacao: 'CB 1689 adota governo congregacional — cada igreja local é autônoma, sem presbitérios ou sínodos supralocais com autoridade vinculante.',
      reforco: 'O debate sobre formas de governo eclesiástico (episcopal, presbiteriano, congregacional) não é questão menor — afeta como a Igreja resolve disputas, ordena ministros e mantém a fé.',
      aplicacao: 'Estude a diferença entre governo episcopal, presbiteriano e congregacional. Qual forma sua congregação adota? Por quê?',
      notas: [],
    },
    {
      dia: 342, data: '9 de dezembro', tema: 'Síntese: Disciplina e Governo a Serviço da Graça',
      capitulo: 'CFW Cap. XXX–XXXI — Síntese', versiculo: '1 Pedro 5.2-3',
      devocional: '"Apascentai o rebanho de Deus... não como dominando sobre a herança de Deus, mas servindo de exemplo ao rebanho" (1Pe 5.2-3). A disciplina eclesiástica (CFW XXX) e os concílios (CFW XXXI) existem a serviço da graça, não do poder. Os presbíteros não governam como chefes de empresa — são pastores que servem ao Bom Pastor. A estrutura conciliar existe para proteger o rebanho, não para criar hierarquia. Quando governo e disciplina são exercidos com mansidão pastoral e firmeza doutrinária, são expressão do cuidado de Cristo por sua Igreja.',
      cfwRef: 'CFW XXX–XXXI — síntese', cfwComparacao: 'CFW e CB 1689 concordam em princípio — disciplina e governo existem para edificação, não dominação; diferem na estrutura que melhor garante isso.',
      reforco: 'Governo eclesiástico sem espírito pastoral vira clericalismo; espírito pastoral sem governo vira sentimentalismo sem estrutura.',
      aplicacao: 'Ore por seus presbíteros e pastores pelo nome. Eles exercem uma responsabilidade pesada — prestam contas pelo seu rebanho (Hb 13.17).',
      notas: [
        'BAVINCK, Herman. <em>Reformed Dogmatics</em>, vol. 4. Grand Rapids: Baker, 2008. Cap. sobre a Igreja — a teologia reformada mais completa sobre governo, disciplina e sacramentos.',
      ],
      notaInicio: 82,
    },
    // ── CFW XXXII — Estado dos Mortos e Ressurreição ────────────────────────
    {
      dia: 343, data: '10 de dezembro', tema: 'O Estado dos Mortos: Entre a Morte e a Ressurreição',
      capitulo: 'CFW Cap. XXXII.1', versiculo: 'Lucas 23.43',
      devocional: 'CFW XXXII.1 ensina que as almas dos justos, ao morrer, vão imediatamente a Deus — "em paraíso" (Lc 23.43), "com Cristo" (Fp 1.23). As almas dos ímpios são lançadas ao inferno. Não há purgatório (invenção medieval sem base bíblica), não há "sono da alma" (aniquilação temporária), não há segunda chance após a morte. O crente que morre entra imediatamente na presença de Cristo — não em plenitude final (aguarda a ressurreição do corpo), mas em comunhão consciente com o Senhor.',
      cfwRef: 'CFW XXXII.1', cfwComparacao: 'CB 1689 Cap. XXXI.1 usa linguagem idêntica — almas dos justos imediatamente com Cristo; almas dos ímpios no inferno. Rejeição do purgatório e do sono da alma.',
      reforco: 'O purgatório nega a suficiência da obra de Cristo; o sono da alma nega a continuidade consciente da pessoa após a morte.',
      aplicacao: 'Um crente que você ama morreu? Ele está com Cristo agora — não dormindo, não sofrendo no purgatório, não esperando. Descanse nessa promessa.',
      notas: [
        'HOEKEMA, Anthony. <em>The Bible and the Future</em>. Grand Rapids: Eerdmans, 1979. O estudo escatológico mais completo e equilibrado na tradição reformada — cobre CFW XXXII-XXXIII.',
      ],
      notaInicio: 83,
    },
    {
      dia: 344, data: '11 de dezembro', tema: 'A Ressurreição do Corpo: Esperança Corporal',
      capitulo: 'CFW Cap. XXXII.2', versiculo: '1 Coríntios 15.42-44',
      devocional: 'CFW XXXII.2 afirma a ressurreição do corpo no último dia — os mesmos corpos que foram depositados na terra serão levantados, embora com qualidades diferentes. O Evangelho não salva apenas almas — salva pessoas, e pessoas são corpos além de almas. "Semeia-se corpo natural, ressuscita corpo espiritual" (1Co 15.44) — não um corpo diferente, mas o mesmo corpo transformado e glorificado. A ressurreição de Cristo é a garantia e primícia da nossa: "como trouxemos a imagem do terreno, assim traremos a imagem do celestial" (1Co 15.49).',
      cfwRef: 'CFW XXXII.2', cfwComparacao: 'CB 1689 Cap. XXXI.2 é idêntico — ressurreição corporal do mesmo corpo, transformado; esperança física, não apenas espiritual.',
      reforco: 'Gnosticismo cristão — a ideia de que a salvação é "escapar do corpo" — é heresia. O corpo é bom e será redimido, não descartado.',
      aplicacao: 'Cuide do seu corpo como templo do Espírito e como objeto da redenção futura. Saúde, descanso e beleza criacional importam escatologicamente.',
      notas: [],
    },
    {
      dia: 345, data: '12 de dezembro', tema: 'A Ressurreição e a Dor do Luto Cristão',
      capitulo: 'CFW Cap. XXXII.2 — Luto', versiculo: '1 Tessalonicenses 4.13-14',
      devocional: '"Não queremos, irmãos, que sejais ignorantes acerca dos que dormem, para que não vos entristeçais como os demais que não têm esperança" (1Ts 4.13). Paulo não diz: "não chorem." Diz: "não chorem como quem não tem esperança." O luto cristão é real — perdemos alguém que amamos. Mas é luto com promessa: "Deus os que dormiram em Jesus, também os tornará a trazer com ele" (1Ts 4.14). A doutrina da ressurreição não remove a dor — a envolve em esperança. Chore, mas chore com esperança.',
      cfwRef: 'CFW XXXII.2 — luto', cfwComparacao: 'CFW e CB 1689 concordam — a ressurreição é a esperança concreta do luto cristão; a doutrina é pastoral, não apenas dogmática.',
      reforco: 'Negar a realidade da dor no luto é estoicismo, não fé cristã. A ressurreição não proíbe o choro — dá-lhe direção.',
      aplicacao: 'Você conhece alguém enlutado? Compartilhe 1Ts 4.13-18 — não como resposta fácil, mas como fundamento de esperança compartilhada.',
      notas: [],
    },
    {
      dia: 346, data: '13 de dezembro', tema: 'Corpo e Alma: Unidade da Pessoa Humana',
      capitulo: 'CFW Cap. XXXII — Antropologia', versiculo: 'Gênesis 2.7',
      devocional: 'A ressurreição do corpo pressupõe a unidade corpo-alma na pessoa humana. Deus criou Adão do pó e soprou nele o fôlego de vida — o resultado foi "alma vivente" (Gn 2.7), não uma alma presa num corpo. O dualismo platônico — corpo como prisão da alma — foi importado pela filosofia grega e corrompeu a antropologia cristã. A Bíblia não diz: "você tem um corpo." Diz: "você é um corpo animado pela alma." A ressurreição restaura essa unidade original, glorificada.',
      cfwRef: 'CFW XXXII — antropologia', cfwComparacao: 'CFW e CB 1689 pressupõem a mesma antropologia unitária — pessoa humana como unidade corpo-alma destinada à ressurreição corporal.',
      reforco: 'O dualismo que despreza o corpo (ascetismo) ou o supervaloriza (hedonismo) ambos erram sobre a natureza humana que a ressurreição vai glorificar.',
      aplicacao: 'Como você trata seu corpo? Tanto o ascetismo quanto o hedonismo são distorções. O corpo é templo (1Co 6.19) e objeto da redenção futura.',
      notas: [],
    },
    {
      dia: 347, data: '14 de dezembro', tema: 'A Ressurreição de Cristo: Garantia da Nossa',
      capitulo: 'CFW Cap. XXXII.2 — Cristo', versiculo: '1 Coríntios 15.20',
      devocional: '"Cristo ressuscitou dentre os mortos, sendo ele as primícias dos que dormem" (1Co 15.20). A ressurreição de Cristo não é caso isolado — é início da ressurreição universal. Ele ressuscitou como "primícias": a primeira parte da colheita que garante o resto. Nossa ressurreição não é metáfora, não é símbolo de esperança vaga — é consequência lógica e teológica da ressurreição de Jesus. "Se Cristo não ressuscitou, é vã a vossa fé" (1Co 15.17). Mas ele ressuscitou. E nós também ressuscitaremos.',
      cfwRef: 'CFW XXXII.2 — Cristo', cfwComparacao: 'CFW e CB 1689 concordam — a ressurreição de Cristo é fundamento e garantia da ressurreição dos crentes.',
      reforco: 'O Evangelho é anúncio de fatos históricos (morte, ressurreição de Cristo), não apenas de princípios morais ou experiências subjetivas.',
      aplicacao: 'Memorize 1Co 15.20-22. Esses versículos são o coração da escatologia cristã — e o fundamento da esperança que supera qualquer sofrimento presente.',
      notas: [],
    },
    {
      dia: 348, data: '15 de dezembro', tema: 'Imortalidade da Alma e Ressurreição do Corpo',
      capitulo: 'CFW Cap. XXXII.1-2 — Distinção', versiculo: 'Filipenses 1.23',
      devocional: 'CFW distingue duas etapas da esperança cristã: (1) a imortalidade da alma — a alma continua consciente após a morte, com Cristo (Fp 1.23) — e (2) a ressurreição do corpo no último dia, quando alma e corpo se reunirão glorificados. Gregos acreditavam na imortalidade da alma, mas rejeitavam a ressurreição do corpo (At 17.32). A esperança cristã é mais radical: não apenas a alma sobrevive — a pessoa inteira é redimida. A imortalidade da alma é preliminar; a ressurreição do corpo é a esperança definitiva.',
      cfwRef: 'CFW XXXII.1-2 — distinção', cfwComparacao: 'CFW e CB 1689 concordam — duas etapas: estado intermediário (alma com Cristo) e estado final (ressurreição corporal).',
      reforco: 'Confundir imortalidade da alma (estado intermediário) com ressurreição do corpo (estado final) empobrece a esperança cristã.',
      aplicacao: 'Explique a diferença entre "ir para o céu ao morrer" e "a ressurreição dos mortos". Ambos são reais, mas distintos.',
      notas: [],
    },
    {
      dia: 349, data: '16 de dezembro', tema: 'O Novo Corpo: Glorioso, Poderoso, Incorruptível',
      capitulo: 'CFW Cap. XXXII.2 — Novo Corpo', versiculo: '1 Coríntios 15.52-53',
      devocional: '"Num momento, num abrir e fechar de olhos, ao som da última trombeta... os mortos ressuscitarão incorruptíveis, e nós seremos transformados" (1Co 15.52). O novo corpo não será limitado pela doença, envelhecimento, fadiga ou morte. Paulo usa quatro antíteses: corruptível/incorruptível, ignominioso/glorioso, fraco/poderoso, natural/espiritual. O mesmo corpo — mas totalmente transformado. Para os que sofrem em corpos enfermos, deficientes ou envelheci dos, esta é promessa de libertação total. A esperança não é escapar do corpo — é ter o corpo redimido.',
      cfwRef: 'CFW XXXII.2 — novo corpo', cfwComparacao: 'CFW e CB 1689 concordam — o mesmo corpo ressuscitará transformado; nenhuma vaguidade sobre o que "ressurreição" significa.',
      reforco: 'A esperança da ressurreição consola diretamente o sofrimento físico — não é abstração teológica, é promessa pastoral.',
      aplicacao: 'Você ou alguém que ama sofre com um corpo doente ou limitado? Leia 1Co 15.42-44 como promessa pessoal. Esse corpo será glorificado.',
      notas: [],
    },
    {
      dia: 350, data: '17 de dezembro', tema: 'A Nova Criação: Não Apenas Almas no Céu',
      capitulo: 'CFW Cap. XXXII — Nova Criação', versiculo: 'Romanos 8.21',
      devocional: 'A ressurreição do corpo aponta para além dos indivíduos — para a renovação de toda a criação. "A própria criação também será libertada da escravidão da corrupção para a liberdade da glória dos filhos de Deus" (Rm 8.21). O destino final não é almas flutuando no céu etéreo — é nova criação: novos céus e nova terra habitados por pessoas com corpos glorificados. A redenção não descarta a criação material; a renova. O Deus que criou o mundo material não o abandona — o transforma. Nossa esperança é encarnada, material, espacial.',
      cfwRef: 'CFW XXXII — nova criação', cfwComparacao: 'CFW e CB 1689 pressupõem a nova criação como lar eterno dos redimidos; a esperança não é fuga do material, mas sua renovação.',
      reforco: 'Escatologia não é sobre "escapar deste mundo" — é sobre a renovação de toda a criação. Cuidar do mundo criado importa escatologicamente.',
      aplicacao: 'Leia Apocalipse 21.1-5 e Romanos 8.18-25. Compare: qual é o destino final dos redimidos? Como isso muda sua relação com o mundo criado?',
      notas: [],
    },
    {
      dia: 351, data: '18 de dezembro', tema: 'Vivendo à Luz da Ressurreição',
      capitulo: 'CFW Cap. XXXII — Ética Escatológica', versiculo: '1 Coríntios 15.58',
      devocional: 'Paulo encerra o capítulo da ressurreição com ética: "sede firmes, inabaláveis, sempre abundantes na obra do Senhor, sabendo que o vosso trabalho não é vão no Senhor" (1Co 15.58). A esperança da ressurreição não produz passividade — produz firmeza. Saber que o corpo será redimido dignifica o trabalho corporal agora. Saber que a criação será renovada dignifica o cuidado do mundo agora. Escatologia bíblica não aliena do presente — ancora no futuro para agir com mais fidelidade no presente.',
      cfwRef: 'CFW XXXII — ética', cfwComparacao: 'CFW e CB 1689 concordam — a esperança escatológica é fundamento da fidelidade presente, não evasão do presente.',
      reforco: '"Somos tão celestiais que não prestamos para nada terreno" é distorção — a esperança da ressurreição deve produzir mais engajamento, não menos.',
      aplicacao: 'Há algo que você tem procrastinado por sentir que "não adianta"? À luz da ressurreição — o trabalho fiel no Senhor não é vão — faça hoje.',
      notas: [],
    },
    {
      dia: 352, data: '19 de dezembro', tema: 'O Milênio e o Retorno de Cristo: A Esperança Reformada',
      capitulo: 'CFW Cap. XXXII — Escatologia', versiculo: 'Apocalipse 20.6',
      devocional: 'CFW não especifica uma posição milenarista — mas a tradição reformada historicamente favorece o amilenismo ou o pós-milenismo. O que é central: Cristo voltará em poder e glória (Mt 24.30); os mortos ressuscitarão (Jo 5.28-29); haverá juízo final. As especulações sobre tribunais, milênio terreno, raptura secreta e Israel profético carecem de fundamento exegético sólido. O crente reformado vive com esperança: "Maranata — vem, Senhor Jesus!" (Ap 22.20) — sem mapas proféticos especulativos, mas com certeza da vitória final de Cristo.',
      cfwRef: 'CFW XXXII — escatologia', cfwComparacao: 'CFW e CB 1689 concordam — retorno de Cristo, ressurreição, juízo; ambas evitam especulações milenaristas não fundamentadas na Escritura.',
      reforco: 'Obsessão com calendários proféticos e identificação de "sinais dos tempos" distrai da fidelidade presente — o foco deve ser em "sê fiel até a morte" (Ap 2.10).',
      aplicacao: 'Você tem dado mais atenção a especulações proféticas do que à fidelidade diária? Simplifique: Cristo voltará; seja encontrado fiel.',
      notas: [
        'RIDDLEBARGER, Kim. <em>A Case for Amillennialism</em>. Grand Rapids: Baker, 2003. A defesa reformada do amilenismo — equilibrado, exegético, sem sensacionalismo.',
      ],
      notaInicio: 84,
    },
    // ── CFW XXXIII — O Juízo Final ──────────────────────────────────────────
    {
      dia: 353, data: '20 de dezembro', tema: 'O Juízo Final: Cristo, o Juiz',
      capitulo: 'CFW Cap. XXXIII.1', versiculo: 'João 5.22',
      devocional: 'CFW XXXIII.1 afirma que Deus designou um dia em que julgará o mundo em justiça por Jesus Cristo — a quem foi dado todo o poder e julgamento. "Porque o Pai não julga ninguém, mas todo o juízo foi entregue ao Filho" (Jo 5.22). O Juiz do universo é o mesmo que foi julgado em nosso lugar. Aquele que carregou nossos pecados na cruz é quem sentará no trono do julgamento. Para os que estão em Cristo, o juízo é veredicto de justiça — não de graça que ignora a lei, mas de graça que a cumpriu.',
      cfwRef: 'CFW XXXIII.1', cfwComparacao: 'CB 1689 Cap. XXXII.1 usa linguagem idêntica — Cristo como juiz designado pelo Pai; julgamento universal, justo e definitivo.',
      reforco: 'O juízo final não é ameaça para o crente — é promessa de vindicação. Cristo que salvou é o mesmo que julgará.',
      aplicacao: 'Leia João 5.24-29. Para os que creem, o julgamento não é terror — é confirmação do que Cristo já fez. Descanse nessa segurança.',
      notas: [
        'FRAME, John. <em>Systematic Theology</em>. Phillipsburg: P&R, 2013. Cap. sobre escatologia e juízo — sólido, equilibrado, reformado.',
      ],
      notaInicio: 85,
    },
    {
      dia: 354, data: '21 de dezembro', tema: 'O Propósito do Juízo: Manifestação da Glória de Deus',
      capitulo: 'CFW Cap. XXXIII.2', versiculo: 'Romanos 2.5',
      devocional: 'CFW XXXIII.2 ensina que o dia do juízo serve para a manifestação da glória de Deus em sua misericórdia (para os eleitos) e em sua justiça (para os réprobos). O juízo não é cruel — é a vindicação definitiva do caráter de Deus. Um universo sem juízo final seria um universo onde Hitler, Stalin e os maiores criminosos da história ficam sem resposta. Deus não é indiferente à injustiça — ele guarda um dia de ajuste de contas. A misericórdia e a justiça divinas serão plenamente manifestadas diante de toda a criação.',
      cfwRef: 'CFW XXXIII.2', cfwComparacao: 'CB 1689 Cap. XXXII.2 é idêntico — o juízo manifesta tanto a misericórdia (para os eleitos) quanto a justiça (para os réprobos) de Deus.',
      reforco: 'Um Deus sem juízo final não é misericordioso — é indiferente ao sofrimento das vítimas de toda injustiça histórica.',
      aplicacao: 'Você já se sentiu impotente diante de injustiças que parecem não ter resposta? O juízo final é a promessa de que Deus não é indiferente — e que tudo será acertado.',
      notas: [],
    },
    {
      dia: 355, data: '22 de dezembro', tema: 'Juízo e Evangelismo: A Urgência das Boas Novas',
      capitulo: 'CFW Cap. XXXIII.2 — Missão', versiculo: 'Atos 17.30-31',
      devocional: 'Paulo usa o juízo como argumento evangelístico: "Deus... agora ordena a todos os homens em todo lugar que se arrependam; porquanto determinou um dia em que há de julgar o mundo em justiça" (At 17.30-31). A certeza do juízo cria urgência missionária. Não pregamos o Evangelho para escapar do inferno nós mesmos — pregamos porque todos os seres humanos são almas imortais que enfrentarão o Juiz. O amor a Deus e ao próximo, à luz do juízo, nos faz abrir a boca com as boas novas que são o único caminho de escape.',
      cfwRef: 'CFW XXXIII.2 — missão', cfwComparacao: 'CFW e CB 1689 concordam — a certeza do juízo cria urgência missionária; a proclamação do Evangelho é o meio pelo qual Deus chama os eleitos.',
      reforco: 'Omitir o juízo do Evangelho é pregar metade da mensagem — e pregar metade do Evangelho é pregar um Evangelho diferente.',
      aplicacao: 'Você tem orado por pessoas específicas que não conhecem o Evangelho? O juízo final torna essa oração urgente. Ore por três pessoas hoje.',
      notas: [],
    },
    {
      dia: 356, data: '23 de dezembro', tema: 'A Eternidade do Inferno: Juízo que Não Termina',
      capitulo: 'CFW Cap. XXXIII.2 — Inferno', versiculo: 'Mateus 25.46',
      devocional: 'CFW XXXIII.2 afirma que os ímpios receberão punição eterna, e os justos, vida eterna (Mt 25.46). O mesmo adjetivo — aionios — qualifica tanto a punição quanto a vida. Negar a eternidade do inferno (aniquilacionismo, universalismo) exige mudar o significado do mesmo termo que descreve a eternidade da vida eterna. A doutrina não é sadismo teológico — é consequência lógica da santidade infinita de Deus, da gravidade do pecado e da rejeição consciente da graça. O inferno é a resposta de Deus à preferência humana: "Faça-se a tua vontade" — separado de mim para sempre.',
      cfwRef: 'CFW XXXIII.2 — inferno', cfwComparacao: 'CB 1689 Cap. XXXII.2 é idêntico — punição eterna dos ímpios; rejeição do aniquilacionismo e do universalismo.',
      reforco: 'Rejeitar a eternidade do inferno por parecer "cruel" é colocar nosso sentimento acima da Palavra — e minar a urgência do Evangelho.',
      aplicacao: 'A doutrina do inferno eterno deve produzir mais evangelismo, mais oração pelos perdidos, mais compaixão — não mais arrogância ou indiferença.',
      notas: [],
    },
    {
      dia: 357, data: '24 de dezembro', tema: 'Natal: O Juiz que se Fez Julgado',
      capitulo: 'CFW Cap. XXXIII — Natal', versiculo: 'João 3.17',
      devocional: 'Na véspera do Natal, o juízo final e a encarnação se encontram. "Deus não enviou o seu Filho ao mundo para julgar o mundo, mas para que o mundo seja salvo por ele" (Jo 3.17). O Juiz veio primeiro como Salvador. O bebê de Belém é o mesmo que sentará no trono branco do julgamento. A encarnação foi a entrada da solução no problema: Deus se fez homem para que os homens não fossem destruídos pelo juízo. Natal não é sentimentalismo — é escatologia antecipada: o Rei veio e voltará.',
      cfwRef: 'CFW XXXIII — natal', cfwComparacao: 'CFW e CB 1689 não desenvolvem a conexão natal-escatologia, mas ela é inerente à teologia da encarnação: o mesmo Cristo que veio humilde voltará em glória.',
      reforco: 'Natal sem escatologia é sentimental; escatologia sem natal é aterrorizante. Unidos, revelam a graça e a glória do mesmo Cristo.',
      aplicacao: 'Esta noite, ao contemplar o presépio, lembre: o bebê que nasceu é o Juiz que voltará. Adore com gratidão: ele veio para nos salvar desse julgamento.',
      notas: [],
    },
    {
      dia: 358, data: '25 de dezembro', tema: 'Natal: Glória a Deus nas Alturas',
      capitulo: 'CFW Cap. VIII — Encarnação', versiculo: 'Lucas 2.14',
      devocional: '"Glória a Deus nas alturas, e paz na terra aos homens de boa vontade" (Lc 2.14). Os anjos proclamam o que a encarnação significa: glória ao Pai que planejou, e paz aos homens que o Filho comprou. CFW VIII cobriu a mediação de Cristo — hoje celebramos a encarnação do Mediador. A paz proclamada no Natal não é atmosférica; é paz com Deus (Rm 5.1) conquistada pela obediência ativa de Cristo e sua morte expiatória. Celebre o Natal com toda a profundidade teológica da Confissão: este menino é o Deus-homem, nosso Mediador, Substituto e Rei.',
      cfwRef: 'CFW VIII — encarnação', cfwComparacao: 'CFW e CB 1689 concordam sobre a pessoa e obra de Cristo — o Natal é a celebração da encarnação do Mediador da aliança da graça.',
      reforco: 'O Natal sem Cruz é sentimentalismo; o Natal com Cruz, com toda a doutrina que a Confissão ensina, é adoração.',
      aplicacao: 'Ao celebrar o Natal hoje, leia Colossenses 1.15-20 em família. Este é o Cristo que o Natal celebra — não apenas o bebê, mas o Filho eterno feito carne.',
      notas: [
        'MACLEOD, Donald. <em>The Person of Christ</em>. Downers Grove: IVP, 1998. A cristologia mais acessível e completa — ideal para aprofundar o significado teológico do Natal.',
      ],
      notaInicio: 86,
    },
    {
      dia: 359, data: '26 de dezembro', tema: 'Entre o Natal e o Ano Novo: Gratidão e Exame',
      capitulo: 'CFW Cap. I–XXXIII — Revisão', versiculo: 'Salmo 103.1-2',
      devocional: '"Bendize, ó minha alma, ao Senhor, e tudo o que há em mim bendiga o seu santo nome. Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios" (Sl 103.1-2). Entre o Natal e o Ano Novo, faça um inventário de graça. A Confissão de Westminster que percorremos este ano — do conhecimento de Deus (Cap. I) ao juízo final (Cap. XXXIII) — é o mapa de uma teologia que glorifica a Deus em tudo. Você aprendeu? Você mudou? Donde a doutrina não transformou a vida, ela permaneceu abstrata.',
      cfwRef: 'CFW Cap. I–XXXIII — revisão', cfwComparacao: 'CFW e CB 1689 têm o mesmo objetivo: formar cristãos que conheçam, amem e obedeçam ao Deus das Escrituras — a diferença de ênfase nunca deve obscurecer essa missão comum.',
      reforco: 'Conhecimento doutrinário sem transformação de caráter é vaidade — a medida da teologia é a vida que ela produz.',
      aplicacao: 'Escreva três verdades da CFW que transformaram sua forma de pensar ou viver este ano. Compartilhe com alguém que você ama.',
      notas: [],
    },
    {
      dia: 360, data: '27 de dezembro', tema: 'A Aliança da Graça: O Fio que Une Tudo',
      capitulo: 'CFW Cap. VII — Revisão', versiculo: 'Gálatas 3.29',
      devocional: 'Se há um fio que percorre toda a Confissão de Westminster, é a aliança da graça: Deus, movido apenas por sua livre soberania, estabelece aliança com pecadores em Cristo, prometendo vida e exigindo fé e obediência. Adão, Abraão, Moisés, Davi, Cristo — a aliança avança e se aprofunda. Na plena revelação do NT, a aliança é selada pelo sangue de Cristo e marcada pelos sacramentos. "Se sois de Cristo, então sois descendentes de Abraão, herdeiros segundo a promessa" (Gl 3.29). Você é herdeiro dessa aliança?',
      cfwRef: 'CFW VII — revisão', cfwComparacao: 'CFW e CB 1689 concordam sobre a aliança da graça como fio condutor da revelação; diferem sobre os sinais da aliança e seus recipientes.',
      reforco: 'Teologia bíblica sem o conceito de aliança perde o fio que une AT e NT, lei e Evangelho, criação e nova criação.',
      aplicacao: 'Trace a aliança da graça da Gênesis ao Apocalipse em cinco versículos. Esse exercício revela a unidade da Bíblia e o caráter fiel de Deus.',
      notas: [],
    },
    {
      dia: 361, data: '28 de dezembro', tema: 'A Eleição e o Evangelho: Certeza para os Que Creem',
      capitulo: 'CFW Cap. III — Revisão', versiculo: 'Efésios 1.4',
      devocional: 'A doutrina da eleição — "escolhidos nele antes da fundação do mundo" (Ef 1.4) — não é especulação fria sobre quem está "de fora". É fundamento da assurance para quem crê. Se minha salvação depende de mim, sou inseguro; se depende do propósito eterno de Deus, posso descansar. "Os que Deus predestinou, esses também chamou; e os que chamou, esses também justificou; e os que justificou, esses também glorificou" (Rm 8.30). A cadeia de ouro da salvação começa na eternidade e termina na glória — sem elos quebrados.',
      cfwRef: 'CFW III — revisão', cfwComparacao: 'CFW e CB 1689 concordam sobre a eleição incondicional — o ponto mais importante de sua convergência doutrinária.',
      reforco: 'A eleição pregada como ameaça é distorção; pregada como fundamento da assurance e da gratidão, é consolação e adoração.',
      aplicacao: 'Você crê em Cristo? Então você é eleito — não por mérito seu, mas pelo eterno propósito de Deus. Descanse nessa rocha e adore.',
      notas: [],
    },
    {
      dia: 362, data: '29 de dezembro', tema: 'Sola Scriptura, Sola Gratia, Sola Fide',
      capitulo: 'CFW Cap. I, X, XIV — Revisão', versiculo: 'Romanos 1.17',
      devocional: '"O justo viverá pela fé" (Rm 1.17). As três solas da Reforma percorrem a Confissão de Westminster: a Escritura como autoridade suprema (CFW I), a graça soberana como origem da salvação (CFW X), a fé como meio de justificação (CFW XIV). Não foi nova doutrina que os reformadores descobriram — foi a redescoberta do Evangelho apostólico enterrado sob séculos de tradição. O crente reformado se coloca na continuidade desse Evangelho: dependente da Palavra, confiante na graça, justificado somente pela fé.',
      cfwRef: 'CFW I, X, XIV — revisão', cfwComparacao: 'CFW e CB 1689 concordam nas três solas — esta é a herança comum da Reforma que ambas as tradições professam e guardam.',
      reforco: 'As solas não são slogans históricos — são fundamentos da vida cristã diária: ler a Escritura, depender da graça, confiar em Cristo pela fé.',
      aplicacao: 'Como cada sola se manifesta em sua vida prática? Sola Scriptura: você lê a Bíblia? Sola Gratia: você depende de Deus? Sola Fide: você confia em Cristo?',
      notas: [],
    },
    {
      dia: 363, data: '30 de dezembro', tema: 'Soli Deo Gloria: O Fim de Todas as Coisas',
      capitulo: 'CFW Cap. I–XXXIII — Doxologia', versiculo: 'Romanos 11.36',
      devocional: '"Porque dele e por ele e para ele são todas as coisas. A ele, pois, a glória eternamente" (Rm 11.36). A Confissão de Westminster começa com a Escritura e termina com o juízo — mas o fio condutor é a glória de Deus. Predestinação: para a glória de Deus. Criação: para a glória de Deus. Redenção: para a glória de Deus. Igreja, sacramentos, juízo final: para a glória de Deus. Soli Deo Gloria não é mais um slogan — é a resposta correta à pergunta: "Para que existe tudo isso?" A resposta: para que Deus seja glorificado em tudo, por todos, para sempre.',
      cfwRef: 'CFW Cap. I–XXXIII — doxologia', cfwComparacao: 'CFW e CB 1689 concordam — Soli Deo Gloria é o telos de toda a doutrina; conhecer a Deus é glorificá-lo.',
      reforco: 'Teologia que não termina em adoração é apenas filosofia. A Confissão existe para produzir crentes que adoram a Deus com mente e coração.',
      aplicacao: 'Leia Romanos 11.33-36 em voz alta como oração de encerramento do ano. Este é o padrão do coração reformado: doutrina que se derrama em doxologia.',
      notas: [
        'PIPER, John. <em>God\'s Passion for His Glory</em>. Wheaton: Crossway, 1998. A recuperação contemporânea da centralidade da glória de Deus — diálogo com Jonathan Edwards e o espírito de Westminster.',
      ],
      notaInicio: 87,
    },
    {
      dia: 364, data: '31 de dezembro', tema: 'Síntese Final: Um Ano com a Confissão de Westminster',
      capitulo: 'CFW Cap. I–XXXIII — Revisão Anual', versiculo: 'Filipenses 1.6',
      devocional: '"Aquele que começou em vós a boa obra, há de completá-la até ao dia de Cristo Jesus" (Fp 1.6). Um ano com a Confissão de Westminster é um ano de catequese na soberania de Deus: desde a Escritura infalível (I) até o juízo final irreversível (XXXIII), passando pela aliança de graça, pela redenção em Cristo, pela obra do Espírito, pela Igreja e seus sacramentos. Você não é o mesmo de um ano atrás — ou ao menos não deveria ser. A teologia que não transforma é teologia que não foi recebida pela fé. Ao entrar em um novo ano, leve a Confissão não como monumento histórico, mas como mapa vivo para andar com Deus.',
      cfwRef: 'CFW Cap. I–XXXIII — revisão anual', cfwComparacao: 'CFW e CB 1689 são marcos inestimáveis da fé reformada — estudá-las juntas, com suas semelhanças e diferenças, aprofunda a compreensão da herança protestante.',
      reforco: 'Concluir um ano devocional com a Confissão não é meta acadêmica — é formação espiritual. O fruto é vida transformada, não apenas conhecimento aumentado.',
      aplicacao: 'Escreva uma oração de encerramento do ano. Agradeça a Deus pelas verdades que mais impactaram você. Comprometa-se a um aspecto específico da CFW que ainda precisa de maior aplicação na sua vida.',
      notas: [
        'WESTMINSTER ASSEMBLY. <em>The Westminster Standards</em>. Filadelfia: Great Commission Publications, 2021. O texto completo da Confissão, Catecismo Maior e Menor — o documento que guiou este ano devocional.',
      ],
      notaInicio: 88,
      aplicacoes: {
        digital: 'Revise seu diário espiritual do ano. Quais entradas mostram crescimento real? Onde houve retrocesso? Leve essas respostas para 2025.',
        familia: 'Reúnam a família e cada um compartilha: qual foi a verdade da CFW que mais impactou você este ano? Orem juntos pelo ano que vem.',
        filhos: 'Pergunte: "O que você aprendeu sobre Deus este ano?" Deixe a criança responder com suas próprias palavras — é o melhor teste de catequese.',
        homens: 'O homem que concluiu um ano estudando a Confissão tem as ferramentas para liderar sua família na fé. Use-as no ano que vem.',
        mulheres: 'A mulher formada pela teologia da Confissão leva para o novo ano uma âncora que não cede com as tempestades da vida.',
      },
    },
  ];
  return dias.map(blocoW);
}
`;

content = content + dezembro;
fs.writeFileSync(filePath, content, 'utf8');
const lines = content.split('\n').length;
console.log('✅ gerarDiasDezembroA() adicionada');
console.log('Linhas:', lines);
