const fs = require('fs');
const filePath = 'src/data/devocionalConfessional.ts';

const content = fs.readFileSync(filePath, 'utf8');
const lines = content.split('\n');

// Lines are 1-indexed in grep output; arrays are 0-indexed
// Start: line 4688 (0-indexed: 4687) = "// ============================================================================"
// before "// Junho A"
// End: line 5596 (0-indexed: 5595) = "}"  (closing of gerarDiasJunho_D)

const startLine = 4687; // 0-indexed (line 4688 in file)
const endLine = 5595;   // 0-indexed inclusive (line 5596 in file)

const newContent = `// ============================================================================
// Junho A — Dias 152–159 — CB 1689 Cap. 26 §10–15 + Cap. 27 §1–2
// ============================================================================

export function gerarDiasJunho_A(): ReturnType<typeof bloco>[] {
  const dias: DiaCompacto[] = [
    {
      dia: 152,
      data: '1 jun',
      tema: 'A Igreja Visível: O Povo de Deus na História',
      capitulo: 'CB 1689 26.10',
      versiculo: 'Mateus 16.18',
      versiculoTexto: 'E eu também te digo que tu és Pedro, e sobre esta pedra edificarei a minha igreja, e as portas do inferno não prevalecerão contra ela.',
      confissaoTexto: 'CB 1689 Cap. 26 §10: O poder das chaves do reino dos céus foi confiado pelos ofícios e assembleias da Igreja, com a finalidade de ligar e desligar, segundo a Palavra de Deus.',
      cfwRef: 'CFW Cap. 25 §2 — sobre a Igreja visível',
      cfwComparacao: 'Tanto CB 1689 quanto CFW reconhecem a Igreja visível como comunidade dos que professam fé e seus filhos. CB 1689 enfatiza a autonomia das igrejas locais; CFW enfatiza a unidade da Igreja universal. Ambas afirmam que Cristo é a única Cabeça da Igreja.',
      exposicao: 'Cristo prometeu edificar sua Igreja sobre a rocha de sua própria confissão como Messias e Filho de Deus. A Igreja visível é a comunidade histórica onde o evangelho é pregado, os sacramentos administrados e a disciplina exercida. As portas do inferno — poder da morte e do mal — não prevalecerão contra ela.',
      reforco: 'Efésios 1.22-23',
      aplicacoes: {
        digital: 'Numa era de igrejas virtuais e fé privatizada, a Igreja visível e local é insubstituível — o corpo de Cristo precisa de presença física.',
        familia: 'A família cristã não substitui a Igreja — ela se submete à Igreja e é formada por ela.',
        filhos: 'Ensine: "A Igreja é a família de Deus. Nós pertencemos a ela."',
        homens: 'O homem que abandona a Igreja abandona o corpo de Cristo. Fidelidade à Igreja é fidelidade a Cristo.',
        mulheres: 'A mulher que investe na vida da Igreja local investe no projeto eterno de Deus.',
        igreja: 'A Igreja local não é clube voluntário — é a expressão visível do corpo de Cristo no espaço e no tempo.',
      },
      oracao: 'Senhor, obrigado pela Igreja que edificaste com teu próprio sangue. Que eu não a despreze, mas a ame como tu a amas. Amém.',
      reflexao: 'Cristo não prometeu que a Igreja seria perfeita — prometeu que ela prevaleceria. A fidelidade à Igreja imperfeita é fidelidade a Cristo.',
      aplicacao: 'Se você tem se afastado da comunhão da Igreja, dê um passo concreto hoje para reconectar-se.',
      notas: [
        'ALLISON, Gregg R. <em>Sojourners and Strangers: The Doctrine of the Church</em>. Wheaton: Crossway, 2012.',
        'CB 1689, Cap. 26 §10. Sobre o poder das chaves e a autoridade eclesiástica.',
      ],
      notaInicio: 308,
    },
    {
      dia: 153,
      data: '2 jun',
      tema: 'As Chaves do Reino: Disciplina que Cura',
      capitulo: 'CB 1689 26.11',
      versiculo: 'Mateus 18.17-18',
      versiculoTexto: 'E, se não os ouvir a eles, dize-o à igreja; e, se também não ouvir a igreja, seja-te como o gentio e o publicano.',
      confissaoTexto: 'CB 1689 Cap. 26 §11: O poder eclesiástico de ligar e desligar deve ser exercido conforme a Palavra de Deus, para a edificação da Igreja e não para sua destruição.',
      cfwRef: 'CFW Cap. 30 §1–4 — sobre a censura eclesiástica',
      cfwComparacao: 'CB 1689 e CFW concordam que a disciplina eclesiástica é poder espiritual dado por Cristo para purificar e edificar. Nenhuma das duas confissões admite disciplina arbitrária ou tirânica — ambas a subordinam à Palavra.',
      exposicao: 'A disciplina eclesiástica é ato de amor, não de punição. Quando a Igreja exclui alguém da comunhão, busca restauração, não eliminação. As chaves do reino ligam e desligam conforme a Palavra — nem mais, nem menos.',
      reforco: '1 Coríntios 5.5',
      aplicacoes: {
        digital: 'Cancelamento nas redes é punição sem restauração. A disciplina eclesiástica busca arrependimento e restauração — é radicalmente diferente.',
        familia: 'Na família, corrija com o objetivo de restaurar, não de punir. A disciplina que não visa restauração é vingança.',
        filhos: 'Ensine: "Quando erramos e somos corrigidos, Deus está cuidando de nós."',
        homens: 'O líder que nunca disciplina não ama — ele teme conflito mais do que ama as ovelhas.',
        mulheres: 'Submeter-se à disciplina eclesiástica é sinal de maturidade, não de fraqueza.',
        igreja: 'A Igreja que não exerce disciplina abdica de um dos sinais da Igreja verdadeira.',
      },
      oracao: 'Senhor, dá-nos sabedoria para exercer disciplina com amor e firmeza, sempre visando a restauração. Amém.',
      reflexao: 'Uma Igreja sem disciplina é uma família sem limites — parece amorosa, mas abandona seus membros ao pecado.',
      aplicacao: 'Ore hoje por alguém que está afastado da comunhão eclesiástica, pedindo sua restauração.',
      notas: [
        'DEVER, Mark. <em>Nine Marks of a Healthy Church</em>. Wheaton: Crossway, 2004. Cap. sobre disciplina eclesiástica.',
        'CB 1689, Cap. 26 §11.',
      ],
      notaInicio: 310,
    },
    {
      dia: 154,
      data: '3 jun',
      tema: 'Sínodos e Concílios: Autoridade Colegial',
      capitulo: 'CB 1689 26.12',
      versiculo: 'Atos 15.2',
      versiculoTexto: 'Tendo havido grande contenda e debate de Paulo e Barnabé com eles, determinaram que Paulo e Barnabé, e alguns outros deles, subissem a Jerusalém aos apóstolos e presbíteros, a respeito desta questão.',
      confissaoTexto: 'CB 1689 Cap. 26 §12: Igrejas constituídas conforme a vontade de Cristo podem comunicar-se entre si por delegados e pela prática do amor cristão mútuo.',
      cfwRef: 'CFW Cap. 31 §1-3 — sobre sínodos e concílios',
      cfwComparacao: 'CFW reconhece autoridade de sínodos e concílios de modo mais amplo que CB 1689, que é mais congregacionalista. CB 1689 enfatiza a comunhão voluntária entre igrejas; CFW reconhece autoridade jurisdicional de assembleias. Ambas subordinam concílios à Escritura.',
      exposicao: 'O Concílio de Jerusalém (At 15) é o modelo bíblico de deliberação colegial. Igrejas não são ilhas — precisam umas das outras para discernir, corrigir erros e manter unidade doutrinária. A comunhão inter-eclesial não viola autonomia local, mas a complementa.',
      reforco: 'Atos 15.28',
      aplicacoes: {
        digital: 'A descentralização digital facilita igrejas sem accountability. Comunhão inter-eclesial é proteção contra desvios.',
        familia: 'Assim como famílias precisam de comunidade, igrejas precisam umas das outras para crescimento e correção.',
        filhos: 'Ensine: "Nossa Igreja não é perfeita, por isso precisa de outras igrejas para crescer juntas."',
        homens: 'O pastor que rejeita accountability externo coloca sua congregação em risco.',
        mulheres: 'Participar de eventos inter-eclesiais é investir na unidade do corpo de Cristo.',
        igreja: 'Busque comunhão com outras igrejas de fé reformada — compare, aprenda, corrija e fortaleça.',
      },
      oracao: 'Senhor, que nossa Igreja não se isole, mas viva em comunhão com o corpo mais amplo de Cristo. Amém.',
      reflexao: 'Nenhuma igreja local possui toda a sabedoria. A humildade de buscar conselho de outras igrejas é sinal de maturidade eclesiástica.',
      aplicacao: 'Informe-se sobre a denominação ou associação de igrejas à qual sua congregação pertence. Ore por ela.',
      notas: [
        'HAMMETT, John S. <em>Biblical Foundations for Baptist Churches</em>. Grand Rapids: Kregel, 2005.',
        'CB 1689, Cap. 26 §12.',
      ],
      notaInicio: 312,
    },
    {
      dia: 155,
      data: '4 jun',
      tema: 'Nenhum Papa: Cristo, Única Cabeça da Igreja',
      capitulo: 'CB 1689 26.13',
      versiculo: 'Colossenses 1.18',
      versiculoTexto: 'E ele é a cabeça do corpo, da igreja; é o princípio e o primogênito dentre os mortos, para que em tudo tenha a preeminência.',
      confissaoTexto: 'CB 1689 Cap. 26 §13: Jesus Cristo é a única cabeça da Igreja. O papa de Roma não pode ser de forma alguma cabeça da Igreja universal.',
      cfwRef: 'CFW Cap. 25 §6 — sobre o papa como anticristo',
      cfwComparacao: 'Ambas as confissões rejeitam qualquer autoridade humana como cabeça universal da Igreja. CFW usa linguagem mais forte ("anticristo"); CB 1689 é mais branda mas igualmente clara: Cristo é o único cabeça.',
      exposicao: 'A preeminência de Cristo na Igreja não é compartilhada com nenhum sucessor humano. Cristo governa sua Igreja pela Palavra e pelo Espírito — não por hierarquia eclesiástica. Qualquer estrutura que coloque um homem como cabeça universal usurpa a prerrogativa exclusiva de Cristo.',
      reforco: 'Efésios 5.23',
      aplicacoes: {
        digital: 'Influenciadores cristãos online acumulam autoridade quase papal sobre seus seguidores. Examine: você segue um homem ou a Cristo?',
        familia: 'O pastor serve a Igreja — não a governa. Cristo governa através da Palavra.',
        filhos: 'Ensine: "Somos batistas porque acreditamos que somente Cristo é o chefe de nossa Igreja."',
        homens: 'Líderes cristãos são servos, não soberanos. Desconfie de qualquer liderança que não admite correção.',
        mulheres: 'Submeta-se aos líderes da Igreja como aqueles que prestam contas a Cristo — não como autoridades absolutas.',
        igreja: 'Examine se sua Igreja está sob a autoridade da Palavra ou sob a personalidade do pastor.',
      },
      oracao: 'Senhor Jesus, és o único Cabeça da Igreja. Que nenhuma estrutura humana usurpe tua coroa. Amém.',
      reflexao: 'Uma Igreja que substitui a autoridade de Cristo por autoridade humana já não é a Igreja de Cristo — é uma instituição religiosa.',
      aplicacao: 'Leia Colossenses 1.15-20 meditando na supremacia de Cristo sobre a Igreja.',
      notas: [
        'GRUDEM, Wayne. <em>Teologia Sistemática</em>. São Paulo: Vida Nova, 1999. Cap. 44: A Natureza da Igreja.',
        'CB 1689, Cap. 26 §13.',
      ],
      notaInicio: 314,
    },
    {
      dia: 156,
      data: '5 jun',
      tema: 'Membresia: Compromisso Visível com o Corpo',
      capitulo: 'CB 1689 26.14',
      versiculo: 'Atos 2.41',
      versiculoTexto: 'De sorte que foram batizados os que receberam a sua palavra; e naquele dia agregaram-se a eles quase três mil almas.',
      confissaoTexto: 'CB 1689 Cap. 26 §14: Os membros da Igreja visível são aqueles que professam verdadeiramente fé em Cristo e obediência a ele, juntamente com seus filhos.',
      cfwRef: 'CFW Cap. 25 §2 — membros da Igreja visível',
      cfwComparacao: 'CB 1689 restringe membresia a crentes batizados (batismo de crentes); CFW inclui filhos de crentes como membros da Igreja visível. Este é o ponto de maior divergência entre as duas confissões no que toca à eclesiologia.',
      exposicao: 'Membresia eclesiástica não é formalidade burocrática — é compromisso público de pertencer ao corpo de Cristo, submeter-se à sua disciplina, e viver em comunhão com outros crentes. Em Atos 2, o batismo é o rito de entrada na comunidade visível dos salvos.',
      reforco: '1 Coríntios 12.13',
      aplicacoes: {
        digital: 'Seguir uma Igreja online sem membresia formal é como namorar sem compromisso. A membresia formaliza o compromisso.',
        familia: 'A família que mantém membresia formal ensina aos filhos que pertencer à Igreja importa.',
        filhos: 'Ensine: "Ser membro da Igreja é uma responsabilidade séria — significa comprometer-se com o corpo de Cristo."',
        homens: 'O homem que frequenta a Igreja sem ser membro não assume suas responsabilidades de cuidado e accountability.',
        mulheres: 'Busque membresia formal onde você está — isso formaliza o compromisso mútuo de cuidado.',
        igreja: 'Tenha um processo claro de membresia que instrua e comprometa os novos membros.',
      },
      oracao: 'Senhor, que eu não apenas frequente a Igreja, mas pertença a ela com compromisso genuíno. Amém.',
      reflexao: 'Cristãos sem membresia são como soldados sem regimento — professam lealdade mas não assumem responsabilidade.',
      aplicacao: 'Se você não é membro formal de uma Igreja local, procure seu pastor e inicie esse processo.',
      notas: [
        'DEVER, Mark. <em>What Is a Healthy Church?</em> Wheaton: Crossway, 2007.',
        'CB 1689, Cap. 26 §14.',
      ],
      notaInicio: 316,
    },
    {
      dia: 157,
      data: '6 jun',
      tema: 'Oficiais da Igreja: Presbitério e Diaconato',
      capitulo: 'CB 1689 26.15',
      versiculo: 'Atos 14.23',
      versiculoTexto: 'E, havendo-lhes constituído presbíteros em cada igreja, e orado com jejuns, os encomendaram ao Senhor em quem haviam crido.',
      confissaoTexto: 'CB 1689 Cap. 26 §15: O Senhor Jesus, como Rei e Cabeça da Igreja, ordenou nela um governo realizado por oficiais escolhidos pela congregação — bispos/presbíteros e diáconos.',
      cfwRef: 'CFW Cap. 29 §1-4 — sobre os oficiais da Igreja',
      cfwComparacao: 'Ambas reconhecem dois ofícios permanentes: presbitério (bispos/pastores/presbíteros) e diaconato. CB 1689 enfatiza que os oficiais são escolhidos pela congregação; CFW tem estrutura mais presbiteriana com eleição via assembleia.',
      exposicao: 'Cristo governa sua Igreja através de homens chamados, qualificados e ordenados. Presbíteros (bispos) pregam, ensinam e pastoreiam; diáconos servem nas necessidades práticas. O governo eclesiástico não é democracia pura, nem monarquia — é aristocracia espiritual sujeita a Cristo.',
      reforco: '1 Timóteo 3.1-13',
      aplicacoes: {
        digital: 'Em igrejas digitais, quem é o pastor responsável? A falta de oficiais identificáveis é sinal de estrutura eclesiástica deficiente.',
        familia: 'Submeta-se aos presbíteros de sua Igreja como àqueles que velarão por sua alma (Hb 13.17).',
        filhos: 'Ensine respeito pelos pastores e diáconos — eles são dons de Cristo para a Igreja.',
        homens: 'Se você aspira ao presbiterado, examine-se pelas qualificações de 1 Tm 3.1-7. É um chamado sério.',
        mulheres: 'O diaconato feminino tem base histórica. Verifique como sua Igreja interpreta Rm 16.1 e 1 Tm 3.11.',
        igreja: 'Ore regularmente por seus pastores e diáconos — o peso do ofício é grande.',
      },
      oracao: 'Senhor, abençoa os oficiais de nossa Igreja. Que sejam homens e mulheres de caráter, competência e chamado genuíno. Amém.',
      reflexao: 'Uma Igreja sem oficiais qualificados está sujeita a todo vento de doutrina. A estrutura não é obstáculo ao Espírito — é seu instrumento.',
      aplicacao: 'Leia 1 Timóteo 3.1-13 e ore por cada um dos oficiais de sua Igreja local.',
      notas: [
        'STRAUCH, Alexander. <em>Liderança Bíblica de Anciãos</em>. São Paulo: Fiel, 2013.',
        'CB 1689, Cap. 26 §15.',
      ],
      notaInicio: 318,
    },
    {
      dia: 158,
      data: '7 jun',
      tema: 'Comunhão dos Santos: Unidos em Cristo',
      capitulo: 'CB 1689 27.1',
      versiculo: '1 João 1.3',
      versiculoTexto: 'O que temos visto e ouvido isso vos anunciamos, para que também vós tenhais comunhão conosco; e a nossa comunhão é com o Pai e com seu Filho Jesus Cristo.',
      confissaoTexto: 'CB 1689 Cap. 27 §1: Todos os santos, unidos a Jesus Cristo seu cabeça pelo seu Espírito e pela fé, têm comunhão com ele em suas graças, sofrimentos, morte, ressurreição e glória.',
      cfwRef: 'CFW Cap. 26 §1 — sobre a comunhão dos santos',
      cfwComparacao: 'CB 1689 e CFW são praticamente idênticas neste capítulo. Ambas fundamentam a comunhão dos santos na união vital com Cristo — não em mero associativismo ou afinidade cultural. A comunhão que temos uns com os outros deriva da comunhão que temos com Cristo.',
      exposicao: 'A comunhão dos santos não é um clube social de pessoas religiosas — é participação na vida de Cristo. Unidos a ele, participamos de suas graças (justificação, santificação), seus sofrimentos (perseguição, mortificação) e sua glória futura. Esta união é obra do Espírito Santo pela fé.',
      reforco: 'Romanos 8.17',
      aplicacoes: {
        digital: 'Comunidade virtual pode ser genuína, mas não substitui a presença física. A comunhão dos santos exige corporalidade.',
        familia: 'A família cristã vive a comunhão dos santos em miniatura — suporte mútuo, confissão de pecados, oração uns pelos outros.',
        filhos: 'Ensine: "Seus amigos na Igreja são seus irmãos e irmãs em Cristo — é uma família maior que a família biológica."',
        homens: 'A comunhão entre homens na Igreja quebra o isolamento masculino. Construa amizades profundas no corpo de Cristo.',
        mulheres: 'Investir em amizades dentro da Igreja é investir em comunhão dos santos — não é luxo, é necessidade espiritual.',
        igreja: 'Promova comunhão real — refeições juntos, visitas, suporte em crises. Não apenas cultos.',
      },
      oracao: 'Senhor, obrigado pela comunhão com Cristo e, nele, com todos os santos. Que eu não viva isolado, mas integrado ao corpo. Amém.',
      reflexao: 'A maior solidão é viver sem comunhão com Cristo. A segunda maior é ser membro de Igreja sem comunhão real com os irmãos.',
      aplicacao: 'Entre em contato hoje com um irmão ou irmã da Igreja que está há tempo sem aparecer. Demonstre que a comunhão importa.',
      notas: [
        'CLOWNEY, Edmund P. <em>The Church</em>. Downers Grove: IVP, 1995.',
        'CB 1689, Cap. 27 §1.',
      ],
      notaInicio: 320,
    },
    {
      dia: 159,
      data: '8 jun',
      tema: 'Comunhão dos Santos: Obrigações Mútuas',
      capitulo: 'CB 1689 27.2',
      versiculo: 'Gálatas 6.2',
      versiculoTexto: 'Levai as cargas uns dos outros e assim cumprireis a lei de Cristo.',
      confissaoTexto: 'CB 1689 Cap. 27 §2: Os santos têm obrigação de manter a comunhão e o companheirismo no culto público e nos serviços mútuos — tanto espirituais quanto materiais.',
      cfwRef: 'CFW Cap. 26 §2 — obrigações mútuas dos santos',
      cfwComparacao: 'Ambas as confissões afirmam que a comunhão dos santos gera obrigações concretas — não é apenas sentimento de pertença. CB 1689 e CFW concordam que os santos devem servir-se mutuamente tanto espiritualmente (oração, encorajamento, instrução) quanto materialmente (ajuda nas necessidades físicas).',
      exposicao: 'Carregar as cargas uns dos outros é cumprir a lei de Cristo — lei do amor. A comunhão dos santos não é optional — é obrigatória. Cada membro do corpo tem responsabilidade com os demais: orar, servir, encorajar, suprir necessidades, corrigir em amor.',
      reforco: 'Atos 2.44-45',
      aplicacoes: {
        digital: 'Solidariedade virtual (curtir posts de pessoas em crise) não substitui presença real. A comunhão dos santos exige ação concreta.',
        familia: 'A família que participa ativamente da vida da Igreja cumpre sua parte na comunhão dos santos.',
        filhos: 'Ensine: "Quando alguém da Igreja precisa de ajuda, nós ajudamos. Isso é o que irmãos fazem."',
        homens: 'O homem que pede ajuda quando precisa pratica humildade e permite que outros exerçam a comunhão.',
        mulheres: 'O ministério de hospitalidade e cuidado prático é expressão concreta da comunhão dos santos.',
        igreja: 'Organize sistemas concretos de cuidado mútuo — lista de necessidades, rede de suporte, fundo de misericórdia.',
      },
      oracao: 'Senhor, que eu seja membro ativo do corpo — não apenas recebendo, mas dando. Que eu carregue as cargas dos irmãos como Cristo carregou as minhas. Amém.',
      reflexao: 'Uma Igreja onde ninguém precisa de nada é uma Igreja onde ninguém é honesto. A comunhão real começa com vulnerabilidade.',
      aplicacao: 'Identifique uma necessidade concreta de um membro da sua Igreja e tome uma atitude para supri-la esta semana.',
      notas: [
        'PIPER, John; TAYLOR, Justin. <em>Suffering and the Sovereignty of God</em>. Wheaton: Crossway, 2006.',
        'CB 1689, Cap. 27 §2.',
      ],
      notaInicio: 322,
    },
  ];
  return dias.map(bloco);
}

// ============================================================================
// Junho B — Dias 160–167 — CB 1689 Cap. 27 §3 + Cap. 28 + Cap. 29 §1–4
// ============================================================================

export function gerarDiasJunho_B(): ReturnType<typeof bloco>[] {
  const dias: DiaCompacto[] = [
    {
      dia: 160,
      data: '9 jun',
      tema: 'Comunhão dos Santos: Amor Sem Idolatria',
      capitulo: 'CB 1689 27.3',
      versiculo: '2 Coríntios 6.14',
      versiculoTexto: 'Não vos ponhais em jugo desigual com os infiéis; porque, que sociedade tem a justiça com a injustiça?',
      confissaoTexto: 'CB 1689 Cap. 27 §3: Esta comunhão dos santos não destrói ou viola o título ou propriedade particular que os homens têm em seus bens e posses.',
      cfwRef: 'CFW Cap. 26 §3 — limites da comunhão dos santos',
      cfwComparacao: 'Ambas as confissões protegem a comunhão dos santos de duas distorções: o individualismo que nega responsabilidade mútua, e o comunitarismo que anula propriedade e individualidade. A comunhão cristã é livre, não coercitiva.',
      exposicao: 'A comunhão dos santos não é comunismo espiritual. Os crentes compartilham livremente, mas não são obrigados a abrir mão de propriedade privada. O Espírito gera generosidade, não expropriação. Atos 2 mostra doação voluntária — não redistribuição compulsória.',
      reforco: 'Atos 5.4',
      aplicacoes: {
        digital: 'Pressão social para doação ou compartilhamento forçado desvirtua a generosidade cristã. A oferta deve ser livre, não constrangida.',
        familia: 'Compartilhe generosamente na Igreja, mas sem deixar de cuidar das necessidades de sua própria família (1 Tm 5.8).',
        filhos: 'Ensine: "Compartilhar é uma escolha de amor, não uma obrigação forçada."',
        homens: 'A generosidade masculina genuína é decidida no coração, não imposta por pressão social.',
        mulheres: 'Generosidade com sabedoria — cuidar da família e da Igreja não são objetivos rivais.',
        igreja: 'Cultive cultura de generosidade voluntária, não de constrangimento. O amor não pode ser compelido.',
      },
      oracao: 'Senhor, faz meu coração generoso — mas que minha generosidade nasça do amor, não do medo ou pressão. Amém.',
      reflexao: 'Generosidade forçada não é virtude — é imposto. A comunhão dos santos prospera quando cada membro dá conforme propôs no coração.',
      aplicacao: 'Ore pedindo a Deus que liberte seu coração de avareza. Planeje uma doação generosa e voluntária para esta semana.',
      notas: [
        'GRUDEM, Wayne. <em>Teologia Sistemática</em>. São Paulo: Vida Nova, 1999. Cap. sobre a Igreja.',
        'CB 1689, Cap. 27 §3.',
      ],
      notaInicio: 324,
    },
    {
      dia: 161,
      data: '10 jun',
      tema: 'Sacramentos: Sinais e Selos da Graça',
      capitulo: 'CB 1689 28.1',
      versiculo: 'Romanos 4.11',
      versiculoTexto: 'E recebeu o sinal da circuncisão, selo da justiça da fé que tivera sendo ainda incircunciso.',
      confissaoTexto: 'CB 1689 Cap. 28 §1: Os sacramentos são sinais e selos santos da aliança da graça, instituídos por Deus, para representar Cristo e seus benefícios, e confirmar o interesse dos crentes nele.',
      cfwRef: 'CFW Cap. 27 §1 — definição dos sacramentos',
      cfwComparacao: 'CB 1689 e CFW têm definições praticamente idênticas dos sacramentos: sinais e selos da aliança da graça. Ambas rejeitam a eficácia ex opere operato (católica) e o memorialism puro (zwingliano). Os sacramentos comunicam graça através da fé, não automaticamente.',
      exposicao: 'Sacramento é sinal que representa e selo que confirma. Não é magia — nem mera memória. Cristo institui dois sacramentos: Batismo e Ceia. Através deles, o Espírito Santo confirma as promessas do evangelho ao coração do crente. A eficácia não está no rito, mas na obra de Cristo selada pelo Espírito.',
      reforco: '1 Coríntios 10.16',
      aplicacoes: {
        digital: 'Em um mundo de realidade virtual e experiências simuladas, os sacramentos são atos físicos, concretos, insubstituíveis. O corpo importa.',
        familia: 'Participe dos sacramentos com a família — e explique o que significam para que não sejam rituais vazios.',
        filhos: 'Ensine: "O batismo e a Ceia são como uma aliança de casamento — são sinais de uma promessa real."',
        homens: 'Tome a Ceia com sobriedade e alegria — examinando-se, mas confiando na graça.',
        mulheres: 'Os sacramentos são para toda a Igreja — não reserve espiritualidade para cultos especiais.',
        igreja: 'Celebre os sacramentos com instrução e reverência — explique o que estão fazendo antes de fazê-lo.',
      },
      oracao: 'Senhor, que os sacramentos que celebramos sejam para nós selos vivos das tuas promessas, não rituais vazios. Amém.',
      reflexao: 'O sacramento que não alimenta a fé se tornou superstição. O sacramento que é apenas memória perdeu sua força de selo. A fé viva recebe o que o sinal representa.',
      aplicacao: 'Na próxima Ceia do Senhor, prepare-se com exame e oração. Leia 1 Coríntios 11.23-32 antes.',
      notas: [
        'FESKO, J.V. <em>Word, Water, and Spirit</em>. Grand Rapids: Reformation Heritage Books, 2010.',
        'CB 1689, Cap. 28 §1.',
      ],
      notaInicio: 326,
    },
    {
      dia: 162,
      data: '11 jun',
      tema: 'Sacramentos: Somente Cristo os Institui',
      capitulo: 'CB 1689 28.2',
      versiculo: 'Mateus 28.19',
      versiculoTexto: 'Portanto ide, fazei discípulos de todas as nações, batizando-os em nome do Pai, e do Filho, e do Espírito Santo.',
      confissaoTexto: 'CB 1689 Cap. 28 §2: Em todo sacramento há uma relação espiritual, ou união sacramental, entre o sinal e a coisa significada. Há somente dois sacramentos instituídos por Cristo: o Batismo e a Ceia do Senhor.',
      cfwRef: 'CFW Cap. 27 §2-3 — instituição e número dos sacramentos',
      cfwComparacao: 'CB 1689 e CFW concordam que apenas Batismo e Ceia são sacramentos — rejeitando os sete sacramentos católicos. Ambas insistem que somente Cristo pode instituir sacramentos; a Igreja não tem autoridade para criar novos sinais e selos da aliança.',
      exposicao: 'Cristo institui dois, apenas dois sacramentos. A Igreja não pode adicionar novos. Confirmação, extrema-unção, penitência — são invenções eclesiásticas sem mandato de Cristo. O princípio regulador do culto protege os sacramentos de acréscimos não bíblicos.',
      reforco: '1 Coríntios 11.23-25',
      aplicacoes: {
        digital: 'A tendência de criar novos rituais "espirituais" online não tem autoridade de Cristo. Os meios de graça instituídos são suficientes.',
        familia: 'Ensine os filhos a valorizar o que Cristo instituiu — e a não buscar experiências espirituais fora dos meios designados.',
        filhos: 'Explique: "O batismo e a Ceia são as duas ordenanças que Jesus mandou sua Igreja celebrar."',
        homens: 'Defenda os sacramentos bíblicos contra a diluição contemporânea. Sacramento não é experiência emocional — é ordenança de Cristo.',
        mulheres: 'Participe dos sacramentos com entendimento — saiba o que está fazendo e por quê.',
        igreja: 'Mantenha apenas os dois sacramentos que Cristo institui. Não acrescente, não subtraia.',
      },
      oracao: 'Senhor, que celebremos somente o que tu instituíste, da maneira que tu ordenaste. Guarda-nos de inovações não bíblicas. Amém.',
      reflexao: 'A Igreja que inventa sacramentos não demonstra criatividade — demonstra arrogância. Cristo é o único que tem autoridade para ordenar os meios de graça.',
      aplicacao: 'Pesquise a história dos dois sacramentos na tradição batista reformada. Como sua Igreja os celebra?',
      notas: [
        'PACKER, J.I. <em>Concise Theology</em>. Wheaton: Tyndale, 1993. Capítulo sobre os sacramentos.',
        'CB 1689, Cap. 28 §2.',
      ],
      notaInicio: 328,
    },
    {
      dia: 163,
      data: '12 jun',
      tema: 'Sacramentos: Eficácia pela Fé, Não pelo Rito',
      capitulo: 'CB 1689 28.3-6',
      versiculo: '1 Coríntios 3.7',
      versiculoTexto: 'De modo que nem o que planta é alguma coisa, nem o que rega, mas Deus que dá o crescimento.',
      confissaoTexto: 'CB 1689 Cap. 28 §6: A eficácia dos sacramentos não depende da piedade ou intenção do ministro que os administra, mas da obra do Espírito e da Palavra de instituição.',
      cfwRef: 'CFW Cap. 27 §3 — eficácia dos sacramentos',
      cfwComparacao: 'Ambas as confissões rejeitam a doutrina ex opere operato (que o rito produz graça automaticamente) e também o donatismo (que a eficácia depende da virtude do ministro). A graça sacramental opera pelo Espírito, recebida pela fé.',
      exposicao: 'Os sacramentos não operam magicamente — nem dependem da santidade do pastor. Um pastor indigno que batiza administra um batismo válido; mas o benefício espiritual é recebido apenas pela fé. O Espírito age através da Palavra e do rito, mas somente os que creem recebem o selo da graça.',
      reforco: 'João 6.63',
      aplicacoes: {
        digital: 'Não julgue a validade de seu batismo pela qualidade moral do pastor que o batizou. O rito é de Cristo, não do homem.',
        familia: 'Se você tem dúvidas sobre seu batismo por causa de quem o administrou, consulte seu pastor. A validade não depende do ministro.',
        filhos: 'Ensine: "O batismo é de Jesus, não do pastor. O pastor é apenas o instrumento."',
        homens: 'A eficácia dos sacramentos deve produzir humildade nos pastores: eles são instrumentos, não fontes.',
        mulheres: 'Receba os sacramentos com fé ativa — não como ritual automático, mas como encontro com as promessas de Cristo.',
        igreja: 'Instrua os membros sobre a natureza dos sacramentos antes de administrá-los. Sacramento sem instrução tende à superstição.',
      },
      oracao: 'Senhor, que eu receba os sacramentos com fé viva, esperando encontrar-te nas tuas próprias ordenanças. Amém.',
      reflexao: 'O sacramento recebido sem fé não alimenta a alma — como comida que se mastiga mas não se engole. A fé é o órgão que recebe o que o sinal representa.',
      aplicacao: 'Reflita: você tem recebido a Ceia do Senhor com fé ativa ou como ritual automático? Ore antes da próxima celebração.',
      notas: [
        'HORTON, Michael. <em>A Place for Weakness</em>. Grand Rapids: Zondervan, 2006.',
        'CB 1689, Cap. 28 §3-6.',
      ],
      notaInicio: 330,
    },
    {
      dia: 164,
      data: '13 jun',
      tema: 'Batismo: Ordenança de Entrada no Corpo de Cristo',
      capitulo: 'CB 1689 29.1',
      versiculo: 'Romanos 6.3-4',
      versiculoTexto: 'Ou não sabeis que todos quantos fomos batizados em Jesus Cristo, fomos batizados em sua morte? De sorte que fomos sepultados com ele pelo batismo na morte, para que, como Cristo ressuscitou dos mortos pela glória do Pai, assim andemos nós também em novidade de vida.',
      confissaoTexto: 'CB 1689 Cap. 29 §1: O Batismo é uma ordenança do Novo Testamento instituída por Jesus Cristo, para ser para o batizando um sinal de sua participação nele, de regeneração, remissão de pecados e entrega a Deus.',
      cfwRef: 'CFW Cap. 28 §1 — sobre o batismo',
      cfwComparacao: 'CB 1689 e CFW concordam na definição do Batismo como sinal e selo. A diferença fundamental: CB 1689 batiza somente crentes professantes (batismo de crentes); CFW estende o batismo aos filhos de crentes (batismo infantil/pedobatismo). Esta é a maior distinção prática entre as duas confissões.',
      exposicao: 'O Batismo é o rito de entrada no povo visível de Deus. Em Romanos 6, Paulo conecta o batismo com a morte e ressurreição de Cristo — o batizando é sepultado com Cristo e ressurge para nova vida. O batismo não regenera — sinaliza e sela a regeneração operada pelo Espírito.',
      reforco: 'Atos 2.38',
      aplicacoes: {
        digital: 'Não existe "batismo virtual." O batismo é ato físico, público, que envolve água, pessoa e comunidade. Corporalidade importa.',
        familia: 'Se alguém da família ainda não é batizado mas professa fé, encoraje o próximo passo de obediência.',
        filhos: 'Ensine: "O batismo é quando a pessoa diz para toda a Igreja: eu pertenço a Cristo."',
        homens: 'O homem que retarda o batismo sem motivo válido desobedece a um mandamento explícito de Cristo.',
        mulheres: 'Testemunhe sobre seu próprio batismo para os filhos — o que significou para você.',
        igreja: 'O batismo deve ser público, explicado e celebrado pela congregação. Não é ato privado.',
      },
      oracao: 'Senhor, que meu batismo não seja apenas um rito passado, mas uma identidade presente: sou batizado em Cristo, morto e ressurreto nele. Amém.',
      reflexao: 'O batismo não salva — mas o que ele representa salvou. A água aponta para o sangue de Cristo e para a obra do Espírito que limpa e regenera.',
      aplicacao: 'Recorde o dia do seu batismo. Se não lembra ou não foi batizado após a conversão, converse com seu pastor.',
      notas: [
        "SCHREINER, Thomas R.; WARE, Bruce A. (eds). <em>Believer's Baptism</em>. Nashville: B&H Academic, 2006.",
        'CB 1689, Cap. 29 §1.',
      ],
      notaInicio: 332,
    },
    {
      dia: 165,
      data: '14 jun',
      tema: 'Batismo: Somente Crentes São Candidatos',
      capitulo: 'CB 1689 29.2',
      versiculo: 'Atos 8.37',
      versiculoTexto: 'E disse Filipe: Se crês de todo o coração, é permitido. E, respondendo ele, disse: Creio que Jesus Cristo é o Filho de Deus.',
      confissaoTexto: 'CB 1689 Cap. 29 §2: Os que realmente professam arrependimento para com Deus, fé em e obediência a nosso Senhor Jesus Cristo são os únicos candidatos adequados para este sacramento.',
      cfwRef: 'CFW Cap. 28 §4 — quanto a quem deve ser batizado',
      cfwComparacao: 'Aqui está a diferença doutrinária central entre CB 1689 e CFW: CB 1689 batiza somente crentes professantes; CFW batiza também os filhos de crentes. CB 1689 vê o batismo como confissão pública de fé pessoal; CFW vê como sinal da aliança que inclui a semente dos crentes.',
      exposicao: 'Para CB 1689, apenas quem professa fé pessoal e arrependimento é candidato ao batismo. Isso reflete a eclesiologia de aliança do Novo Testamento: a Igreja é comunidade de regenerados, não de nascidos em família cristã. O batismo de crentes protege a pureza da Igreja visível.',
      reforco: 'Marcos 16.16',
      aplicacoes: {
        digital: 'A pressão familiar para batizar crianças não convertidas deve ser resistida com amor. O batismo exige fé professa.',
        familia: 'Se seus filhos foram batizados na infância por outra tradição, explique sua posição e encoraje confissão de fé quando maduros.',
        filhos: 'Ensine: "Você será batizado quando decidir seguir Jesus por si mesmo — não porque seus pais são cristãos."',
        homens: 'Não pressione filhos adolescentes ao batismo por conveniência social. Espere fé genuína.',
        mulheres: 'Ore pela conversão genuína dos filhos — o batismo deve seguir a fé, não precedê-la.',
        igreja: 'Tenha processo de entrevista antes do batismo: examine a profissão de fé do candidato.',
      },
      oracao: 'Senhor, que ninguém seja batizado em nossa Igreja sem que primeiro seja tocado pelo Espírito e professe fé genuína. Amém.',
      reflexao: 'O batismo sem fé é água molhada. A ordenança de Cristo foi dada para confessar fé — não para produzi-la.',
      aplicacao: 'Se você tem filhos, ore especificamente pela conversão genuína de cada um deles.',
      notas: [
        'WELLUM, Stephen J. "Baptism and the Relationship Between the Covenants." In: SCHREINER; WARE (eds). <em>Believer\'s Baptism</em>. Nashville: B&H, 2006.',
        'CB 1689, Cap. 29 §2.',
      ],
      notaInicio: 334,
    },
    {
      dia: 166,
      data: '15 jun',
      tema: 'Batismo: Imersão, o Modo Correto',
      capitulo: 'CB 1689 29.3',
      versiculo: 'João 3.23',
      versiculoTexto: 'Baptizava também João em Enom, perto de Salim, porque havia ali muita água; e os que iam lá eram batizados.',
      confissaoTexto: 'CB 1689 Cap. 29 §3: O modo externo de ministrar este sacramento é mergulhar no — ou imergir a pessoa na — água; no nome do Pai, do Filho e do Espírito Santo.',
      cfwRef: 'CFW Cap. 28 §3 — sobre o modo do batismo',
      cfwComparacao: 'CFW é mais ampla: permite imersão, aspersão ou afusão. CB 1689 é específica: o modo correto é imersão. Esta diferença reflete a herança batista da CB 1689 — o nome "batista" deriva de "baptizō" (mergulhar), e a imersão é vista como o único modo fiel ao significado simbólico do batismo.',
      exposicao: 'João Batizava onde havia "muita água" — porque precisava de água suficiente para imersão. O termo grego baptizō significa mergulhar, imergir. A imersão representa melhor a morte, sepultura e ressurreição de Cristo descrita em Rm 6.3-4. O modo não é indiferente — ele comunica teologia.',
      reforco: 'Colossenses 2.12',
      aplicacoes: {
        digital: 'Em um mundo que desincorpora tudo, o batismo por imersão insiste na corporalidade. O corpo vai à água — não apenas a cabeça.',
        familia: 'Explique aos filhos o simbolismo da imersão: morte ao velho, ressurreição ao novo.',
        filhos: 'Ensine: "Quando alguém é batizado, está sendo sepultado com Jesus e ressurgindo com ele."',
        homens: 'O modo do batismo não é questão secundária para batistas — ele comunica o evangelho.',
        mulheres: 'Se você veio de outra tradição e foi aspergida, estude a posição batista com a Bíblia aberta.',
        igreja: 'Celebre os batismos de modo que toda a congregação veja e entenda o que está acontecendo.',
      },
      oracao: 'Senhor, que o modo como celebramos o batismo comunique fielmente tua morte e ressurreição. Que não seja ritual mecânico, mas proclamação viva. Amém.',
      reflexao: 'A forma do batismo não é decoração — é teologia em ação. Quando o crente é imerso e emerge, o evangelho é encenado diante dos olhos de todos.',
      aplicacao: 'Assista a um batismo em sua Igreja com olhos teológicos. O que você vê comunicado pelo ato?',
      notas: [
        'CARSON, D.A. "Evangelicals, Ecumenism, and the Church." In: KANTZER; HENRY (eds). <em>Evangelical Affirmations</em>. Grand Rapids: Zondervan, 1990.',
        'CB 1689, Cap. 29 §3.',
      ],
      notaInicio: 336,
    },
    {
      dia: 167,
      data: '16 jun',
      tema: 'Batismo: Uma Vez para Sempre',
      capitulo: 'CB 1689 29.4',
      versiculo: 'Efésios 4.5',
      versiculoTexto: 'Um só Senhor, uma só fé, um só batismo.',
      confissaoTexto: 'CB 1689 Cap. 29 §4: O batismo não deve ser repetido para nenhuma pessoa.',
      cfwRef: 'CFW Cap. 28 §7 — sobre a repetição do batismo',
      cfwComparacao: 'CB 1689 e CFW concordam plenamente: o batismo é administrado uma única vez. Não se rebatiza. A unicidade do batismo reflete a unicidade da obra de Cristo — ele morreu uma vez para sempre (Hb 9.26). Repetir o batismo seria implicar que a obra de Cristo precisasse ser repetida.',
      exposicao: 'Paulo declara: "um só batismo." O batismo é marca permanente de pertença a Cristo — não precisa ser renovado quando a fé vacila ou quando mudamos de Igreja. Aqueles que foram batizados como crentes professantes em outra Igreja evangélica não precisam ser rebatizados. O batismo é de Cristo, não da denominação.',
      reforco: 'Hebreus 9.26-28',
      aplicacoes: {
        digital: 'Igrejas que rebatizam por questões de filiação denominacional desviam o batismo de seu significado teológico para marcação territorial.',
        familia: 'Se cônjuge de outra tradição foi batizado como crente professo, respeite seu batismo como válido.',
        filhos: 'Ensine: "Você só será batizado uma vez — é um sinal permanente que você pertence a Jesus."',
        homens: 'Resista à pressão de rebatizar membros vindos de outras igrejas evangélicas sem razão teológica sólida.',
        mulheres: 'A unicidade do batismo é fonte de segurança: "Fui batizada — pertenço a Cristo. Isso não muda."',
        igreja: 'Não exija rebatismo de membros transferidos a não ser que haja dúvida séria sobre a validade do batismo anterior.',
      },
      oracao: 'Senhor, que meu batismo seja âncora da minha identidade em Cristo — uma realidade permanente que não depende do meu desempenho diário. Amém.',
      reflexao: 'Nos dias de dúvida espiritual, Lutero dizia: "Fui batizado." Não "tenho fé suficiente" — mas a marca objetiva e permanente do batismo o ancorava na graça.',
      aplicacao: 'Memorize Efésios 4.4-6 como âncora da sua identidade em Cristo.',
      notas: [
        'LUTHER, Martin. <em>Catecismo Maior</em>. São Paulo: Concórdia, 2000. Sobre o Batismo.',
        'CB 1689, Cap. 29 §4.',
      ],
      notaInicio: 338,
    },
  ];
  return dias.map(bloco);
}

// ============================================================================
// Junho C — Dias 168–175 — CB 1689 Cap. 29 §5–8 + Cap. 30 §1–7
// ============================================================================

function gerarDiasJunho_C(): ReturnType<typeof bloco>[] {
  const dias: DiaCompacto[] = [
    {
      dia: 168,
      data: '17 jun',
      tema: 'Batismo: Obediência que Não Depende de Perfeição',
      capitulo: 'CB 1689 29.5-8',
      versiculo: 'Atos 10.47-48',
      versiculoTexto: 'Pode alguém recusar a água para que não sejam batizados estes, que receberam o Espírito Santo como nós também? E mandou que fossem batizados em nome do Senhor.',
      confissaoTexto: 'CB 1689 Cap. 29 §5-8: A graça do batismo não está vinculada ao momento exato de sua administração; todavia, é dever de todo crente fazer uso diligente desta ordenança.',
      cfwRef: 'CFW Cap. 28 §5-7 — eficácia e dever do batismo',
      cfwComparacao: 'Ambas afirmam que a graça ligada ao batismo não opera no exato momento do rito — o Espírito age quando e como quer. Mas ambas insistem na obrigação de ser batizado. A desobediência ao mandamento do batismo não é questão de liberdade cristã.',
      exposicao: 'Cornélio e sua família receberam o Espírito antes do batismo — mas Pedro mandou que fossem batizados assim mesmo. O batismo é obediência a um mandamento de Cristo, não condição para receber o Espírito. A graça não está encerrada no rito, mas o rito não é opcional.',
      reforco: 'Mateus 28.19-20',
      aplicacoes: {
        digital: 'Não adie o batismo por sentir que "não está pronto." Obediência a Cristo não espera perfeição.',
        familia: 'Encoraje membros da família que professam fé mas procrastinam o batismo.',
        filhos: 'Ensine: "Quando você crer em Jesus, o próximo passo é ser batizado. É assim que Jesus mandou."',
        homens: 'Se você ainda não foi batizado após sua conversão, fale com seu pastor esta semana.',
        mulheres: 'Ore por aqueles que professam fé mas ainda não deram o passo do batismo.',
        igreja: 'Tenha cultura de encorajar batismo logo após profissão de fé — não deixe candidatos esperando indefinidamente.',
      },
      oracao: 'Senhor, que eu obedeca teus mandamentos sem procrastinar, sabendo que a obediência é o caminho da bênção. Amém.',
      reflexao: 'Adiar o batismo indefinidamente é sinalizar que obediência a Cristo é opcional. Não é.',
      aplicacao: 'Se há alguém que você conhece que professa fé mas não foi batizado, ore e encoraje-o gentilmente.',
      notas: [
        "WELLUM, Stephen. \"Baptism and the Relationship Between the Covenants.\" In: <em>Believer's Baptism</em>. Nashville: B&H, 2006.",
        'CB 1689, Cap. 29 §5-8.',
      ],
      notaInicio: 340,
    },
    {
      dia: 169,
      data: '18 jun',
      tema: 'Ceia do Senhor: Memorial e Comunhão Real',
      capitulo: 'CB 1689 30.1',
      versiculo: '1 Coríntios 11.24',
      versiculoTexto: 'E, havendo dado graças, partiu-o e disse: Tomai, comei; isto é o meu corpo que é partido por vós; fazei isto em memória de mim.',
      confissaoTexto: 'CB 1689 Cap. 30 §1: A Ceia do Senhor foi instituída por Jesus Cristo na noite em que foi traído, para ser observada em sua Igreja até o fim do mundo, para a lembrança perpétua e a proclamação do sacrifício de si mesmo na morte.',
      cfwRef: 'CFW Cap. 29 §1 — instituição da Ceia',
      cfwComparacao: 'CB 1689 e CFW concordam plenamente: a Ceia é memorial que proclama a morte de Cristo até sua vinda. Ambas rejeitam o sacrifício da missa (catolicismo) — Cristo não é re-sacrificado na Ceia. Ambas afirmam presença espiritual real de Cristo, não presença corporal física.',
      exposicao: 'A Ceia é "memória" — mas não mera memória intelectual. É proclamação ativa ("anunciais a morte do Senhor") e comunhão real com Cristo ressurreto. O pão e o vinho não se tornam corpo e sangue literais — mas o crente que participa com fé recebe espiritualmente os benefícios da morte de Cristo.',
      reforco: '1 Coríntios 11.26',
      aplicacoes: {
        digital: 'Numa era de experiências virtuais, a Ceia insiste em elementos físicos: pão real, vinho real. Corporalidade importa.',
        familia: 'Explique aos filhos mais velhos o significado da Ceia antes de participarem pela primeira vez.',
        filhos: 'Ensine: "A Ceia é quando a Igreja lembra juntos que Jesus morreu por nós e que ele voltará."',
        homens: 'Tome a Ceia com sobriedade — examine-se, confesse o pecado, celebre a graça.',
        mulheres: 'A Ceia é momento de profunda comunhão — com Cristo e com os irmãos. Não a tome distraidamente.',
        igreja: 'Celebre a Ceia com frequência e instrução. O que é feito sem entendimento não alimenta a fé.',
      },
      oracao: 'Senhor Jesus, quando tomamos o pão e o vinho, proclamamos tua morte até que voltes. Que esta memória seja viva, não ritual. Amém.',
      reflexao: 'A Ceia do Senhor é o evangelho encenado. Cada vez que partimos o pão, proclamamos: "Cristo morreu, ressuscitou, voltará."',
      aplicacao: 'Antes da próxima Ceia, leia 1 Coríntios 11.17-34 e prepare seu coração com exame e gratidão.',
      notas: [
        "MATHISON, Keith. <em>Given for You: Reclaiming Calvin's Doctrine of the Lord's Supper</em>. Phillipsburg: P&R, 2002.",
        'CB 1689, Cap. 30 §1.',
      ],
      notaInicio: 342,
    },
    {
      dia: 170,
      data: '19 jun',
      tema: 'Ceia: Somente Cristo Pode Instituir os Elementos',
      capitulo: 'CB 1689 30.2',
      versiculo: 'Mateus 26.26-27',
      versiculoTexto: 'E, enquanto comiam, tomou Jesus o pão e, abençoando-o, o partiu e o deu aos discípulos e disse: Tomai, comei; isto é o meu corpo. E, tomando o cálice e, havendo dado graças, deu-lho, dizendo: Bebei dele todos.',
      confissaoTexto: 'CB 1689 Cap. 30 §2: Nesta ordenança, Cristo não é oferecido ao Pai nem qualquer sacrifício real é feito pela remissão dos pecados dos vivos ou dos mortos, mas somente uma comemoração daquele único sacrifício de si mesmo na cruz.',
      cfwRef: 'CFW Cap. 29 §2 — rejeição do sacrifício da missa',
      cfwComparacao: 'CB 1689 e CFW são idênticas em rejeitar a doutrina católica do sacrifício da missa. Cristo foi sacrificado uma vez para sempre (Hb 9.28). A Ceia comemora — não repete — esse sacrifício único. Não há sacerdote humano que ofereça Cristo ao Pai.',
      exposicao: 'O sacrifício de Cristo foi perfeito e único — "por uma só oblação aperfeiçoou para sempre os que são santificados" (Hb 10.14). Qualquer doutrina que faz da Ceia um novo sacrifício nega a suficiência da cruz. A Ceia olha para trás (memorial), proclama no presente, e antecipa o futuro (vinda de Cristo).',
      reforco: 'Hebreus 10.10-14',
      aplicacoes: {
        digital: 'Em uma era de ofertas digitais, lembre: a única oferta que salva foi feita por Cristo na cruz — uma vez.',
        familia: 'Explique a diferença entre a Ceia protestante e a missa católica quando perguntado pelos filhos.',
        filhos: 'Ensine: "Jesus morreu uma só vez. A Ceia é para lembrar esse sacrifício — não para repeti-lo."',
        homens: 'A suficiência do sacrifício de Cristo é a base de toda segurança espiritual. Não é preciso nada mais.',
        mulheres: 'Celebre a Ceia com certeza: o sacrifício que ela comemora é completo, perfeito e irreversível.',
        igreja: 'Instrua a congregação sobre a distinção entre memorial e sacrifício. Esta diferença é evangelicamente fundamental.',
      },
      oracao: 'Senhor Jesus, teu sacrifício foi perfeito e completo. Não precisamos oferecer-te novamente — apenas comemorar com gratidão o que fizeste. Amém.',
      reflexao: 'A cruz não precisa de complemento. A Ceia que comemora um sacrifício suficiente é ato de fé; a missa que o repete é ato de dúvida.',
      aplicacao: 'Leia Hebreus 9.11-28 e medite na suficiência absoluta do sacrifício de Cristo.',
      notas: [
        'SPROUL, R.C. <em>The Truth of the Cross</em>. Orlando: Reformation Trust, 2007.',
        'CB 1689, Cap. 30 §2.',
      ],
      notaInicio: 344,
    },
    {
      dia: 171,
      data: '20 jun',
      tema: 'Ceia: Presença Espiritual, Não Corporal',
      capitulo: 'CB 1689 30.3',
      versiculo: 'João 6.63',
      versiculoTexto: 'O espírito é o que vivifica; a carne para nada aproveita; as palavras que eu vos disse são espírito e são vida.',
      confissaoTexto: 'CB 1689 Cap. 30 §3: O corpo e o sangue de Cristo não estão corporal ou carnalmente no pão e no vinho; mas são tão realmente presentes para a fé dos que creem como os elementos mesmos são para os sentidos externos.',
      cfwRef: 'CFW Cap. 29 §7 — sobre a presença de Cristo na Ceia',
      cfwComparacao: 'CB 1689 e CFW concordam: Cristo está espiritualmente presente na Ceia — não corporalmente. Rejeitam transubstanciação (Roma) e consubstanciação (Lutero). A presença é real, mas espiritual — recebida pela fé, não pelos dentes.',
      exposicao: 'O pão é pão e o vinho é vinho — mas são sinais que comunicam realidades espirituais. Cristo não desce do céu a cada Ceia; o Espírito eleva o crente a Cristo. A fé recebe Cristo espiritualmente — e isso é mais real do que a mastigação literal.',
      reforco: 'Atos 3.21',
      aplicacoes: {
        digital: 'Assim como uma mensagem de amor comunicada digitalmente é real sem presença física, Cristo se comunica espiritualmente pela Ceia de modo real.',
        familia: 'Na Ceia, elevamos nossa fé a Cristo — não o trazemos ao pão. Esta distinção importa.',
        filhos: 'Ensine: "O pão e o vinho representam o corpo e o sangue de Jesus. Quando comemos com fé, encontramos Jesus."',
        homens: 'Tome a Ceia com expectativa espiritual real — não como ritual mecânico, nem como ato místico-mágico.',
        mulheres: 'A Ceia alimenta a alma de modo real — espiritual, mas não menos real do que o alimento físico alimenta o corpo.',
        igreja: 'Ensine a congregação a tomar a Ceia com fé ativa e expectativa de comunhão real com Cristo.',
      },
      oracao: 'Senhor Jesus, quando partimos o pão, que nossa fé se eleve a ti que estás à direita do Pai. Que a Ceia seja encontro espiritual real, não ritual mecânico. Amém.',
      reflexao: 'A Ceia alimenta não porque o pão se torna carne, mas porque a fé que recebe o sinal recebe também a realidade que ele sinaliza — Cristo e seus benefícios.',
      aplicacao: 'Na próxima Ceia, feche os olhos após receber os elementos e ore: "Senhor Jesus, recebo teus benefícios por fé."',
      notas: [
        'CALVIN, John. <em>Institutes of the Christian Religion</em>. IV.17. Grand Rapids: Eerdmans, 1960.',
        'CB 1689, Cap. 30 §3.',
      ],
      notaInicio: 346,
    },
    {
      dia: 172,
      data: '21 jun',
      tema: 'Ceia: Exame Próprio e Participação Digna',
      capitulo: 'CB 1689 30.4',
      versiculo: '1 Coríntios 11.28-29',
      versiculoTexto: 'Examine-se, pois, o homem a si mesmo, e, assim, coma do pão e beba do cálice. Porque quem come e bebe indignamente, sem discernir o corpo do Senhor, come e bebe juízo para si.',
      confissaoTexto: 'CB 1689 Cap. 30 §4: Os ignorantes e ímpios são impróprios para desfrutar da Ceia do Senhor e não devem ser admitidos a ela.',
      cfwRef: 'CFW Cap. 29 §8 — sobre a admissão à Ceia',
      cfwComparacao: 'CB 1689 e CFW concordam: a Ceia não é para todos — somente para crentes batizados e membros em boa situação. Ambas citam 1 Co 11 como base para o exame próprio e para a disciplina de admissão.',
      exposicao: 'Paulo é claro: tomar a Ceia sem discernir o corpo do Senhor é comer juízo. O exame não é sobre perfeição moral — é sobre fé viva em Cristo, arrependimento de pecados conhecidos, e paz com os irmãos.',
      reforco: '2 Coríntios 13.5',
      aplicacoes: {
        digital: 'Participar da Ceia por transmissão sem membresia, exame ou accountability eclesial fragiliza o significado do ato.',
        familia: 'Ensine as crianças que a Ceia é para membros batizados — e use isso para incentivar conversão e batismo.',
        filhos: 'Explique: "A Ceia é para quem já decidiu seguir Jesus e foi batizado."',
        homens: 'Antes da Ceia, examine-se: há pecado não confessado? Há conflito não resolvido com um irmão?',
        mulheres: 'O exame antes da Ceia é hábito espiritual saudável — não obsessão por perfeição, mas honestidade diante de Deus.',
        igreja: 'Pratique a comunhão controlada — não como exclusividade orgulhosa, mas como proteção espiritual.',
      },
      oracao: 'Senhor, que eu nunca tome a Ceia de modo rotineiro. Que cada participação seja precedida de exame genuíno. Amém.',
      reflexao: 'O crente que toma a Ceia sem exame subestima o que está fazendo. O crente que nunca participa por sentir-se indigno precisa de fé, não de perfeição.',
      aplicacao: 'Antes da próxima Ceia, escreva numa folha os pecados que precisa confessar e as relações que precisa restaurar.',
      notas: [
        'PIPER, John. <em>This Momentary Marriage</em>. Wheaton: Crossway, 2009.',
        'CB 1689, Cap. 30 §4.',
      ],
      notaInicio: 348,
    },
    {
      dia: 173,
      data: '22 jun',
      tema: 'Ceia: Frequência e Celebração',
      capitulo: 'CB 1689 30.5',
      versiculo: 'Atos 20.7',
      versiculoTexto: 'E no primeiro dia da semana, estando os discípulos reunidos para partir o pão, Paulo lhes falava, tendo de partir no dia seguinte.',
      confissaoTexto: 'CB 1689 Cap. 30 §5: A Ceia do Senhor é para ser frequentemente participada pelos santos, para a sua edificação espiritual e encorajamento.',
      cfwRef: 'CFW Cap. 29 §7 — frequência da Ceia',
      cfwComparacao: 'Tanto CB 1689 quanto CFW incentivam participação frequente. A Igreja primitiva partia o pão toda semana (At 20.7). A frequência importa — a Ceia não é evento especial anual.',
      exposicao: 'A Igreja primitiva partia o pão toda semana. A Ceia é alimento espiritual regular — não banquete de gala esporádico. Igrejas que celebram a Ceia raramente privam seus membros de nutrição espiritual que Cristo proveu.',
      reforco: '1 Coríntios 11.26',
      aplicacoes: {
        digital: 'Assim como você não se alimenta fisicamente uma vez por mês, não faz sentido receber o alimento espiritual da Ceia raramente.',
        familia: 'Priorize os cultos em que a Ceia é celebrada. Não os salte por conveniência.',
        filhos: 'Ensine: "A Ceia é como a refeição da família de Deus — fazemos regularmente porque somos família."',
        homens: 'Se sua Igreja celebra a Ceia mensalmente, esteja presente. Priorize a assemblia que celebra os meios de graça.',
        mulheres: 'Celebre a Ceia com alegria e antecipação — não como dever pesado, mas como banquete com Cristo.',
        igreja: 'Considere aumentar a frequência da Ceia se ela é celebrada raramente.',
      },
      oracao: 'Senhor, que a Ceia seja alimento regular de nossa comunidade. Amém.',
      reflexao: 'A Igreja que celebra a Ceia raramente treina seus membros a considerar os meios de graça como opcionais.',
      aplicacao: 'Descubra com que frequência sua Igreja celebra a Ceia. Se raramente, converse com os presbíteros sobre a prática histórica reformada.',
      notas: [
        'MATHISON, Keith. <em>Given for You</em>. Phillipsburg: P&R, 2002.',
        'CB 1689, Cap. 30 §5.',
      ],
      notaInicio: 350,
    },
    {
      dia: 174,
      data: '23 jun',
      tema: 'Ceia: Elementos para Todos — Pão e Cálice',
      capitulo: 'CB 1689 30.6',
      versiculo: 'Mateus 26.27',
      versiculoTexto: 'E, tomando o cálice e, havendo dado graças, deu-lho, dizendo: Bebei dele todos.',
      confissaoTexto: 'CB 1689 Cap. 30 §6: A Ceia deve ser ministrada em ambas as espécies — pão e vinho — a todos os participantes.',
      cfwRef: 'CFW Cap. 29 §3 — sobre as espécies da Ceia',
      cfwComparacao: 'CB 1689 e CFW concordam: todos os participantes devem receber tanto o pão quanto o cálice. Rejeitam a prática católica de comunhão sob uma só espécie.',
      exposicao: 'Cristo disse "bebei dele todos" — não apenas os sacerdotes. A retenção do cálice ao laicato é inovação humana sem base bíblica. Quando recebemos pão e cálice, proclamamos juntos a morte de Cristo.',
      reforco: '1 Coríntios 11.25-26',
      aplicacoes: {
        digital: 'Comunhão parcial (pão sem cálice) é como evangelho parcial — desfigura a mensagem completa da morte de Cristo.',
        familia: 'Quando sua família participa da Ceia, certifique-se que todos os membros batizados recebam os dois elementos.',
        filhos: 'Ensine: "Na Ceia, todos que pertencem a Jesus recebem o pão e o vinho — não apenas os pastores."',
        homens: 'Defenda a integridade dos dois elementos contra qualquer prática de exclusão.',
        mulheres: 'Receba ambos os elementos com gratidão — o pão que representa o corpo entregue, o cálice que representa o sangue derramado.',
        igreja: 'Verifique se sua prática de Ceia é fiel ao mandamento de Cristo — pão e cálice para todos os participantes.',
      },
      oracao: 'Senhor, que recebamos o pão e o cálice com entendimento completo do que representam. Amém.',
      reflexao: 'Os dois elementos da Ceia comunicam juntos a mensagem completa do evangelho: corpo partido, sangue derramado.',
      aplicacao: 'Na próxima Ceia, ao receber o cálice, diga em silêncio: "Este sangue foi derramado por mim."',
      notas: [
        "LETHAM, Robert. <em>The Lord's Supper: Eternal Word in Broken Bread</em>. Phillipsburg: P&R, 2001.",
        'CB 1689, Cap. 30 §6.',
      ],
      notaInicio: 352,
    },
    {
      dia: 175,
      data: '24 jun',
      tema: 'Ceia: Não Se Adora o Pão',
      capitulo: 'CB 1689 30.7',
      versiculo: 'Deuteronômio 4.15-16',
      versiculoTexto: 'Guardai, pois, muito bem as vossas almas... para que não vos corrompais e vos façais alguma imagem esculpida.',
      confissaoTexto: 'CB 1689 Cap. 30 §7: O pão e o vinho não devem ser adorados, elevados para adoração, ou reservados para qualquer uso religioso posterior. Adorar os elementos é idolatria.',
      cfwRef: 'CFW Cap. 29 §4 — rejeição da adoração dos elementos',
      cfwComparacao: 'CB 1689 e CFW são unânimes: adorar os elementos da Ceia é idolatria. A prática católica de elevação da hóstia e adoração eucarística é diretamente rejeitada por ambas.',
      exposicao: 'Adorar o pão em vez de Cristo que o pão representa é cometer o mesmo erro que adorar uma imagem. O pão é sinal — sinais apontam para além de si mesmos. Elevar o pão para adoração perverte sua função.',
      reforco: 'João 4.23-24',
      aplicacoes: {
        digital: 'A adoração de imagens digitais de Cristo ou símbolos religiosos é versão moderna do mesmo erro — substituir o original pelo símbolo.',
        familia: 'Ensine os filhos a distinguir entre símbolo e realidade — a adoração pertence a Cristo, não às representações de Cristo.',
        filhos: 'Explique: "O pão aponta para Jesus. Nós adoramos Jesus, não o pão."',
        homens: 'Defenda a distinção entre símbolo e realidade contra práticas de veneração de objetos religiosos.',
        mulheres: 'A adoração em espírito e verdade não depende de objetos físicos — depende de fé e do Espírito.',
        igreja: 'Garanta que os elementos sejam descartados reverentemente após a Ceia — sem tratamento de relíquias sagradas.',
      },
      oracao: 'Senhor, que adoremos a ti e somente a ti — não os sinais, não as imagens. Guarda-nos da idolatria sutil. Amém.',
      reflexao: 'O sinal que atrai adoração para si mesmo se torna ídolo. O sinal fiel aponta além de si mesmo para Cristo.',
      aplicacao: 'Examine sua vida: há objetos, imagens, ou símbolos religiosos que estão recebendo reverência que pertence somente a Cristo?',
      notas: [
        'SPROUL, R.C. <em>The Holiness of God</em>. Wheaton: Tyndale, 1985.',
        'CB 1689, Cap. 30 §7.',
      ],
      notaInicio: 354,
    },
  ];
  return dias.map(bloco);
}

// ============================================================================
// Junho D — Dias 176–181 — CB 1689 Cap. 31 + Cap. 32
// ============================================================================

export function gerarDiasJunho_D(): ReturnType<typeof bloco>[] {
  const dias: DiaCompacto[] = [
    {
      dia: 176,
      data: '25 jun',
      tema: 'Estado após a Morte: A Alma Nunca Dorme',
      capitulo: 'CB 1689 31.1',
      versiculo: 'Filipenses 1.23',
      versiculoTexto: 'Porque de ambos os lados estou em aperto: tenho desejo de partir e estar com Cristo, porque isto é muito melhor.',
      confissaoTexto: 'CB 1689 Cap. 31 §1: Os corpos dos homens, após a morte, retornam ao pó; mas suas almas, que nem morrem nem dormem, tendo subsistência imortal, retornam imediatamente a Deus que as deu.',
      cfwRef: 'CFW Cap. 32 §1 — sobre o estado após a morte',
      cfwComparacao: 'CB 1689 e CFW são praticamente idênticas neste ponto. Ambas rejeitam o "sono da alma" (psychopannychia). Paulo deseja "partir e estar com Cristo" — não dormir inconscientemente. A consciência persiste após a morte.',
      exposicao: 'A morte separa corpo e alma — temporariamente. O corpo retorna ao pó; a alma consciente vai imediatamente à presença de Deus (crentes) ou ao tormento (ímpios). Para o crente, partir é "muito melhor" porque é estar com Cristo.',
      reforco: 'Lucas 23.43',
      aplicacoes: {
        digital: 'Em uma cultura obcecada com prolongar a vida biológica, o crente tem perspectiva diferente: a morte não é o pior fim.',
        familia: 'Fale sobre morte com seus filhos — especialmente sobre o que acontece depois. A Bíblia não silencia sobre isso.',
        filhos: 'Ensine: "Quando um cristão morre, sua alma vai estar com Jesus. O corpo dorme, mas a pessoa está acordada com o Senhor."',
        homens: 'O homem que não tem medo da morte é livre para viver corajosamente.',
        mulheres: 'Ore pelos membros da Igreja que estão em luto — consolando-os com a esperança bíblica.',
        igreja: 'Nos cultos fúnebres, proclame a esperança bíblica do estado intermediário e da ressurreição.',
      },
      oracao: 'Senhor, que a certeza de que partir é estar com Cristo nos liberte do medo da morte. Amém.',
      reflexao: 'Paulo chama a morte de "ganho" — porque a morte não termina a existência consciente do crente, mas a leva à plena presença de Cristo.',
      aplicacao: 'Leia Filipenses 1.20-23 e medite: você tem a perspectiva de Paulo sobre a morte?',
      notas: [
        'HOEKEMA, Anthony A. <em>The Bible and the Future</em>. Grand Rapids: Eerdmans, 1979.',
        'CB 1689, Cap. 31 §1.',
      ],
      notaInicio: 356,
    },
    {
      dia: 177,
      data: '26 jun',
      tema: 'Estado Intermediário: Com Cristo ou Separado',
      capitulo: 'CB 1689 31.2',
      versiculo: 'Lucas 16.22-23',
      versiculoTexto: 'E aconteceu que morreu o mendigo e foi levado pelos anjos ao seio de Abraão; morreu também o rico e foi sepultado. E no inferno, estando em tormentos, levantou os olhos.',
      confissaoTexto: 'CB 1689 Cap. 31 §2: As almas dos justos, sendo então aperfeiçoadas em santidade, são recebidas no mais alto céu. As almas dos ímpios são lançadas ao inferno, onde permanecem em tormentos até ao juízo do grande dia.',
      cfwRef: 'CFW Cap. 32 §1 — estado intermediário dos justos e dos ímpios',
      cfwComparacao: 'CB 1689 e CFW concordam: dois destinos imediatos após a morte — presença de Cristo (justos) ou tormento (ímpios). Ambas rejeitam o purgatório romano e o universalismo.',
      exposicao: 'A parábola do rico e Lázaro ensina destinos conscientes e distintos após a morte. O pobre vai ao "seio de Abraão". O rico vai ao inferno em tormentos. Este estado intermediário é anterior à ressurreição e ao juízo final.',
      reforco: '2 Coríntios 5.6-8',
      aplicacoes: {
        digital: 'O universalismo digital — "todos vão para o céu" — contraria tanto a parábola de Jesus quanto ambas as confissões reformadas.',
        familia: 'A certeza do estado intermediário motiva evangelismo: as pessoas morrem e vão para algum lugar.',
        filhos: 'Ensine: "Quem morre confiando em Jesus vai estar com ele. Por isso contamos sobre Jesus."',
        homens: 'O estado intermediário consciente deve motivar urgência evangélica: não há segunda chance após a morte.',
        mulheres: 'Ore pelos não-convertidos com urgência — a morte pode chegar a qualquer momento.',
        igreja: 'Pregue sobre o estado intermediário com clareza e amor.',
      },
      oracao: 'Senhor, que a realidade do estado intermediário nos mova a viver com urgência espiritual. Amém.',
      reflexao: 'Não existe segunda oportunidade após a morte — o estado em que a pessoa morre é o estado em que permanecerá até o juízo.',
      aplicacao: 'Ore pelo nome de pelo menos uma pessoa que você conhece que não é salva.',
      notas: [
        'GRUDEM, Wayne. <em>Teologia Sistemática</em>. São Paulo: Vida Nova, 1999. Cap. 41.',
        'CB 1689, Cap. 31 §2.',
      ],
      notaInicio: 358,
    },
    {
      dia: 178,
      data: '27 jun',
      tema: 'Ressurreição: Estes Mesmos Corpos Se Levantarão',
      capitulo: 'CB 1689 31.3',
      versiculo: 'João 5.28-29',
      versiculoTexto: 'Não vos maravilheis disso, porque a hora vem em que todos os que estão nos sepulcros ouvirão a sua voz; e os que tiverem feito o bem ressurgirão para a ressurreição da vida, e os que tiverem praticado o mal, para a ressurreição da condenação.',
      confissaoTexto: 'CB 1689 Cap. 31 §3: No último dia, os corpos dos mortos serão ressuscitados — os mesmos corpos que morreram, unidos às suas almas para sempre.',
      cfwRef: 'CFW Cap. 32 §2-3 — sobre a ressurreição dos mortos',
      cfwComparacao: 'CB 1689 e CFW concordam: a ressurreição é corporal, real e universal. Todos ressuscitarão — justos e ímpios. Os corpos ressurretos serão os mesmos que morreram, porém transformados.',
      exposicao: 'A fé cristã não é escape do corpo — é redenção do corpo. "Estes mesmos corpos" ressuscitarão — identidade corporal preservada. O corpo ressurreto de Cristo é o modelo do nosso: reconhecível mas glorificado. A esperança cristã não é imortalidade da alma apenas — é ressurreição do corpo.',
      reforco: '1 Coríntios 15.52-53',
      aplicacoes: {
        digital: 'Numa era que quer "fazer upload" da consciência — a fé cristã insiste na importância do corpo. Você não é uma mente — você é uma pessoa encarnada.',
        familia: 'A esperança da ressurreição consola nos lutos. Aquele corpo que amamos ressurgirá.',
        filhos: 'Ensine: "Quando Jesus voltar, os corpos de todos os cristãos mortos vão se levantar e ser transformados."',
        homens: 'A esperança da ressurreição dá dignidade ao corpo agora. Como você trata seu corpo importa — ele ressuscitará.',
        mulheres: 'Cuide de seu corpo como templo do Espírito e semente de ressurreição.',
        igreja: 'Afirme claramente nas pregações sobre morte e luto: a esperança cristã é ressurreição corporal.',
      },
      oracao: 'Senhor, que a esperança da ressurreição corporal nos liberte de desespero diante da morte. Amém.',
      reflexao: 'A ressurreição não é consolação poética — é afirmação ontológica: o mesmo "eu" encarnado que morreu será o mesmo que ressurgirá, transformado pela glória de Cristo.',
      aplicacao: 'Leia 1 Coríntios 15.35-58 inteiro. O que a ressurreição corporal significa para como você vive hoje?',
      notas: [
        'WRIGHT, N.T. <em>Surprised by Hope</em>. New York: HarperOne, 2008.',
        'CB 1689, Cap. 31 §3.',
      ],
      notaInicio: 360,
    },
    {
      dia: 179,
      data: '28 jun',
      tema: 'Juízo Final: Todos Prestarão Contas',
      capitulo: 'CB 1689 32.1',
      versiculo: '2 Coríntios 5.10',
      versiculoTexto: 'Porque todos nós havemos de comparecer ante o tribunal de Cristo, para que cada um receba o que merece, segundo o que tiver feito por meio do corpo, ou bem ou mal.',
      confissaoTexto: 'CB 1689 Cap. 32 §1: Deus designou um dia em que ele julgará o mundo com justiça por Jesus Cristo, ao qual todo poder e julgamento foram dados pelo Pai.',
      cfwRef: 'CFW Cap. 33 §1 — sobre o juízo final',
      cfwComparacao: 'CB 1689 e CFW concordam plenamente: haverá um juízo final, executado por Cristo, universal e justo. Todos — vivos e mortos, crentes e incrédulos — prestarão contas.',
      exposicao: 'O juízo final não é ameaça vaga — é certeza histórica. Deus "designou um dia" — há uma data no calendário eterno. O juiz é Cristo. Para os crentes, o juízo é confirmação de graça. Para os ímpios, é sentença de justiça. Ninguém escapa.',
      reforco: 'Apocalipse 20.12',
      aplicacoes: {
        digital: 'Em uma cultura de anonimato online onde as pessoas dizem e fazem sem consequências, o juízo final afirma: cada palavra proferida será pesada.',
        familia: 'Ensine os filhos que Deus vê tudo — não como ameaça, mas como motivação para integridade.',
        filhos: 'Ensine: "Deus vê tudo o que fazemos. Um dia todos prestarão contas."',
        homens: 'O homem que vive como se não houvesse julgamento viverá sem integridade.',
        mulheres: 'O serviço fiel e não reconhecido nesta vida será recompensado no julgamento.',
        igreja: 'Pregue sobre o juízo final sem embaraço — é doutrina bíblica que motiva evangelismo, santidade e consolo.',
      },
      oracao: 'Senhor Jesus, que a certeza do tribunal de Cristo me motive a viver com integridade hoje. Amém.',
      reflexao: 'O crente aparece diante do tribunal de Cristo não para ser condenado, mas para ser recompensado. A condenação já foi absorvida na cruz.',
      aplicacao: 'Imagine estar hoje diante do tribunal de Cristo. O que mudaria em suas prioridades e decisões?',
      notas: [
        'SPROUL, R.C. <em>The Last Days According to Jesus</em>. Grand Rapids: Baker, 1998.',
        'CB 1689, Cap. 32 §1.',
      ],
      notaInicio: 362,
    },
    {
      dia: 180,
      data: '29 jun',
      tema: 'Juízo Final: Para Glória de Deus e Consolação dos Santos',
      capitulo: 'CB 1689 32.2',
      versiculo: 'Mateus 25.34',
      versiculoTexto: 'Então dirá o Rei aos que estiverem à sua direita: Vinde, benditos de meu Pai, possuí em herança o reino que vos está preparado desde a fundação do mundo.',
      confissaoTexto: 'CB 1689 Cap. 32 §2: O fim de Deus ao designar este dia é para a manifestação da glória de sua misericórdia na salvação dos eleitos e de sua justiça na condenação dos réprobos.',
      cfwRef: 'CFW Cap. 33 §2 — propósito do juízo',
      cfwComparacao: 'CB 1689 e CFW concordam: o juízo final serve à glória de Deus — tanto da sua misericórdia (salvar os eleitos) quanto da sua justiça (condenar os ímpios).',
      exposicao: 'O juízo final não é capricho divino — é manifestação coordenada da misericórdia e da justiça de Deus. Os eleitos entram na herança preparada "desde a fundação do mundo". Os réprobos recebem o que seus pecados merecem. Ambos os destinos revelam a perfeição de Deus.',
      reforco: 'Romanos 9.22-23',
      aplicacoes: {
        digital: 'A pergunta moderna "como um Deus bom pode condenar?" pressupõe que a misericórdia anula a justiça. O juízo final mostra que Deus é bom precisamente porque é justo.',
        familia: 'Ensine os filhos que o céu não é direito automático — é herança para os que estão em Cristo.',
        filhos: 'Ensine: "Deus preparou um lugar incrível para os que amam Jesus — e o planejou antes de criar o mundo."',
        homens: 'A eleição não é motivo de orgulho — é motivo de gratidão e de urgência em proclamar o evangelho.',
        mulheres: 'A segurança da eleição e do juízo favorável em Cristo é base de paz profunda.',
        igreja: 'Pregue o juízo final com equilíbrio: condenação real para os ímpios, herança gloriosa para os eleitos.',
      },
      oracao: 'Senhor, que o juízo final me encha de assombro e gratidão: fui eleito em Cristo antes da fundação do mundo. Amém.',
      reflexao: 'O dia do juízo será, para os santos, o dia da maior alegria — quando o que sempre foi verdade (justificados em Cristo) será publicamente declarado.',
      aplicacao: 'Leia Mateus 25.31-46. O que você sente ao imaginar ouvir "vinde, benditos de meu Pai"?',
      notas: [
        'PIPER, John. <em>God Is the Gospel</em>. Wheaton: Crossway, 2005.',
        'CB 1689, Cap. 32 §2.',
      ],
      notaInicio: 364,
    },
    {
      dia: 181,
      data: '30 jun',
      tema: 'Juízo Final: Conhecer o Dia Encoraja a Vigilância',
      capitulo: 'CB 1689 32.3',
      versiculo: 'Mateus 24.42',
      versiculoTexto: 'Portanto, vigiai, porque não sabeis a que hora há de vir o vosso Senhor.',
      confissaoTexto: 'CB 1689 Cap. 32 §3: Cristo quis que o dia do juízo fosse desconhecido pelos homens, para que eles sacudissem toda segurança carnal e estivessem sempre vigilantes.',
      cfwRef: 'CFW Cap. 33 §3 — sobre a incerteza do dia do juízo',
      cfwComparacao: 'CB 1689 e CFW concordam: o dia do juízo é propositalmente desconhecido. Nenhum homem, anjo ou profeta sabe a data. A incerteza é pedagógica — mantém os crentes em vigilância constante.',
      exposicao: 'Cristo poderia ter revelado a data do seu retorno — optou por não revelar. Porque a vigilância não sobrevive ao prazo certo. A incerteza nos mantém sempre prontos. Todo dia pode ser o último — por isso, todo dia deve ser vivido com plenitude de devoção.',
      reforco: '1 Tessalonicenses 5.2',
      aplicacoes: {
        digital: 'Profetas online que anunciam datas para o retorno de Cristo contradizem o ensinamento explícito de Jesus. Bloqueie e ignore.',
        familia: 'Ensine os filhos que não sabemos quando Jesus voltará — por isso vivemos preparados todos os dias.',
        filhos: 'Ensine: "Ninguém sabe quando Jesus vai voltar. Por isso vivemos prontos — como se fosse hoje."',
        homens: 'A vigilância espiritual não é tensão ansiosa — é atenção amorosa ao Senhor que pode vir a qualquer momento.',
        mulheres: 'Viver com o retorno de Cristo em mente liberta. O que importa fica claro quando sabemos que o fim pode ser hoje.',
        igreja: 'Pregue sobre a volta de Cristo com regularidade. A expectativa da parousia molda o caráter da Igreja.',
      },
      oracao: 'Senhor Jesus, não sei quando voltarás. Mas sei que voltarás. Que essa certeza me mantenha vigilante e fiel — até que venhas ou me chames. Amém.',
      reflexao: 'O crente que vive como se Cristo pudesse voltar hoje é o mesmo que planeja para o futuro com sabedoria — a vigilância e a fidelidade cotidiana são a mesma coisa.',
      aplicacao: 'Se Jesus voltasse hoje, o que você mudaria na sua vida? Faça essa mudança agora.',
      notas: [
        'CLOWNEY, Edmund P. <em>The Message of 1 Peter</em>. Downers Grove: IVP, 1988.',
        'CB 1689, Cap. 32 §3.',
      ],
      notaInicio: 366,
    },
  ];
  return dias.map(bloco);
}`;

// Replace lines startLine through endLine (inclusive) with new content
const before = lines.slice(0, startLine);
const after = lines.slice(endLine + 1);

const newLines = [...before, ...newContent.split('\n'), ...after];
fs.writeFileSync(filePath, newLines.join('\n'), 'utf8');

console.log('Done. Lines replaced:', startLine + 1, 'to', endLine + 1);
console.log('New total lines:', newLines.length);
