const fs = require('fs');
let content = fs.readFileSync('src/data/calendarioDevocional.ts', 'utf8');

const fixes = [
  ['Jardim não Éden','Jardim no Éden'],
  ['Abrão e Ló Separate','Abrão e Ló se Separam'],
  ['Pursuers afogado','Os Perseguidores Afogados'],
  ['Amargo Água fez Sweet','Água Amarga Tornada Doce'],
  ['Israelitas Reach Monte Sinai','Os Israelitas Chegam ao Monte Sinai'],
  ['Shining face de Moisés','O Rosto Resplandecente de Moisés'],
  ['Handicapped Sacerdotes','Sacerdotes com Deficiências'],
  ['Votive Ofertas','Ofertas Votivas'],
  ['Order de acampamento e marching','Ordem do Acampamento e da Marcha'],
  ['Arão e Miriã Jealous de Moisés','Arão e Miriã com Ciúmes de Moisés'],
  ['Um Attempted Invasão é Repulsed','Uma Tentativa de Invasão é Repelida'],
  ['Peanalty para violando O Sábado','Penalidade por Violar o Sábado'],
  ['Fringes sobre vestes','Franjas sobre as Vestes'],
  ['Revolt de Coré, Datã, e Abrão','Revolta de Coré, Datã e Abrão'],
  ['Regulamentos sobre sacerdotes e Levitess','Regulamentos sobre Sacerdotes e Levitas'],
  ['Waters de Meribah','As Águas de Meribá'],
  ['Passages através de Edom recusou','Passagem por Edom Recusada'],
  ['Counquest e division de Transjordânia','Conquista e Divisão da Transjordânia'],
  ['Orders sobre herança','Ordenações sobre a Herança'],
  ['Marriages de female herdeiros','Casamentos das Herdeiras'],
  ['Events em Horebe recalled','Acontecimentos em Horebe Relembrados'],
  ['Nomeação de Tribal Líderes','Nomeação de Líderes Tribais'],
  ['Cidades de refúgio East de Jordão','Cidades de Refúgio a Leste do Jordão'],
  ['Advertência sobre perish','Advertência sobre Perecer'],
  ['Consequences de rebelando-se contra Deus','Consequências de se Rebelar contra Deus'],
  ['Segundo pair de tábuas','Segundo Par de Tábuas'],
  ['Correct lugar para adoração','Lugar Correto para a Adoração'],
  ['Um prescribed lugar de adoração','Um Lugar Prescrito para a Adoração'],
  ['Concluding exortação','Exortação Final'],
  ['Bênçãos para obediência e warnings contra desobediência','Bênçãos pela Obediência e Advertências contra a Desobediência'],
  ['O território east de Jordão','O Território a Leste do Jordão'],
  ['Os territórios ofn remaining tribos','Os Territórios das Tribos Restantes'],
  ['Eastern tribos retorno a seus terittory','As Tribos do Leste Retornam a seu Território'],
  ['O Altar de Eastern tribos','O Altar das Tribos do Leste'],
  ['O sinal de Fleece','O Sinal do Velo'],
  ['Gideão surpreende e derrota Midianites','Gideão Surpreende e Derrota os Midianitas'],
  ['De Gibeah crime','O Crime de Gibeá'],
  ['De Elimelech família vai a Moabe','A Família de Elimeleque Vai a Moabe'],
  ['Profecia Contra de Eli Household','Profecia contra a Casa de Eli'],
  ['De Samuel Vocação e Prophetic Atividade','A Vocação de Samuel e sua Atividade Profética'],
  ['De Saul Unlawfull Sacrifício','O Sacrifício Ilegal de Saul'],
  ['De Saul Continuing Guerras','As Guerras Contínuas de Saul'],
  ['Davi toca/executa Lyte para Saul','Davi Toca Harpa para Saul'],
  ['Davi e Goliath','Davi e Golias'],
  ['Filisteus Reject Davi','Os Filisteus Rejeitam Davi'],
  ['Abner Defects a Davi','Abner Defecciona para Davi'],
  ['Filisteu Ataque Repulsed','Ataque Filisteu Repelido'],
  ['Davi Commits Adultério com Bate-Seba','Davi Comete Adultério com Bate-Seba'],
  ['Amonitas Crushed','Os Amonitas São Esmagados'],
  ['Absalão vinga Violation de seu Irmã','Absalão Vinga a Violação de sua Irmã'],
  ['Davi Recalled a Jerusalém','Davi é Chamado de Volta a Jerusalém'],
  ['De Salomão palácio e other construções','O Palácio de Salomão e Outras Construções'],
  ['Products de Hirão bronzeworker','Obras do Bronzista Hirão'],
  ['Elah reina sobre Israel','Elá Reina sobre Israel'],
  ['De Acabe woars com Arameus','As Guerras de Acabe com os Arameus'],
  ['De Naboth vinhedo','O Vinhedo de Nabote'],
  ['Eliseu secceeds Elias','Eliseu Sucede a Elias'],
  ['Arameu ataque é thwarted','Ataque Arameu é Frustrado'],
  ['Israel carregado captive a Assíria','Israel Levado Cativo à Assíria'],
  ['Reinado e capitivity de Jeoacaz','Reinado e Cativeiro de Jeoacaz'],
  ['Reinado e capitivity de Joaquim','Reinado e Cativeiro de Joaquim'],
  ['Guerras contra estrangeiro countries','Guerras contra Países Estrangeiros'],
  ['Cerco e captura de Rabbah','Cerco e Captura de Rabá'],
  ['Guerras contra Rapha','Guerras contra os Rafaítas'],
  ['Famílias de Levitas e seus functions','Famílias dos Levitas e suas Funções'],
  ['Revolt contra Roboão','Revolta contra Roboão'],
  ['De Roboão marriages','Os Casamentos de Roboão'],
  ['Ethiopian invasão repulsed','Invasão Etíope Repelida'],
  ['Invasão de east','Invasão do Leste'],
  ['Restauração do Templo resumed','Restauração do Templo Retomada'],
  ['Heads de famílias que retornou com Esdras','Chefes de Famílias que Retornaram com Esdras'],
  ['Denunciation de mixed marriages','Denúncia dos Casamentos Mistos'],
  ['Lista de sinned povo','Lista do Povo que Pecou'],
  ['Hostil conspirações thwarted','Conspirações Hostis Frustradas'],
  ['Neemias deals com opressão','Neemias Enfrenta a Opressão'],
  ['Intrigues de inimigos frustrado','Intrigas dos Inimigos Frustradas'],
  ['Nacional confession','Confissão Nacional'],
  ['Contribution de Mordecai','A Contribuição de Mordecai'],
  ['Honor de Mordecai','A Honra de Mordecai'],
  ['Pleasure de Judeus','O Prazer dos Judeus'],
  ['De Jó fortunes e sofrimentos','As Vicissitudes e Sofrimentos de Jó'],
  ['De Jó fortunes','As Vicissitudes de Jó'],
  ['Advertência contra others','Advertência contra os Outros'],
  ['Fair lábios','Lábios Honestos'],
  ['A respeito parents','A Respeito dos Pais'],
  ['Other palavras de sábio homem','Outras Palavras do Sábio'],
  ['Sayings de Agur','Ditos de Agur'],
  ['Wickednedd de Judá','A Perversidade de Judá'],
  ['Future casa de Deus','A Casa Futura de Deus'],
  ['Future glória dos sobreviventes em Sião','A Glória Futura dos Sobreviventes em Sião'],
  ['O cântico de unfruitiful vinhedo','O Cântico do Vinhedo Infrutífero'],
  ['O sinal de Immanuel','O Sinal de Emanuel'],
  ['Repentant remanescente de Israel','O Remanescente Arrependido de Israel'],
  ['Um oráculo sobre Ethiopia','Um Oráculo sobre a Etiópia'],
  ['Isaías dramatiza conquista de Egito e Ethiopia','Isaías Dramatiza a Conquista do Egito e da Etiópia'],
  ['Denunciation de egoísmo officials','Denúncia dos Funcionários Egoístas'],
  ['De Farmer sabedoria','A Sabedoria do Agricultor'],
  ['Drunken governantes','Governantes Embriagados'],
  ['Esperança para future','Esperança para o Futuro'],
  ['Aliança com Egito é futile','A Aliança com o Egito é Inútil'],
  ['Ciro, de Deus instrument','Ciro, Instrumento de Deus'],
  ['Deus redeemer','Deus o Redentor'],
  ['De Sião crianças a ser trouxe home','Os Filhos de Sião Trazidos de Volta'],
  ['De sercant humilitation e vindicação','A Humilhação e Vindicação do Servo'],
  ['Everlasting misericórdia','Misericórdia Eterna'],
  ['Thecovenant estendido a todo que obedecer','A Aliança Estendida a Todos os que Obedecem'],
  ['Utter corrupção de de Deus povo','A Total Corrupção do Povo de Deus'],
  ['Imminence e horror da invasão','A Iminência e o Horror da Invasão'],
  ['Idolatory tem trouxe ruína sobre Israel','A Idolatria Trouxe Ruína sobre Israel'],
  ['Linen pano de linho','O Pano de Linho'],
  ['Punição é inevitable','A Punição é Inevitável'],
  ['Jeremias reclama novamente e é reassured','Jeremias Reclama de Novo e é Encorajado'],
  ['Hallow O sábado dia','Santifique o Dia de Sábado'],
  ['Jeremias denuncia seu persecutors','Jeremias Denuncia seus Perseguidores'],
  ['Jerusalém irá cair a Nebuchadrezzar','Jerusalém Cairá nas Mãos de Nabucodonosor'],
  ['Cup de de Deus ira','O Cálice da Ira de Deus'],
  ['Morte de Uriah','A Morte de Urias'],
  ['Hananias opposes Jeremias e morre','Hananias se Opõe a Jeremias e Morre'],
  ['Joyful retorno de exiles','O Alegre Retorno dos Exilados'],
  ['De Deus assurace de de povo retorno','A Garantia de Deus quanto ao Retorno do Povo'],
  ['Rechabites elogiado','Os Recabitas Elogiados'],
  ['Jeremias, coloca free, lembra Ébede-melech','Jeremias, Posto em Liberdade, Lembra Ébede-Melech'],
  ['Insurrection contra Gedalias','Insurreição contra Gedalias'],
  ['Denunciation de persistente idolatria','Denúncia da Idolatria Persistente'],
  ['Babilônia irá strike Egito','A Babilônia Golpeará o Egito'],
  ['Julgamento sobre Elam','Julgamento sobre Elã'],
  ['Joaquim favored em cativeiro','Joaquim Favorecido no Cativeiro'],
  ['Defiled pão','Pão Profanado'],
  ['Hair e barba','Cabelo e Barba'],
  ['Massacre de idolaters','Massacre dos Idólatras'],
  ['De Judá cativeiro portrayed','O Cativeiro de Judá Representado'],
  ['De Deus julgamento justified','O Julgamento de Deus Justificado'],
  ['De Deus faithless noiva','A Noiva Infiel de Deus'],
  ['Israel degraded','Israel Degradado'],
  ['De Israel continuing rebelião','A Rebelião Contínua de Israel'],
  ['Drawn espada de Deus','A Espada Desembainhada de Deus'],
  ['De Ezequiel bereavement','O Luto de Ezequiel'],
  ['Elevado cedar','O Cedro Elevado'],
  ['O vale de dry ossos','O Vale dos Ossos Secos'],
  ['Levitical sacerdotes','Sacerdotes Levíticos'],
  ['Santo district','O Distrito Sagrado'],
  ['Fiery fornalha','A Fornalha Ardente'],
  ['Mais certeza de de Deus redeeming amor','Maior Certeza do Amor Redentor de Deus'],
  ['History de rebelião','Histórico de Rebelião'],
  ['De Deus espírito poured out','O Espírito de Deus Derramado'],
  ['Glorioso future de Judá','O Glorioso Futuro de Judá'],
  ['Revenge a Esaú','Vingança contra Esaú'],
  ['Future papel do remanescente','O Papel Futuro do Remanescente'],
  ['Deus challenges Israle','Deus Desafia Israel'],
  ['Penitence e confia em Deus','Penitência e Confiança em Deus'],
  ['Consuming ira de Deus','A Ira Consumidora de Deus'],
  ['Ruína iminente e inevitable','Ruína Iminente e Inevitável'],
  ['Ordenar a rebuild O templo','Ordem para Reconstruir o Templo'],
  ['Future glória do templo','A Glória Futura do Templo'],
  ['Um rebuke e uma promessa','Uma Repreensão e uma Promessa'],
  ['Punição para rejecting de Deus exigências','Punição por Rejeitar as Exigências de Deus'],
  ['Judgement para paz','Julgamento pela Paz'],
  ['Joyful jejum','Jejum Alegre'],
  ['Dois kinds de pastores','Dois Tipos de Pastores'],
  ['Jesus ministers a multidões de povo','Jesus Ministra às Multidões'],
  ['Não não warry','Não Fique Ansioso'],
  ['Hearers e doers','Ouvintes e Praticantes'],
  ['Jesus thanks seu pai','Jesus Agradece a seu Pai'],
  ['Plucking grão sobre O Sábado','Colhendo Espigas no Sábado'],
  ['Tresures novo e antigo','Tesouros Novos e Antigos'],
  ['Jesus cura sick em Genesaré','Jesus Cura os Enfermos em Genesaré'],
  ['Jesus cures muitos povo','Jesus Cura Muitas Pessoas'],
  ['Jesus cures um menino com um Demônio','Jesus Cura um Menino com um Demônio'],
  ['Sobre que deverá ser greatest','Sobre Quem Será o Maior'],
  ['Labors no vinhedo','Trabalhadores no Vinhedo'],
  ['Greatest mandamento','O Maior Mandamento'],
  ['Necessity para vigilância','Necessidade de Vigilância'],
  ['Judgiment das nações','Julgamento das Nações'],
  ['Commissioning dos discípulos','Missão dos Discípulos'],
  ['O início de Galilean ministério','O Início do Ministério na Galileia'],
  ['Uma multitude na beira-mar','Uma Multidão à Beira-Mar'],
  ['Jesus appoints doze','Jesus Nomeia os Doze'],
  ['Jesus cura Gerasene endemoninhado','Jesus Cura o Endemoninhado Geraseno'],
  ['Cura sick em Genesaré','Cura dos Enfermos em Genesaré'],
  ['Jesus cures um surdo homem','Jesus Cura um Homem Surdo'],
  ['Jesus cures um cego homem em Betsaida','Jesus Cura um Homem Cego em Betsaida'],
  ['Um homem que não taste morte','Um Homem que Não Provará a Morte'],
  ['Que é greatest?','Quem é o Maior?'],
  ['Lesson de seco figueira árvore','Lição da Figueira Seca'],
  ['Jesus denuncia scribes','Jesus Denuncia os Escribas'],
  ['Necedssity de vigilância','Necessidade de Vigilância'],
  ['De Zachariah profecia','A Profecia de Zacarias'],
  ['Jesus é presented no templo','Jesus é Apresentado no Templo'],
  ['Jesus drives out um mau espírito','Jesus Expulsa um Mau Espírito'],
  ['Dois foundations','Dois Alicerces'],
  ['Não um é greater do que João','Ninguém é Maior do que João'],
  ['Jesus calms um tempestade','Jesus Acalma a Tempestade'],
  ['De Herodes perplexity','A Perplexidade de Herodes'],
  ['Nature de discipulado','A Natureza do Discipulado'],
  ['Jesus rejoices','Jesus Exulta'],
  ['Jesus denuncia Fariseus e Lawyers','Jesus Denuncia Fariseus e Doutores da Lei'],
  ['Não não worry','Não Fique Preocupado'],
  ['Faithfiul ou infiel escravo','Servo Fiel ou Infiel'],
  ['Jesus é cause de division','Jesus é Causa de Divisão'],
  ['Com Multitude sobre Os Sinais do Tempo','Com a Multidão sobre os Sinais dos Tempos'],
  ['Arrepender-se ou perish','Arrependimento ou Perdição'],
  ['Cost de discipulado','O Custo do Discipulado'],
  ['Alguns sayings de Jesus','Alguns Ditos de Jesus'],
  ['A pergunta sobre de david filho','A Pergunta sobre o Filho de Davi'],
  ['Jesus ora sobre O Monte de Olives','Jesus Ora no Monte das Oliveiras'],
  ['Jesus aparece a seu desciples','Jesus Aparece aos seus Discípulos'],
  ['Cura de Official Filho','Cura do Filho do Funcionário'],
  ['Judgement por palavra de Jesus','Julgamento pela Palavra de Jesus'],
  ['Os crentes compartilha seus possessions','Os Crentes Compartilham seus Bens'],
  ['Filipe e Ethiopian eunuco','Filipe e o Eunuco Etíope'],
  ['Pedro em Lydda e Joppa','Pedro em Lida e Jope'],
  ['Paulo apelos a emoperor','Paulo Apela ao Imperador'],
  ['Paulo sobre Island de Malta','Paulo na Ilha de Malta'],
  ['De Deus promessa realized através de fé','A Promessa de Deus Realizada pela Fé'],
  ['Results de justificação','Os Resultados da Justificação'],
  ['De Israel rejection é não final','A Rejeição de Israel não é Definitiva'],
  ['Sendo subject a authorities','Sendo Sujeito às Autoridades'],
  ['Please others, não vocês mesmos','Agradai aos Outros, não a Vós Mesmos'],
  ['De Paulo razão para escrita então boldly','A Razão de Paulo para Escrever com Ousadia'],
  ['Proclaiming Cristo crucificado','Proclamando Cristo Crucificado'],
  ['Rights de um apóstolos','Os Direitos de um Apóstolo'],
  ['Warnings contra idolatria','Advertências contra a Idolatria'],
  ['Final messages e saudações','Mensagens Finais e Saudações'],
  ['Ministers de novo convenant','Ministros da Nova Aliança'],
  ['Commendation de Tito','O Elogio de Tito'],
  ['De Paulo visões e revelations','As Visões e Revelações de Paulo'],
  ['Paulo e other apóstolos','Paulo e os Outros Apóstolos'],
  ['Judeus e gentiles são salvou por fé','Judeus e Gentios são Salvos pela Fé'],
  ['Nature de Christian liberdade','A Natureza da Liberdade Cristã'],
  ['Suporta um de another cargas','Carreguem uns as Cargas dos Outros'],
  ['Oração para readers','Oração pelos Leitores'],
  ['Renounce pagão caminhos','Renuncia aos Caminhos Pagãos'],
  ['De Paulo present circumstances','As Circunstâncias Presentes de Paulo'],
  ['Imitating de Cristo humildade','Imitando a Humildade de Cristo'],
  ['Shining como luzes no mundo','Brilhando como Luzes no Mundo'],
  ['Quebrando com past','Rompendo com o Passado'],
  ['Pressing em direção a goal','Avançando em Direção à Meta'],
  ['Final greeting e bênção final','Saudação Final e Bênção'],
  ['Other principals e powers','Outros Principados e Potestades'],
  ['Qualificações de bishops e diáconos','Qualificações de Bispos e Diáconos'],
  ['Um bom minister de Jesus Cristo','Um Bom Ministro de Jesus Cristo'],
  ['Santo ones','Os Santos'],
  ['Godlessness em último dias','Impiedade nos Últimos Dias'],
  ['Tito em Crete','Tito em Creta'],
  ['Final messages e bênção final','Mensagens Finais e Bênção'],
  ['Please acolher Onésimo','Por Favor, Acolha Onésimo'],
  ['Advertência a pay attention','Advertência para Prestar Atenção'],
  ['Certainty de de Deus promessa','A Certeza da Promessa de Deus'],
  ['Priestly order de Melquisedeque','A Ordem Sacerdotal de Melquisedeque'],
  ['Earthly e celestial santuários','Santuários Terrenos e Celestiais'],
  ['Um chamado a persevere','Um Chamado a Perseverar'],
  ['Advertência contra rejecting de Deus graça','Advertência contra Rejeitar a Graça de Deus'],
  ['Dois kinds de sabedoria','Dois Tipos de Sabedoria'],
  ['Couple e escravo','Cônjuges e Escravos'],
  ['De Christian chamado e eleição','O Chamado e a Eleição do Cristão'],
  ['Eyewitnesses de de Cristo glória','Testemunhas Oculares da Glória de Cristo'],
  ['Criticism a antagonistas','Crítica aos Antagonistas'],
  ['Amor cada other','Amai uns aos Outros'],
  ['De Dreamer autodestruição','A Autodestruição do Sonhador'],
  ['Sete Honors','Sete Honrarias'],
  ['Povo que Wears Branco Mantos','O Povo que Veste Mantos Brancos'],
  ['Deverá ser Não mais Delay','Não Haverá Mais Demora'],
  ['O Dragão É Thrown','O Dragão é Lançado'],
  ['Uma Mulher Seated sobre Um Escarlate Besta','Uma Mulher Sentada sobre a Besta Escarlate'],
  ['O Cavaleiro sobre Branco Hourse','O Cavaleiro sobre o Cavalo Branco'],
];

// Regex-based fixes for titles with apostrophes and other issues
content = content
  .replace(/pericope: "Exodus"/g, 'pericope: "O Êxodo"')
  .replace(/pericope: "Engagement"/g, 'pericope: "O Noivado"')
  .replace(/pericope: "Negotiation"/g, 'pericope: "A Negociação"')
  .replace(/pericope: "Rewards"/g, 'pericope: "As Recompensas"')
  .replace(/pericope: "Future glória"/g, 'pericope: "A Glória Futura"')
  .replace(/pericope: "É não other Evangelho"/g, 'pericope: "Não há Outro Evangelho"')
  .replace(/pericope: "Lesson da figueira árvore"/g, 'pericope: "Lição da Figueira"')
  .replace(/pericope: "Não não deixar seu hearts ser perturbado"/g, 'pericope: "Não Deixem seus Corações se Perturbarem"')
  .replace(/Arão'S Sacerdócio Inaugumented/g, 'O Sacerdócio de Arão Inaugurado')
  .replace(/Jesus' application das parábolas/g, 'A Aplicação das Parábolas de Jesus')
  .replace(/Jesus' side é traspassado/g, 'O Lado de Jesus é Traspassado')
  .replace(/Não todo a groly de SENHOR/g, 'Façam Tudo para a Glória do SENHOR')
  .replace(/De José Irmãos' Primeiro Trip a Egito/g, 'Primeira Viagem dos Irmãos de José ao Egito')
  .replace(/De José Irmãos' Segundo Trip a Egito/g, 'Segunda Viagem dos Irmãos de José ao Egito');

let count = 0;
for (const [from, to] of fixes) {
  if (content.includes(from)) {
    content = content.replaceAll(from, to);
    count++;
  }
}

fs.writeFileSync('src/data/calendarioDevocional.ts', content);
console.log('Fixed:', count, 'entries');
